# Test declarations exercise the same production libraries in both builds.
get_filename_component(XR_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../../.." ABSOLUTE)
set(XR_TEST_DECLARATIONS_BINARY "${CMAKE_CURRENT_BINARY_DIR}/test-declarations")
file(MAKE_DIRECTORY "${XR_TEST_DECLARATIONS_BINARY}")
set(old_root "${XR_TEST_DECLARATIONS_BINARY}/old-program27")
file(MAKE_DIRECTORY "${old_root}")
file(READ "${CMAKE_CURRENT_LIST_DIR}/old_program27.json" old_record)
string(JSON old_archive_hash GET "${old_record}" archive sha256)
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/old_program27_headers.zip" actual_archive_hash)
if(NOT old_archive_hash STREQUAL actual_archive_hash)
    message(FATAL_ERROR "The preserved old header archive differs from its provenance record")
endif()
string(JSON old_source_hash GET "${old_record}" source sha256)
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/old_program27.c" actual_source_hash)
if(NOT old_source_hash STREQUAL actual_source_hash)
    message(FATAL_ERROR "The actual old generated C differs from its provenance record")
endif()
string(JSON old_count LENGTH "${old_record}" archive members)
math(EXPR old_last "${old_count}-1")
set(old_headers)
foreach(index RANGE ${old_last})
    string(JSON path GET "${old_record}" archive members ${index} path)
    list(APPEND old_headers "${old_root}/${path}")
endforeach()
add_custom_command(OUTPUT "${old_root}/extracted.stamp" BYPRODUCTS ${old_headers}
    COMMAND "${CMAKE_COMMAND}" -E tar xf "${CMAKE_CURRENT_LIST_DIR}/old_program27_headers.zip"
    COMMAND "${CMAKE_COMMAND}" -E touch "${old_root}/extracted.stamp"
    DEPENDS "${CMAKE_CURRENT_LIST_DIR}/old_program27_headers.zip" "${CMAKE_CURRENT_LIST_DIR}/old_program27.json"
    WORKING_DIRECTORY "${old_root}" VERBATIM)
add_custom_target(test_test_old_headers DEPENDS "${old_root}/extracted.stamp")
add_library(test_test_old_program27 OBJECT "${CMAKE_CURRENT_LIST_DIR}/old_program27.c")
add_dependencies(test_test_old_program27 test_test_old_headers)
target_include_directories(test_test_old_program27 BEFORE PRIVATE "${old_root}/src")
add_executable(test_test_old_rebuilt "${CMAKE_CURRENT_LIST_DIR}/test_old_object.c" $<TARGET_OBJECTS:test_test_old_program27>)
target_link_libraries(test_test_old_rebuilt PRIVATE xray_xir_scalar xray_compile_resources)
add_test(NAME test_test_old_rebuilt COMMAND test_test_old_rebuilt)
add_executable(test_test_source_cases "${CMAKE_CURRENT_LIST_DIR}/test_source_cases.c")
target_link_libraries(test_test_source_cases PRIVATE xray_xir_source_product)
add_test(NAME test_test_source_cases COMMAND "${Python3_EXECUTABLE}" -X utf8
    "${CMAKE_CURRENT_LIST_DIR}/source_cases.py" --driver "$<TARGET_FILE:test_test_source_cases>"
    --stdlib "${XR_ROOT}/stdlib" --output "${XR_TEST_DECLARATIONS_BINARY}/source-cases")
add_executable(test_test_directory_resources "${CMAKE_CURRENT_LIST_DIR}/test_directory_resources.c")
target_link_libraries(test_test_directory_resources PRIVATE xray_xir_source_product)
add_test(NAME test_test_directory_resources COMMAND test_test_directory_resources "${CMAKE_CURRENT_LIST_DIR}" "${XR_ROOT}/stdlib")
add_executable(test_test_identity "${CMAKE_CURRENT_LIST_DIR}/test_identity.c")
target_link_libraries(test_test_identity PRIVATE xray_xir_vm xray_compile_resources)
add_test(NAME test_test_identity COMMAND "${Python3_EXECUTABLE}" -X utf8
    "${CMAKE_CURRENT_LIST_DIR}/identity_wire.py" "$<TARGET_FILE:test_test_identity>" "${XR_TEST_DECLARATIONS_BINARY}/identity-packets")
add_executable(test_test_packets "${CMAKE_CURRENT_LIST_DIR}/test_packets.c")
target_link_libraries(test_test_packets PRIVATE xray_xir_admission xray_compile_resources)
add_test(NAME test_test_packet_oracle COMMAND "${Python3_EXECUTABLE}" -X utf8
    "${CMAKE_CURRENT_LIST_DIR}/../derive_test_roles_vectors.py" --output "${XR_TEST_DECLARATIONS_BINARY}/ordinary-packets")
set_tests_properties(test_test_packet_oracle PROPERTIES FIXTURES_SETUP role_packets)
add_test(NAME test_test_packets COMMAND test_test_packets "${XR_TEST_DECLARATIONS_BINARY}/ordinary-packets")
set_tests_properties(test_test_packets PROPERTIES FIXTURES_REQUIRED role_packets)
add_executable(test_method_role_regression "${CMAKE_CURRENT_LIST_DIR}/../test_xir_compile_runtime_owner.c")
target_link_libraries(test_method_role_regression PRIVATE xray_xir_vm)
add_test(NAME test_method_role_regression COMMAND test_method_role_regression)
add_executable(test_test_declarations "${CMAKE_CURRENT_LIST_DIR}/test_test_declarations.c")
target_link_libraries(test_test_declarations PRIVATE xray_xir_source_product)
add_test(NAME test_test_declarations COMMAND test_test_declarations "${CMAKE_CURRENT_LIST_DIR}" "${XR_ROOT}/stdlib")
set(test_generated "${XR_TEST_DECLARATIONS_BINARY}/test-roles.c")
add_custom_command(OUTPUT "${test_generated}"
    COMMAND test_test_declarations "${CMAKE_CURRENT_LIST_DIR}" "${XR_ROOT}/stdlib" "${test_generated}"
    DEPENDS test_test_declarations "${CMAKE_CURRENT_LIST_DIR}/basic.xr" "${CMAKE_CURRENT_LIST_DIR}/library.xr" VERBATIM)
add_executable(test_test_native "${CMAKE_CURRENT_LIST_DIR}/test_native.c" "${test_generated}")
target_link_libraries(test_test_native PRIVATE xray_xir_scalar xray_compile_resources)
add_test(NAME test_test_native COMMAND test_test_native)
if(XR_OLD_TEST_OBJECT)
    add_executable(test_test_old_object "${CMAKE_CURRENT_LIST_DIR}/test_old_object.c" "${XR_OLD_TEST_OBJECT}")
    target_link_libraries(test_test_old_object PRIVATE xray_xir_scalar xray_compile_resources)
    add_test(NAME test_test_old_object COMMAND test_test_old_object)
endif()

set(test_declaration_targets test_test_old_program27 test_test_old_rebuilt
    test_test_source_cases test_test_directory_resources test_test_identity
    test_test_packets test_method_role_regression test_test_declarations test_test_native)
if(TARGET test_test_old_object)
    list(APPEND test_declaration_targets test_test_old_object)
endif()
foreach(target IN LISTS test_declaration_targets)
    target_include_directories(${target} PRIVATE "${XR_ROOT}/src" "${XR_ROOT}/include")
    set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /WX /utf-8)
        target_compile_definitions(${target} PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
        if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${target} PRIVATE /experimental:c11atomics)
        endif()
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
endforeach()
set_tests_properties(test_test_old_rebuilt test_test_source_cases test_test_directory_resources
    test_test_identity test_test_packet_oracle test_test_packets test_method_role_regression
    test_test_declarations test_test_native PROPERTIES
    LABELS "unit;xir;test-declarations;ownership;budget;abi" TIMEOUT 90)
