get_filename_component(CGEN_RESOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include(CheckCSourceCompiles)
include(CMakePushCheckState)
function(cgen_reject_missing_resources)
    cmake_push_check_state(RESET)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_REQUIRED_INCLUDES "${CGEN_RESOURCE_ROOT}/src")
    set(CMAKE_REQUIRED_DEFINITIONS -D_CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        set(CMAKE_REQUIRED_FLAGS "/std:c11 /WX /utf-8")
    else()
        set(CMAKE_REQUIRED_FLAGS "-std=c11 -Werror")
    endif()
    unset(CGEN_RESOURCE_CURRENT_COMPILES CACHE)
    check_c_source_compiles("#include <aot/xi_cgen_verify_output.h>\nvoid accepted(XrCompileResources *r) { (void)xr_compile_cgen_verify_output(r, \"\", 0, 0); (void)xr_compile_cgen_verify_output_or_ice(r, \"\", 0, \"tu\"); (void)xr_compile_cgen_verify_c90_output(r, \"\", 0, 0); }" CGEN_RESOURCE_CURRENT_COMPILES)
    if(NOT CGEN_RESOURCE_CURRENT_COMPILES)
        message(FATAL_ERROR "Resource-bearing verifier prototypes must compile before rejection tests")
    endif()
    foreach(operation output output_or_ice c90_output)
        set(result_name "CGEN_RESOURCE_OLD_${operation}_COMPILES")
        unset(${result_name} CACHE)
        check_c_source_compiles("#include <aot/xi_cgen_verify_output.h>\nvoid rejected(void) { (void)xr_compile_cgen_verify_${operation}(\"\", 0, 0); }" ${result_name})
        if(${result_name})
            message(FATAL_ERROR "Verifier operation ${operation} accepted a call without resources")
        endif()
    endforeach()
    cmake_pop_check_state()
endfunction()
cgen_reject_missing_resources()
add_library(cgen_compile_resources_production OBJECT "${CGEN_RESOURCE_ROOT}/src/aot/xi_cgen_verify_output.c")
add_executable(test_cgen_compile_resources
    "${CMAKE_CURRENT_LIST_DIR}/test_cgen_compile_resources.c"
    "${CGEN_RESOURCE_ROOT}/src/aot/xi_cgen_verify_output.c")
foreach(target cgen_compile_resources_production test_cgen_compile_resources)
    target_include_directories(${target} PRIVATE "${CGEN_RESOURCE_ROOT}/src")
    target_compile_features(${target} PRIVATE c_std_11)
    target_compile_definitions(${target} PRIVATE _CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /WX /utf-8)
        if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${target} PRIVATE /experimental:c11atomics)
        endif()
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
endforeach()
add_test(NAME test_cgen_compile_resources COMMAND test_cgen_compile_resources)
set_tests_properties(test_cgen_compile_resources PROPERTIES LABELS "unit;aot;compiler;ownership;budget" TIMEOUT 60)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/check_cgen_compile_resources_ice.cmake" [=[
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(dump_dir "${OUTPUT_ROOT}/cgen-ice-${nonce}")
file(MAKE_DIRECTORY "${dump_dir}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "XRAY_CGEN_ICE_DIR=${dump_dir}" "${PROGRAM}" --ice
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 20)
if(result STREQUAL "0" OR result STREQUAL "86")
    message(FATAL_ERROR "Malformed verification returned instead of aborting: ${result}")
endif()
if(NOT stderr MATCHES "\\[xi_cgen\\]\\[ICE\\]" OR NOT stderr MATCHES "W1_BALANCE" OR NOT stderr MATCHES "resource-fatal")
    message(FATAL_ERROR "Missing fatal diagnostic: ${result}; ${stderr}")
endif()
if(stderr MATCHES "ERROR: AddressSanitizer|runtime error:|UndefinedBehaviorSanitizer")
    message(FATAL_ERROR "Unexpected sanitizer failure before the required abort: ${stderr}")
endif()
file(GLOB dumps "${dump_dir}/xray_cgen_ice_resource_fatal_*.c")
list(LENGTH dumps count)
if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected one real source dump: ${dumps}")
endif()
list(GET dumps 0 dump)
file(READ "${dump}" contents)
if(NOT contents STREQUAL "void f(void) {\n")
    message(FATAL_ERROR "Fatal dump did not preserve all malformed input bytes")
endif()
message(STATUS "Fatal malformed child aborted and preserved complete source: ${dump}")
]=])
add_test(NAME test_cgen_compile_resources_fatal COMMAND ${CMAKE_COMMAND}
    "-DPROGRAM=$<TARGET_FILE:test_cgen_compile_resources>"
    "-DOUTPUT_ROOT=${CMAKE_CURRENT_BINARY_DIR}"
    -P "${CMAKE_CURRENT_BINARY_DIR}/check_cgen_compile_resources_ice.cmake")
set_tests_properties(test_cgen_compile_resources_fatal PROPERTIES LABELS "unit;aot;compiler;ownership" TIMEOUT 30)
