/* AUTO-GENERATED by xisagen - DO NOT EDIT */
/* Source: xisa/xi/lowering.def */
/* Included inside xvm.c dispatch switch; relies on i, R, vmcase, vmbreak. */

#define XVM_TEMPLATE_NARROW_INT_CASE(op, kernel) \
    vmcase(op) { \
        int a = GETARG_A(i), b = GETARG_B(i); \
        R(a) = XR_FROM_INT(XR_NUMERIC_NARROW_OWNER_APPLY( \
            XR_SEM_OWNER_ID_SHARED_NUMERIC_CONVERSION_HI, \
            XR_SEM_OWNER_ID_SHARED_NUMERIC_CONVERSION_LO, \
            XR_SEM_CONSUMER_VM, kernel, XR_TO_INT(R(b)))); \
        vmbreak; \
    }

#define XVM_TEMPLATE_NARROW_F32_CASE(op, kernel) \
    vmcase(op) { \
        int a = GETARG_A(i), b = GETARG_B(i); \
        R(a) = XR_FROM_FLOAT(XR_NUMERIC_NARROW_OWNER_APPLY( \
            XR_SEM_OWNER_ID_SHARED_NUMERIC_CONVERSION_HI, \
            XR_SEM_OWNER_ID_SHARED_NUMERIC_CONVERSION_LO, \
            XR_SEM_CONSUMER_VM, kernel, XR_TO_FLOAT(R(b)))); \
        vmbreak; \
    }

#define XVM_TEMPLATE_WIDTH_INT_CASE(op, scalar_rep) \
    vmcase(op) { \
        int a = GETARG_A(i), b = GETARG_B(i); \
        R(a) = XR_FROM_INT(xr_numeric_int_convert_i64( \
            XR_TO_INT(R(b)), scalar_rep, scalar_rep, 64)); \
        vmbreak; \
    }

#define XVM_TEMPLATE_WIDTH_F32_CASE(op) \
    vmcase(op) { \
        int a = GETARG_A(i), b = GETARG_B(i); \
        R(a) = XR_FROM_FLOAT(xr_numeric_f64_to_f32(XR_TO_FLOAT(R(b)))); \
        vmbreak; \
    }

XVM_TEMPLATE_NARROW_INT_CASE(OP_NARROW_I8, xr_numeric_narrow_i8)
XVM_TEMPLATE_NARROW_INT_CASE(OP_NARROW_U8, xr_numeric_narrow_u8)
XVM_TEMPLATE_NARROW_INT_CASE(OP_NARROW_I16, xr_numeric_narrow_i16)
XVM_TEMPLATE_NARROW_INT_CASE(OP_NARROW_U16, xr_numeric_narrow_u16)
XVM_TEMPLATE_NARROW_INT_CASE(OP_NARROW_I32, xr_numeric_narrow_i32)
XVM_TEMPLATE_NARROW_INT_CASE(OP_NARROW_U32, xr_numeric_narrow_u32)
XVM_TEMPLATE_NARROW_F32_CASE(OP_NARROW_F32, xr_numeric_narrow_f32)
XVM_TEMPLATE_WIDTH_INT_CASE(OP_WIDEN_I8, XR_NATIVE_I8)
XVM_TEMPLATE_WIDTH_INT_CASE(OP_WIDEN_U8, XR_NATIVE_U8)
XVM_TEMPLATE_WIDTH_INT_CASE(OP_WIDEN_I16, XR_NATIVE_I16)
XVM_TEMPLATE_WIDTH_INT_CASE(OP_WIDEN_U16, XR_NATIVE_U16)
XVM_TEMPLATE_WIDTH_INT_CASE(OP_WIDEN_I32, XR_NATIVE_I32)
XVM_TEMPLATE_WIDTH_INT_CASE(OP_WIDEN_U32, XR_NATIVE_U32)
XVM_TEMPLATE_WIDTH_F32_CASE(OP_WIDEN_F32)

#undef XVM_TEMPLATE_NARROW_INT_CASE
#undef XVM_TEMPLATE_NARROW_F32_CASE
#undef XVM_TEMPLATE_WIDTH_INT_CASE
#undef XVM_TEMPLATE_WIDTH_F32_CASE
