/* AUTO-GENERATED by xisagen - DO NOT EDIT */
/* Source: xisa/xi/lowering.def */
/* Included inside xvm_dispatch_arith.inc.c with template macros defined. */

#ifndef XVM_TEMPLATE_ARITH_ADD_CASE
#error "XVM_TEMPLATE_ARITH_ADD_CASE must be defined before including this file"
#endif
#ifndef XVM_TEMPLATE_ARITH_NUMERIC_CASE
#error "XVM_TEMPLATE_ARITH_NUMERIC_CASE must be defined before including this file"
#endif
#ifndef XVM_TEMPLATE_ARITH_MUL_CASE
#error "XVM_TEMPLATE_ARITH_MUL_CASE must be defined before including this file"
#endif

XVM_TEMPLATE_ARITH_ADD_CASE(OP_ADD, +, +, xr_bigint_add, XR_OP_ADD_FLAG, SYMBOL_OP_ADD, "+", "operator '+' requires both operands to be numeric or both string, got '%s' and '%s'")
XVM_TEMPLATE_ARITH_NUMERIC_CASE(OP_SUB, -, -, xr_bigint_sub, XR_OP_SUB_FLAG, SYMBOL_OP_SUB, "-", "subtraction requires numeric types")
XVM_TEMPLATE_ARITH_MUL_CASE(OP_MUL, *, *, xr_bigint_mul, XR_OP_MUL_FLAG, SYMBOL_OP_MUL, "*", "multiplication requires numeric types")
