/* AUTO-GENERATED by xisagen — DO NOT EDIT */
/* Golden-bytes verification test for arm64 instruction encoding */

#ifdef __aarch64__

#include <stdio.h>
#include <string.h>
#include "xm_arm64.h"

static int g_pass = 0;
static int g_fail = 0;

static void check_golden(const char *name, uint32_t got, const uint8_t *expected) {
    uint32_t exp_word;
    memcpy(&exp_word, expected, 4);
    if (got != exp_word) {
        fprintf(stderr, "FAIL: %s: expected 0x%08x, got 0x%08x\n", name, exp_word, got);
        g_fail++;
    } else {
        g_pass++;
    }
}

int main(void) {
    /* arm64.add.rrr: x0 x1 x2 → 20 00 02 8b */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0x8b};
        check_golden("arm64.add.rrr (x0 x1 x2)", a64_add(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.add.rrr: x3 x4 x5 → 83 00 05 8b */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0x8b};
        check_golden("arm64.add.rrr (x3 x4 x5)", a64_add(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.add.rrr: x28 fp lr → bc 03 1e 8b */
    {
        static const uint8_t exp[] = {0xbc, 0x03, 0x1e, 0x8b};
        check_golden("arm64.add.rrr (x28 fp lr)", a64_add(A64_X28, A64_FP, A64_LR), exp);
    }

    /* arm64.sub.rrr: x0 x1 x2 → 20 00 02 cb */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0xcb};
        check_golden("arm64.sub.rrr (x0 x1 x2)", a64_sub(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.sub.rrr: x3 x4 x5 → 83 00 05 cb */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0xcb};
        check_golden("arm64.sub.rrr (x3 x4 x5)", a64_sub(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.sub.rrr: x28 fp lr → bc 03 1e cb */
    {
        static const uint8_t exp[] = {0xbc, 0x03, 0x1e, 0xcb};
        check_golden("arm64.sub.rrr (x28 fp lr)", a64_sub(A64_X28, A64_FP, A64_LR), exp);
    }

    /* arm64.and.rrr: x0 x1 x2 → 20 00 02 8a */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0x8a};
        check_golden("arm64.and.rrr (x0 x1 x2)", a64_and(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.and.rrr: x3 x4 x5 → 83 00 05 8a */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0x8a};
        check_golden("arm64.and.rrr (x3 x4 x5)", a64_and(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.orr.rrr: x0 x1 x2 → 20 00 02 aa */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0xaa};
        check_golden("arm64.orr.rrr (x0 x1 x2)", a64_orr(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.orr.rrr: x3 x4 x5 → 83 00 05 aa */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0xaa};
        check_golden("arm64.orr.rrr (x3 x4 x5)", a64_orr(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.eor.rrr: x0 x1 x2 → 20 00 02 ca */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0xca};
        check_golden("arm64.eor.rrr (x0 x1 x2)", a64_eor(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.eor.rrr: x3 x4 x5 → 83 00 05 ca */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0xca};
        check_golden("arm64.eor.rrr (x3 x4 x5)", a64_eor(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.mul.rrr: x0 x1 x2 → 20 7c 02 9b */
    {
        static const uint8_t exp[] = {0x20, 0x7c, 0x02, 0x9b};
        check_golden("arm64.mul.rrr (x0 x1 x2)", a64_mul(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.mul.rrr: x3 x4 x5 → 83 7c 05 9b */
    {
        static const uint8_t exp[] = {0x83, 0x7c, 0x05, 0x9b};
        check_golden("arm64.mul.rrr (x3 x4 x5)", a64_mul(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.sdiv.rrr: x0 x1 x2 → 20 0c c2 9a */
    {
        static const uint8_t exp[] = {0x20, 0x0c, 0xc2, 0x9a};
        check_golden("arm64.sdiv.rrr (x0 x1 x2)", a64_sdiv(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.sdiv.rrr: x3 x4 x5 → 83 0c c5 9a */
    {
        static const uint8_t exp[] = {0x83, 0x0c, 0xc5, 0x9a};
        check_golden("arm64.sdiv.rrr (x3 x4 x5)", a64_sdiv(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.add.ri12: x0 x1 1 → 20 04 00 91 */
    {
        static const uint8_t exp[] = {0x20, 0x04, 0x00, 0x91};
        check_golden("arm64.add.ri12 (x0 x1 1)", a64_add_imm(A64_X0, A64_X1, 1), exp);
    }

    /* arm64.add.ri12: x0 x1 42 → 20 a8 00 91 */
    {
        static const uint8_t exp[] = {0x20, 0xa8, 0x00, 0x91};
        check_golden("arm64.add.ri12 (x0 x1 42)", a64_add_imm(A64_X0, A64_X1, 42), exp);
    }

    /* arm64.add.ri12: sp sp 16 → ff 43 00 91 */
    {
        static const uint8_t exp[] = {0xff, 0x43, 0x00, 0x91};
        check_golden("arm64.add.ri12 (sp sp 16)", a64_add_imm(A64_SP, A64_SP, 16), exp);
    }

    /* arm64.sub.ri12: sp sp 16 → ff 43 00 d1 */
    {
        static const uint8_t exp[] = {0xff, 0x43, 0x00, 0xd1};
        check_golden("arm64.sub.ri12 (sp sp 16)", a64_sub_imm(A64_SP, A64_SP, 16), exp);
    }

    /* arm64.sub.ri12: x0 x1 1 → 20 04 00 d1 */
    {
        static const uint8_t exp[] = {0x20, 0x04, 0x00, 0xd1};
        check_golden("arm64.sub.ri12 (x0 x1 1)", a64_sub_imm(A64_X0, A64_X1, 1), exp);
    }

    /* arm64.cmp.ri12: x0 0 → 1f 00 00 f1 */
    {
        static const uint8_t exp[] = {0x1f, 0x00, 0x00, 0xf1};
        check_golden("arm64.cmp.ri12 (x0 0)", a64_cmp_imm(A64_X0, 0), exp);
    }

    /* arm64.cmp.ri12: x1 42 → 3f a8 00 f1 */
    {
        static const uint8_t exp[] = {0x3f, 0xa8, 0x00, 0xf1};
        check_golden("arm64.cmp.ri12 (x1 42)", a64_cmp_imm(A64_X1, 42), exp);
    }

    /* arm64.mov.rr: x0 x1 → e0 03 01 aa */
    {
        static const uint8_t exp[] = {0xe0, 0x03, 0x01, 0xaa};
        check_golden("arm64.mov.rr (x0 x1)", a64_mov(A64_X0, A64_X1), exp);
    }

    /* arm64.mov.rr: x3 x4 → e3 03 04 aa */
    {
        static const uint8_t exp[] = {0xe3, 0x03, 0x04, 0xaa};
        check_golden("arm64.mov.rr (x3 x4)", a64_mov(A64_X3, A64_X4), exp);
    }

    /* arm64.lsl.rrr: x0 x1 x2 → 20 20 c2 9a */
    {
        static const uint8_t exp[] = {0x20, 0x20, 0xc2, 0x9a};
        check_golden("arm64.lsl.rrr (x0 x1 x2)", a64_lsl(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.lsl.rrr: x3 x4 x5 → 83 20 c5 9a */
    {
        static const uint8_t exp[] = {0x83, 0x20, 0xc5, 0x9a};
        check_golden("arm64.lsl.rrr (x3 x4 x5)", a64_lsl(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.asr.rrr: x0 x1 x2 → 20 28 c2 9a */
    {
        static const uint8_t exp[] = {0x20, 0x28, 0xc2, 0x9a};
        check_golden("arm64.asr.rrr (x0 x1 x2)", a64_asr(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.asr.rrr: x3 x4 x5 → 83 28 c5 9a */
    {
        static const uint8_t exp[] = {0x83, 0x28, 0xc5, 0x9a};
        check_golden("arm64.asr.rrr (x3 x4 x5)", a64_asr(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.bl: 0 → 00 00 00 94 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0x94};
        check_golden("arm64.bl (0)", a64_bl(0), exp);
    }

    /* arm64.bl: 1 → 01 00 00 94 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0x94};
        check_golden("arm64.bl (1)", a64_bl(1), exp);
    }

    /* arm64.blr: x0 → 00 00 3f d6 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x3f, 0xd6};
        check_golden("arm64.blr (x0)", a64_blr(A64_X0), exp);
    }

    /* arm64.blr: x8 → 00 01 3f d6 */
    {
        static const uint8_t exp[] = {0x00, 0x01, 0x3f, 0xd6};
        check_golden("arm64.blr (x8)", a64_blr(A64_X8), exp);
    }

    /* arm64.blr: lr → c0 03 3f d6 */
    {
        static const uint8_t exp[] = {0xc0, 0x03, 0x3f, 0xd6};
        check_golden("arm64.blr (lr)", a64_blr(A64_LR), exp);
    }

    /* arm64.ret:  → c0 03 5f d6 */
    {
        static const uint8_t exp[] = {0xc0, 0x03, 0x5f, 0xd6};
        check_golden("arm64.ret ()", a64_ret(), exp);
    }

    /* arm64.b: 0 → 00 00 00 14 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0x14};
        check_golden("arm64.b (0)", a64_b(0), exp);
    }

    /* arm64.b: 1 → 01 00 00 14 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0x14};
        check_golden("arm64.b (1)", a64_b(1), exp);
    }

    /* arm64.b.cond: 0 0 → 00 00 00 54 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0x54};
        check_golden("arm64.b.cond (0 0)", a64_bcond(0, 0), exp);
    }

    /* arm64.b.cond: 1 0 → 01 00 00 54 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0x54};
        check_golden("arm64.b.cond (1 0)", a64_bcond(1, 0), exp);
    }

    /* arm64.b.cond: 11 0 → 0b 00 00 54 */
    {
        static const uint8_t exp[] = {0x0b, 0x00, 0x00, 0x54};
        check_golden("arm64.b.cond (11 0)", a64_bcond(11, 0), exp);
    }

    /* arm64.b.cond: 13 0 → 0d 00 00 54 */
    {
        static const uint8_t exp[] = {0x0d, 0x00, 0x00, 0x54};
        check_golden("arm64.b.cond (13 0)", a64_bcond(13, 0), exp);
    }

    /* arm64.cbz: x0 0 → 00 00 00 b4 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0xb4};
        check_golden("arm64.cbz (x0 0)", a64_cbz(A64_X0, 0), exp);
    }

    /* arm64.cbz: x1 0 → 01 00 00 b4 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0xb4};
        check_golden("arm64.cbz (x1 0)", a64_cbz(A64_X1, 0), exp);
    }

    /* arm64.cbnz: x0 0 → 00 00 00 b5 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0xb5};
        check_golden("arm64.cbnz (x0 0)", a64_cbnz(A64_X0, 0), exp);
    }

    /* arm64.cbnz: x1 0 → 01 00 00 b5 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0xb5};
        check_golden("arm64.cbnz (x1 0)", a64_cbnz(A64_X1, 0), exp);
    }

    /* arm64.stp.pre: fp lr sp -2 → fd 7b bf a9 */
    {
        static const uint8_t exp[] = {0xfd, 0x7b, 0xbf, 0xa9};
        check_golden("arm64.stp.pre (fp lr sp -2)", a64_stp_pre(A64_FP, A64_LR, A64_SP, -2), exp);
    }

    /* arm64.stp.pre: x19 x20 sp -2 → f3 53 bf a9 */
    {
        static const uint8_t exp[] = {0xf3, 0x53, 0xbf, 0xa9};
        check_golden("arm64.stp.pre (x19 x20 sp -2)", a64_stp_pre(A64_X19, A64_X20, A64_SP, -2),
                     exp);
    }

    /* arm64.ldp.post: fp lr sp 2 → fd 7b c1 a8 */
    {
        static const uint8_t exp[] = {0xfd, 0x7b, 0xc1, 0xa8};
        check_golden("arm64.ldp.post (fp lr sp 2)", a64_ldp_post(A64_FP, A64_LR, A64_SP, 2), exp);
    }

    /* arm64.ldp.post: x19 x20 sp 2 → f3 53 c1 a8 */
    {
        static const uint8_t exp[] = {0xf3, 0x53, 0xc1, 0xa8};
        check_golden("arm64.ldp.post (x19 x20 sp 2)", a64_ldp_post(A64_X19, A64_X20, A64_SP, 2),
                     exp);
    }

    /* arm64.nop:  → 1f 20 03 d5 */
    {
        static const uint8_t exp[] = {0x1f, 0x20, 0x03, 0xd5};
        check_golden("arm64.nop ()", a64_nop(), exp);
    }

    /* arm64.neg.rr: x0 x1 → e0 03 01 cb */
    {
        static const uint8_t exp[] = {0xe0, 0x03, 0x01, 0xcb};
        check_golden("arm64.neg.rr (x0 x1)", a64_neg(A64_X0, A64_X1), exp);
    }

    /* arm64.neg.rr: x3 x4 → e3 03 04 cb */
    {
        static const uint8_t exp[] = {0xe3, 0x03, 0x04, 0xcb};
        check_golden("arm64.neg.rr (x3 x4)", a64_neg(A64_X3, A64_X4), exp);
    }

    /* arm64.cmp.rr: x0 x1 → 1f 00 01 eb */
    {
        static const uint8_t exp[] = {0x1f, 0x00, 0x01, 0xeb};
        check_golden("arm64.cmp.rr (x0 x1)", a64_cmp(A64_X0, A64_X1), exp);
    }

    /* arm64.cmp.rr: x3 x4 → 7f 00 04 eb */
    {
        static const uint8_t exp[] = {0x7f, 0x00, 0x04, 0xeb};
        check_golden("arm64.cmp.rr (x3 x4)", a64_cmp(A64_X3, A64_X4), exp);
    }

    fprintf(stderr, "golden-bytes: %d passed, %d failed (of 54 total)\n", g_pass, g_fail);
    return g_fail > 0 ? 1 : 0;
}

#else
int main(void) {
    return 0;
}
#endif  // __aarch64__
