/* AUTO-GENERATED by xisagen — DO NOT EDIT */
/* Golden-bytes verification test for arm64 instruction encoding */

#ifdef __aarch64__

#include <stdio.h>
#include <string.h>
#include "xm_arm64.h"

static int g_pass = 0;
static int g_fail = 0;

static void check_golden(const char *name, uint32_t got, const uint8_t *expected) {
    uint32_t exp_word;
    memcpy(&exp_word, expected, 4);
    if (got != exp_word) {
        fprintf(stderr, "FAIL: %s: expected 0x%08x, got 0x%08x\n", name, exp_word, got);
        g_fail++;
    } else {
        g_pass++;
    }
}

int main(void) {
    /* arm64.add.rrr: x0 x1 x2 → 20 00 02 8b */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0x8b};
        check_golden("arm64.add.rrr (x0 x1 x2)", a64_add(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.add.rrr: x3 x4 x5 → 83 00 05 8b */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0x8b};
        check_golden("arm64.add.rrr (x3 x4 x5)", a64_add(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.add.rrr: x28 fp lr → bc 03 1e 8b */
    {
        static const uint8_t exp[] = {0xbc, 0x03, 0x1e, 0x8b};
        check_golden("arm64.add.rrr (x28 fp lr)", a64_add(A64_X28, A64_FP, A64_LR), exp);
    }

    /* arm64.sub.rrr: x0 x1 x2 → 20 00 02 cb */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0xcb};
        check_golden("arm64.sub.rrr (x0 x1 x2)", a64_sub(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.sub.rrr: x3 x4 x5 → 83 00 05 cb */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0xcb};
        check_golden("arm64.sub.rrr (x3 x4 x5)", a64_sub(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.sub.rrr: x28 fp lr → bc 03 1e cb */
    {
        static const uint8_t exp[] = {0xbc, 0x03, 0x1e, 0xcb};
        check_golden("arm64.sub.rrr (x28 fp lr)", a64_sub(A64_X28, A64_FP, A64_LR), exp);
    }

    /* arm64.and.rrr: x0 x1 x2 → 20 00 02 8a */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0x8a};
        check_golden("arm64.and.rrr (x0 x1 x2)", a64_and(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.and.rrr: x3 x4 x5 → 83 00 05 8a */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0x8a};
        check_golden("arm64.and.rrr (x3 x4 x5)", a64_and(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.orr.rrr: x0 x1 x2 → 20 00 02 aa */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0xaa};
        check_golden("arm64.orr.rrr (x0 x1 x2)", a64_orr(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.orr.rrr: x3 x4 x5 → 83 00 05 aa */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0xaa};
        check_golden("arm64.orr.rrr (x3 x4 x5)", a64_orr(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.eor.rrr: x0 x1 x2 → 20 00 02 ca */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0xca};
        check_golden("arm64.eor.rrr (x0 x1 x2)", a64_eor(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.eor.rrr: x3 x4 x5 → 83 00 05 ca */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0xca};
        check_golden("arm64.eor.rrr (x3 x4 x5)", a64_eor(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.mul.rrr: x0 x1 x2 → 20 7c 02 9b */
    {
        static const uint8_t exp[] = {0x20, 0x7c, 0x02, 0x9b};
        check_golden("arm64.mul.rrr (x0 x1 x2)", a64_mul(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.mul.rrr: x3 x4 x5 → 83 7c 05 9b */
    {
        static const uint8_t exp[] = {0x83, 0x7c, 0x05, 0x9b};
        check_golden("arm64.mul.rrr (x3 x4 x5)", a64_mul(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.sdiv.rrr: x0 x1 x2 → 20 0c c2 9a */
    {
        static const uint8_t exp[] = {0x20, 0x0c, 0xc2, 0x9a};
        check_golden("arm64.sdiv.rrr (x0 x1 x2)", a64_sdiv(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.sdiv.rrr: x3 x4 x5 → 83 0c c5 9a */
    {
        static const uint8_t exp[] = {0x83, 0x0c, 0xc5, 0x9a};
        check_golden("arm64.sdiv.rrr (x3 x4 x5)", a64_sdiv(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.subs.rrr: x0 x1 x2 → 20 00 02 eb */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0xeb};
        check_golden("arm64.subs.rrr (x0 x1 x2)", a64_subs(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.subs.rrr: x3 x4 x5 → 83 00 05 eb */
    {
        static const uint8_t exp[] = {0x83, 0x00, 0x05, 0xeb};
        check_golden("arm64.subs.rrr (x3 x4 x5)", a64_subs(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.msub.rrrr: x0 x1 x2 x3 → 20 8c 02 9b */
    {
        static const uint8_t exp[] = {0x20, 0x8c, 0x02, 0x9b};
        check_golden("arm64.msub.rrrr (x0 x1 x2 x3)", a64_msub(A64_X0, A64_X1, A64_X2, A64_X3),
                     exp);
    }

    /* arm64.msub.rrrr: x5 x6 x7 x8 → c5 a0 07 9b */
    {
        static const uint8_t exp[] = {0xc5, 0xa0, 0x07, 0x9b};
        check_golden("arm64.msub.rrrr (x5 x6 x7 x8)", a64_msub(A64_X5, A64_X6, A64_X7, A64_X8),
                     exp);
    }

    /* arm64.add.lsl: x0 x1 x2 3 → 20 0c 02 8b */
    {
        static const uint8_t exp[] = {0x20, 0x0c, 0x02, 0x8b};
        check_golden("arm64.add.lsl (x0 x1 x2 3)", a64_add_lsl(A64_X0, A64_X1, A64_X2, 3), exp);
    }

    /* arm64.add.lsl: x0 x1 x2 0 → 20 00 02 8b */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x02, 0x8b};
        check_golden("arm64.add.lsl (x0 x1 x2 0)", a64_add_lsl(A64_X0, A64_X1, A64_X2, 0), exp);
    }

    /* arm64.add.ri12: x0 x1 1 → 20 04 00 91 */
    {
        static const uint8_t exp[] = {0x20, 0x04, 0x00, 0x91};
        check_golden("arm64.add.ri12 (x0 x1 1)", a64_add_imm(A64_X0, A64_X1, 1), exp);
    }

    /* arm64.add.ri12: x0 x1 42 → 20 a8 00 91 */
    {
        static const uint8_t exp[] = {0x20, 0xa8, 0x00, 0x91};
        check_golden("arm64.add.ri12 (x0 x1 42)", a64_add_imm(A64_X0, A64_X1, 42), exp);
    }

    /* arm64.add.ri12: sp sp 16 → ff 43 00 91 */
    {
        static const uint8_t exp[] = {0xff, 0x43, 0x00, 0x91};
        check_golden("arm64.add.ri12 (sp sp 16)", a64_add_imm(A64_SP, A64_SP, 16), exp);
    }

    /* arm64.sub.ri12: sp sp 16 → ff 43 00 d1 */
    {
        static const uint8_t exp[] = {0xff, 0x43, 0x00, 0xd1};
        check_golden("arm64.sub.ri12 (sp sp 16)", a64_sub_imm(A64_SP, A64_SP, 16), exp);
    }

    /* arm64.sub.ri12: x0 x1 1 → 20 04 00 d1 */
    {
        static const uint8_t exp[] = {0x20, 0x04, 0x00, 0xd1};
        check_golden("arm64.sub.ri12 (x0 x1 1)", a64_sub_imm(A64_X0, A64_X1, 1), exp);
    }

    /* arm64.cmp.ri12: x0 0 → 1f 00 00 f1 */
    {
        static const uint8_t exp[] = {0x1f, 0x00, 0x00, 0xf1};
        check_golden("arm64.cmp.ri12 (x0 0)", a64_cmp_imm(A64_X0, 0), exp);
    }

    /* arm64.cmp.ri12: x1 42 → 3f a8 00 f1 */
    {
        static const uint8_t exp[] = {0x3f, 0xa8, 0x00, 0xf1};
        check_golden("arm64.cmp.ri12 (x1 42)", a64_cmp_imm(A64_X1, 42), exp);
    }

    /* arm64.subs_imm_w: x0 x1 42 → 20 a8 00 71 */
    {
        static const uint8_t exp[] = {0x20, 0xa8, 0x00, 0x71};
        check_golden("arm64.subs_imm_w (x0 x1 42)", a64_subs_imm_w(A64_X0, A64_X1, 42), exp);
    }

    /* arm64.mvn.rr: x0 x1 → e0 03 21 aa */
    {
        static const uint8_t exp[] = {0xe0, 0x03, 0x21, 0xaa};
        check_golden("arm64.mvn.rr (x0 x1)", a64_mvn(A64_X0, A64_X1), exp);
    }

    /* arm64.mvn.rr: x3 x4 → e3 03 24 aa */
    {
        static const uint8_t exp[] = {0xe3, 0x03, 0x24, 0xaa};
        check_golden("arm64.mvn.rr (x3 x4)", a64_mvn(A64_X3, A64_X4), exp);
    }

    /* arm64.mov.rr: x0 x1 → e0 03 01 aa */
    {
        static const uint8_t exp[] = {0xe0, 0x03, 0x01, 0xaa};
        check_golden("arm64.mov.rr (x0 x1)", a64_mov(A64_X0, A64_X1), exp);
    }

    /* arm64.mov.rr: x3 x4 → e3 03 04 aa */
    {
        static const uint8_t exp[] = {0xe3, 0x03, 0x04, 0xaa};
        check_golden("arm64.mov.rr (x3 x4)", a64_mov(A64_X3, A64_X4), exp);
    }

    /* arm64.movz: x0 42 0 → 40 05 80 d2 */
    {
        static const uint8_t exp[] = {0x40, 0x05, 0x80, 0xd2};
        check_golden("arm64.movz (x0 42 0)", a64_movz(A64_X0, 42, 0), exp);
    }

    /* arm64.movz: x0 0xFFFF 16 → e0 ff bf d2 */
    {
        static const uint8_t exp[] = {0xe0, 0xff, 0xbf, 0xd2};
        check_golden("arm64.movz (x0 0xFFFF 16)", a64_movz(A64_X0, 65535, 16), exp);
    }

    /* arm64.movk: x0 42 0 → 40 05 80 f2 */
    {
        static const uint8_t exp[] = {0x40, 0x05, 0x80, 0xf2};
        check_golden("arm64.movk (x0 42 0)", a64_movk(A64_X0, 42, 0), exp);
    }

    /* arm64.movk: x0 0xFFFF 16 → e0 ff bf f2 */
    {
        static const uint8_t exp[] = {0xe0, 0xff, 0xbf, 0xf2};
        check_golden("arm64.movk (x0 0xFFFF 16)", a64_movk(A64_X0, 65535, 16), exp);
    }

    /* arm64.cset: x0 0 → e0 17 9f 9a */
    {
        static const uint8_t exp[] = {0xe0, 0x17, 0x9f, 0x9a};
        check_golden("arm64.cset (x0 0)", a64_cset(A64_X0, 0), exp);
    }

    /* arm64.cset: x0 1 → e0 07 9f 9a */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x9f, 0x9a};
        check_golden("arm64.cset (x0 1)", a64_cset(A64_X0, 1), exp);
    }

    /* arm64.cset: x3 11 → e3 a7 9f 9a */
    {
        static const uint8_t exp[] = {0xe3, 0xa7, 0x9f, 0x9a};
        check_golden("arm64.cset (x3 11)", a64_cset(A64_X3, 11), exp);
    }

    /* arm64.lsl.rrr: x0 x1 x2 → 20 20 c2 9a */
    {
        static const uint8_t exp[] = {0x20, 0x20, 0xc2, 0x9a};
        check_golden("arm64.lsl.rrr (x0 x1 x2)", a64_lsl(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.lsl.rrr: x3 x4 x5 → 83 20 c5 9a */
    {
        static const uint8_t exp[] = {0x83, 0x20, 0xc5, 0x9a};
        check_golden("arm64.lsl.rrr (x3 x4 x5)", a64_lsl(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.asr.rrr: x0 x1 x2 → 20 28 c2 9a */
    {
        static const uint8_t exp[] = {0x20, 0x28, 0xc2, 0x9a};
        check_golden("arm64.asr.rrr (x0 x1 x2)", a64_asr(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.asr.rrr: x3 x4 x5 → 83 28 c5 9a */
    {
        static const uint8_t exp[] = {0x83, 0x28, 0xc5, 0x9a};
        check_golden("arm64.asr.rrr (x3 x4 x5)", a64_asr(A64_X3, A64_X4, A64_X5), exp);
    }

    /* arm64.lsr_imm: x0 x1 4 → 20 7c 04 53 */
    {
        static const uint8_t exp[] = {0x20, 0x7c, 0x04, 0x53};
        check_golden("arm64.lsr_imm (x0 x1 4)", a64_lsr_imm(A64_X0, A64_X1, 4), exp);
    }

    /* arm64.lsr_imm64: x0 x1 4 → 20 fc 44 d3 */
    {
        static const uint8_t exp[] = {0x20, 0xfc, 0x44, 0xd3};
        check_golden("arm64.lsr_imm64 (x0 x1 4)", a64_lsr_imm64(A64_X0, A64_X1, 4), exp);
    }

    /* arm64.csel: x0 x1 x2 0 → 20 00 82 9a */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x82, 0x9a};
        check_golden("arm64.csel (x0 x1 x2 0)", a64_csel(A64_X0, A64_X1, A64_X2, 0), exp);
    }

    /* arm64.csel: x0 x1 x2 1 → 20 10 82 9a */
    {
        static const uint8_t exp[] = {0x20, 0x10, 0x82, 0x9a};
        check_golden("arm64.csel (x0 x1 x2 1)", a64_csel(A64_X0, A64_X1, A64_X2, 1), exp);
    }

    /* arm64.fcsel: x0 x1 x2 0 → 20 0c 62 1e */
    {
        static const uint8_t exp[] = {0x20, 0x0c, 0x62, 0x1e};
        check_golden("arm64.fcsel (x0 x1 x2 0)", a64_fcsel(A64_X0, A64_X1, A64_X2, 0), exp);
    }

    /* arm64.ldr: x0 x1 0 → 20 00 40 f9 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x40, 0xf9};
        check_golden("arm64.ldr (x0 x1 0)", a64_ldr(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldr: x0 sp 8 → e0 07 40 f9 */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x40, 0xf9};
        check_golden("arm64.ldr (x0 sp 8)", a64_ldr(A64_X0, A64_SP, 8), exp);
    }

    /* arm64.ldr: x3 fp 16 → a3 0b 40 f9 */
    {
        static const uint8_t exp[] = {0xa3, 0x0b, 0x40, 0xf9};
        check_golden("arm64.ldr (x3 fp 16)", a64_ldr(A64_X3, A64_FP, 16), exp);
    }

    /* arm64.str: x0 x1 0 → 20 00 00 f9 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x00, 0xf9};
        check_golden("arm64.str (x0 x1 0)", a64_str(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.str: x0 sp 8 → e0 07 00 f9 */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x00, 0xf9};
        check_golden("arm64.str (x0 sp 8)", a64_str(A64_X0, A64_SP, 8), exp);
    }

    /* arm64.ldp: x0 x1 sp 0 → e0 07 40 a9 */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x40, 0xa9};
        check_golden("arm64.ldp (x0 x1 sp 0)", a64_ldp(A64_X0, A64_X1, A64_SP, 0), exp);
    }

    /* arm64.ldp: x0 x1 sp 16 → e0 07 41 a9 */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x41, 0xa9};
        check_golden("arm64.ldp (x0 x1 sp 16)", a64_ldp(A64_X0, A64_X1, A64_SP, 16), exp);
    }

    /* arm64.stp: x0 x1 sp 0 → e0 07 00 a9 */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x00, 0xa9};
        check_golden("arm64.stp (x0 x1 sp 0)", a64_stp(A64_X0, A64_X1, A64_SP, 0), exp);
    }

    /* arm64.stp: x0 x1 sp 16 → e0 07 01 a9 */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x01, 0xa9};
        check_golden("arm64.stp (x0 x1 sp 16)", a64_stp(A64_X0, A64_X1, A64_SP, 16), exp);
    }

    /* arm64.ldrb: x0 x1 0 → 20 00 40 39 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x40, 0x39};
        check_golden("arm64.ldrb (x0 x1 0)", a64_ldrb(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldrb: x0 sp 4 → e0 13 40 39 */
    {
        static const uint8_t exp[] = {0xe0, 0x13, 0x40, 0x39};
        check_golden("arm64.ldrb (x0 sp 4)", a64_ldrb(A64_X0, A64_SP, 4), exp);
    }

    /* arm64.strb: x0 x1 0 → 20 00 00 39 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x00, 0x39};
        check_golden("arm64.strb (x0 x1 0)", a64_strb(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldrsb: x0 x1 0 → 20 00 80 39 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x80, 0x39};
        check_golden("arm64.ldrsb (x0 x1 0)", a64_ldrsb(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldrsb: x0 sp 4 → e0 13 80 39 */
    {
        static const uint8_t exp[] = {0xe0, 0x13, 0x80, 0x39};
        check_golden("arm64.ldrsb (x0 sp 4)", a64_ldrsb(A64_X0, A64_SP, 4), exp);
    }

    /* arm64.ldrh: x0 x1 0 → 20 00 40 79 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x40, 0x79};
        check_golden("arm64.ldrh (x0 x1 0)", a64_ldrh(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldrh: x0 sp 4 → e0 0b 40 79 */
    {
        static const uint8_t exp[] = {0xe0, 0x0b, 0x40, 0x79};
        check_golden("arm64.ldrh (x0 sp 4)", a64_ldrh(A64_X0, A64_SP, 4), exp);
    }

    /* arm64.ldrsh: x0 x1 0 → 20 00 80 79 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x80, 0x79};
        check_golden("arm64.ldrsh (x0 x1 0)", a64_ldrsh(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldrsh: x0 sp 4 → e0 0b 80 79 */
    {
        static const uint8_t exp[] = {0xe0, 0x0b, 0x80, 0x79};
        check_golden("arm64.ldrsh (x0 sp 4)", a64_ldrsh(A64_X0, A64_SP, 4), exp);
    }

    /* arm64.strh: x0 x1 0 → 20 00 00 79 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x00, 0x79};
        check_golden("arm64.strh (x0 x1 0)", a64_strh(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldr_w: x0 x1 0 → 20 00 40 b9 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x40, 0xb9};
        check_golden("arm64.ldr_w (x0 x1 0)", a64_ldr_w(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldr_w: x0 sp 8 → e0 0b 40 b9 */
    {
        static const uint8_t exp[] = {0xe0, 0x0b, 0x40, 0xb9};
        check_golden("arm64.ldr_w (x0 sp 8)", a64_ldr_w(A64_X0, A64_SP, 8), exp);
    }

    /* arm64.str_w: x0 x1 0 → 20 00 00 b9 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x00, 0xb9};
        check_golden("arm64.str_w (x0 x1 0)", a64_str_w(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldrsw: x0 x1 0 → 20 00 80 b9 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x80, 0xb9};
        check_golden("arm64.ldrsw (x0 x1 0)", a64_ldrsw(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldrsw: x0 sp 8 → e0 0b 80 b9 */
    {
        static const uint8_t exp[] = {0xe0, 0x0b, 0x80, 0xb9};
        check_golden("arm64.ldrsw (x0 sp 8)", a64_ldrsw(A64_X0, A64_SP, 8), exp);
    }

    /* arm64.ldr_s: x0 x1 0 → 20 00 40 bd */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x40, 0xbd};
        check_golden("arm64.ldr_s (x0 x1 0)", a64_ldr_s(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.str_s: x0 x1 0 → 20 00 00 bd */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x00, 0xbd};
        check_golden("arm64.str_s (x0 x1 0)", a64_str_s(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldr_fp: x0 x1 0 → 20 00 40 fd */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x40, 0xfd};
        check_golden("arm64.ldr_fp (x0 x1 0)", a64_ldr_fp(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.ldr_fp: x0 sp 8 → e0 07 40 fd */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x40, 0xfd};
        check_golden("arm64.ldr_fp (x0 sp 8)", a64_ldr_fp(A64_X0, A64_SP, 8), exp);
    }

    /* arm64.str_fp: x0 x1 0 → 20 00 00 fd */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x00, 0xfd};
        check_golden("arm64.str_fp (x0 x1 0)", a64_str_fp(A64_X0, A64_X1, 0), exp);
    }

    /* arm64.stp_fp: x0 x1 sp 0 → e0 07 00 6d */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x00, 0x6d};
        check_golden("arm64.stp_fp (x0 x1 sp 0)", a64_stp_fp(A64_X0, A64_X1, A64_SP, 0), exp);
    }

    /* arm64.stp_fp: x0 x1 sp 16 → e0 07 01 6d */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x01, 0x6d};
        check_golden("arm64.stp_fp (x0 x1 sp 16)", a64_stp_fp(A64_X0, A64_X1, A64_SP, 16), exp);
    }

    /* arm64.ldp_fp: x0 x1 sp 0 → e0 07 40 6d */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x40, 0x6d};
        check_golden("arm64.ldp_fp (x0 x1 sp 0)", a64_ldp_fp(A64_X0, A64_X1, A64_SP, 0), exp);
    }

    /* arm64.ldp_fp: x0 x1 sp 16 → e0 07 41 6d */
    {
        static const uint8_t exp[] = {0xe0, 0x07, 0x41, 0x6d};
        check_golden("arm64.ldp_fp (x0 x1 sp 16)", a64_ldp_fp(A64_X0, A64_X1, A64_SP, 16), exp);
    }

    /* arm64.bl: 0 → 00 00 00 94 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0x94};
        check_golden("arm64.bl (0)", a64_bl(0), exp);
    }

    /* arm64.bl: 1 → 01 00 00 94 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0x94};
        check_golden("arm64.bl (1)", a64_bl(1), exp);
    }

    /* arm64.blr: x0 → 00 00 3f d6 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x3f, 0xd6};
        check_golden("arm64.blr (x0)", a64_blr(A64_X0), exp);
    }

    /* arm64.blr: x8 → 00 01 3f d6 */
    {
        static const uint8_t exp[] = {0x00, 0x01, 0x3f, 0xd6};
        check_golden("arm64.blr (x8)", a64_blr(A64_X8), exp);
    }

    /* arm64.blr: lr → c0 03 3f d6 */
    {
        static const uint8_t exp[] = {0xc0, 0x03, 0x3f, 0xd6};
        check_golden("arm64.blr (lr)", a64_blr(A64_LR), exp);
    }

    /* arm64.br: x0 → 00 00 1f d6 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x1f, 0xd6};
        check_golden("arm64.br (x0)", a64_br(A64_X0), exp);
    }

    /* arm64.br: x8 → 00 01 1f d6 */
    {
        static const uint8_t exp[] = {0x00, 0x01, 0x1f, 0xd6};
        check_golden("arm64.br (x8)", a64_br(A64_X8), exp);
    }

    /* arm64.br: lr → c0 03 1f d6 */
    {
        static const uint8_t exp[] = {0xc0, 0x03, 0x1f, 0xd6};
        check_golden("arm64.br (lr)", a64_br(A64_LR), exp);
    }

    /* arm64.ret:  → c0 03 5f d6 */
    {
        static const uint8_t exp[] = {0xc0, 0x03, 0x5f, 0xd6};
        check_golden("arm64.ret ()", a64_ret(), exp);
    }

    /* arm64.b: 0 → 00 00 00 14 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0x14};
        check_golden("arm64.b (0)", a64_b(0), exp);
    }

    /* arm64.b: 1 → 01 00 00 14 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0x14};
        check_golden("arm64.b (1)", a64_b(1), exp);
    }

    /* arm64.b.cond: 0 0 → 00 00 00 54 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0x54};
        check_golden("arm64.b.cond (0 0)", a64_bcond(0, 0), exp);
    }

    /* arm64.b.cond: 1 0 → 01 00 00 54 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0x54};
        check_golden("arm64.b.cond (1 0)", a64_bcond(1, 0), exp);
    }

    /* arm64.b.cond: 11 0 → 0b 00 00 54 */
    {
        static const uint8_t exp[] = {0x0b, 0x00, 0x00, 0x54};
        check_golden("arm64.b.cond (11 0)", a64_bcond(11, 0), exp);
    }

    /* arm64.b.cond: 13 0 → 0d 00 00 54 */
    {
        static const uint8_t exp[] = {0x0d, 0x00, 0x00, 0x54};
        check_golden("arm64.b.cond (13 0)", a64_bcond(13, 0), exp);
    }

    /* arm64.cbz: x0 0 → 00 00 00 b4 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0xb4};
        check_golden("arm64.cbz (x0 0)", a64_cbz(A64_X0, 0), exp);
    }

    /* arm64.cbz: x1 0 → 01 00 00 b4 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0xb4};
        check_golden("arm64.cbz (x1 0)", a64_cbz(A64_X1, 0), exp);
    }

    /* arm64.cbnz: x0 0 → 00 00 00 b5 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x00, 0xb5};
        check_golden("arm64.cbnz (x0 0)", a64_cbnz(A64_X0, 0), exp);
    }

    /* arm64.cbnz: x1 0 → 01 00 00 b5 */
    {
        static const uint8_t exp[] = {0x01, 0x00, 0x00, 0xb5};
        check_golden("arm64.cbnz (x1 0)", a64_cbnz(A64_X1, 0), exp);
    }

    /* arm64.stp.pre: fp lr sp -2 → fd 7b bf a9 */
    {
        static const uint8_t exp[] = {0xfd, 0x7b, 0xbf, 0xa9};
        check_golden("arm64.stp.pre (fp lr sp -2)", a64_stp_pre(A64_FP, A64_LR, A64_SP, -2), exp);
    }

    /* arm64.stp.pre: x19 x20 sp -2 → f3 53 bf a9 */
    {
        static const uint8_t exp[] = {0xf3, 0x53, 0xbf, 0xa9};
        check_golden("arm64.stp.pre (x19 x20 sp -2)", a64_stp_pre(A64_X19, A64_X20, A64_SP, -2),
                     exp);
    }

    /* arm64.ldp.post: fp lr sp 2 → fd 7b c1 a8 */
    {
        static const uint8_t exp[] = {0xfd, 0x7b, 0xc1, 0xa8};
        check_golden("arm64.ldp.post (fp lr sp 2)", a64_ldp_post(A64_FP, A64_LR, A64_SP, 2), exp);
    }

    /* arm64.ldp.post: x19 x20 sp 2 → f3 53 c1 a8 */
    {
        static const uint8_t exp[] = {0xf3, 0x53, 0xc1, 0xa8};
        check_golden("arm64.ldp.post (x19 x20 sp 2)", a64_ldp_post(A64_X19, A64_X20, A64_SP, 2),
                     exp);
    }

    /* arm64.nop:  → 1f 20 03 d5 */
    {
        static const uint8_t exp[] = {0x1f, 0x20, 0x03, 0xd5};
        check_golden("arm64.nop ()", a64_nop(), exp);
    }

    /* arm64.brk: 0 → 00 00 20 d4 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x20, 0xd4};
        check_golden("arm64.brk (0)", a64_brk(0), exp);
    }

    /* arm64.brk: 1 → 20 00 20 d4 */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x20, 0xd4};
        check_golden("arm64.brk (1)", a64_brk(1), exp);
    }

    /* arm64.brk: 0xf000 → 00 00 3e d4 */
    {
        static const uint8_t exp[] = {0x00, 0x00, 0x3e, 0xd4};
        check_golden("arm64.brk (0xf000)", a64_brk(61440), exp);
    }

    /* arm64.brk: 0xff00 → 00 e0 3f d4 */
    {
        static const uint8_t exp[] = {0x00, 0xe0, 0x3f, 0xd4};
        check_golden("arm64.brk (0xff00)", a64_brk(65280), exp);
    }

    /* arm64.neg.rr: x0 x1 → e0 03 01 cb */
    {
        static const uint8_t exp[] = {0xe0, 0x03, 0x01, 0xcb};
        check_golden("arm64.neg.rr (x0 x1)", a64_neg(A64_X0, A64_X1), exp);
    }

    /* arm64.neg.rr: x3 x4 → e3 03 04 cb */
    {
        static const uint8_t exp[] = {0xe3, 0x03, 0x04, 0xcb};
        check_golden("arm64.neg.rr (x3 x4)", a64_neg(A64_X3, A64_X4), exp);
    }

    /* arm64.cmp.rr: x0 x1 → 1f 00 01 eb */
    {
        static const uint8_t exp[] = {0x1f, 0x00, 0x01, 0xeb};
        check_golden("arm64.cmp.rr (x0 x1)", a64_cmp(A64_X0, A64_X1), exp);
    }

    /* arm64.cmp.rr: x3 x4 → 7f 00 04 eb */
    {
        static const uint8_t exp[] = {0x7f, 0x00, 0x04, 0xeb};
        check_golden("arm64.cmp.rr (x3 x4)", a64_cmp(A64_X3, A64_X4), exp);
    }

    /* arm64.fadd: x0 x1 x2 → 20 28 62 1e */
    {
        static const uint8_t exp[] = {0x20, 0x28, 0x62, 0x1e};
        check_golden("arm64.fadd (x0 x1 x2)", a64_fadd(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.fsub: x0 x1 x2 → 20 38 62 1e */
    {
        static const uint8_t exp[] = {0x20, 0x38, 0x62, 0x1e};
        check_golden("arm64.fsub (x0 x1 x2)", a64_fsub(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.fmul: x0 x1 x2 → 20 08 62 1e */
    {
        static const uint8_t exp[] = {0x20, 0x08, 0x62, 0x1e};
        check_golden("arm64.fmul (x0 x1 x2)", a64_fmul(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.fdiv: x0 x1 x2 → 20 18 62 1e */
    {
        static const uint8_t exp[] = {0x20, 0x18, 0x62, 0x1e};
        check_golden("arm64.fdiv (x0 x1 x2)", a64_fdiv(A64_X0, A64_X1, A64_X2), exp);
    }

    /* arm64.fneg: x0 x1 → 20 40 61 1e */
    {
        static const uint8_t exp[] = {0x20, 0x40, 0x61, 0x1e};
        check_golden("arm64.fneg (x0 x1)", a64_fneg(A64_X0, A64_X1), exp);
    }

    /* arm64.fmov.rr: x0 x1 → 20 40 60 1e */
    {
        static const uint8_t exp[] = {0x20, 0x40, 0x60, 0x1e};
        check_golden("arm64.fmov.rr (x0 x1)", a64_fmov(A64_X0, A64_X1), exp);
    }

    /* arm64.fmov.gp_to_fp: x0 x1 → 20 00 67 9e */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x67, 0x9e};
        check_golden("arm64.fmov.gp_to_fp (x0 x1)", a64_fmov_gp_to_fp(A64_X0, A64_X1), exp);
    }

    /* arm64.fmov.to_gpr: x0 x1 → 20 00 66 9e */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x66, 0x9e};
        check_golden("arm64.fmov.to_gpr (x0 x1)", a64_fmov_to_gpr(A64_X0, A64_X1), exp);
    }

    /* arm64.fcmp: x0 x1 → 00 20 61 1e */
    {
        static const uint8_t exp[] = {0x00, 0x20, 0x61, 0x1e};
        check_golden("arm64.fcmp (x0 x1)", a64_fcmp(A64_X0, A64_X1), exp);
    }

    /* arm64.fcmp: x1 x2 → 20 20 62 1e */
    {
        static const uint8_t exp[] = {0x20, 0x20, 0x62, 0x1e};
        check_golden("arm64.fcmp (x1 x2)", a64_fcmp(A64_X1, A64_X2), exp);
    }

    /* arm64.scvtf: x0 x1 → 20 00 62 9e */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x62, 0x9e};
        check_golden("arm64.scvtf (x0 x1)", a64_scvtf(A64_X0, A64_X1), exp);
    }

    /* arm64.fcvtzs: x0 x1 → 20 00 78 9e */
    {
        static const uint8_t exp[] = {0x20, 0x00, 0x78, 0x9e};
        check_golden("arm64.fcvtzs (x0 x1)", a64_fcvtzs(A64_X0, A64_X1), exp);
    }

    /* arm64.fcvt_d_s: x0 x1 → 20 c0 22 1e */
    {
        static const uint8_t exp[] = {0x20, 0xc0, 0x22, 0x1e};
        check_golden("arm64.fcvt_d_s (x0 x1)", a64_fcvt_d_s(A64_X0, A64_X1), exp);
    }

    /* arm64.fcvt_s_d: x0 x1 → 20 40 62 1e */
    {
        static const uint8_t exp[] = {0x20, 0x40, 0x62, 0x1e};
        check_golden("arm64.fcvt_s_d (x0 x1)", a64_fcvt_s_d(A64_X0, A64_X1), exp);
    }

    fprintf(stderr, "golden-bytes: %d passed, %d failed (of 129 total)\n", g_pass, g_fail);
    return g_fail > 0 ? 1 : 0;
}

#else
int main(void) {
    return 0;
}
#endif  // __aarch64__
