/* AUTO-GENERATED by xisagen — DO NOT EDIT */
/* Disassembler round-trip test for riscv64 (cross-platform table lookup). */

#include <stdio.h>
#include <stdint.h>
#include "xm_riscv64_disasm_gen.h"

static int g_pass = 0;
static int g_fail = 0;

static void check_disasm(const char *desc, uint32_t insn, int expected) {
    int got = xm_rv64_disasm(insn);
    if (got != expected) {
        fprintf(stderr, "FAIL: %s (0x%08x): expected %d (%s), got %d (%s)\n",
                desc, insn, expected, xm_rv64_insn_name(expected),
                got, xm_rv64_insn_name(got));
        g_fail++;
    } else {
        g_pass++;
    }
}

int main(void) {
    check_disasm("riscv64.add ['x1', 'x2', 'x3']", 0x003100b3u, XM_RV64_INSN_ADD);
    check_disasm("riscv64.add ['x10', 'x11', 'x12']", 0x00c58533u, XM_RV64_INSN_ADD);
    check_disasm("riscv64.add ['x31', 'x30', 'x29']", 0x01df0fb3u, XM_RV64_INSN_ADD);
    check_disasm("riscv64.sub ['x1', 'x2', 'x3']", 0x403100b3u, XM_RV64_INSN_SUB);
    check_disasm("riscv64.sub ['x10', 'x11', 'x12']", 0x40c58533u, XM_RV64_INSN_SUB);
    check_disasm("riscv64.and ['x1', 'x2', 'x3']", 0x003170b3u, XM_RV64_INSN_AND);
    check_disasm("riscv64.and ['x10', 'x11', 'x12']", 0x00c5f533u, XM_RV64_INSN_AND);
    check_disasm("riscv64.or ['x1', 'x2', 'x3']", 0x003160b3u, XM_RV64_INSN_OR);
    check_disasm("riscv64.or ['x10', 'x11', 'x12']", 0x00c5e533u, XM_RV64_INSN_OR);
    check_disasm("riscv64.xor ['x1', 'x2', 'x3']", 0x003140b3u, XM_RV64_INSN_XOR);
    check_disasm("riscv64.xor ['x10', 'x11', 'x12']", 0x00c5c533u, XM_RV64_INSN_XOR);
    check_disasm("riscv64.sll ['x1', 'x2', 'x3']", 0x003110b3u, XM_RV64_INSN_SLL);
    check_disasm("riscv64.sll ['x10', 'x11', 'x12']", 0x00c59533u, XM_RV64_INSN_SLL);
    check_disasm("riscv64.srl ['x1', 'x2', 'x3']", 0x003150b3u, XM_RV64_INSN_SRL);
    check_disasm("riscv64.srl ['x10', 'x11', 'x12']", 0x00c5d533u, XM_RV64_INSN_SRL);
    check_disasm("riscv64.sra ['x1', 'x2', 'x3']", 0x403150b3u, XM_RV64_INSN_SRA);
    check_disasm("riscv64.sra ['x10', 'x11', 'x12']", 0x40c5d533u, XM_RV64_INSN_SRA);
    check_disasm("riscv64.slt ['x1', 'x2', 'x3']", 0x003120b3u, XM_RV64_INSN_SLT);
    check_disasm("riscv64.slt ['x10', 'x11', 'x12']", 0x00c5a533u, XM_RV64_INSN_SLT);
    check_disasm("riscv64.sltu ['x1', 'x2', 'x3']", 0x003130b3u, XM_RV64_INSN_SLTU);
    check_disasm("riscv64.addw ['x1', 'x2', 'x3']", 0x003100bbu, XM_RV64_INSN_ADDW);
    check_disasm("riscv64.addw ['x10', 'x11', 'x12']", 0x00c5853bu, XM_RV64_INSN_ADDW);
    check_disasm("riscv64.subw ['x1', 'x2', 'x3']", 0x403100bbu, XM_RV64_INSN_SUBW);
    check_disasm("riscv64.subw ['x10', 'x11', 'x12']", 0x40c5853bu, XM_RV64_INSN_SUBW);
    check_disasm("riscv64.sllw ['x1', 'x2', 'x3']", 0x003110bbu, XM_RV64_INSN_SLLW);
    check_disasm("riscv64.srlw ['x1', 'x2', 'x3']", 0x003150bbu, XM_RV64_INSN_SRLW);
    check_disasm("riscv64.sraw ['x1', 'x2', 'x3']", 0x403150bbu, XM_RV64_INSN_SRAW);
    check_disasm("riscv64.addi ['x1', 'x2', '1']", 0x00110093u, XM_RV64_INSN_ADDI);
    check_disasm("riscv64.addi ['x10', 'x11', '-1']", 0xfff58513u, XM_RV64_INSN_ADDI);
    check_disasm("riscv64.addi ['x2', 'x2', '-16']", 0xff010113u, XM_RV64_INSN_ADDI);
    check_disasm("riscv64.andi ['x1', 'x2', '0xFF']", 0x0ff17093u, XM_RV64_INSN_ANDI);
    check_disasm("riscv64.andi ['x10', 'x11', '0x7']", 0x0075f513u, XM_RV64_INSN_ANDI);
    check_disasm("riscv64.ori ['x1', 'x2', '1']", 0x00116093u, XM_RV64_INSN_ORI);
    check_disasm("riscv64.ori ['x10', 'x11', '0xFF']", 0x0ff5e513u, XM_RV64_INSN_ORI);
    check_disasm("riscv64.xori ['x1', 'x2', '1']", 0x00114093u, XM_RV64_INSN_XORI);
    check_disasm("riscv64.slti ['x1', 'x2', '1']", 0x00112093u, XM_RV64_INSN_SLTI);
    check_disasm("riscv64.sltiu ['x1', 'x2', '1']", 0x00113093u, XM_RV64_INSN_SLTIU);
    check_disasm("riscv64.slli ['x1', 'x2', '1']", 0x00111093u, XM_RV64_INSN_SLLI);
    check_disasm("riscv64.slli ['x10', 'x11', '32']", 0x02059513u, XM_RV64_INSN_SLLI);
    check_disasm("riscv64.srli ['x1', 'x2', '1']", 0x00115093u, XM_RV64_INSN_SRAI);
    check_disasm("riscv64.srai ['x1', 'x2', '0x401']", 0x40115093u, XM_RV64_INSN_SRAI);
    check_disasm("riscv64.addiw ['x1', 'x2', '1']", 0x0011009bu, XM_RV64_INSN_ADDIW);
    check_disasm("riscv64.addiw ['x10', 'x11', '-1']", 0xfff5851bu, XM_RV64_INSN_ADDIW);
    check_disasm("riscv64.slliw ['x1', 'x2', '1']", 0x0011109bu, XM_RV64_INSN_SLLIW);
    check_disasm("riscv64.srliw ['x1', 'x2', '1']", 0x0011509bu, XM_RV64_INSN_SRAIW);
    check_disasm("riscv64.sraiw ['x1', 'x2', '0x401']", 0x4011509bu, XM_RV64_INSN_SRAIW);
    check_disasm("riscv64.lb ['x1', 'x2', '0']", 0x00010083u, XM_RV64_INSN_LB);
    check_disasm("riscv64.lh ['x1', 'x2', '0']", 0x00011083u, XM_RV64_INSN_LH);
    check_disasm("riscv64.lw ['x1', 'x2', '0']", 0x00012083u, XM_RV64_INSN_LW);
    check_disasm("riscv64.ld ['x1', 'x2', '0']", 0x00013083u, XM_RV64_INSN_LD);
    check_disasm("riscv64.ld ['x10', 'x8', '8']", 0x00843503u, XM_RV64_INSN_LD);
    check_disasm("riscv64.ld ['x1', 'x2', '-8']", 0xff813083u, XM_RV64_INSN_LD);
    check_disasm("riscv64.lbu ['x1', 'x2', '0']", 0x00014083u, XM_RV64_INSN_LBU);
    check_disasm("riscv64.lhu ['x1', 'x2', '0']", 0x00015083u, XM_RV64_INSN_LHU);
    check_disasm("riscv64.lwu ['x1', 'x2', '0']", 0x00016083u, XM_RV64_INSN_LWU);
    check_disasm("riscv64.sb ['x1', 'x2', '0']", 0x00110023u, XM_RV64_INSN_SB);
    check_disasm("riscv64.sh ['x1', 'x2', '0']", 0x00111023u, XM_RV64_INSN_SH);
    check_disasm("riscv64.sw ['x1', 'x2', '0']", 0x00112023u, XM_RV64_INSN_SW);
    check_disasm("riscv64.sd ['x1', 'x2', '0']", 0x00113023u, XM_RV64_INSN_SD);
    check_disasm("riscv64.sd ['x10', 'x8', '8']", 0x00a43423u, XM_RV64_INSN_SD);
    check_disasm("riscv64.sd ['x1', 'x2', '-8']", 0xfe113c23u, XM_RV64_INSN_SD);
    check_disasm("riscv64.jal ['x1', '0']", 0x000000efu, XM_RV64_INSN_JAL);
    check_disasm("riscv64.jal ['x0', '0']", 0x0000006fu, XM_RV64_INSN_JAL);
    check_disasm("riscv64.jalr ['x1', 'x5', '0']", 0x000280e7u, XM_RV64_INSN_JALR);
    check_disasm("riscv64.jalr ['x0', 'x1', '0']", 0x00008067u, XM_RV64_INSN_JALR);
    check_disasm("riscv64.beq ['x1', 'x2', '0']", 0x00208063u, XM_RV64_INSN_BEQ);
    check_disasm("riscv64.beq ['x10', 'x11', '0']", 0x00b50063u, XM_RV64_INSN_BEQ);
    check_disasm("riscv64.bne ['x1', 'x2', '0']", 0x00209063u, XM_RV64_INSN_BNE);
    check_disasm("riscv64.bne ['x10', 'x11', '0']", 0x00b51063u, XM_RV64_INSN_BNE);
    check_disasm("riscv64.blt ['x1', 'x2', '0']", 0x0020c063u, XM_RV64_INSN_BLT);
    check_disasm("riscv64.blt ['x10', 'x11', '0']", 0x00b54063u, XM_RV64_INSN_BLT);
    check_disasm("riscv64.bge ['x1', 'x2', '0']", 0x0020d063u, XM_RV64_INSN_BGE);
    check_disasm("riscv64.bge ['x10', 'x11', '0']", 0x00b55063u, XM_RV64_INSN_BGE);
    check_disasm("riscv64.bltu ['x1', 'x2', '0']", 0x0020e063u, XM_RV64_INSN_BLTU);
    check_disasm("riscv64.bgeu ['x1', 'x2', '0']", 0x0020f063u, XM_RV64_INSN_BGEU);
    check_disasm("riscv64.lui ['x1', '1']", 0x000010b7u, XM_RV64_INSN_LUI);
    check_disasm("riscv64.lui ['x10', '0xABCDE']", 0xabcde537u, XM_RV64_INSN_LUI);
    check_disasm("riscv64.auipc ['x1', '0']", 0x00000097u, XM_RV64_INSN_AUIPC);
    check_disasm("riscv64.auipc ['x10', '1']", 0x00001517u, XM_RV64_INSN_AUIPC);
    check_disasm("riscv64.nop []", 0x00000013u, XM_RV64_INSN_NOP);
    check_disasm("riscv64.ebreak []", 0x00100073u, XM_RV64_INSN_EBREAK);
    check_disasm("riscv64.mul ['x1', 'x2', 'x3']", 0x023100b3u, XM_RV64_INSN_MUL);
    check_disasm("riscv64.mulh ['x1', 'x2', 'x3']", 0x023110b3u, XM_RV64_INSN_MULH);
    check_disasm("riscv64.mulhu ['x1', 'x2', 'x3']", 0x023130b3u, XM_RV64_INSN_MULHU);
    check_disasm("riscv64.div ['x1', 'x2', 'x3']", 0x023140b3u, XM_RV64_INSN_DIV);
    check_disasm("riscv64.divu ['x1', 'x2', 'x3']", 0x023150b3u, XM_RV64_INSN_DIVU);
    check_disasm("riscv64.rem ['x1', 'x2', 'x3']", 0x023160b3u, XM_RV64_INSN_REM);
    check_disasm("riscv64.remu ['x1', 'x2', 'x3']", 0x023170b3u, XM_RV64_INSN_REMU);
    check_disasm("riscv64.mulw ['x1', 'x2', 'x3']", 0x023100bbu, XM_RV64_INSN_MULW);
    check_disasm("riscv64.divw ['x1', 'x2', 'x3']", 0x023140bbu, XM_RV64_INSN_DIVW);
    check_disasm("riscv64.divuw ['x1', 'x2', 'x3']", 0x023150bbu, XM_RV64_INSN_DIVUW);
    check_disasm("riscv64.remw ['x1', 'x2', 'x3']", 0x023160bbu, XM_RV64_INSN_REMW);
    check_disasm("riscv64.remuw ['x1', 'x2', 'x3']", 0x023170bbu, XM_RV64_INSN_REMUW);
    check_disasm("riscv64.fld ['f1', 'x2', '0']", 0x00013087u, XM_RV64_INSN_FLD);
    check_disasm("riscv64.fsd ['f1', 'x2', '0']", 0x00113027u, XM_RV64_INSN_FSD);
    check_disasm("riscv64.fadd.d ['f1', 'f2', 'f3']", 0x023100d3u, XM_RV64_INSN_FADD_D);
    check_disasm("riscv64.fsub.d ['f1', 'f2', 'f3']", 0x0a3100d3u, XM_RV64_INSN_FSUB_D);
    check_disasm("riscv64.fmul.d ['f1', 'f2', 'f3']", 0x123100d3u, XM_RV64_INSN_FMUL_D);
    check_disasm("riscv64.fdiv.d ['f1', 'f2', 'f3']", 0x1a3100d3u, XM_RV64_INSN_FDIV_D);
    check_disasm("riscv64.fsqrt.d ['f1', 'f2']", 0x5a0100d3u, XM_RV64_INSN_FSQRT_D);
    check_disasm("riscv64.feq.d ['x1', 'f2', 'f3']", 0xa23120d3u, XM_RV64_INSN_FEQ_D);
    check_disasm("riscv64.flt.d ['x1', 'f2', 'f3']", 0xa23110d3u, XM_RV64_INSN_FLT_D);
    check_disasm("riscv64.fle.d ['x1', 'f2', 'f3']", 0xa23100d3u, XM_RV64_INSN_FLE_D);
    check_disasm("riscv64.fcvt.d.l ['f1', 'x2']", 0xd22100d3u, XM_RV64_INSN_FCVT_D_L);
    check_disasm("riscv64.fcvt.l.d ['x1', 'f2']", 0xc22110d3u, XM_RV64_INSN_FCVT_L_D);
    check_disasm("riscv64.fsgnjn.d ['f1', 'f2', 'f2']", 0x222110d3u, XM_RV64_INSN_FSGNJN_D);
    check_disasm("riscv64.fsgnjn.d ['f1', 'f3', 'f3']", 0x223190d3u, XM_RV64_INSN_FSGNJN_D);
    check_disasm("riscv64.fmv.x.d ['x1', 'f2']", 0xe20100d3u, XM_RV64_INSN_FMV_X_D);
    check_disasm("riscv64.fmv.d.x ['f1', 'x2']", 0xf20100d3u, XM_RV64_INSN_FMV_D_X);

    if (g_fail > 0) {
        fprintf(stderr, "%d disasm tests failed, %d passed\n", g_fail, g_pass);
        return 1;
    }
    fprintf(stderr, "All %d disasm tests passed\n", g_pass);
    return 0;
}
