# The signal handler records that the real always-on abort path ran.
# A successful parser or a different fatal cause must not satisfy this check.
if(NOT DEFINED TEST_EXECUTABLE)
    message(FATAL_ERROR "TEST_EXECUTABLE is required")
endif()
foreach(mode IN ITEMS oom overflow)
    execute_process(COMMAND "${TEST_EXECUTABLE}" "${mode}"
        RESULT_VARIABLE result ERROR_VARIABLE diagnostic OUTPUT_VARIABLE output TIMEOUT 15)
    if(NOT "${result}" STREQUAL "73")
        message(FATAL_ERROR "AST ${mode}: expected abort handler 73, got ${result}: ${diagnostic}")
    endif()
    if(mode STREQUAL "oom")
        set(expected "ast_alloc: arena allocation failed")
    else()
        set(expected "ast_alloc_array: array size overflow")
    endif()
    string(FIND "${diagnostic}" "${expected}" at)
    if(at EQUAL -1)
        message(FATAL_ERROR "AST ${mode}: wrong fatal reason: ${diagnostic}")
    endif()
endforeach()
