# All format gates consume the unique owned formatter and parser libraries.
file(MAKE_DIRECTORY "${PROJECT_SOURCE_DIR}/build-formatter-owner")
foreach(name test_xfmt_literal test_formatter_strings test_formatter_comments test_fmt_roundtrip)
    add_executable(${name} "${CMAKE_CURRENT_LIST_DIR}/${name}.c")
    target_link_libraries(${name} PRIVATE xray_frontend_format)
    target_include_directories(${name} PRIVATE "${PROJECT_SOURCE_DIR}/src/base")
    if(MSVC)
        target_compile_options(${name} PRIVATE /W4 /WX /utf-8)
    endif()
    add_test(NAME ${name} COMMAND ${name})
    set_tests_properties(${name} PROPERTIES WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}/build-formatter-owner")
endforeach()
add_executable(test_format_owner "${CMAKE_CURRENT_LIST_DIR}/format_owner/test_format_owner.c")
target_link_libraries(test_format_owner PRIVATE xray_frontend_format)
add_test(NAME test_format_owner COMMAND test_format_owner)
