# Genuine C is generated from the complete bounded Source pipeline.
set(FILL_C "${CMAKE_BINARY_DIR}/generated/xir_array_fill.c")
add_executable(test_xir_array_fill "${PROJECT_SOURCE_DIR}/tests/unit/xir/test_xir_array_fill.c")
target_link_libraries(test_xir_array_fill PRIVATE xray_xir_source xray_xir_vm xray_xir_cgen)
add_custom_command(OUTPUT "${FILL_C}"
    COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/generated"
    COMMAND $<TARGET_FILE:test_xir_array_fill> 0 "${FILL_C}"
    DEPENDS test_xir_array_fill "${PROJECT_SOURCE_DIR}/tests/fixtures/xir_array_fill/transaction/root.xr"
        "${PROJECT_SOURCE_DIR}/tests/fixtures/xir_array_fill/transaction/producer.xr" VERBATIM)
add_executable(test_xir_array_fill_native "${PROJECT_SOURCE_DIR}/tests/unit/xir/test_xir_array_fill.c" "${FILL_C}")
target_link_libraries(test_xir_array_fill_native PRIVATE xray_xir_source xray_xir_vm xray_xir_cgen)
target_compile_definitions(test_xir_array_fill_native PRIVATE XR_FILL_NATIVE=1)
foreach(target test_xir_array_fill test_xir_array_fill_native)
    target_compile_definitions(${target} PRIVATE XR_FILL_FIXTURES="${PROJECT_SOURCE_DIR}/tests/fixtures/xir_array_fill")
    set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /W4 /WX)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror)
    endif()
endforeach()
add_test(NAME test_xir_array_fill_vm COMMAND test_xir_array_fill 0)
add_test(NAME test_xir_array_fill_native COMMAND test_xir_array_fill_native 1)
add_test(NAME test_xir_array_fill_mixed_root COMMAND test_xir_array_fill_native 2)
add_test(NAME test_xir_array_fill_mixed_import COMMAND test_xir_array_fill_native 3)
set_tests_properties(test_xir_array_fill_vm test_xir_array_fill_native test_xir_array_fill_mixed_root
    test_xir_array_fill_mixed_import PROPERTIES TIMEOUT 120 LABELS "unit;xir;array;ownership;execution")
add_test(NAME test_xir_array_fill_source_rejections COMMAND test_xir_array_fill --rejections)
set_tests_properties(test_xir_array_fill_source_rejections PROPERTIES TIMEOUT 120 LABELS "unit;xir;array;ownership;permission")

add_executable(test_xir_array_fill_faults "${PROJECT_SOURCE_DIR}/tests/unit/xir/test_xir_array_fill_faults.c")
add_executable(test_xir_array_fill_faults_native "${PROJECT_SOURCE_DIR}/tests/unit/xir/test_xir_array_fill_faults.c" "${FILL_C}")
target_compile_definitions(test_xir_array_fill_faults_native PRIVATE XR_FILL_NATIVE=1)
foreach(target test_xir_array_fill_faults test_xir_array_fill_faults_native)
    target_link_libraries(${target} PRIVATE xray_xir_source xray_xir_vm xray_xir_cgen)
    target_compile_definitions(${target} PRIVATE XR_FILL_FIXTURES="${PROJECT_SOURCE_DIR}/tests/fixtures/xir_array_fill")
    set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /W4 /WX)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror)
    endif()
endforeach()
foreach(mode RANGE 0 3)
    if(mode EQUAL 0)
        set(executable test_xir_array_fill_faults)
    else()
        set(executable test_xir_array_fill_faults_native)
    endif()
    add_test(NAME test_xir_array_fill_runtime_${mode} COMMAND ${executable} --runtime ${mode})
    set_tests_properties(test_xir_array_fill_runtime_${mode} PROPERTIES TIMEOUT 120
        LABELS "unit;xir;array;ownership;memory;cancel;budget")
    if(WIN32)
        add_test(NAME test_xir_array_fill_compiler_${mode}
            COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/unit/xir/run_array_fill_compiler.py"
            --executable $<TARGET_FILE:${executable}> --mode ${mode} --workers 8
            --reports-root "${CMAKE_BINARY_DIR}/array-fill-compiler/transaction_${mode}")
    else()
        add_test(NAME test_xir_array_fill_compiler_${mode} COMMAND ${executable} --compiler ${mode})
    endif()
    if(ENABLE_ASAN OR ENABLE_SANITIZERS)
        if(mode LESS 2)
            set(fill_compiler_cost 94)
        else()
            set(fill_compiler_cost 168)
        endif()
    else()
        set(fill_compiler_cost 21)
    endif()
    set_tests_properties(test_xir_array_fill_compiler_${mode} PROPERTIES TIMEOUT 300 RUN_SERIAL TRUE COST ${fill_compiler_cost}
        LABELS "unit;xir;array;ownership;memory;budget")
    if(WIN32)
        set_tests_properties(test_xir_array_fill_compiler_${mode} PROPERTIES PROCESSORS 8)
    endif()
endforeach()
