# One complete program and its actual generated native translation unit.
set(RESIZE_C "${CMAKE_BINARY_DIR}/generated/xir_array_resize.c")
add_executable(test_xir_array_resize "${CMAKE_SOURCE_DIR}/tests/unit/xir/test_xir_array_resize.c")
target_link_libraries(test_xir_array_resize PRIVATE xray_xir_source xray_xir_vm xray_xir_cgen)
add_custom_command(OUTPUT "${RESIZE_C}"
    COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/generated"
    COMMAND $<TARGET_FILE:test_xir_array_resize> 0 "${RESIZE_C}"
    DEPENDS test_xir_array_resize "${CMAKE_SOURCE_DIR}/tests/fixtures/xir_array_resize/transaction/root.xr"
        "${CMAKE_SOURCE_DIR}/tests/fixtures/xir_array_resize/transaction/producer.xr" VERBATIM)
add_executable(test_xir_array_resize_native "${CMAKE_SOURCE_DIR}/tests/unit/xir/test_xir_array_resize.c" "${RESIZE_C}")
target_link_libraries(test_xir_array_resize_native PRIVATE xray_xir_source xray_xir_vm xray_xir_cgen)
target_compile_definitions(test_xir_array_resize_native PRIVATE XR_RESIZE_NATIVE=1)
foreach(target test_xir_array_resize test_xir_array_resize_native)
    target_compile_definitions(${target} PRIVATE XR_RESIZE_FIXTURES="${CMAKE_SOURCE_DIR}/tests/fixtures/xir_array_resize")
    set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /W4 /WX)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror)
    endif()
endforeach()
add_test(NAME test_xir_array_resize_vm COMMAND test_xir_array_resize 0)
add_test(NAME test_xir_array_resize_native COMMAND test_xir_array_resize_native 1)
add_test(NAME test_xir_array_resize_mixed_root COMMAND test_xir_array_resize_native 2)
add_test(NAME test_xir_array_resize_mixed_import COMMAND test_xir_array_resize_native 3)
set_tests_properties(test_xir_array_resize_vm test_xir_array_resize_native test_xir_array_resize_mixed_root
    test_xir_array_resize_mixed_import PROPERTIES TIMEOUT 120 LABELS "unit;xir;array;ownership;execution")

set(resize_modes vm native mixed_root mixed_import)
if(WIN32)
    find_package(Python3 COMPONENTS Interpreter REQUIRED)
    foreach(mode RANGE 0 3)
        list(GET resize_modes ${mode} suffix)
        if(mode EQUAL 0)
            set(binary test_xir_array_resize_native)
        else()
            set(binary test_xir_array_resize_native)
        endif()
        add_test(NAME test_xir_array_resize_compiler_${suffix}
            COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/unit/xir/run_array_resize_compiler.py"
                --executable $<TARGET_FILE:${binary}> --mode ${mode} --workers 8
                --reports-root "${CMAKE_BINARY_DIR}/array-resize-compiler-reports/${suffix}"
                --shared-prefix-root "${CMAKE_BINARY_DIR}/array-resize-shared-prefix")
    endforeach()
else()
    add_test(NAME test_xir_array_resize_compiler_vm COMMAND test_xir_array_resize --compiler 0)
    add_test(NAME test_xir_array_resize_compiler_native COMMAND test_xir_array_resize_native --compiler 1)
    add_test(NAME test_xir_array_resize_compiler_mixed_root COMMAND test_xir_array_resize_native --compiler 2)
    add_test(NAME test_xir_array_resize_compiler_mixed_import COMMAND test_xir_array_resize_native --compiler 3)
endif()
set_tests_properties(test_xir_array_resize_compiler_vm test_xir_array_resize_compiler_native
    test_xir_array_resize_compiler_mixed_root test_xir_array_resize_compiler_mixed_import
    PROPERTIES TIMEOUT 300 RUN_SERIAL TRUE LABELS "unit;xir;array;memory;ownership;budget")
if(WIN32)
    set_tests_properties(test_xir_array_resize_compiler_vm test_xir_array_resize_compiler_native
        test_xir_array_resize_compiler_mixed_root test_xir_array_resize_compiler_mixed_import PROPERTIES PROCESSORS 8)
endif()

foreach(group RANGE 1 7)
    set(generated "${CMAKE_BINARY_DIR}/generated/xir_array_resize_matrix${group}.c")
    set(vm "test_xir_array_resize_matrix${group}")
    set(native "${vm}_native")
    add_executable(${vm} "${CMAKE_SOURCE_DIR}/tests/unit/xir/test_xir_array_resize.c")
    add_custom_command(OUTPUT "${generated}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/generated"
        COMMAND $<TARGET_FILE:${vm}> 0 "${generated}"
        DEPENDS ${vm} "${CMAKE_SOURCE_DIR}/tests/fixtures/xir_array_resize/matrix${group}/root.xr"
            "${CMAKE_SOURCE_DIR}/tests/fixtures/xir_array_resize/matrix${group}/producer.xr" VERBATIM)
    add_executable(${native} "${CMAKE_SOURCE_DIR}/tests/unit/xir/test_xir_array_resize.c" "${generated}")
    target_compile_definitions(${native} PRIVATE XR_RESIZE_NATIVE=1)
    foreach(target ${vm} ${native})
        target_link_libraries(${target} PRIVATE xray_xir_source xray_xir_vm xray_xir_cgen)
        target_compile_definitions(${target} PRIVATE XR_RESIZE_MATRIX=${group} XR_RESIZE_COMPONENT="matrix${group}"
            XR_RESIZE_FIXTURES="${CMAKE_SOURCE_DIR}/tests/fixtures/xir_array_resize")
        set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
        if(MSVC)
            target_compile_options(${target} PRIVATE /utf-8 /W4 /WX)
        else()
            target_compile_options(${target} PRIVATE -Wall -Wextra -Werror)
        endif()
    endforeach()
    add_test(NAME ${vm}_vm COMMAND ${vm} 0)
    add_test(NAME ${vm}_native COMMAND ${native} 1)
    add_test(NAME ${vm}_mixed_root COMMAND ${native} 2)
    add_test(NAME ${vm}_mixed_import COMMAND ${native} 3)
    set_tests_properties(${vm}_vm ${vm}_native ${vm}_mixed_root ${vm}_mixed_import
        PROPERTIES TIMEOUT 120 LABELS "unit;xir;array;memory;ownership;execution")
    if(group GREATER 0)
        foreach(mode RANGE 0 3)
            list(GET resize_modes ${mode} suffix)
            if(mode EQUAL 0)
                set(binary ${native})
            else()
                set(binary ${native})
            endif()
            if(WIN32)
                add_test(NAME ${vm}_compiler_${suffix}
                    COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/unit/xir/run_array_resize_compiler.py"
                        --executable $<TARGET_FILE:${binary}> --mode ${mode} --workers 8 --component matrix${group}
                        --reports-root "${CMAKE_BINARY_DIR}/array-resize-compiler-reports/matrix${group}_${suffix}"
                        --shared-prefix-root "${CMAKE_BINARY_DIR}/array-resize-shared-prefix")
            else()
                add_test(NAME ${vm}_compiler_${suffix} COMMAND ${binary} --compiler ${mode})
            endif()
            set_tests_properties(${vm}_compiler_${suffix} PROPERTIES TIMEOUT 300 RUN_SERIAL TRUE
                LABELS "unit;xir;array;memory;ownership;budget")
            if(WIN32)
                set_tests_properties(${vm}_compiler_${suffix} PROPERTIES PROCESSORS 8)
            endif()
        endforeach()
    endif()
endforeach()

add_test(NAME test_xir_array_resize_rejections COMMAND test_xir_array_resize --rejections)
set_tests_properties(test_xir_array_resize_rejections PROPERTIES TIMEOUT 120 LABELS "unit;xir;array;permissions")

# Scheduling costs are measured parent times; resource limits and deadlines stay fixed.
if(ENABLE_ASAN)
    set_tests_properties(test_xir_array_resize_compiler_mixed_import PROPERTIES COST 226)
    set_tests_properties(test_xir_array_resize_compiler_mixed_root PROPERTIES COST 234)
    set_tests_properties(test_xir_array_resize_compiler_native PROPERTIES COST 110)
    set_tests_properties(test_xir_array_resize_compiler_vm PROPERTIES COST 95)
    set_tests_properties(test_xir_array_resize_matrix1_compiler_mixed_import PROPERTIES COST 62)
    set_tests_properties(test_xir_array_resize_matrix1_compiler_mixed_root PROPERTIES COST 62)
    set_tests_properties(test_xir_array_resize_matrix1_compiler_native PROPERTIES COST 32)
    set_tests_properties(test_xir_array_resize_matrix1_compiler_vm PROPERTIES COST 39)
    set_tests_properties(test_xir_array_resize_matrix2_compiler_mixed_import PROPERTIES COST 61)
    set_tests_properties(test_xir_array_resize_matrix2_compiler_mixed_root PROPERTIES COST 62)
    set_tests_properties(test_xir_array_resize_matrix2_compiler_native PROPERTIES COST 31)
    set_tests_properties(test_xir_array_resize_matrix2_compiler_vm PROPERTIES COST 35)
    set_tests_properties(test_xir_array_resize_matrix3_compiler_mixed_import PROPERTIES COST 162)
    set_tests_properties(test_xir_array_resize_matrix3_compiler_mixed_root PROPERTIES COST 134)
    set_tests_properties(test_xir_array_resize_matrix3_compiler_native PROPERTIES COST 56)
    set_tests_properties(test_xir_array_resize_matrix3_compiler_vm PROPERTIES COST 64)
    set_tests_properties(test_xir_array_resize_matrix4_compiler_mixed_import PROPERTIES COST 233)
    set_tests_properties(test_xir_array_resize_matrix4_compiler_mixed_root PROPERTIES COST 178)
    set_tests_properties(test_xir_array_resize_matrix4_compiler_native PROPERTIES COST 128)
    set_tests_properties(test_xir_array_resize_matrix4_compiler_vm PROPERTIES COST 156)
    set_tests_properties(test_xir_array_resize_matrix5_compiler_mixed_import PROPERTIES COST 42)
    set_tests_properties(test_xir_array_resize_matrix5_compiler_mixed_root PROPERTIES COST 43)
    set_tests_properties(test_xir_array_resize_matrix5_compiler_native PROPERTIES COST 23)
    set_tests_properties(test_xir_array_resize_matrix5_compiler_vm PROPERTIES COST 27)
    set_tests_properties(test_xir_array_resize_matrix6_compiler_mixed_import PROPERTIES COST 8)
    set_tests_properties(test_xir_array_resize_matrix6_compiler_mixed_root PROPERTIES COST 8)
    set_tests_properties(test_xir_array_resize_matrix6_compiler_native PROPERTIES COST 5)
    set_tests_properties(test_xir_array_resize_matrix6_compiler_vm PROPERTIES COST 6)
    set_tests_properties(test_xir_array_resize_matrix7_compiler_mixed_import PROPERTIES COST 22)
    set_tests_properties(test_xir_array_resize_matrix7_compiler_mixed_root PROPERTIES COST 22)
    set_tests_properties(test_xir_array_resize_matrix7_compiler_native PROPERTIES COST 11)
    set_tests_properties(test_xir_array_resize_matrix7_compiler_vm PROPERTIES COST 12)
else()
    set_tests_properties(test_xir_array_resize_compiler_mixed_import PROPERTIES COST 26)
    set_tests_properties(test_xir_array_resize_compiler_mixed_root PROPERTIES COST 27)
    set_tests_properties(test_xir_array_resize_compiler_native PROPERTIES COST 12)
    set_tests_properties(test_xir_array_resize_compiler_vm PROPERTIES COST 13)
    set_tests_properties(test_xir_array_resize_matrix1_compiler_mixed_import PROPERTIES COST 12)
    set_tests_properties(test_xir_array_resize_matrix1_compiler_mixed_root PROPERTIES COST 12)
    set_tests_properties(test_xir_array_resize_matrix1_compiler_native PROPERTIES COST 6)
    set_tests_properties(test_xir_array_resize_matrix1_compiler_vm PROPERTIES COST 7)
    set_tests_properties(test_xir_array_resize_matrix2_compiler_mixed_import PROPERTIES COST 13)
    set_tests_properties(test_xir_array_resize_matrix2_compiler_mixed_root PROPERTIES COST 12)
    set_tests_properties(test_xir_array_resize_matrix2_compiler_native PROPERTIES COST 7)
    set_tests_properties(test_xir_array_resize_matrix2_compiler_vm PROPERTIES COST 7)
    set_tests_properties(test_xir_array_resize_matrix3_compiler_mixed_import PROPERTIES COST 20)
    set_tests_properties(test_xir_array_resize_matrix3_compiler_mixed_root PROPERTIES COST 21)
    set_tests_properties(test_xir_array_resize_matrix3_compiler_native PROPERTIES COST 10)
    set_tests_properties(test_xir_array_resize_matrix3_compiler_vm PROPERTIES COST 12)
    set_tests_properties(test_xir_array_resize_matrix4_compiler_mixed_import PROPERTIES COST 26)
    set_tests_properties(test_xir_array_resize_matrix4_compiler_mixed_root PROPERTIES COST 26)
    set_tests_properties(test_xir_array_resize_matrix4_compiler_native PROPERTIES COST 13)
    set_tests_properties(test_xir_array_resize_matrix4_compiler_vm PROPERTIES COST 17)
    set_tests_properties(test_xir_array_resize_matrix5_compiler_mixed_import PROPERTIES COST 6)
    set_tests_properties(test_xir_array_resize_matrix5_compiler_mixed_root PROPERTIES COST 6)
    set_tests_properties(test_xir_array_resize_matrix5_compiler_native PROPERTIES COST 3)
    set_tests_properties(test_xir_array_resize_matrix5_compiler_vm PROPERTIES COST 4)
    set_tests_properties(test_xir_array_resize_matrix6_compiler_mixed_import PROPERTIES COST 2)
    set_tests_properties(test_xir_array_resize_matrix6_compiler_mixed_root PROPERTIES COST 2)
    set_tests_properties(test_xir_array_resize_matrix6_compiler_native PROPERTIES COST 1)
    set_tests_properties(test_xir_array_resize_matrix6_compiler_vm PROPERTIES COST 1)
    set_tests_properties(test_xir_array_resize_matrix7_compiler_mixed_import PROPERTIES COST 4)
    set_tests_properties(test_xir_array_resize_matrix7_compiler_mixed_root PROPERTIES COST 4)
    set_tests_properties(test_xir_array_resize_matrix7_compiler_native PROPERTIES COST 2)
    set_tests_properties(test_xir_array_resize_matrix7_compiler_vm PROPERTIES COST 3)
endif()

# A common prefix is executed once; each original mode retains its complete seal tail and axes.
if(WIN32)
    foreach(group RANGE 0 7)
        if(group EQUAL 0)
            set(component transaction)
            set(base test_xir_array_resize)
        else()
            set(component "matrix${group}")
            set(base "test_xir_array_resize_matrix${group}")
        endif()
        set(prefix "${base}_compiler_prefix")
        add_test(NAME ${prefix} COMMAND "${Python3_EXECUTABLE}"
            "${CMAKE_SOURCE_DIR}/tests/unit/xir/run_array_resize_compiler.py"
            --executable $<TARGET_FILE:${base}_native> --mode 0 --workers 8 --component ${component}
            --prefix-only --shared-prefix-root "${CMAKE_BINARY_DIR}/array-resize-shared-prefix"
            --reports-root "${CMAKE_BINARY_DIR}/array-resize-compiler-reports/${component}_prefix")
        set_tests_properties(${prefix} PROPERTIES TIMEOUT 300 RUN_SERIAL TRUE PROCESSORS 8
            LABELS "unit;xir;array;memory;ownership;budget")
        foreach(suffix IN LISTS resize_modes)
            set_tests_properties(${base}_compiler_${suffix} PROPERTIES DEPENDS ${prefix})
        endforeach()
    endforeach()
endif()
