set(ATOMIC_BACKEND_WRAPPERS xir/xir_atomic_a2_backend_value.c xir/xir_atomic_a2_backend_call.c xir/xir_atomic_a2_backend_instance.c)
add_executable(test_xir_atomic_a2_retry_vm xir/test_xir_atomic_a2_retry_vm.c ${ATOMIC_BACKEND_WRAPPERS})
target_link_libraries(test_xir_atomic_a2_retry_vm PRIVATE xray_xir_source xray_xir_vm xray_xir_cgen)
target_include_directories(test_xir_atomic_a2_retry_vm PRIVATE ${XRAY_COMMON_INCLUDES} ${CMAKE_BINARY_DIR}/generated)
target_compile_definitions(test_xir_atomic_a2_retry_vm PRIVATE XR_ATOMIC_A2_FIXTURES="${PROJECT_SOURCE_DIR}/tests/fixtures/xir_atomic_a2_retry" XR_ATOMIC_A2_STDLIB="${PROJECT_SOURCE_DIR}/stdlib")
set(ATOMIC_RETRY_NATIVE "${CMAKE_CURRENT_BINARY_DIR}/atomic-a2-retry-native.c")
add_custom_command(OUTPUT "${ATOMIC_RETRY_NATIVE}"
    COMMAND $<TARGET_FILE:test_xir_atomic_a2_retry_vm> "${ATOMIC_RETRY_NATIVE}"
    DEPENDS test_xir_atomic_a2_retry_vm "${PROJECT_SOURCE_DIR}/tests/fixtures/xir_atomic_a2_retry/root.xr" VERBATIM)
add_executable(test_xir_atomic_a2_retry_native xir/test_xir_atomic_a2_retry_native.c ${ATOMIC_BACKEND_WRAPPERS} "${ATOMIC_RETRY_NATIVE}")
target_link_libraries(test_xir_atomic_a2_retry_native PRIVATE xray_xir_scalar xray_compile_resources)
target_include_directories(test_xir_atomic_a2_retry_native PRIVATE ${XRAY_COMMON_INCLUDES} ${CMAKE_BINARY_DIR}/generated)
foreach(target test_xir_atomic_a2_retry_vm test_xir_atomic_a2_retry_native)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /WX /utf-8)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
    add_test(NAME ${target} COMMAND ${target})
    set_tests_properties(${target} PROPERTIES LABELS "unit;xir;ownership;execution;generated-c" TIMEOUT 60)
endforeach()
