add_executable(test_xir_atomic_admission_owner xir/test_xir_atomic_admission_owner.c)
target_link_libraries(test_xir_atomic_admission_owner PRIVATE xray_xir_source)
target_include_directories(test_xir_atomic_admission_owner PRIVATE ${XRAY_COMMON_INCLUDES} ${CMAKE_BINARY_DIR}/generated)
target_compile_definitions(test_xir_atomic_admission_owner PRIVATE XR_ATOMIC_STDLIB="${PROJECT_SOURCE_DIR}/stdlib")
add_dependencies(test_xir_atomic_admission_owner gen-xir-core-source gen-stdlib-embedded-sources)
if(MSVC)
    target_compile_options(test_xir_atomic_admission_owner PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_atomic_admission_owner PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_atomic_admission_owner COMMAND test_xir_atomic_admission_owner)
set_tests_properties(test_xir_atomic_admission_owner PROPERTIES LABELS "unit;xir;metadata;ownership" TIMEOUT 300)
