if(NOT WIN32)
    return()
endif()
add_executable(test_cgen_bytes_owner "${CMAKE_CURRENT_LIST_DIR}/cgen_bytes_owner/test_cgen_bytes_owner.c")
target_link_libraries(test_cgen_bytes_owner PRIVATE xray_xir_cgen)
target_include_directories(test_cgen_bytes_owner PRIVATE "${PROJECT_SOURCE_DIR}/src" "${PROJECT_SOURCE_DIR}/include")
target_compile_definitions(test_cgen_bytes_owner PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
set_target_properties(test_cgen_bytes_owner PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
target_compile_options(test_cgen_bytes_owner PRIVATE /W4 /WX /utf-8)
if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
    target_compile_options(test_cgen_bytes_owner PRIVATE /experimental:c11atomics)
endif()
add_test(NAME cgen_bytes_owner COMMAND test_cgen_bytes_owner)
set_tests_properties(cgen_bytes_owner PROPERTIES TIMEOUT 30 LABELS "unit;xir;ownership;budget")
