# Canonical declaration proof implementation with actual compiler allocation observation.
add_executable(test_xir_declaration_proof_scratch xir/test_xir_declaration_proof_scratch.c)
target_link_libraries(test_xir_declaration_proof_scratch PRIVATE xray_xir)
if(MSVC)
    target_compile_options(test_xir_declaration_proof_scratch PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_declaration_proof_scratch PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_declaration_proof_scratch COMMAND test_xir_declaration_proof_scratch)
set_tests_properties(test_xir_declaration_proof_scratch PROPERTIES LABELS "unit;xir;metadata;ownership" TIMEOUT 300)
