add_executable(test_xir_library_generics_source ${CMAKE_CURRENT_LIST_DIR}/test_xir_library_generics_source.c ${CMAKE_CURRENT_LIST_DIR}/xir_library_generics_runtime.c)
target_link_libraries(test_xir_library_generics_source PRIVATE xray_xir_source xray_xir_vm xray_xir_cgen)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/library-generic-work")
target_compile_definitions(test_xir_library_generics_source PRIVATE XR_GENERIC_LIBRARY_WORK="${CMAKE_CURRENT_BINARY_DIR}/library-generic-work")
set(generic_library_base "${CMAKE_CURRENT_BINARY_DIR}/generated/generic-library")
set(generic_library_sources)
set(generic_library_outputs)
foreach(mode RANGE 0 3)
  list(APPEND generic_library_sources "${generic_library_base}.${mode}.c")
  list(APPEND generic_library_outputs "${generic_library_base}.${mode}.c" "${generic_library_base}.${mode}.c.h")
endforeach()
add_custom_command(OUTPUT ${generic_library_outputs}
  COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/generated"
  COMMAND $<TARGET_FILE:test_xir_library_generics_source> ${generic_library_base}
  DEPENDS test_xir_library_generics_source VERBATIM)
set_source_files_properties(${generic_library_sources} PROPERTIES GENERATED TRUE)
add_executable(test_xir_library_generics_native ${CMAKE_CURRENT_LIST_DIR}/test_xir_library_generics_native.c ${generic_library_sources})
target_include_directories(test_xir_library_generics_native PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated")
target_link_libraries(test_xir_library_generics_native PRIVATE xray_xir_vm)
foreach(target test_xir_library_generics_source test_xir_library_generics_native)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /WX)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Werror)
  endif()
  add_test(NAME ${target} COMMAND ${target})
  set_tests_properties(${target} PROPERTIES LABELS "unit;xir;execution;ownership;abi")
endforeach()
