# Each graph has a separate producer, generated image and fixed runtime oracle.
function(xr_add_ordinary_live_limit_graph suffix fixture modules functions)
    set(_oll_dir "${CMAKE_BINARY_DIR}/generated/ordinary_live_limit_${suffix}")
    set(_oll_c "${_oll_dir}/ordinary_live_limit.c")
    set(_oll_h "${_oll_dir}/ordinary_live_limit_generated.h")
    set(_oll_producer "test_xir_ordinary_live_limit_${suffix}_producer")
    add_executable(${_oll_producer} "${CMAKE_CURRENT_LIST_DIR}/test_xir_ordinary_live_limit_producer.c")
    target_link_libraries(${_oll_producer} PRIVATE xray_xir_source xray_xir_cgen)
    set(_oll_definitions OLL_MODULES=${modules}u OLL_FUNCTIONS=${functions}u
        OLL_FIXTURE_DIRECTORY="${CMAKE_CURRENT_LIST_DIR}/fixtures/${fixture}")
    if(suffix STREQUAL "ready")
        list(APPEND _oll_definitions OLL_READY_GRAPH=1)
    endif()
    target_compile_definitions(${_oll_producer} PRIVATE ${_oll_definitions})
    file(GLOB _oll_inputs CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/fixtures/${fixture}/*.xr")
    add_custom_command(OUTPUT "${_oll_c}" "${_oll_h}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${_oll_dir}"
        COMMAND $<TARGET_FILE:${_oll_producer}> "${_oll_c}" "${_oll_h}"
        DEPENDS ${_oll_producer} ${_oll_inputs} "${CMAKE_CURRENT_LIST_DIR}/ordinary_live_limit_compile.h"
        VERBATIM)
    foreach(_oll_kind native mixed)
        set(_oll_target "test_xir_ordinary_live_limit_${suffix}_${_oll_kind}")
        add_executable(${_oll_target} "${CMAKE_CURRENT_LIST_DIR}/test_xir_ordinary_live_limit.c" "${_oll_c}" "${_oll_h}")
        target_compile_definitions(${_oll_target} PRIVATE ${_oll_definitions})
        target_include_directories(${_oll_target} PRIVATE "${_oll_dir}")
        target_link_libraries(${_oll_target} PRIVATE xray_xir_scalar)
        if(_oll_kind STREQUAL "mixed")
            target_compile_definitions(${_oll_target} PRIVATE OLL_VM=1)
            target_link_libraries(${_oll_target} PRIVATE xray_xir_source xray_xir_vm)
        endif()
        xr_enable_pure_aot_symbol_map(${_oll_target})
    endforeach()
    foreach(_oll_target ${_oll_producer} test_xir_ordinary_live_limit_${suffix}_native test_xir_ordinary_live_limit_${suffix}_mixed)
        set_target_properties(${_oll_target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
        if(MSVC)
            target_compile_options(${_oll_target} PRIVATE /utf-8 /W4 /WX)
        else()
            target_compile_options(${_oll_target} PRIVATE -Wall -Wextra -Werror)
        endif()
    endforeach()
    foreach(_oll_mode source vm native native-vm vm-native)
        if(_oll_mode STREQUAL "native")
            set(_oll_target "test_xir_ordinary_live_limit_${suffix}_native")
        else()
            set(_oll_target "test_xir_ordinary_live_limit_${suffix}_mixed")
        endif()
        string(REPLACE "-" "_" _oll_name "${_oll_mode}")
        add_test(NAME test_xir_ordinary_live_limit_${suffix}_${_oll_name} COMMAND ${_oll_target} "${_oll_mode}")
        set_tests_properties(test_xir_ordinary_live_limit_${suffix}_${_oll_name} PROPERTIES
            TIMEOUT 120 RUN_SERIAL TRUE PROCESSORS 1 LABELS "unit;xir;program;instance;source;generated-c;resources;ownership;abi")
    endforeach()
endfunction()
# The independent READY graph does not replace the original 25-module graph.
xr_add_ordinary_live_limit_graph(ready ordinary_live_limit_ready 18 37)
