add_executable(test_xir_range_check "${PROJECT_SOURCE_DIR}/tests/unit/xir/test_xir_range_check.c")
target_link_libraries(test_xir_range_check PRIVATE xray_xir_vm)
set_target_properties(test_xir_range_check PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
if(MSVC)
    target_compile_options(test_xir_range_check PRIVATE /utf-8 /W4 /WX)
else()
    target_compile_options(test_xir_range_check PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_range_check COMMAND test_xir_range_check)
set_tests_properties(test_xir_range_check PROPERTIES TIMEOUT 120 LABELS "unit;xir;memory;ownership;budget")
