"""Independent dependency graph and formatter expectations; never infer an oracle from execution."""
from __future__ import annotations
import argparse
import hashlib
import io
import json
import os
from pathlib import Path
import re
import subprocess
import tarfile
import tempfile

CAPS=(1073741824,268435456,8589934592)

def expected_reports(entry, rows):
    std=[p for _,k,p,_ in rows if k==0]
    packages=[p for _,k,p,_ in rows if k==2]
    local=[p for _,k,p,_ in rows if k==1 and p!=entry]
    q=lambda s:json.dumps(s,ensure_ascii=False)
    js='{\n  "entry": '+q(entry)+',\n  "stdlib": ['+', '.join(map(q,std))+'],\n'
    js+='  "packages": ['+', '.join(map(q,packages))+'],\n'
    js+='  "local_modules": ['+', '.join(map(q,local))+']\n}\n'
    listing=''
    for title,values in [('Stdlib',std),('Third-party packages',packages),('Local modules',local)]:
        if values: listing+='# '+title+'\n'+'\n'.join(values)+'\n'
    shell='#!/bin/bash\n# Dependency install script\n# Auto-generated by xray deps\n# Entry: '+entry+'\n\nset -e\n\n'
    if packages:
        shell+='echo "Installing third-party package dependencies..."\n'
        shell+=''.join('xray pkg add '+"'"+p.replace("'", "'\\''")+"'"+'\n' for p in packages)+'\necho "All dependencies installed"\n'
    else: shell+='echo "No third-party package dependencies"\n'
    if std: shell+='\n# Stdlib dependencies (built-in, no install needed):\n'+''.join('#   - '+p+'\n' for p in std)
    return {'.sh':shell.encode(),'.json':js.encode(),'.list':listing.encode()}

def fixture(root):
    sources={
        'root.xr':'import { left } from "./left"\nimport { right } from "./right"\n'
          'import { single } from "./single"\nimport { value } from "fixture/math"\n'
          'export fn answer()->i64 { return left()+right()+single()+value() }\n',
        'left.xr':'import { shared } from "./shared"\nexport fn left()->i64 { return shared() }\n',
        'right.xr':'import { shared } from "./shared"\nexport fn right()->i64 { return shared() }\n',
        'shared.xr':'export fn shared()->i64 { return 10 }\n',
        'single.xr':'export fn single()->i64 { return 1 }\n',
        'io.xr':'import "std/io/output" as output\nexport fn answer()->bool { return output.writeStdout("41\\n") }\n',
        'bad.xr':'export fn broken()->i64 { return "wrong" }\n',
        'missing.xr':'import "./absent"\n',
        'cycle.xr':'import "./cyclepeer"\n',
        'cyclepeer.xr':'import "./cycle"\n',
    }
    for name,content in sources.items(): (root/name).write_text(content,encoding='utf-8')
    pkg=root/'.xray/packages/fixture/math/1.0.0';pkg.mkdir(parents=True,exist_ok=True)
    files={'main.xr':'import { part } from "./part"\nexport fn value()->i64 { return part() }\n',
        'part.xr':'export fn part()->i64 { return 20 }\n'}
    cache=root/'.xray/cache';cache.mkdir(parents=True,exist_ok=True)
    archive=cache/'fixture-math-1.0.0.tar.gz'
    with tarfile.open(archive,'w:gz') as out:
        for name,content in files.items():
            data=content.encode();(pkg/name).write_bytes(data);info=tarfile.TarInfo(name);info.size=len(data)
            out.addfile(info,io.BytesIO(data))
    # BFS source discovery: root=0,left=1,right=2,single=3,package=4,shared=5,part=6.
    # Tarjan emits dependency first, in source import order. No runtime measurement is used.
    path=lambda p:str(p.resolve())
    rows=[(5,1,path(root/'shared.xr'),[]),(1,1,path(root/'left.xr'),[5]),
        (2,1,path(root/'right.xr'),[5]),(3,1,path(root/'single.xr'),[]),
        (6,2,path(pkg/'part.xr'),[]),(4,2,path(pkg/'main.xr'),[6]),
        (0,1,path(root/'root.xr'),[1,2,3,4])]
    return 'sha256:'+hashlib.sha256(archive.read_bytes()).hexdigest(),rows

def invoke(args, root, case, checksum, rows):
    entry=root/('root.xr' if case=='package' else 'io.xr' if case in ('raw-io','catalog-io') else case+'.xr')
    prefix=root/(case+'-report')
    for suffix in ('.sh','.json','.list'):
        Path(str(prefix)+suffix).unlink(missing_ok=True)
    route='catalog' if case=='catalog-io' else 'raw'
    expected=args.expected if args.expected is not None else (9 if case in ('bad','missing','cycle') else 0)
    command=[str(args.binary),str(root),str(entry),str(args.stdlib),checksum if case=='package' else '-',route,
        str(prefix),str(expected),str(args.index) if args.index is not None else 'none',*map(str,args.caps)]
    if args.retry_expected is not None: command.append(str(args.retry_expected))
    result=subprocess.run(command,env=dict(os.environ,HOME=str(root),USERPROFILE=str(root)),
        capture_output=True,text=True,encoding='utf-8',timeout=120)
    print(result.stdout,end='');print(result.stderr,end='',file=__import__('sys').stderr)
    if result.returncode: raise AssertionError((command,result.returncode,result.stdout,result.stderr))
    assert result.stdout.rstrip().endswith('PHYSICAL blocks=0 bytes=0')
    census=re.findall(r'CENSUS attempts=(\d+) allocated=(\d+) peak=(\d+) work=(\d+) live=(\d+) status=(\d+) injected=(\d+)',result.stdout)
    assert len(census)==1 and int(census[0][5])==expected
    if args.index is not None: assert int(census[0][0])>args.index and census[0][6]=='1' and expected==6
    actual_success=(args.retry_expected if args.retry_expected is not None else expected)==0
    if not actual_success:
        assert not any(Path(str(prefix)+s).exists() for s in ('.sh','.json','.list'))
        return
    if case in ('raw-io','catalog-io'): rows=[(1,0,'io',[]),(0,1,str(entry.resolve()),[1])]
    assert rows is not None
    graph=re.search(r'GRAPH count=(\d+) entry=(\d+) viewmodules=(\d+)',result.stdout)
    assert graph and int(graph[1])==len(rows) and int(graph[2])==len(rows)-1 and int(graph[3])>=len(rows)
    parsed=[]
    for row in re.finditer(r'^ROW (\d+) module=(\d+) kind=(\d+) imports=([0-9,]*) path=(.*)$',result.stdout,re.M):
        assert int(row[1])==len(parsed)
        parsed.append((int(row[2]),int(row[3]),row[5],list(map(int,row[4].split(','))) if row[4] else []))
    assert parsed==rows,(parsed,rows)
    for suffix,expected_bytes in expected_reports(str(entry.resolve()),rows).items():
        actual=Path(str(prefix)+suffix).read_bytes()
        assert actual==expected_bytes,(case,suffix,actual,expected_bytes)

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('binary',type=Path);parser.add_argument('stdlib',type=Path)
    parser.add_argument('--case',choices=['package','raw-io','catalog-io','bad','missing','cycle'])
    parser.add_argument('--directory',type=Path)
    parser.add_argument('--index',type=int)
    parser.add_argument('--caps',nargs=3,type=int,default=CAPS)
    parser.add_argument('--expected',type=int)
    parser.add_argument('--retry-expected',type=int)
    args=parser.parse_args();args.binary=args.binary.resolve();args.stdlib=args.stdlib.resolve()
    if args.index is not None:
        if not args.case or args.index<0 or args.expected!=6: parser.error('FI requires one case, nonnegative index and --expected 6')
    if args.retry_expected is not None and not args.case: parser.error('retry requires one case')
    def run(root):
        root.mkdir(parents=True,exist_ok=True)
        checksum,rows=fixture(root)
        for case in [args.case] if args.case else ['package','raw-io','catalog-io','bad','missing','cycle']:
            invoke(args,root,case,checksum,rows if case=='package' else None)
    if args.directory: run(args.directory.resolve())
    else:
        with tempfile.TemporaryDirectory(prefix='xir-deps-') as directory: run(Path(directory))

if __name__ == "__main__":
    main()
