add_executable(test_xir_semantic65_vectors xir/test_xir_semantic65_vectors.c)
target_link_libraries(test_xir_semantic65_vectors PRIVATE xray_xir_source_product)
if(MSVC)
    target_compile_options(test_xir_semantic65_vectors PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_semantic65_vectors PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_semantic65_vectors COMMAND test_xir_semantic65_vectors)
set_tests_properties(test_xir_semantic65_vectors PROPERTIES LABELS "unit;xir;checked;ownership;wire" TIMEOUT 180)
add_test(NAME test_xir_semantic65_role_oracle COMMAND ${XRAY_PYTHON} ${CMAKE_CURRENT_SOURCE_DIR}/xir/derive_semantic65_packets.py)
set_tests_properties(test_xir_semantic65_role_oracle PROPERTIES LABELS "unit;xir;checked;wire" TIMEOUT 60)
