add_executable(test_xir_task_executor xir/test_xir_task_executor.c)
target_link_libraries(test_xir_task_executor PRIVATE xray_xir_scalar xray_xir)
if(MSVC)
    target_compile_options(test_xir_task_executor PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_task_executor PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_task_executor COMMAND test_xir_task_executor)
set_tests_properties(test_xir_task_executor PROPERTIES LABELS "unit;xir;task;ownership;runtime" TIMEOUT 60)
add_executable(test_xir_task_types xir/test_xir_task_types.c ${PROJECT_SOURCE_DIR}/src/xir/xxir_type_inference.c)
target_link_libraries(test_xir_task_types PRIVATE xray_xir xray_xir_scalar)
if(MSVC)
    target_compile_options(test_xir_task_types PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_task_types PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_task_types COMMAND test_xir_task_types)
set_tests_properties(test_xir_task_types PROPERTIES LABELS "unit;xir;task;ownership;compiler" TIMEOUT 60)
