add_executable(test_xir_task_outcome_copy_controls "${CMAKE_CURRENT_LIST_DIR}/test_xir_task_outcome_copy_controls.c")
target_include_directories(test_xir_task_outcome_copy_controls PRIVATE "${PROJECT_SOURCE_DIR}/tests/unit/xir")
target_link_libraries(test_xir_task_outcome_copy_controls PRIVATE xray_xir_source xray_xir_vm)
target_compile_definitions(test_xir_task_outcome_copy_controls PRIVATE XR_TASK_UNIT_FIXTURES="${PROJECT_SOURCE_DIR}/tests/fixtures/xir_task_unit" XR_SOURCE_STDLIB="${PROJECT_SOURCE_DIR}/stdlib")
if(MSVC)
    target_compile_options(test_xir_task_outcome_copy_controls PRIVATE /W4 /WX /utf-8 /std:c11)
    if(NOT CMAKE_C_COMPILER_ID STREQUAL "Clang")
        target_compile_options(test_xir_task_outcome_copy_controls PRIVATE /experimental:c11atomics)
    endif()
else()
    target_compile_options(test_xir_task_outcome_copy_controls PRIVATE -Wall -Wextra -Werror)
endif()
if(WIN32)
    # This qualification records real Windows process creation and exit times.
    add_test(NAME test_xir_task_outcome_copy_controls COMMAND "${XRAY_PYTHON}" "${CMAKE_CURRENT_LIST_DIR}/run_task_outcome_copy_controls.py" --exe "$<TARGET_FILE:test_xir_task_outcome_copy_controls>" --output "${CMAKE_CURRENT_BINARY_DIR}/task-outcome-copy-controls")
    set_tests_properties(test_xir_task_outcome_copy_controls PROPERTIES TIMEOUT 60 RUN_SERIAL TRUE PROCESSORS 1 LABELS "unit;xir;task;source;runtime;ownership")
endif()
