/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * test_cli_dependency_output.c - Independent escaped byte and single-argument output oracles
 */
#include "app/cli/xcli_dependency_output.h"
#include <stdlib.h>
#include <string.h>
#define CHECK(c) do { if (!(c)) { fprintf(stderr, "%d: %s\n", __LINE__, #c); exit(1); } } while (0)

static void compare(const XrXirSourceDependencies *facts, OutputFormat format,
    const char *expected, size_t length) {
    FILE *file = tmpfile(); CHECK(file);
    CHECK(deps_emit(file, facts, format));
    CHECK(fflush(file) == 0 && fseek(file, 0, SEEK_SET) == 0);
    for (size_t i = 0; i < length; ++i) CHECK(fgetc(file) == (unsigned char)expected[i]);
    CHECK(fgetc(file) == EOF && !ferror(file));
    CHECK(fclose(file) == 0);
}

int main(void) {
    static const char entry[] = "root\r\n# inject";
    static const char stdlib[] = "io\r\n$(boom)";
    static const char package[] = "odd ' $(boom)\\\r\n";
    static const char local[] = "\001\002\003\004\005\006\007\010\t\n\013\014\r\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037\177\"\\\303\251";
    static const char expected_json[] = "{\n  \"entry\": \"root\\r\\n# inject\",\n  \"stdlib\": [\"io\\r\\n$(boom)\"],\n  \"packages\": [\"odd ' $(boom)\\\\\\r\\n\"],\n  \"local_modules\": [\"\\u0001\\u0002\\u0003\\u0004\\u0005\\u0006\\u0007\\b\\t\\n\\u000b\\f\\r\\u000e\\u000f\\u0010\\u0011\\u0012\\u0013\\u0014\\u0015\\u0016\\u0017\\u0018\\u0019\\u001a\\u001b\\u001c\\u001d\\u001e\\u001f\177\\\"\\\\\303\251\"]\n}\n";
    static const char expected_shell[] = "#!/bin/bash\n# Dependency install script\n# Auto-generated by xray deps\n# Entry: root\\x0d\\x0a# inject\n\nset -e\n\necho \"Installing third-party package dependencies...\"\nxray pkg add 'odd '\\'' $(boom)\\\r\n'\n\necho \"All dependencies installed\"\n\n# Stdlib dependencies (built-in, no install needed):\n#   - io\\x0d\\x0a$(boom)\n";
    static const char expected_list[] = "# Stdlib\nio\r\n$(boom)\n# Third-party packages\nodd ' $(boom)\\\r\n\n# Local modules\n\001\002\003\004\005\006\007\010\t\n\013\014\r\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037\177\"\\\303\251\n";
    const XrXirSourceDependency rows[] = {
        {1, XR_XIR_DEPENDENCY_STDLIB, stdlib, NULL, 0},
        {2, XR_XIR_DEPENDENCY_PACKAGE, package, NULL, 0},
        {3, XR_XIR_DEPENDENCY_FILE, local, NULL, 0},
        {0, XR_XIR_DEPENDENCY_FILE, entry, NULL, 0}
    };
    const XrXirSourceDependencies facts = {rows, 4, 3, entry};
    compare(&facts, OUTPUT_JSON, expected_json, sizeof(expected_json) - 1);
    compare(&facts, OUTPUT_SHELL, expected_shell, sizeof(expected_shell) - 1);
    compare(&facts, OUTPUT_LIST, expected_list, sizeof(expected_list) - 1);
    FILE *file = tmpfile(); CHECK(file);
    CHECK(!deps_emit(file, &facts, (OutputFormat)3) && ftell(file) == 0);
    CHECK(!deps_emit(file, &facts, (OutputFormat)-1) && ftell(file) == 0);
    CHECK(!deps_emit(NULL, &facts, OUTPUT_JSON));
    CHECK(!deps_emit(file, NULL, OUTPUT_JSON) && ftell(file) == 0);
    CHECK(fclose(file) == 0);
    puts("dependency formats: all non-NUL controls, UTF-8, shell metacharacters, invalid format PASS");
    return 0;
}
