add_executable(test_xir_tuple_destructure_source xir/test_xir_tuple_destructure_source.c)
target_link_libraries(test_xir_tuple_destructure_source PRIVATE xray_xir_source_product)
target_compile_definitions(test_xir_tuple_destructure_source PRIVATE
    XR_TUPLE_DESTRUCTURE_FIXTURES="${CMAKE_SOURCE_DIR}/tests/fixtures/xir_tuple_destructure/local"
    XR_TUPLE_DESTRUCTURE_STDLIB="${CMAKE_SOURCE_DIR}/stdlib")
if(MSVC)
    target_compile_options(test_xir_tuple_destructure_source PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_destructure_source PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_destructure_source COMMAND test_xir_tuple_destructure_source)
set_tests_properties(test_xir_tuple_destructure_source PROPERTIES LABELS "unit;xir;tuple;source;ownership;execution" TIMEOUT 180)
set(XIR_TUPLE_DESTRUCTURE_GENERATED ${CMAKE_CURRENT_BINARY_DIR}/generated/xir_tuple_destructure.c)
add_custom_command(OUTPUT ${XIR_TUPLE_DESTRUCTURE_GENERATED}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/generated
    COMMAND $<TARGET_FILE:test_xir_tuple_destructure_source> ${XIR_TUPLE_DESTRUCTURE_GENERATED}
    DEPENDS test_xir_tuple_destructure_source
        ${CMAKE_SOURCE_DIR}/tests/fixtures/xir_tuple_destructure/local/root.xr
        ${CMAKE_SOURCE_DIR}/tests/fixtures/xir_tuple_destructure/local/library.xr
    VERBATIM)
add_executable(test_xir_tuple_destructure_native xir/test_xir_tuple_destructure_native.c ${XIR_TUPLE_DESTRUCTURE_GENERATED})
include(${CMAKE_CURRENT_SOURCE_DIR}/xir/tuple_destructure_mixed.cmake)
target_link_libraries(test_xir_tuple_destructure_native PRIVATE xray_xir_scalar)
if(MSVC)
    target_compile_options(test_xir_tuple_destructure_native PRIVATE /W4 /WX /utf-8 /std:c11)
else()
    target_compile_options(test_xir_tuple_destructure_native PRIVATE -Wall -Wextra -Werror -std=c11 -Wpedantic)
endif()
add_test(NAME test_xir_tuple_destructure_native COMMAND test_xir_tuple_destructure_native)
set_tests_properties(test_xir_tuple_destructure_native PROPERTIES LABELS "unit;xir;tuple;native;ownership;execution" TIMEOUT 180)
add_executable(test_xir_tuple_slot_publication_gap xir/test_xir_tuple_slot_publication_gap.c)
target_link_libraries(test_xir_tuple_slot_publication_gap PRIVATE xray_xir_source_product)
if(MSVC)
    target_compile_options(test_xir_tuple_slot_publication_gap PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_slot_publication_gap PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_slot_publication_gap COMMAND test_xir_tuple_slot_publication_gap)
set_tests_properties(test_xir_tuple_slot_publication_gap PROPERTIES LABELS "unit;xir;tuple;ownership;publication;evidence" TIMEOUT 180)
add_executable(test_xir_tuple_destructure_owner xir/test_xir_tuple_destructure_owner.c)
target_link_libraries(test_xir_tuple_destructure_owner PRIVATE xray_xir_source_product)
target_compile_definitions(test_xir_tuple_destructure_owner PRIVATE
    XR_TUPLE_DESTRUCTURE_FIXTURES="${CMAKE_SOURCE_DIR}/tests/fixtures/xir_tuple_destructure/local"
    XR_TUPLE_DESTRUCTURE_STDLIB="${CMAKE_SOURCE_DIR}/stdlib")
if(MSVC)
    target_compile_options(test_xir_tuple_destructure_owner PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_destructure_owner PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_destructure_owner COMMAND test_xir_tuple_destructure_owner)
set_tests_properties(test_xir_tuple_destructure_owner PROPERTIES LABELS "unit;xir;tuple;source;ownership;fault-injection;resource" TIMEOUT 600 COST 134 PROCESSORS 1)
add_executable(test_xir_tuple_slot_group xir/test_xir_tuple_slot_group.c)
target_link_libraries(test_xir_tuple_slot_group PRIVATE xray_xir_source_product)
if(MSVC)
    target_compile_options(test_xir_tuple_slot_group PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_slot_group PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_slot_group COMMAND test_xir_tuple_slot_group)
set_tests_properties(test_xir_tuple_slot_group PROPERTIES LABELS "unit;xir;tuple;ownership;publication;fault-injection;resource" TIMEOUT 180)
add_executable(test_xir_tuple_slot_group_checked xir/test_xir_tuple_slot_group_checked.c)
target_link_libraries(test_xir_tuple_slot_group_checked PRIVATE xray_xir_source_product)
if(MSVC)
    target_compile_options(test_xir_tuple_slot_group_checked PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_slot_group_checked PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_slot_group_checked COMMAND test_xir_tuple_slot_group_checked)
set_tests_properties(test_xir_tuple_slot_group_checked PROPERTIES LABELS "unit;xir;tuple;checked;ownership;publication;fault-injection;resource" TIMEOUT 180)
add_executable(test_xir_tuple_destructure_rejections xir/test_xir_tuple_destructure_rejections.c)
target_link_libraries(test_xir_tuple_destructure_rejections PRIVATE xray_xir_source_product)
target_compile_definitions(test_xir_tuple_destructure_rejections PRIVATE
    XR_TUPLE_DESTRUCTURE_REJECTED="${CMAKE_SOURCE_DIR}/tests/fixtures/xir_tuple_destructure/rejected"
    XR_TUPLE_DESTRUCTURE_STDLIB="${CMAKE_SOURCE_DIR}/stdlib")
if(MSVC)
    target_compile_options(test_xir_tuple_destructure_rejections PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_destructure_rejections PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_destructure_rejections COMMAND test_xir_tuple_destructure_rejections)
set_tests_properties(test_xir_tuple_destructure_rejections PROPERTIES LABELS "unit;xir;tuple;source;ownership;rejection" TIMEOUT 180)
