add_executable(test_xir_tuple_owner xir/test_xir_tuple_owner.c ${PROJECT_SOURCE_DIR}/src/xir/xxir_type_inference.c)
target_link_libraries(test_xir_tuple_owner PRIVATE xray_xir xray_xir_scalar)
if(MSVC)
    target_compile_options(test_xir_tuple_owner PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_owner PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_owner COMMAND test_xir_tuple_owner)
set_tests_properties(test_xir_tuple_owner PROPERTIES LABELS "unit;xir;metadata;ownership" TIMEOUT 300)
add_executable(test_xir_tuple_source_owner xir/test_xir_tuple_source_owner.c)
target_link_libraries(test_xir_tuple_source_owner PRIVATE xray_xir_source)
target_include_directories(test_xir_tuple_source_owner PRIVATE ${XRAY_COMMON_INCLUDES} ${CMAKE_BINARY_DIR}/generated)
add_dependencies(test_xir_tuple_source_owner gen-xir-core-source gen-stdlib-embedded-sources)
if(MSVC)
    target_compile_options(test_xir_tuple_source_owner PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_source_owner PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_source_owner COMMAND test_xir_tuple_source_owner)
set_tests_properties(test_xir_tuple_source_owner PROPERTIES LABELS "unit;xir;metadata;ownership" TIMEOUT 300)
add_test(NAME test_xir_tuple62_vectors COMMAND ${XRAY_PYTHON} ${CMAKE_CURRENT_SOURCE_DIR}/xir/derive_tuple62_vectors.py)
add_test(NAME test_xir_tuple62_readers COMMAND ${XRAY_PYTHON} ${CMAKE_CURRENT_SOURCE_DIR}/xir/verify_tuple62_readers.py
    --reader $<TARGET_FILE:test_xir_nested_nullable_reader> --output ${CMAKE_CURRENT_BINARY_DIR}/tuple62-reader-probes)
set_tests_properties(test_xir_tuple62_vectors test_xir_tuple62_readers PROPERTIES LABELS "unit;xir;abi;ownership" TIMEOUT 300)
add_executable(test_xir_tuple_previous_owner xir/compile_owner/test_compile_owner.c ${PROJECT_SOURCE_DIR}/src/xir/xxir_type_inference.c)
target_link_libraries(test_xir_tuple_previous_owner PRIVATE xray_xir)
if(MSVC)
    target_compile_options(test_xir_tuple_previous_owner PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(test_xir_tuple_previous_owner PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME test_xir_tuple_previous_owner COMMAND test_xir_tuple_previous_owner)
set_tests_properties(test_xir_tuple_previous_owner PROPERTIES LABELS "unit;xir;abi;ownership" TIMEOUT 300)
add_test(NAME test_xir_tuple62_sizing_vectors COMMAND ${XRAY_PYTHON} ${CMAKE_CURRENT_SOURCE_DIR}/xir/derive_tuple62_migration.py)
set_tests_properties(test_xir_tuple62_sizing_vectors PROPERTIES LABELS "unit;xir;abi;ownership" TIMEOUT 300)
