/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * xir_stdlib_output_module_probe.h - Actual module allocation fault boundary
 */
#ifndef XIR_STDLIB_OUTPUT_MODULE_PROBE_H
#define XIR_STDLIB_OUTPUT_MODULE_PROBE_H
#include <stddef.h>
#include <stdbool.h>
extern size_t module_attempts, module_fail_at, module_live, module_bytes;
extern bool module_injecting;
extern size_t module_os_attempts[2], module_os_fail_at[2];
extern unsigned long module_os_error;
extern bool module_attributes_override;
extern unsigned long module_attributes;
void xr_test_stdlib_output_module_forget(void *pointer);
XR_FUNC void *xr_test_stdlib_output_module_allocate(size_t bytes);
XR_FUNC void xr_test_stdlib_output_module_release(void *pointer);
extern bool module_injected;
#define xr_file_probe_owned xr_test_output_file_probe_owned
#define xr_path_dirname_owned xr_test_output_path_dirname_owned
#define xr_path_join_owned xr_test_output_path_join_owned
#define xr_realpath_owned xr_test_output_realpath_owned
#define xr_file_read_all xr_test_output_file_read_all
#define xr_path_basename xr_test_output_path_basename
#define xr_compile_module_identity_from_logical xr_test_output_compile_module_identity_from_logical
#define xr_compile_module_identity_from_source xr_test_output_compile_module_identity_from_source
#define xr_compile_module_identity_script_authority_from_source xr_test_output_compile_module_identity_script_authority_from_source
#define xr_compile_module_id_cleanup xr_test_output_compile_module_id_cleanup
#define xr_compile_module_resolver_free xr_test_output_compile_module_resolver_free
#define xr_compile_module_resolver_new xr_test_output_compile_module_resolver_new
#define xr_compile_module_resolver_set_lockfile xr_test_output_compile_module_resolver_set_lockfile
#define xr_compile_module_resolver_resolve xr_test_output_compile_module_resolver_resolve
#define xr_compile_module_graph_free xr_test_output_compile_module_graph_free
#define xr_compile_module_graph_new xr_test_output_compile_module_graph_new
#define xr_compile_module_graph_find xr_test_output_compile_module_graph_find
#define xr_compile_module_graph_find_source xr_test_output_compile_module_graph_find_source
#define xr_compile_module_graph_owns_top_level_decl xr_test_output_compile_module_graph_owns_top_level_decl
#define xr_compile_module_graph_find_named_dependency xr_test_output_compile_module_graph_find_named_dependency
#define xr_compile_module_graph_build xr_test_output_compile_module_graph_build
#define xr_compile_module_graph_include xr_test_output_compile_module_graph_include
#define xr_compile_module_graph_build_source xr_test_output_compile_module_graph_build_source
#define xr_compile_module_graph_build_logical_source xr_test_output_compile_module_graph_build_logical_source
#define xr_compile_module_graph_include_logical_source xr_test_output_compile_module_graph_include_logical_source
#define xr_compile_module_graph_add_dependency xr_test_output_compile_module_graph_add_dependency
#define xr_compile_module_graph_topological_sort xr_test_output_compile_module_graph_topological_sort
#define xr_module_spec_import_name xr_test_output_module_spec_import_name
#endif
