/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 *
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * xcmd_deps.c - 'xray deps' command implementation
 *
 * KEY CONCEPT:
 *   Analyzes project dependencies and generates install scripts.
 */

#include "xcli.h"
#include "xcli_spec.h"
#include "xcli_isolate.h"
#include "xray.h"
#include "xray_isolate.h"
#include "../../module/xbundle.h"
#include "../../base/xchecks.h"
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

// Write a JSON-escaped string to file (handles \, ", and control chars)
static void fprint_json_string(FILE *f, const char *s) {
    fputc('"', f);
    for (; *s; s++) {
        switch (*s) {
            case '"':
                fputs("\\\"", f);
                break;
            case '\\':
                fputs("\\\\", f);
                break;
            case '\n':
                fputs("\\n", f);
                break;
            case '\t':
                fputs("\\t", f);
                break;
            default:
                fputc(*s, f);
                break;
        }
    }
    fputc('"', f);
}

typedef enum {
    OUTPUT_SHELL,
    OUTPUT_JSON,
    OUTPUT_LIST
} OutputFormat;

XR_FUNC int cmd_deps(const XrCliInvocation *inv) {
    XR_DCHECK(inv != NULL, "inv is NULL");
    XR_DCHECK(inv->positional_count == 1, "deps expects exactly 1 positional");

    const char *input_file = inv->positionals[0];
    const char *output_file = xr_cli_opt_string(&inv->options, "output", NULL);

    OutputFormat format = OUTPUT_SHELL;
    if (xr_cli_opt_present(&inv->options, "json"))
        format = OUTPUT_JSON;
    else if (xr_cli_opt_present(&inv->options, "list"))
        format = OUTPUT_LIST;
    else if (xr_cli_opt_present(&inv->options, "shell"))
        format = OUTPUT_SHELL;

    /* Create isolate and analyze dependencies */
    XrayIsolate *X = xr_cli_isolate_new(XR_CLI_ISOLATE_RUN);
    if (!X) {
        xr_cli_error("deps", "failed to create isolate");
        return XR_CLI_EXIT_INTERNAL;
    }

    XrBundle *bundle = xr_bundle_create(X, input_file);
    xray_isolate_delete(X);

    if (!bundle) {
        xr_cli_error("deps", "dependency analysis failed for '%s'", input_file);
        return XR_CLI_EXIT_FAIL;
    }

    /* Open output file */
    FILE *out = stdout;
    if (output_file) {
        out = fopen(output_file, "w");
        if (!out) {
            xr_cli_error("deps", "cannot create '%s'", output_file);
            xr_bundle_free(bundle);
            return XR_CLI_EXIT_FAIL;
        }
    }

    /* Write output */
    switch (format) {
        case OUTPUT_LIST:
            if (bundle->stdlib.count > 0) {
                fprintf(out, "# Stdlib\n");
                for (int i = 0; i < bundle->stdlib.count; i++) {
                    fprintf(out, "%s\n", bundle->stdlib.deps[i]);
                }
            }
            if (bundle->packages.count > 0) {
                fprintf(out, "# Third-party packages\n");
                for (int i = 0; i < bundle->packages.count; i++) {
                    fprintf(out, "%s\n", bundle->packages.deps[i]);
                }
            }
            if (bundle->count > 1) {
                fprintf(out, "# Local modules\n");
                for (int i = 0; i < bundle->count - 1; i++) {
                    fprintf(out, "%s\n", bundle->entries[i].path);
                }
            }
            break;

        case OUTPUT_JSON:
            fprintf(out, "{\n");
            fprintf(out, "  \"entry\": ");
            fprint_json_string(out, bundle->entry_path);
            fprintf(out, ",\n");

            fprintf(out, "  \"stdlib\": [");
            for (int i = 0; i < bundle->stdlib.count; i++) {
                if (i > 0)
                    fprintf(out, ", ");
                fprint_json_string(out, bundle->stdlib.deps[i]);
            }
            fprintf(out, "],\n");

            fprintf(out, "  \"packages\": [");
            for (int i = 0; i < bundle->packages.count; i++) {
                if (i > 0)
                    fprintf(out, ", ");
                fprint_json_string(out, bundle->packages.deps[i]);
            }
            fprintf(out, "],\n");

            fprintf(out, "  \"local_modules\": [");
            for (int i = 0; i < bundle->count - 1; i++) {
                if (i > 0)
                    fprintf(out, ", ");
                fprint_json_string(out, bundle->entries[i].path);
            }
            fprintf(out, "]\n");
            fprintf(out, "}\n");
            break;

        case OUTPUT_SHELL:
        default:
            fprintf(out, "#!/bin/bash\n");
            fprintf(out, "# Dependency install script\n");
            fprintf(out, "# Auto-generated by xray deps\n");
            fprintf(out, "# Entry: %s\n", bundle->entry_path);
            fprintf(out, "\n");
            fprintf(out, "set -e\n");
            fprintf(out, "\n");

            if (bundle->packages.count > 0) {
                fprintf(out, "echo \"Installing third-party package dependencies...\"\n");
                for (int i = 0; i < bundle->packages.count; i++) {
                    fprintf(out, "xray pkg add %s\n", bundle->packages.deps[i]);
                }
                fprintf(out, "\n");
                fprintf(out, "echo \"All dependencies installed\"\n");
            } else {
                fprintf(out, "echo \"No third-party package dependencies\"\n");
            }

            if (bundle->stdlib.count > 0) {
                fprintf(out, "\n");
                fprintf(out, "# Stdlib dependencies (built-in, no install needed):\n");
                for (int i = 0; i < bundle->stdlib.count; i++) {
                    fprintf(out, "#   - %s\n", bundle->stdlib.deps[i]);
                }
            }
            break;
    }

    if (output_file) {
        fclose(out);
        printf("Dependency script generated: %s\n", output_file);
        if (format == OUTPUT_SHELL) {
            printf("Run with: bash %s\n", output_file);
        }
    }

    xr_bundle_free(bundle);
    return 0;
}
