/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/stdlibgen/stdlibgen.py
 *
 * xstdlib_vm_bindings_generated.inc.c - VM stdlib binding shell
 */

/* clang-format off */

/*
 * Include this file from a stdlib module TU after stdlib/common.h
 * and after the module's static
 * C functions have been declared, then define exactly one
 * XR_STDLIB_VM_BIND_MODULE_<MODULE> macro before including it.
 */

#ifdef XR_STDLIB_VM_BIND_MODULE_CLUSTER
static void xr_stdlib_vm_bind_cluster_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "start", cluster_start);
    XRS_EXPORT(module, isolate, "join", cluster_join);
    XRS_EXPORT(module, isolate, "self", cluster_self);
    XRS_EXPORT(module, isolate, "nodes", cluster_nodes);
    XRS_EXPORT(module, isolate, "channel", cluster_channel_fn);
    XRS_EXPORT(module, isolate, "serve", cluster_serve_fn);
    XRS_EXPORT(module, isolate, "reply", cluster_reply_fn);
    XRS_EXPORT(module, isolate, "call", cluster_call_fn);
    XRS_EXPORT(module, isolate, "monitor", cluster_monitor_coro_fn);
    XRS_EXPORT(module, isolate, "discover", cluster_discover_fn);
    XRS_EXPORT(module, isolate, "stop", cluster_stop_fn);
    XRS_EXPORT(module, isolate, "info", cluster_info_fn);
    XRS_EXPORT(module, isolate, "publish", cluster_publish_fn);
    XRS_EXPORT(module, isolate, "subscribe", cluster_subscribe_fn);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_CLUSTER */

#ifdef XR_STDLIB_VM_BIND_MODULE_COMPRESS
static void xr_stdlib_vm_bind_compress_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "crc32", compress_crc32);
    XRS_EXPORT(module, isolate, "adler32", compress_adler32);
    XRS_EXPORT(module, isolate, "gzip", compress_gzip);
    XRS_EXPORT(module, isolate, "gunzip", compress_gunzip);
    XRS_EXPORT(module, isolate, "deflate", compress_deflate);
    XRS_EXPORT(module, isolate, "inflate", compress_inflate);
    XRS_EXPORT(module, isolate, "zlibCompress", compress_zlib_compress);
    XRS_EXPORT(module, isolate, "zlibDecompress", compress_zlib_decompress);
    XRS_EXPORT(module, isolate, "isGzip", compress_is_gzip);
    XRS_EXPORT(module, isolate, "isZlib", compress_is_zlib);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_COMPRESS */

#ifdef XR_STDLIB_VM_BIND_MODULE_CRYPTO
static void xr_stdlib_vm_bind_crypto_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "md5", crypto_md5);
    XRS_EXPORT(module, isolate, "sha1", crypto_sha1);
    XRS_EXPORT(module, isolate, "sha256", crypto_sha256);
    XRS_EXPORT(module, isolate, "sha512", crypto_sha512);
    XRS_EXPORT(module, isolate, "hmac", crypto_hmac);
    XRS_EXPORT(module, isolate, "randomBytes", crypto_random_bytes);
    XRS_EXPORT(module, isolate, "uuid", crypto_uuid);
    XRS_EXPORT(module, isolate, "encrypt", crypto_encrypt);
    XRS_EXPORT(module, isolate, "decrypt", crypto_decrypt);
    XRS_EXPORT(module, isolate, "timingSafeEqual", crypto_timing_safe_equal);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_CRYPTO */

#ifdef XR_STDLIB_VM_BIND_MODULE_CSV
static void xr_stdlib_vm_bind_csv_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "parse", csv_parse);
    XRS_EXPORT(module, isolate, "parseDetailed", csv_parse_detailed);
    XRS_EXPORT(module, isolate, "parseTsv", csv_parse_tsv);
    XRS_EXPORT(module, isolate, "parseAuto", csv_parse_auto);
    XRS_EXPORT(module, isolate, "stringify", csv_stringify);
    XRS_EXPORT(module, isolate, "parseFile", csv_parse_file);
    XRS_EXPORT(module, isolate, "writeFile", csv_write_file);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_CSV */

#ifdef XR_STDLIB_VM_BIND_MODULE_DATETIME
static void xr_stdlib_vm_bind_datetime_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "now", dt_now);
    XRS_EXPORT(module, isolate, "utc", dt_utc);
    XRS_EXPORT(module, isolate, "create", dt_create);
    XRS_EXPORT(module, isolate, "createUTC", dt_create_utc);
    XRS_EXPORT(module, isolate, "fromTimestamp", dt_from_timestamp);
    XRS_EXPORT(module, isolate, "fromTimestampMs", dt_from_timestamp_ms);
    XRS_EXPORT(module, isolate, "parse", dt_parse);
    XRS_EXPORT(module, isolate, "offset", dt_offset);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_DATETIME */

#ifdef XR_STDLIB_VM_BIND_MODULE_HTTP
static void xr_stdlib_vm_bind_http_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT_SLOW(module, isolate, "get", http_get);
    XRS_EXPORT_SLOW(module, isolate, "post", http_post);
    XRS_EXPORT_SLOW(module, isolate, "put", http_put);
    XRS_EXPORT_SLOW(module, isolate, "delete", http_delete);
    XRS_EXPORT_SLOW(module, isolate, "request", http_request);
    XRS_EXPORT(module, isolate, "urlEncode", http_url_encode);
    XRS_EXPORT(module, isolate, "urlDecode", http_url_decode);
    XRS_EXPORT(module, isolate, "route", http_route);
    XRS_EXPORT(module, isolate, "static", http_static);
    XRS_EXPORT(module, isolate, "setConnHandler", http_set_conn_handler);
    XRS_EXPORT(module, isolate, "__getConnHandler", http_get_conn_handler);
    XRS_EXPORT_YIELDABLE(module, isolate, "listen", xr_http_listen_impl);
    XRS_EXPORT(module, isolate, "config", xr_http_config_impl);
    XRS_EXPORT(module, isolate, "response", xr_http_response_impl);
    XRS_EXPORT(module, isolate, "serverStats", xr_http_server_stats);
    XRS_EXPORT(module, isolate, "ws", http_ws_route);
    XRS_EXPORT_SLOW(module, isolate, "readChunk", http_read_chunk);
    XRS_EXPORT(module, isolate, "closeStream", http_close_stream);
    XRS_EXPORT(module, isolate, "stopServer", http_stop_server);
    XRS_EXPORT(module, isolate, "parseRequest", http_parse_request_fast);
    XRS_EXPORT(module, isolate, "sendResponse", http_send_response_fast);
    XRS_EXPORT_SLOW(module, isolate, "download", http_download);
    XRS_EXPORT(module, isolate, "getContentLength", http_get_content_length);
    XRS_EXPORT(module, isolate, "formDataNew", http_form_data_new);
    XRS_EXPORT(module, isolate, "formDataAppend", http_form_data_append);
    XRS_EXPORT(module, isolate, "formDataAppendFile", http_form_data_append_file);
    XRS_EXPORT(module, isolate, "formDataPost", http_form_data_post);
    XRS_EXPORT(module, isolate, "setProxy", http_set_proxy);
    XRS_EXPORT(module, isolate, "clearProxy", http_clear_proxy);
    XRS_EXPORT(module, isolate, "h2Get", h2_get);
    XRS_EXPORT(module, isolate, "h2Post", h2_post);
    XRS_EXPORT(module, isolate, "h2Request", h2_request);
    XRS_EXPORT(module, isolate, "h2CreateServer", h2_create_server);
    XRS_EXPORT(module, isolate, "h2Listen", h2_server_listen);
    XRS_EXPORT(module, isolate, "h2Stop", h2_server_stop);
    XRS_EXPORT(module, isolate, "h2Push", h2_push);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_HTTP */

#ifdef XR_STDLIB_VM_BIND_MODULE_IO
static void xr_stdlib_vm_bind_io_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "appendFile", io_appendFile);
    XRS_EXPORT(module, isolate, "chmod", io_chmod);
    XRS_EXPORT(module, isolate, "chdir", io_chdir);
    XRS_EXPORT(module, isolate, "copyFile", io_copyFile);
    XRS_EXPORT(module, isolate, "cwd", io_cwd);
    XRS_EXPORT(module, isolate, "exists", io_exists);
    XRS_EXPORT(module, isolate, "fileSize", io_fileSize);
    XRS_EXPORT(module, isolate, "isDir", io_isDir);
    XRS_EXPORT(module, isolate, "isFile", io_isFile);
    XRS_EXPORT(module, isolate, "isSymlink", io_isSymlink);
    XRS_EXPORT(module, isolate, "mkdir", io_mkdir);
    XRS_EXPORT(module, isolate, "mkdirp", io_mkdirp);
    XRS_EXPORT(module, isolate, "readDir", io_readDir);
    XRS_EXPORT(module, isolate, "readDirRecursive", io_readDirRecursive);
    XRS_EXPORT_YIELDABLE(module, isolate, "readFile", io_readFile);
    XRS_EXPORT_YIELDABLE(module, isolate, "readFileBytes", io_readFileBytes);
    XRS_EXPORT(module, isolate, "readLines", io_readLines);
    XRS_EXPORT(module, isolate, "readStdin", io_readStdin);
    XRS_EXPORT(module, isolate, "readlink", io_readlink);
    XRS_EXPORT(module, isolate, "realpath", io_realpath);
    XRS_EXPORT(module, isolate, "remove", io_remove);
    XRS_EXPORT(module, isolate, "removeAll", io_removeAll);
    XRS_EXPORT(module, isolate, "rename", io_rename);
    XRS_EXPORT(module, isolate, "stat", io_stat);
    XRS_EXPORT(module, isolate, "symlink", io_symlink);
    XRS_EXPORT(module, isolate, "tempDir", io_tempDir);
    XRS_EXPORT(module, isolate, "tempFile", io_tempFile);
    XRS_EXPORT(module, isolate, "touch", io_touch);
    XRS_EXPORT_YIELDABLE(module, isolate, "writeFile", io_writeFile);
    XRS_EXPORT_YIELDABLE(module, isolate, "writeFileBytes", io_writeFileBytes);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_IO */

#ifdef XR_STDLIB_VM_BIND_MODULE_LOG
static void xr_stdlib_vm_bind_log_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "debug", xr_log_debug);
    XRS_EXPORT(module, isolate, "info", xr_log_info);
    XRS_EXPORT(module, isolate, "warn", xr_log_warn);
    XRS_EXPORT(module, isolate, "error", xr_log_error);
    XRS_EXPORT(module, isolate, "fatal", xr_log_fatal);
    XRS_EXPORT(module, isolate, "setLevel", xr_log_set_level);
    XRS_EXPORT(module, isolate, "setFormat", xr_log_set_format);
    XRS_EXPORT(module, isolate, "setOutput", xr_log_set_output);
    XRS_EXPORT(module, isolate, "isEnabled", xr_log_is_enabled);
    XRS_EXPORT(module, isolate, "enableSource", xr_log_enable_source);
    XRS_EXPORT(module, isolate, "enableAsync", xr_log_enable_async);
    XRS_EXPORT(module, isolate, "flush", xr_log_flush);
    XRS_EXPORT(module, isolate, "child", xr_log_child);
    xr_module_add_export(isolate, module, "DEBUG", xr_int(XR_LOG_DEBUG));
    xr_module_add_export(isolate, module, "INFO", xr_int(XR_LOG_INFO));
    xr_module_add_export(isolate, module, "WARN", xr_int(XR_LOG_WARN));
    xr_module_add_export(isolate, module, "ERROR", xr_int(XR_LOG_ERROR));
    xr_module_add_export(isolate, module, "FATAL", xr_int(XR_LOG_FATAL));
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_LOG */

#ifdef XR_STDLIB_VM_BIND_MODULE_MATH
static void xr_stdlib_vm_bind_math_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "abs", math_abs);
    XRS_EXPORT(module, isolate, "floor", math_floor);
    XRS_EXPORT(module, isolate, "ceil", math_ceil);
    XRS_EXPORT(module, isolate, "round", math_round);
    XRS_EXPORT(module, isolate, "sqrt", math_sqrt);
    XRS_EXPORT(module, isolate, "pow", math_pow);
    XRS_EXPORT(module, isolate, "sin", math_sin);
    XRS_EXPORT(module, isolate, "cos", math_cos);
    XRS_EXPORT(module, isolate, "tan", math_tan);
    XRS_EXPORT(module, isolate, "asin", math_asin);
    XRS_EXPORT(module, isolate, "acos", math_acos);
    XRS_EXPORT(module, isolate, "atan", math_atan);
    XRS_EXPORT(module, isolate, "atan2", math_atan2);
    XRS_EXPORT(module, isolate, "log", math_log);
    XRS_EXPORT(module, isolate, "log10", math_log10);
    XRS_EXPORT(module, isolate, "log2", math_log2);
    XRS_EXPORT(module, isolate, "exp", math_exp);
    XRS_EXPORT(module, isolate, "min", math_min);
    XRS_EXPORT(module, isolate, "max", math_max);
    XRS_EXPORT(module, isolate, "clamp", math_clamp);
    XRS_EXPORT(module, isolate, "random", math_random);
    XRS_EXPORT(module, isolate, "randomInt", math_randomInt);
    XRS_EXPORT(module, isolate, "sign", math_sign);
    XRS_EXPORT(module, isolate, "sinh", math_sinh);
    XRS_EXPORT(module, isolate, "cosh", math_cosh);
    XRS_EXPORT(module, isolate, "tanh", math_tanh);
    XRS_EXPORT(module, isolate, "hypot", math_hypot);
    XRS_EXPORT(module, isolate, "cbrt", math_cbrt);
    XRS_EXPORT(module, isolate, "trunc", math_trunc);
    XRS_EXPORT(module, isolate, "fmod", math_fmod);
    XRS_EXPORT(module, isolate, "log1p", math_log1p);
    XRS_EXPORT(module, isolate, "expm1", math_expm1);
    XRS_EXPORT(module, isolate, "lerp", math_lerp);
    XRS_EXPORT(module, isolate, "degToRad", math_degToRad);
    XRS_EXPORT(module, isolate, "radToDeg", math_radToDeg);
    XRS_EXPORT(module, isolate, "isNaN", math_isNaN);
    XRS_EXPORT(module, isolate, "isFinite", math_isFinite);
    xr_module_add_export(isolate, module, "PI", xr_float(M_PI));
    xr_module_add_export(isolate, module, "E", xr_float(M_E));
    xr_module_add_export(isolate, module, "TAU", xr_float(2.0 * M_PI));
    xr_module_add_export(isolate, module, "SQRT2", xr_float(M_SQRT2));
    xr_module_add_export(isolate, module, "LN2", xr_float(M_LN2));
    xr_module_add_export(isolate, module, "LN10", xr_float(M_LN10));
    xr_module_add_export(isolate, module, "LOG2E", xr_float(M_LOG2E));
    xr_module_add_export(isolate, module, "LOG10E", xr_float(M_LOG10E));
    xr_module_add_export(isolate, module, "EPSILON", xr_float(DBL_EPSILON));
    xr_module_add_export(isolate, module, "MAX_INT", xr_int(INT64_MAX));
    xr_module_add_export(isolate, module, "MIN_INT", xr_int(INT64_MIN));
    xr_module_add_export(isolate, module, "MAX_FLOAT", xr_float(DBL_MAX));
    xr_module_add_export(isolate, module, "INF", xr_float(INFINITY));
    xr_module_add_export(isolate, module, "NAN", xr_float(NAN));
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_MATH */

#ifdef XR_STDLIB_VM_BIND_MODULE_MEM
static void xr_stdlib_vm_bind_mem_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "collectCycles", mem_collect_cycles);
    XRS_EXPORT(module, isolate, "disableCycleCollection", mem_disable_cycle_collection);
    XRS_EXPORT(module, isolate, "enableCycleCollection", mem_enable_cycle_collection);
    XRS_EXPORT(module, isolate, "isCycleCollectionEnabled", mem_is_cycle_collection_enabled);
    XRS_EXPORT(module, isolate, "liveBytes", mem_live_bytes);
    XRS_EXPORT(module, isolate, "liveObjects", mem_live_objects);
    XRS_EXPORT(module, isolate, "info", mem_info);
    XRS_EXPORT(module, isolate, "fence", mem_fence);
    XRS_EXPORT(module, isolate, "prefetch", mem_prefetch);
    XRS_EXPORT(module, isolate, "cacheFlush", mem_cache_flush);
    XRS_EXPORT(module, isolate, "cacheInvalidate", mem_cache_invalidate);
    XRS_EXPORT(module, isolate, "nontemporalStore", mem_nontemporal_store);
    XRS_EXPORT(module, isolate, "cacheLineSize", mem_cache_line_size);
    XRS_EXPORT(module, isolate, "alloc", mem_alloc);
    XRS_EXPORT(module, isolate, "allocZeroed", mem_alloc_zeroed);
    XRS_EXPORT(module, isolate, "allocAligned", mem_alloc_aligned);
    XRS_EXPORT(module, isolate, "realloc", mem_realloc);
    XRS_EXPORT(module, isolate, "free", mem_free);
    XRS_EXPORT(module, isolate, "pageAlloc", mem_page_alloc);
    XRS_EXPORT(module, isolate, "pageProtect", mem_page_protect);
    XRS_EXPORT(module, isolate, "pageFree", mem_page_free);
    XRS_EXPORT(module, isolate, "fromAddress", mem_from_address);
    XRS_EXPORT(module, isolate, "addressOf", mem_address_of);
    XRS_EXPORT(module, isolate, "copy", mem_copy);
    XRS_EXPORT(module, isolate, "move", mem_move);
    XRS_EXPORT(module, isolate, "set", mem_set);
    XRS_EXPORT(module, isolate, "compare", mem_compare);
    XRS_EXPORT(module, isolate, "volatileLoad", mem_volatile_load);
    XRS_EXPORT(module, isolate, "volatileStore", mem_volatile_store);
    XRS_EXPORT(module, isolate, "popcount", mem_popcount);
    XRS_EXPORT(module, isolate, "leadingZeros", mem_leading_zeros);
    XRS_EXPORT(module, isolate, "trailingZeros", mem_trailing_zeros);
    XRS_EXPORT(module, isolate, "byteswap", mem_byteswap);
    XRS_EXPORT(module, isolate, "rotateLeft", mem_rotate_left);
    XRS_EXPORT(module, isolate, "rotateRight", mem_rotate_right);
    XRS_EXPORT(module, isolate, "addWrapping", mem_add_wrapping);
    XRS_EXPORT(module, isolate, "subWrapping", mem_sub_wrapping);
    XRS_EXPORT(module, isolate, "mulWrapping", mem_mul_wrapping);
    XRS_EXPORT(module, isolate, "addOverflows", mem_add_overflows);
    XRS_EXPORT(module, isolate, "subOverflows", mem_sub_overflows);
    XRS_EXPORT(module, isolate, "mulOverflows", mem_mul_overflows);
    xr_module_add_export(isolate, module, "PROT_NONE", xr_int(XR_MEM_PROT_NONE));
    xr_module_add_export(isolate, module, "PROT_READ", xr_int(XR_MEM_PROT_READ));
    xr_module_add_export(isolate, module, "PROT_WRITE", xr_int(XR_MEM_PROT_WRITE));
    xr_module_add_export(isolate, module, "PROT_EXEC", xr_int(XR_MEM_PROT_EXEC));
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_MEM */

#ifdef XR_STDLIB_VM_BIND_MODULE_NET
static void xr_stdlib_vm_bind_net_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT_YIELDABLE(module, isolate, "dial", net_dial_yieldable);
    XRS_EXPORT(module, isolate, "listen", net_listen_handle);
    XRS_EXPORT_YIELDABLE(module, isolate, "accept", net_accept_handle_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "read", net_read_handle_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "readInto", net_read_into_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "write", net_write_handle_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "writeBytes", net_write_bytes_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "copy", net_copy_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "copyBidirectional", net_copy_bidirectional_yieldable);
    XRS_EXPORT(module, isolate, "shutdownRead", net_shutdown_read);
    XRS_EXPORT(module, isolate, "shutdownWrite", net_shutdown_write);
    XRS_EXPORT(module, isolate, "shutdown", net_shutdown_conn);
    XRS_EXPORT(module, isolate, "close", net_close_handle);
    XRS_EXPORT(module, isolate, "fd", net_fd_handle);
    XRS_EXPORT(module, isolate, "setReadDeadline", net_set_read_deadline);
    XRS_EXPORT(module, isolate, "setWriteDeadline", net_set_write_deadline);
    XRS_EXPORT(module, isolate, "setDeadline", net_set_deadline);
    XRS_EXPORT(module, isolate, "setAcceptDeadline", net_set_accept_deadline);
    XRS_EXPORT(module, isolate, "lastError", net_last_error);
    XRS_EXPORT(module, isolate, "lastErrno", net_last_errno);
    XRS_EXPORT(module, isolate, "lookup", net_dns_lookup);
    XRS_EXPORT(module, isolate, "hasTLS", net_has_tls);
#ifdef XR_ENABLE_TLS
    XRS_EXPORT_YIELDABLE(module, isolate, "dialTLS", net_dial_tls_yieldable);
#endif  /* XR_ENABLE_TLS */
#ifdef XR_ENABLE_TLS
    XRS_EXPORT_YIELDABLE(module, isolate, "upgradeTLS", net_upgrade_tls_yieldable);
#endif  /* XR_ENABLE_TLS */
    XRS_EXPORT(module, isolate, "udpBind", net_udp_bind_handle);
    XRS_EXPORT_YIELDABLE(module, isolate, "sendTo", net_send_to_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "recvFrom", net_recv_from_yieldable);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_NET */

#ifdef XR_STDLIB_VM_BIND_MODULE_OS
static void xr_stdlib_vm_bind_os_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "getenv", os_getenv);
    XRS_EXPORT(module, isolate, "setenv", os_setenv);
    XRS_EXPORT(module, isolate, "unsetenv", os_unsetenv);
    XRS_EXPORT(module, isolate, "environ", os_environ);
    XRS_EXPORT(module, isolate, "exit", os_exit);
    XRS_EXPORT(module, isolate, "getpid", os_getpid);
    XRS_EXPORT(module, isolate, "getcwd", os_getcwd);
    XRS_EXPORT(module, isolate, "chdir", os_chdir);
    XRS_EXPORT(module, isolate, "hostname", os_hostname);
    XRS_EXPORT(module, isolate, "tmpdir", os_tmpdir);
    XRS_EXPORT(module, isolate, "username", os_username);
    XRS_EXPORT(module, isolate, "homedir", os_homedir);
    XRS_EXPORT(module, isolate, "uid", os_uid);
    XRS_EXPORT(module, isolate, "gid", os_gid);
    XRS_EXPORT(module, isolate, "cpuCount", os_cpuCount);
    XRS_EXPORT(module, isolate, "ppid", os_ppid);
    XRS_EXPORT(module, isolate, "kill", os_kill);
    XRS_EXPORT(module, isolate, "totalMemory", os_totalMemory);
    XRS_EXPORT(module, isolate, "freeMemory", os_freeMemory);
    XRS_EXPORT(module, isolate, "uptime", os_uptime);
    XRS_EXPORT(module, isolate, "loadavg", os_loadavg);
    XRS_EXPORT(module, isolate, "clock", os_clock);
    XRS_EXPORT_YIELDABLE(module, isolate, "sleep", os_sleep);
    XRS_EXPORT(module, isolate, "exec", os_exec);
    xr_module_add_export(isolate, module, "platform", xrs_string_value_c(isolate, get_platform()));
    xr_module_add_export(isolate, module, "arch", xrs_string_value_c(isolate, get_arch()));
    xr_module_add_export(isolate, module, "sep", xrs_string_value_c(isolate, get_sep()));
    xr_module_add_export(isolate, module, "eol", xrs_string_value_c(isolate, get_eol()));
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_OS */

#ifdef XR_STDLIB_VM_BIND_MODULE_REGEX
static void xr_stdlib_vm_bind_regex_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "compile", regex_compile);
    XRS_EXPORT(module, isolate, "test", regex_test);
    XRS_EXPORT(module, isolate, "count", regex_count);
    XRS_EXPORT(module, isolate, "findText", regex_find_text);
    XRS_EXPORT(module, isolate, "findGroup", regex_find_group);
    XRS_EXPORT(module, isolate, "find", regex_find);
    XRS_EXPORT(module, isolate, "fullFind", regex_full_match);
    XRS_EXPORT(module, isolate, "findAll", regex_find_all);
    XRS_EXPORT(module, isolate, "replace", regex_replace);
    XRS_EXPORT(module, isolate, "replaceAll", regex_replace_all);
    XRS_EXPORT(module, isolate, "split", regex_split);
    XRS_EXPORT(module, isolate, "escape", regex_escape);
    XRS_EXPORT(module, isolate, "isValid", regex_is_valid);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_REGEX */

#ifdef XR_STDLIB_VM_BIND_MODULE_SYS
static void xr_stdlib_vm_bind_sys_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "Mutex", sys_mutex_new);
    XRS_EXPORT(module, isolate, "RwLock", sys_rwlock_new);
    XRS_EXPORT(module, isolate, "Condvar", sys_condvar_new);
    XRS_EXPORT(module, isolate, "Barrier", sys_barrier_new);
    XRS_EXPORT(module, isolate, "Once", sys_once_new);
    XRS_EXPORT(module, isolate, "cpuCount", sys_cpu_count);
    XRS_EXPORT(module, isolate, "threadYield", sys_thread_yield);
    XRS_EXPORT(module, isolate, "sleepMs", sys_sleep_ms);
    XRS_EXPORT(module, isolate, "pinToCpu", sys_pin_to_cpu);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_SYS */

#ifdef XR_STDLIB_VM_BIND_MODULE_TIME
static void xr_stdlib_vm_bind_time_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "now", xr_time_now);
    XRS_EXPORT(module, isolate, "clock", xr_time_clock);
    XRS_EXPORT(module, isolate, "monotonic", xr_time_monotonic);
    XRS_EXPORT(module, isolate, "nanos", xr_time_nanos);
    XRS_EXPORT(module, isolate, "micros", xr_time_micros);
    XRS_EXPORT_YIELDABLE(module, isolate, "sleep", xr_time_sleep);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_TIME */

#ifdef XR_STDLIB_VM_BIND_MODULE_TOML
static void xr_stdlib_vm_bind_toml_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "parse", toml_parse);
    XRS_EXPORT(module, isolate, "parseStrict", toml_parse_strict);
    XRS_EXPORT(module, isolate, "stringify", toml_stringify);
    XRS_EXPORT(module, isolate, "parseFile", toml_parse_file);
    XRS_EXPORT(module, isolate, "writeFile", toml_write_file);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_TOML */

#ifdef XR_STDLIB_VM_BIND_MODULE_WS
static void xr_stdlib_vm_bind_ws_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT_YIELDABLE(module, isolate, "connect", ws_connect_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "send", ws_send_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "recv", ws_recv_yieldable);
    XRS_EXPORT(module, isolate, "close", ws_close);
    XRS_EXPORT(module, isolate, "ping", ws_ping);
    XRS_EXPORT(module, isolate, "state", ws_state);
    XRS_EXPORT(module, isolate, "isOpen", ws_is_open);
    XRS_EXPORT_YIELDABLE(module, isolate, "recvData", ws_recvdata);
    XRS_EXPORT_YIELDABLE(module, isolate, "sendData", ws_send_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "serve", ws_serve_yieldable);
    XRS_EXPORT_YIELDABLE(module, isolate, "echoServe", ws_echo_serve_yieldable);
    XRS_EXPORT(module, isolate, "stopServer", ws_stop_server);
    XRS_EXPORT(module, isolate, "isServerRunning", ws_is_server_running);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_WS */

#ifdef XR_STDLIB_VM_BIND_MODULE_XML
static void xr_stdlib_vm_bind_xml_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "parse", xml_parse_fn);
    XRS_EXPORT(module, isolate, "parseDetailed", xml_parse_detailed);
    XRS_EXPORT(module, isolate, "parseFile", xml_parse_file);
    XRS_EXPORT(module, isolate, "stringify", xml_stringify_fn);
    XRS_EXPORT(module, isolate, "writeFile", xml_write_file);
    XRS_EXPORT(module, isolate, "document", xml_document_fn);
    XRS_EXPORT(module, isolate, "element", xml_element_fn);
    XRS_EXPORT(module, isolate, "text", xml_text_fn);
    XRS_EXPORT(module, isolate, "comment", xml_comment_fn);
    XRS_EXPORT(module, isolate, "cdata", xml_cdata_fn);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_XML */

#ifdef XR_STDLIB_VM_BIND_MODULE_YAML
static void xr_stdlib_vm_bind_yaml_generated(XrVMRuntime *isolate, XrModule *module) {
    XRS_EXPORT(module, isolate, "parse", yaml_parse);
    XRS_EXPORT(module, isolate, "parseStrict", yaml_parse_strict);
    XRS_EXPORT(module, isolate, "parseAll", yaml_parse_all);
    XRS_EXPORT(module, isolate, "stringify", yaml_stringify);
    XRS_EXPORT(module, isolate, "parseFile", yaml_parse_file);
    XRS_EXPORT(module, isolate, "writeFile", yaml_write_file);
}
#endif  /* XR_STDLIB_VM_BIND_MODULE_YAML */

/* clang-format on */
