/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/stdlibgen/stdlibgen.py
 *
 * xstdlib_class_bindings_generated.inc.c - VM stdlib class binding shell
 */

/* clang-format off */

/*
 * Include this file from a stdlib module TU after the class method
 * functions and native body descriptor have been declared, then define
 * one or more XR_STDLIB_VM_BIND_CLASS_<CLASS> macros before including it.
 */

#ifdef XR_STDLIB_VM_BIND_CLASS___BUFFER_STORAGE
static void xr_stdlib_vm_register___buffer_storage_class_generated(XrVMRuntime *X) {
    XR_DCHECK(X != NULL, "xr_stdlib_vm_register___buffer_storage_class_generated: NULL isolate");
    XrayCoreClasses *core = xr_isolate_get_core_classes(X);
    XR_DCHECK(core != NULL, "xr_stdlib_vm_register___buffer_storage_class_generated: core not initialised");
    XR_DCHECK(core->objectClass != NULL, "xr_stdlib_vm_register___buffer_storage_class_generated: super class not registered");
    XR_DCHECK(core->memBufferClass == NULL, "xr_stdlib_vm_register___buffer_storage_class_generated: already registered");
    XrClassBuilder *builder = xr_class_builder_new(X, "__BufferStorage", core->objectClass);
    XR_CHECK(builder != NULL, "xr_stdlib_vm_register___buffer_storage_class_generated: builder alloc failed");
    xr_class_builder_set_native_body(builder, xr_buffer_native_body_desc());
    XrClass *cls = xr_class_builder_finalize(builder);
    XR_CHECK(cls != NULL, "xr_stdlib_vm_register___buffer_storage_class_generated: finalize failed");
    cls->flags |= XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY;
    cls->builtin_kind = XR_BK_BUFFER;
    core->memBufferClass = cls;
}
#endif  /* XR_STDLIB_VM_BIND_CLASS___BUFFER_STORAGE */

#ifdef XR_STDLIB_VM_BIND_CLASS_NET_CONN
static void xr_stdlib_vm_register_net_conn_class_generated(XrVMRuntime *X) {
    XR_DCHECK(X != NULL, "xr_stdlib_vm_register_net_conn_class_generated: NULL isolate");
    XrayCoreClasses *core = xr_isolate_get_core_classes(X);
    XR_DCHECK(core != NULL, "xr_stdlib_vm_register_net_conn_class_generated: core not initialised");
    XR_DCHECK(core->netConnClass == NULL, "xr_stdlib_vm_register_net_conn_class_generated: already registered");
    XrClassBuilder *builder = xr_class_builder_new(X, "NetConn", NULL);
    XR_CHECK(builder != NULL, "xr_stdlib_vm_register_net_conn_class_generated: builder alloc failed");
    xr_class_builder_set_native_body(builder, xr_netconn_body_desc());
    XrClass *cls = xr_class_builder_finalize(builder);
    XR_CHECK(cls != NULL, "xr_stdlib_vm_register_net_conn_class_generated: finalize failed");
    cls->flags |= XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY;
    cls->builtin_kind = XR_BK_NETCONN;
    core->netConnClass = cls;
}
#endif  /* XR_STDLIB_VM_BIND_CLASS_NET_CONN */

#ifdef XR_STDLIB_VM_BIND_CLASS_NET_LISTENER
static void xr_stdlib_vm_register_net_listener_class_generated(XrVMRuntime *X) {
    XR_DCHECK(X != NULL, "xr_stdlib_vm_register_net_listener_class_generated: NULL isolate");
    XrayCoreClasses *core = xr_isolate_get_core_classes(X);
    XR_DCHECK(core != NULL, "xr_stdlib_vm_register_net_listener_class_generated: core not initialised");
    XR_DCHECK(core->netListenerClass == NULL, "xr_stdlib_vm_register_net_listener_class_generated: already registered");
    XrClassBuilder *builder = xr_class_builder_new(X, "NetListener", NULL);
    XR_CHECK(builder != NULL, "xr_stdlib_vm_register_net_listener_class_generated: builder alloc failed");
    xr_class_builder_set_native_body(builder, xr_netlistener_body_desc());
    XrClass *cls = xr_class_builder_finalize(builder);
    XR_CHECK(cls != NULL, "xr_stdlib_vm_register_net_listener_class_generated: finalize failed");
    cls->flags |= XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY;
    cls->builtin_kind = XR_BK_NETLISTENER;
    core->netListenerClass = cls;
}
#endif  /* XR_STDLIB_VM_BIND_CLASS_NET_LISTENER */

/* clang-format on */
