/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/stdlibgen/stdlibgen.py
 *
 * xstdlib_defs_generated.h - stdlib declarative metadata
 */

/* clang-format off */

#ifndef XSTDLIB_DEFS_GENERATED_H
#define XSTDLIB_DEFS_GENERATED_H

#include <stdbool.h>
#include <math.h>
#include <stdint.h>
#include "../base/xentry_plan.h"

typedef enum XrStdlibTargetLeafKind {
    XR_STDLIB_TARGET_LEAF_NONE = 0,
    XR_STDLIB_TARGET_LEAF_I64_GETPID = 1,
    XR_STDLIB_TARGET_LEAF_COUNT,
} XrStdlibTargetLeafKind;

typedef struct XrStdlibDefEntry {
    const char *module;
    const char *name;
    const char *signature;
    const char *doc;
    const char *vm;
    const char *vm_binding;
    const char *vm_ifdef;
    const char *aot;
    const char *arg_spec;
    const char *ret;
    const char *aot_enum;
    const char *link_object;
    const char *define;
    const char *layer;
    const char *aot_kind;
    uint32_t runtime_capabilities;
    uint16_t argc;
    uint16_t target_leaf;
    bool aot_direct;
} XrStdlibDefEntry;

typedef struct XrStdlibConstDefEntry {
    const char *module;
    const char *name;
    const char *signature;
    const char *doc;
    const char *vm;
    const char *vm_value;
    const char *aot;
    const char *aot_const_kind;
    const char *link_object;
    const char *define;
    const char *layer;
    uint32_t runtime_capabilities;
    int64_t value;
    double f64_value;
} XrStdlibConstDefEntry;

typedef struct XrStdlibHandleFieldDefEntry {
    const char *module;
    const char *handle;
    const char *name;
    const char *type;
    bool is_const;
} XrStdlibHandleFieldDefEntry;

typedef struct XrStdlibHandleDefEntry {
    const char *module;
    const char *name;
    const char *doc;
    const XrStdlibHandleFieldDefEntry *fields;
    uint16_t field_count;
} XrStdlibHandleDefEntry;

typedef struct XrStdlibObjectShapeDefEntry {
    const char *module;
    const char *name;
    const char *doc;
    const XrStdlibHandleFieldDefEntry *fields;
    uint16_t field_count;
    bool exact;
} XrStdlibObjectShapeDefEntry;

typedef struct XrStdlibEnumVariantDefEntry {
    const char *name;
    const char *const *payload_types;
    uint16_t payload_count;
} XrStdlibEnumVariantDefEntry;

typedef struct XrStdlibEnumDefEntry {
    const char *module;
    const char *name;
    const char *doc;
    const XrStdlibEnumVariantDefEntry *variants;
    uint16_t variant_count;
    uint32_t layout_id;
} XrStdlibEnumDefEntry;

typedef struct XrStdlibTypeMethodDefEntry {
    const char *module;
    const char *type_name;
    const char *name;
    const char *signature;
    const char *doc;
} XrStdlibTypeMethodDefEntry;

typedef struct XrStdlibNativeClassDefEntry {
    const char *module;
    const char *name;
    const char *super_slot;
    const char *core_slot;
    const char *native_body_expr;
    const char *flags;
    const char *builtin_kind;
} XrStdlibNativeClassDefEntry;

typedef struct XrStdlibClassDefEntry {
    const char *module;
    const char *name;
    const char *super_slot;
    const char *core_slot;
    const char *flags;
    const char *builtin_kind;
} XrStdlibClassDefEntry;

typedef struct XrStdlibClassMethodDefEntry {
    const char *module;
    const char *class_name;
    const char *name;
    const char *vm;
    int16_t argc;
    const char *flags;
} XrStdlibClassMethodDefEntry;

typedef struct XrStdlibClassFieldDefEntry {
    const char *module;
    const char *class_name;
    const char *name;
    const char *flags;
} XrStdlibClassFieldDefEntry;

static const XrStdlibDefEntry xr_stdlib_def_entries[] = {
    {"time", "__realtimeNanos", "(): i64", "Nanoseconds since the Unix epoch on the wall clock", "time_realtimeNanos", "normal", "", "xrt_time_realtime_nanos", "", "value", "", "time.__realtimeNanos", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"time", "__monotonicNanos", "(): i64", "Nanoseconds on the runtime monotonic clock", "time_monotonicNanos", "normal", "", "xrt_time_monotonic_nanos", "", "value", "", "time.__monotonicNanos", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"time", "__cpuNanos", "(): i64", "Nanoseconds of process CPU time consumed", "time_cpuNanos", "normal", "", "xrt_time_cpu_nanos", "", "value", "", "time.__cpuNanos", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"time", "__utcOffsetAt", "(seconds: i64): i64", "Minutes east of UTC at a Unix timestamp in seconds", "time_utcOffsetAt", "normal", "", "xrt_time_utc_offset_at", "v", "value", "", "time.__utcOffsetAt", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"time", "sleep", "(ms: i64): ()", "Sleep for milliseconds", "xr_time_sleep", "yieldable", "", "", "v", "value", "", "", "", "runtime", "", XR_CAP_COROUTINE | XR_CAP_TIMER, 1, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"math", "abs", "(x: f64): f64", "Absolute value", "math_abs", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "floor", "(x: f64): i64", "Floor to integer", "math_floor", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "ceil", "(x: f64): i64", "Ceiling to integer", "math_ceil", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "round", "(x: f64): i64", "Round to nearest integer", "math_round", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "sqrt", "(x: f64): f64", "Square root", "math_sqrt", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "pow", "(base: f64, exp: f64): f64", "Power", "math_pow", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "sin", "(x: f64): f64", "Sine", "math_sin", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "cos", "(x: f64): f64", "Cosine", "math_cos", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "tan", "(x: f64): f64", "Tangent", "math_tan", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "asin", "(x: f64): f64", "Arc sine", "math_asin", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "acos", "(x: f64): f64", "Arc cosine", "math_acos", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "atan", "(x: f64): f64", "Arc tangent", "math_atan", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "atan2", "(y: f64, x: f64): f64", "Arc tangent of y/x", "math_atan2", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "log", "(x: f64): f64", "Natural logarithm", "math_log", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "log10", "(x: f64): f64", "Base-10 logarithm", "math_log10", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "log2", "(x: f64): f64", "Base-2 logarithm", "math_log2", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "exp", "(x: f64): f64", "Exponential e^x", "math_exp", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "min", "(...args: f64): f64", "Minimum value", "math_min", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, UINT16_MAX, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "max", "(...args: f64): f64", "Maximum value", "math_max", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, UINT16_MAX, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "clamp", "(x: f64, min: f64, max: f64): f64", "Clamp to a closed interval", "math_clamp", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "random", "(): f64", "Random f64 in [0, 1)", "math_random", "normal", "", "xrt_math_random", "", "value", "", "math.random", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "randomInt", "(min: i64, max: i64): i64", "Random integer in [min, max]", "math_randomInt", "normal", "", "xrt_math_random_int", "vv", "value", "", "math.randomInt", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "sign", "(x: f64): i64", "Sign of value (-1, 0, 1)", "math_sign", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "sinh", "(x: f64): f64", "Hyperbolic sine", "math_sinh", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "cosh", "(x: f64): f64", "Hyperbolic cosine", "math_cosh", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "tanh", "(x: f64): f64", "Hyperbolic tangent", "math_tanh", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "hypot", "(x: f64, y: f64): f64", "Hypotenuse sqrt(x*x+y*y)", "math_hypot", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "cbrt", "(x: f64): f64", "Cube root", "math_cbrt", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "trunc", "(x: f64): i64", "Truncate toward zero", "math_trunc", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "fmod", "(x: f64, y: f64): f64", "Floating-point remainder", "math_fmod", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "log1p", "(x: f64): f64", "log(1+x) accurate for small x", "math_log1p", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "expm1", "(x: f64): f64", "exp(x)-1 accurate for small x", "math_expm1", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "lerp", "(a: f64, b: f64, t: f64): f64", "Linear interpolation", "math_lerp", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "degToRad", "(deg: f64): f64", "Degrees to radians", "math_degToRad", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "radToDeg", "(rad: f64): f64", "Radians to degrees", "math_radToDeg", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "isNaN", "(x: f64): bool", "Check if NaN", "math_isNaN", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"math", "isFinite", "(x: f64): bool", "Check if finite", "math_isFinite", "normal", "", "builtin", "", "value", "", "", "", "core", "builtin", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"compress", "__gzip", "(data: string, level: i64): string?", "Gzip-wrap and deflate at the given level", "compress_gzip", "normal", "", "xrt_compress_gzip", "sv", "value", "", "compress.__gzip", "", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"compress", "__gunzip", "(data: string): string", "Inflate a gzip member, refusing a header that is not gzip", "compress_gunzip", "normal", "", "xrt_compress_gunzip", "s", "value", "", "compress.__gunzip", "", "alloc", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"compress", "__deflate", "(data: string, level: i64): string?", "Raw deflate at the given level", "compress_deflate", "normal", "", "xrt_compress_deflate", "sv", "value", "", "compress.__deflate", "", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"compress", "__inflate", "(data: string): string", "Raw inflate", "compress_inflate", "normal", "", "xrt_compress_inflate", "s", "value", "", "compress.__inflate", "", "alloc", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"compress", "__zlibCompress", "(data: string, level: i64): string?", "Zlib-wrap and deflate at the given level", "compress_zlib_compress", "normal", "", "xrt_compress_zlib_compress", "sv", "value", "", "compress.__zlibCompress", "", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"compress", "__zlibDecompress", "(data: string): string", "Inflate a zlib stream, refusing a header that is not zlib", "compress_zlib_decompress", "normal", "", "xrt_compress_zlib_decompress", "s", "value", "", "compress.__zlibDecompress", "", "alloc", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"crypto", "__randomBytes", "(n: i64): Array<u8>", "Read n bytes from the platform CSPRNG", "crypto_random_bytes_raw", "normal", "", "xrt_crypto_random_bytes_raw", "v", "value", "", "crypto.__randomBytes", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"crypto", "__timingSafeEqualBytes", "(a: Array<u8>, b: Array<u8>): bool", "Compare two byte buffers in time independent of where they differ", "crypto_timing_safe_equal_bytes", "normal", "", "xrt_crypto_timing_safe_equal_bytes", "vv", "value", "", "", "", "core", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "OsMutex", "(): OsMutex", "Create an OS-domain mutex", "sys_mutex_new", "normal", "", "xrt_sys_mutex_new", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__osMutexNew", "(): OsMutex", "Create an OS-domain mutex for sys module internals", "sys_mutex_new", "normal", "", "xrt_sys_mutex_new", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "OsRwLock", "(): OsRwLock", "Create an OS-domain read-write lock", "sys_rwlock_new", "normal", "", "xrt_sys_rwlock_new", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "OsCondvar", "(): OsCondvar", "Create an OS-domain condition variable", "sys_condvar_new", "normal", "", "xrt_sys_condvar_new", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "OsBarrier", "(parties: i64): OsBarrier", "Create a reusable OS-domain barrier", "sys_barrier_new", "normal", "", "xrt_sys_barrier_new", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "OsOnce", "(): OsOnce", "Create an OS-domain once gate", "sys_once_new", "normal", "", "xrt_sys_once_new", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "cpuCount", "(): i64", "Return the number of CPUs available to OS-thread work", "sys_cpu_count", "normal", "", "xrt_sys_cpu_count", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "threadYield", "(): ()", "Yield the current OS thread to another runnable OS thread", "sys_thread_yield", "normal", "", "xrt_sys_thread_yield", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "sleepMs", "(ms: i64): ()", "Block the current OS thread for at least ms milliseconds", "sys_sleep_ms", "normal", "", "xrt_sys_sleep_ms", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "pinToCpu", "(cpu: i64): bool", "Best-effort pin of the current OS thread to a CPU index", "sys_pin_to_cpu", "normal", "", "xrt_sys_pin_to_cpu", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__threadLocalId", "(): i64", "Return a stable token for the current OS thread", "sys_thread_local_id", "normal", "", "xrt_sys_thread_local_id", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__threadLocalAlive", "(id: i64): bool", "Return whether an internal sys.ThreadLocal OS-thread token is still live", "sys_thread_local_alive", "normal", "", "xrt_sys_thread_local_alive", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__onSignal", "(signal: i64, handler: fn(): ()): bool", "Register a VM-hosted safe-point handler for a portable process signal", "sys_on_signal", "normal", "", "xrt_sys_on_signal", "vv", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__dylibOpen", "(path: Path): i64", "Open a dynamic library and return an opaque handle token, or 0 on failure", "sys_dylib_open", "normal", "", "xrt_sys_dylib_open", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__dylibSymbol", "(handle: i64, name: string): Ptr<u8>?", "Resolve a dynamic-library symbol to a raw address, or null on failure", "sys_dylib_symbol", "normal", "", "xrt_sys_dylib_symbol", "vs", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__dylibClose", "(handle: i64): bool", "Close a dynamic library handle token", "sys_dylib_close", "normal", "", "xrt_sys_dylib_close", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__dylibLastError", "(): string", "Return the platform dynamic-loader error message for the current thread", "sys_dylib_last_error", "normal", "", "xrt_sys_dylib_last_error", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__processSpawn", "(program: string, args: Array<string>, cwd: string?, envKeys: Array<string>?, envValues: Array<string>?, stdinRead: i64?, stdoutWrite: i64?, stderrWrite: i64?, detached: bool): i64", "Spawn a process and return an opaque process handle token, or -1 on failure", "sys_process_spawn", "normal", "", "xrt_sys_process_spawn", "svvvvvvvv", "value", "", "", "", "system", "method", 0, 9, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__processWait", "(id: i64): i64", "Wait for a process handle token and return its exit code, or -1 on failure", "sys_process_wait_yieldable", "yieldable", "", "xrt_sys_process_wait", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__processTryWait", "(id: i64): i64?", "Poll a process handle token; return null while running, exit code when finished, or -1 on failure", "sys_process_try_wait", "normal", "", "xrt_sys_process_try_wait", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__processKill", "(id: i64, signal: i64): bool", "Send a portable process signal to a process handle token", "sys_process_kill", "normal", "", "xrt_sys_process_kill", "vv", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__pipeOpen", "(): Array<i64>?", "Create an anonymous pipe and return read/write endpoint tokens", "sys_pipe_open", "normal", "", "xrt_sys_pipe_open", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__pipeRead", "(handle: i64, maxBytes: i64): Array<u8>?", "Read one chunk from a pipe endpoint", "sys_pipe_read_yieldable", "yieldable", "", "xrt_sys_pipe_read", "vv", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__pipeWrite", "(handle: i64, data: Array<u8>): i64", "Write one chunk to a pipe endpoint", "sys_pipe_write_yieldable", "yieldable", "", "xrt_sys_pipe_write", "vv", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"sys", "__pipeClose", "(handle: i64): bool", "Close a pipe endpoint", "sys_pipe_close", "normal", "", "xrt_sys_pipe_close", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__compile", "(pattern: string, flags?: string): Regex", "Compile regex pattern", "regex_compile", "normal", "", "xrt_regex_compile_default", "s", "value", "", "regex.__compile", "XRT_ENABLE_REGEX", "alloc", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__compile", "(pattern: string, flags?: string): Regex", "Compile regex pattern", "regex_compile", "normal", "", "xrt_regex_compile_with_flags", "ss", "value", "", "regex.__compile", "XRT_ENABLE_REGEX", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__test", "(pattern: Regex, s: string): bool", "Test if regex matches", "regex_test", "normal", "", "xrt_regex_test", "vs", "value", "", "regex.__test", "XRT_ENABLE_REGEX", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__count", "(pattern: Regex, s: string): i64", "Count matches", "regex_count", "normal", "", "xrt_regex_count", "vs", "value", "", "regex.__count", "XRT_ENABLE_REGEX", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__findText", "(pattern: Regex, s: string): string?", "Find first matching text", "regex_find_text", "normal", "", "xrt_regex_find_text", "vs", "value", "", "regex.__findText", "XRT_ENABLE_REGEX", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__findGroup", "(pattern: Regex, s: string, index: i64): string?", "Find capture group", "regex_find_group", "normal", "", "xrt_regex_find_group", "vsv", "value", "", "regex.__findGroup", "XRT_ENABLE_REGEX", "alloc", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "find", "(pattern: Regex, s: string, offset?: i64): RegexMatch?", "Find first match", "regex_find", "normal", "", "xrt_regex_find", "vs", "value", "", "regex.find", "XRT_ENABLE_REGEX", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "find", "(pattern: Regex, s: string, offset?: i64): RegexMatch?", "Find first match", "regex_find", "normal", "", "xrt_regex_find_offset", "vsv", "value", "", "regex.find", "XRT_ENABLE_REGEX", "alloc", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "fullFind", "(pattern: Regex, s: string): RegexMatch?", "Find full match", "regex_full_match", "normal", "", "xrt_regex_full_find", "vs", "value", "", "regex.fullFind", "XRT_ENABLE_REGEX", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "findAll", "(pattern: Regex, s: string, limit?: i64): Array<RegexMatch>", "Find all matches", "regex_find_all", "normal", "", "xrt_regex_find_all", "vs", "value", "", "regex.findAll", "XRT_ENABLE_REGEX", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "findAll", "(pattern: Regex, s: string, limit?: i64): Array<RegexMatch>", "Find all matches", "regex_find_all", "normal", "", "xrt_regex_find_all_limit", "vsv", "value", "", "regex.findAll", "XRT_ENABLE_REGEX", "alloc", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__replace", "(pattern: Regex, s: string, repl: string): string", "Replace first match", "regex_replace", "normal", "", "xrt_regex_replace", "vss", "value", "", "regex.__replace", "XRT_ENABLE_REGEX", "alloc", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__replaceAll", "(pattern: Regex, s: string, repl: string): string", "Replace all matches", "regex_replace_all", "normal", "", "xrt_regex_replace_all", "vss", "value", "", "regex.__replaceAll", "XRT_ENABLE_REGEX", "alloc", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__split", "(pattern: Regex, s: string, limit?: i64): Array<string>", "Split string by regex", "regex_split", "normal", "", "xrt_regex_split", "vs", "value", "", "regex.__split", "XRT_ENABLE_REGEX", "alloc", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__split", "(pattern: Regex, s: string, limit?: i64): Array<string>", "Split string by regex", "regex_split", "normal", "", "xrt_regex_split_limit", "vsv", "value", "", "regex.__split", "XRT_ENABLE_REGEX", "alloc", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__escape", "(s: string): string", "Escape regex special chars", "regex_escape", "normal", "", "xrt_regex_escape", "s", "value", "", "", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"regex", "__isValid", "(pattern: string): bool", "Check if pattern is valid", "regex_is_valid", "normal", "", "xrt_regex_is_valid", "s", "value", "", "regex.__isValid", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__platform", "(): string", "Host operating system name", "os_platform", "normal", "", "xrt_os_platform", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__arch", "(): string", "Host CPU architecture name", "os_arch", "normal", "", "xrt_os_arch", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__getenv", "(name: string): string?", "Get environment variable", "os_getenv", "normal", "", "xrt_os_getenv", "s", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__setenv", "(name: string, value: string): bool", "Set environment variable", "os_setenv", "normal", "", "xrt_os_setenv", "ss", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__unsetenv", "(name: string): bool", "Unset environment variable", "os_unsetenv", "normal", "", "xrt_os_unsetenv", "s", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__environBlock", "(): Array<string>", "Host environment block as raw NAME=VALUE entries", "os_environ_block", "normal", "", "xrt_os_environ_block", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__exit", "(code?: i64): ()", "Exit process", "os_exit", "normal", "", "xrt_os_exit", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__getpid", "(): i64", "Get process ID", "os_getpid", "normal", "", "xrt_os_getpid", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_I64_GETPID, true},
    {"os", "__getcwd", "(): string", "Get current working directory", "os_getcwd", "normal", "", "xrt_os_getcwd", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__hostname", "(): string", "Get hostname", "os_hostname", "normal", "", "xrt_os_hostname", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__systemUsername", "(): string?", "Get the host-reported current user name", "os_system_username", "normal", "", "xrt_os_system_username", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__systemHomedir", "(): string?", "Get user home directory", "os_system_homedir", "normal", "", "xrt_os_system_homedir", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__uid", "(): i64", "Get user ID", "os_uid", "normal", "", "xrt_os_uid", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__gid", "(): i64", "Get group ID", "os_gid", "normal", "", "xrt_os_gid", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__cpuCount", "(): i64", "Get number of CPU cores", "os_cpuCount", "normal", "", "xrt_os_cpu_count", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__ppid", "(): i64", "Get parent process ID", "os_ppid", "normal", "", "xrt_os_ppid", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__kill", "(pid: i64, signal?: i64): bool", "Send signal to process", "os_kill", "normal", "", "xrt_os_kill", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__kill", "(pid: i64, signal?: i64): bool", "Send signal to process", "os_kill", "normal", "", "xrt_os_kill_signal", "vv", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__totalMemory", "(): i64", "Get total system memory in bytes", "os_totalMemory", "normal", "", "xrt_os_total_memory", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__freeMemory", "(): i64", "Get available system memory in bytes", "os_freeMemory", "normal", "", "xrt_os_free_memory", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__uptime", "(): f64", "Get system uptime in seconds", "os_uptime", "normal", "", "xrt_os_uptime", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__loadavg", "(): Array<f64>", "Get system load averages (1, 5, 15 min)", "os_loadavg", "normal", "", "xrt_os_loadavg", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__clock", "(): f64", "Get process CPU time in seconds", "os_clock", "normal", "", "xrt_os_clock", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__sleep", "(ms: i64): ()", "Sleep for milliseconds", "os_sleep", "yieldable", "", "xrt_os_sleep", "v", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__exec", "(cmd: string): __ExecResult?", "Execute shell command", "os_exec", "normal", "", "xrt_os_exec", "s", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"os", "__spawn", "(program: string, args: Array<string>): __ExecResult?", "Execute a program without a shell (injection-safe argv)", "os_spawn", "normal", "", "", "sv", "value", "", "", "", "system", "", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"io", "__appendFile", "(path: Path, data: string): bool", "Append string to file", "io_appendFile", "normal", "", "xrt_io_append_file", "ps", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__chmod", "(path: Path, mode: i64): bool", "Change file permissions", "io_chmod", "normal", "", "xrt_io_chmod_value", "pv", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__chdir", "(path: Path): bool", "Change working directory", "io_chdir", "normal", "", "xrt_io_chdir", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__copyFile", "(src: Path, dst: Path): bool", "Copy a file", "io_copyFile", "normal", "", "xrt_io_copy_file", "pp", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__cwd", "(): string", "Get current working directory (raw string; io.xr wraps as Path)", "io_cwd", "normal", "", "xrt_io_cwd", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__exists", "(path: Path): bool", "Check if path exists", "io_exists", "normal", "", "xrt_io_exists", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__fileClose", "(handle: i64): bool", "Close an owned binary file handle", "io_fileClose", "normal", "", "xrt_io_file_close", "i", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__fileOpen", "(path: Path): i64", "Open a file for binary reading and return an opaque handle", "io_fileOpen", "normal", "", "xrt_io_file_open", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__fileRead", "(handle: i64, maxBytes: i64): Array<u8>?", "Read at most maxBytes from an opaque binary stream; empty means EOF", "io_fileRead", "normal", "", "xrt_io_read_handle_chunk", "ii", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__fileSize", "(path: Path): i64", "Get file size in bytes", "io_fileSize", "normal", "", "xrt_io_file_size", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__isDir", "(path: Path): bool", "Check if path is a directory", "io_isDir", "normal", "", "xrt_io_is_dir", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__isFile", "(path: Path): bool", "Check if path is a file", "io_isFile", "normal", "", "xrt_io_is_file", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__isSymlink", "(path: Path): bool", "Check if path is a symlink", "io_isSymlink", "normal", "", "xrt_io_is_symlink", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__mkdir", "(path: Path): bool", "Create directory", "io_mkdir", "normal", "", "xrt_io_mkdir", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__readDir", "(path: Path): Array<string>?", "List directory entries (raw strings; io.xr wraps as Path)", "io_readDir", "normal", "", "xrt_io_read_dir", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__readFile", "(path: Path): string?", "Read entire file as string", "io_readFile", "yieldable", "", "xrt_io_read_file", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__readFileBytes", "(path: Path): Array<u8>?", "Read entire file as byte array", "io_readFileBytes", "yieldable", "", "xrt_io_read_file_bytes", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__readStdin", "(): string?", "Read all data from standard input", "io_readStdin", "normal", "", "xrt_io_read_stdin", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__readStdinBytes", "(): Array<u8>?", "Read all standard input as binary bytes", "io_readStdinBytes", "normal", "", "xrt_io_read_stdin_bytes", "", "value", "", "", "", "system", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__readlink", "(path: Path): string?", "Read symlink target (raw string; io.xr wraps as Path)", "io_readlink", "normal", "", "xrt_io_readlink", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__realpath", "(path: Path): string?", "Resolve to absolute path (raw string; io.xr wraps as Path)", "io_realpath", "normal", "", "xrt_io_realpath", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__rmdir", "(path: Path): bool", "Remove an empty directory", "io_rmdir", "normal", "", "xrt_io_rmdir", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__remove", "(path: Path): bool", "Remove a file", "io_remove", "normal", "", "xrt_io_remove", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__rename", "(old: Path, new: Path): bool", "Rename a file", "io_rename", "normal", "", "xrt_io_rename", "pp", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__stat", "(path: Path): __FileStat?", "Get file stat info", "io_stat", "normal", "", "xrt_io_stat", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__symlink", "(target: Path, link: Path): bool", "Create symbolic link", "io_symlink", "normal", "", "xrt_io_symlink", "pp", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__makeTempDir", "(root: string): string?", "Create a uniquely named directory inside the given root", "io_make_temp_dir", "normal", "", "xrt_io_make_temp_dir", "s", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__makeTempFile", "(root: string): string?", "Create a uniquely named file inside the given root", "io_make_temp_file", "normal", "", "xrt_io_make_temp_file", "s", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__utimeNow", "(path: Path): bool", "Set a path's access and modification times to now", "io_utime_now", "normal", "", "xrt_io_utime_now", "p", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__writeFile", "(path: Path, data: string): bool", "Write string to file", "io_writeFile", "yieldable", "", "xrt_io_write_file", "ps", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__writeFileBytes", "(path: Path, data: Array<u8>): bool", "Write byte array to file", "io_writeFileBytes", "yieldable", "", "xrt_io_write_file_bytes", "pv", "value", "", "", "", "system", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__writeStderr", "(data: string): bool", "Write text to standard error without adding a newline", "io_writeStderr", "normal", "", "xrt_io_write_stderr", "s", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"io", "__writeStdout", "(data: string): bool", "Write text to standard output without adding a newline", "io_writeStdout", "normal", "", "xrt_io_write_stdout", "s", "value", "", "", "", "system", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"runtime", "__stats", "(): __RuntimeStats", "Read the current execution-local reclamation domain counters", "runtime_stats", "normal", "", "xr_aot_runtime_info", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"runtime", "__liveBytes", "(): i64", "Live memory bytes in the current execution-local reclamation domain", "runtime_live_bytes", "normal", "", "xr_aot_runtime_live_bytes", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"runtime", "__liveObjects", "(): i64", "Live object count in the current execution-local reclamation domain", "runtime_live_objects", "normal", "", "xr_aot_runtime_live_objects", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"runtime", "__sharedLiveBytes", "(): i64", "Live bytes held by SYNC_SHARED system-heap objects (process-wide)", "runtime_shared_bytes", "normal", "", "xr_aot_runtime_shared_bytes", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"runtime", "__staticAllocBytes", "(): i64", "Memory allocated into the MODULE_STATIC class/module arena (process-wide)", "runtime_static_bytes", "normal", "", "xr_aot_runtime_static_bytes", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "__fence", "(ordering: i64): ()", "Standalone memory fence; ordering mirrors Ordering enum ordinals (0 Relaxed .. 4 SeqCst)", "mem_fence", "normal", "", "xrt_mem_fence", "v", "value", "", "", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__prefetch", "(ptr: Ptr<u8>, rw: i64): ()", "Prefetch a cache line at ptr (performance hint; rw!=0 = write intent). VM no-op, AOT __builtin_prefetch", "mem_prefetch", "normal", "", "xrt_mem_prefetch", "vv", "value", "", "", "", "core", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__cacheFlush", "(ptr: Ptr<u8>, n: i64): ()", "Best-effort data-cache flush for a byte range. VM no-op; AOT emits platform cache maintenance when available", "mem_cache_flush", "normal", "", "xrt_mem_cache_flush", "vv", "value", "", "", "", "core", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__cacheInvalidate", "(ptr: Ptr<u8>, n: i64): ()", "Best-effort data-cache invalidation for a byte range. VM no-op; AOT emits platform cache maintenance when available", "mem_cache_invalidate", "normal", "", "xrt_mem_cache_invalidate", "vv", "value", "", "", "", "core", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__nontemporalStore", "(ptr: MutPtr<u8>, v: i64, size: i64): ()", "Best-effort non-temporal sized store (size in {1,2,4,8}). VM stores normally; AOT emits streaming stores when available", "mem_nontemporal_store", "normal", "", "xrt_mem_nontemporal_store", "vvv", "value", "", "", "", "core", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__cacheLineSize", "(): i64", "CPU cache line size in bytes", "mem_cache_line_size", "normal", "", "xrt_mem_cache_line_size", "", "value", "", "", "", "core", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "sizeOf", "(): i64", "Compile-time size in bytes of a statically laid out type T", "mem_size_of", "normal", "", "", "", "value", "", "", "", "core", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "alignOf", "(): i64", "Compile-time alignment in bytes of a statically laid out type T", "mem_align_of", "normal", "", "", "", "value", "", "", "", "core", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "offsetOf", "(field: string): i64", "Compile-time byte offset of a field in a fixed-layout struct T", "mem_offset_of", "normal", "", "", "v", "value", "", "", "", "core", "", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "slice", "(ptr: Ptr<u8>, count: i64, owner: any): Slice<u8>", "Unsafe caller-proven borrowed Slice over raw memory, rooted in owner; pointer, count, alignment, and range are unchecked", "mem_slice_intrinsic", "normal", "", "", "vvv", "value", "", "", "", "core", "", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "assumeInitialized", "(buffer: Buffer): any", "Unsafe compiler-verified materialization of a completely initialized native output Buffer as T", "mem_assume_initialized_intrinsic", "normal", "", "", "v", "value", "", "", "", "core", "", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "__alloc", "(n: i64): Buffer", "Allocate n uninitialized bytes as a managed Buffer; released automatically when dropped", "mem_alloc", "normal", "", "xrt_mem_alloc", "v", "value", "", "", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__allocZeroed", "(n: i64): Buffer", "Allocate n zero-initialized bytes as a managed Buffer", "mem_alloc_zeroed", "normal", "", "xrt_mem_alloc_zeroed", "v", "value", "", "", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__allocAligned", "(n: i64, align: i64): Buffer", "Allocate n managed bytes aligned to align (power-of-two >= sizeof(void*))", "mem_alloc_aligned", "normal", "", "xrt_mem_alloc_aligned", "vv", "value", "", "", "", "core", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "pageAlloc", "(bytes: i64, prot?: i64): MutPtr<u8>", "Allocate zero-filled anonymous pages with read/write protection (mmap/VirtualAlloc). NULL on failure; pair with mem.pageFree", "mem_page_alloc", "normal", "", "xrt_mem_page_alloc_default", "v", "value", "", "", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "pageAlloc", "(bytes: i64, prot?: i64): MutPtr<u8>", "Allocate zero-filled anonymous pages with protection bits PROT_READ/PROT_WRITE/PROT_EXEC (mmap/VirtualAlloc). NULL on failure; pair with mem.pageFree", "mem_page_alloc", "normal", "", "xrt_mem_page_alloc", "vv", "value", "", "", "", "core", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__pageProtect", "(ptr: MutPtr<u8>, bytes: i64, prot: i64): bool", "Change anonymous page protection bits; returns false on OS failure", "mem_page_protect", "normal", "", "xrt_mem_page_protect", "vvv", "value", "", "", "", "core", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__pageFree", "(ptr: MutPtr<u8>, bytes: i64): bool", "Release anonymous pages from mem.pageAlloc; returns false on OS failure", "mem_page_free", "normal", "", "xrt_mem_page_free", "vv", "value", "", "", "", "core", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "ptr", "(addr: i64): Ptr<u8>", "Construct Ptr<T> from a numeric address; constructing is safe, dereferencing requires unsafe", "mem_ptr", "normal", "", "xrt_mem_ptr", "v", "value", "", "", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "withSliceMut", "(ptr: MutPtr<u8>, count: i64, guard: any, callback: any): any", "Unsafe caller-proven exclusive mutable Slice loan scoped to a no-suspend callback; pointer, count, alignment, and range are unchecked", "mem_with_slice_mut_intrinsic", "normal", "", "", "vvvv", "value", "", "", "", "core", "", 0, 4, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "mutPtr", "(addr: i64): MutPtr<u8>", "Construct MutPtr<T> from a numeric address; constructing is safe, dereferencing requires unsafe", "mem_mut_ptr", "normal", "", "xrt_mem_mut_ptr", "v", "value", "", "", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "addr", "(ptr: Ptr<u8>): i64", "Numeric address of any Ptr<T> or MutPtr<T>", "mem_addr", "normal", "", "xrt_mem_addr", "v", "value", "", "", "", "core", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "load", "(ptr: Ptr<u8>, offset?: i64, endian?: Endian): i64", "Unsafe unaligned load of scalar or pointer T from ptr plus a byte offset", "mem_load_intrinsic", "normal", "", "", "vvv", "value", "", "", "", "core", "", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "store", "(ptr: MutPtr<u8>, offset: i64, value: any, endian?: Endian): ()", "Unsafe unaligned store of scalar or pointer T at ptr plus a byte offset", "mem_store_intrinsic", "normal", "", "", "vvvv", "value", "", "", "", "core", "", 0, 4, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"mem", "__copy", "(dst: MutPtr<u8>, src: Ptr<u8>, n: i64): ()", "Copy n bytes from src to dst (non-overlapping; memcpy)", "mem_copy", "normal", "", "xrt_mem_copy", "vvv", "value", "", "", "", "core", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__move", "(dst: MutPtr<u8>, src: Ptr<u8>, n: i64): ()", "Copy n bytes from src to dst (may overlap; memmove)", "mem_move", "normal", "", "xrt_mem_move", "vvv", "value", "", "", "", "core", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__set", "(dst: MutPtr<u8>, u8: i64, n: i64): ()", "Fill n bytes at dst with byte (memset)", "mem_set", "normal", "", "xrt_mem_set", "vvv", "value", "", "", "", "core", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__compare", "(a: Ptr<u8>, b: Ptr<u8>, n: i64): i64", "Compare n bytes at a and b (memcmp: <0, 0, >0)", "mem_compare", "normal", "", "xrt_mem_compare", "vvv", "value", "", "", "", "core", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__volatileLoad", "(ptr: Ptr<u8>, size: i64): i64", "Volatile load of size bytes (MMIO; size in {1,2,4,8}, native byte order)", "mem_volatile_load", "normal", "", "xrt_mem_volatile_load", "vv", "value", "", "", "", "core", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"mem", "__volatileStore", "(ptr: MutPtr<u8>, v: i64, size: i64): ()", "Volatile store of size bytes (MMIO; size in {1,2,4,8}, native byte order)", "mem_volatile_store", "normal", "", "xrt_mem_volatile_store", "vvv", "value", "", "", "", "core", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__resolveAll", "(host: string): Array<string>", "Resolve every address for a host, RFC 8305 interleaved; empty on failure", "net_resolve_all_yieldable", "yieldable", "", "xrt_net_resolve_all", "s", "value", "", "", "", "runtime", "method", XR_CAP_COROUTINE | XR_CAP_NETPOLL, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__connectFd", "(addr: string, port: i64, timeoutMs: i64): NetConn?", "Connect one literal address; null on failure with the code on __lastConnectCode", "net_connect_fd_yieldable", "yieldable", "", "xrt_net_connect_fd", "vvv", "value", "", "", "", "runtime", "method", XR_CAP_COROUTINE | XR_CAP_NETPOLL, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__nowMs", "(): i64", "Monotonic clock in milliseconds for net's own deadline arithmetic", "net_now_ms_fn", "normal", "", "xrt_net_now_ms_fn", "", "value", "", "", "", "runtime", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__lastConnectCode", "(): i64", "Portable error code from the most recent __connectFd on this worker; 0 when the last attempt connected", "net_last_connect_code", "normal", "", "xrt_net_last_connect_code", "", "value", "", "", "", "runtime", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__listenFd", "(port: i64, backlog: i64, forceV4: bool): NetListener?", "Bind and listen; dual-stack preferred unless forceV4", "net_listen_fd", "normal", "", "xrt_net_listen_fd", "vvv", "value", "", "", "", "runtime", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__accept", "(listener: NetListener): NetConn?", "Accept a new connection", "net_accept_handle_yieldable", "yieldable", "", "xrt_net_accept", "v", "value", "", "", "", "runtime", "method", XR_CAP_COROUTINE | XR_CAP_NETPOLL, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__readInto", "(conn: NetConn, buffer: Array<u8>, maxlen: i64): i64", "Read once into a caller buffer; 0 is EOF, -1 is a stored error", "net_read_into_yieldable", "yieldable", "", "xrt_net_read_into", "vvv", "value", "", "", "", "runtime", "method", XR_CAP_COROUTINE | XR_CAP_NETPOLL, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__writeBytes", "(conn: NetConn, data: Array<u8>): i64", "Write the whole buffer; returns bytes written, -1 when nothing was sent", "net_write_bytes_yieldable", "yieldable", "", "xrt_net_write_bytes", "vv", "value", "", "", "", "runtime", "method", XR_CAP_COROUTINE | XR_CAP_NETPOLL, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__copyBidirectional", "(a: NetConn, b: NetConn): __CopyBidirectionalResult", "Copy two TCP/TLS streams in both directions", "net_copy_bidirectional_yieldable", "yieldable", "", "xrt_net_copy_bidirectional", "vv", "i64_pair_result", "NetError", "", "", "runtime", "method", XR_CAP_COROUTINE | XR_CAP_NETPOLL, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__shutdownRead", "(conn: NetConn): bool", "Shut down the read side", "net_shutdown_read", "normal", "", "xrt_net_shutdown_read", "v", "value", "", "", "", "runtime", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__shutdownWrite", "(conn: NetConn): bool", "Shut down the write side", "net_shutdown_write", "normal", "", "xrt_net_shutdown_write", "v", "value", "", "", "", "runtime", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__shutdown", "(conn: NetConn): bool", "Shut down both directions", "net_shutdown_conn", "normal", "", "xrt_net_shutdown", "v", "value", "", "", "", "runtime", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__close", "(handle: NetConn | NetListener): ()", "Close a connection or listener; idempotent", "net_close_handle", "normal", "", "xrt_net_close", "v", "value", "", "", "", "runtime", "method", XR_CAP_NETPOLL, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__fd", "(handle: NetConn | NetListener): i64", "Raw fd of a handle, -1 when closed", "net_fd_handle", "normal", "", "xrt_net_fd", "v", "value", "", "", "", "runtime", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__setReadDeadline", "(conn: NetConn, deadline: i64): bool", "Absolute monotonic read deadline in ms; 0 clears", "net_set_read_deadline", "normal", "", "xrt_net_set_read_deadline", "vv", "value", "", "", "", "runtime", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__setWriteDeadline", "(conn: NetConn, deadline: i64): bool", "Absolute monotonic write deadline in ms; 0 clears", "net_set_write_deadline", "normal", "", "xrt_net_set_write_deadline", "vv", "value", "", "", "", "runtime", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__setDeadline", "(conn: NetConn, deadline: i64): bool", "Set both read and write deadlines", "net_set_deadline", "normal", "", "xrt_net_set_deadline", "vv", "value", "", "", "", "runtime", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__setAcceptDeadline", "(listener: NetListener, deadline: i64): bool", "Absolute monotonic accept deadline in ms; 0 clears", "net_set_accept_deadline", "normal", "", "xrt_net_set_accept_deadline", "vv", "value", "", "", "", "runtime", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__lastCode", "(handle: NetConn | NetListener): i64", "Portable error code of the last failed operation; 0 when none", "net_last_code", "normal", "", "xrt_net_last_code", "v", "value", "", "", "", "runtime", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__lastErrno", "(handle: NetConn | NetListener): i64", "Raw errno captured for the last failed operation", "net_last_errno", "normal", "", "xrt_net_last_errno", "v", "value", "", "", "", "runtime", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__hasTLS", "(): bool", "Whether TLS support is compiled in", "net_has_tls", "normal", "", "xrt_net_has_tls", "", "value", "", "", "", "runtime", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__tlsHandshake", "(conn: NetConn, hostname: string, deadlineMs: i64): i64", "Client TLS handshake under one absolute deadline; 0 promotes the conn in place, else closes it and returns a net error code", "net_tls_handshake_yieldable", "yieldable", "XR_ENABLE_TLS", "xrt_net_tls_handshake", "vvv", "value", "", "", "", "runtime", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__udpBind", "(port: i64, addr: string): NetConn?", "Bind a UDP socket; empty addr binds the wildcard address", "net_udp_bind_handle", "normal", "", "xrt_net_udp_bind", "vv", "value", "", "", "", "runtime", "method", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__udpSendTo", "(conn: NetConn, data: Array<u8>, addr: string, port: i64, timeoutMs: i64): i64", "Send one datagram to a literal address; bytes sent or -1 with a stored code", "net_udp_send_to_yieldable", "yieldable", "", "xrt_net_udp_send_to", "vvvvv", "value", "", "", "", "runtime", "method", XR_CAP_COROUTINE | XR_CAP_NETPOLL, 5, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__udpRecvInto", "(conn: NetConn, buffer: Array<u8>, timeoutMs: i64): i64", "Receive one datagram into a caller buffer; bytes received, or -1 with a stored code", "net_udp_recv_into_yieldable", "yieldable", "", "xrt_net_udp_recv_into", "vvv", "value", "", "", "", "runtime", "method", 0, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__udpFromHost", "(conn: NetConn): string", "Sender address of the last successful datagram receive; empty when none", "net_udp_from_host", "normal", "", "xrt_net_udp_from_host", "v", "value", "", "", "", "runtime", "method", XR_CAP_COROUTINE | XR_CAP_NETPOLL, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"net", "__udpFromPort", "(conn: NetConn): i64", "Sender port of the last successful datagram receive; 0 when none", "net_udp_from_port", "normal", "", "xrt_net_udp_from_port", "v", "value", "", "", "", "runtime", "method", 0, 1, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"http2", "__supported", "(): bool", "Whether the built-in HTTP/2 standard module is available on this target", "h2_supported", "normal", "", "xrt_http_h2_supported", "", "value", "", "", "", "runtime", "method", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"http2", "__request", "(url: string, method: string, headerNames: Array<string>, headerValues: Array<string>, body: Array<u8>, timeoutMs: i64): (i64, Array<string>, Array<string>, Array<u8>)?", "Execute one typed HTTP/2 request", "h2_request_typed", "normal", "", "xrt_http_h2_request_unavailable", "vvvvvv", "value", "", "", "", "runtime", "method", 0, 6, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"cluster", "__start", "(name: string, port: i64, secret: string, tlsEnabled: bool, caFile: string, certFile: string, keyFile: string, insecure: bool, heartbeatIntervalMs: i64, heartbeatTimeoutMs: i64, maxMissedHeartbeats: i64): bool", "Start the backend-neutral cluster runtime from normalized scalar configuration and the heartbeat schedule cluster.xr decides", "cluster_start_primitive", "normal", "", "xrt_cluster_start", "svsvsssvvvv", "value", "", "cluster.__start", "", "runtime", "method", XR_CAP_CHANNEL, 11, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"cluster", "__join", "(host: string, port: i64): bool", "Join cluster at a host and port cluster.xr already parsed, without blocking the scheduler worker", "cluster_join", "yieldable", "", "xrt_cluster_join", "sv", "value", "", "cluster.__join", "", "runtime", "method", XR_CAP_CHANNEL, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"cluster", "__self", "(): string", "Get own node name", "cluster_self", "normal", "", "", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"cluster", "__nodes", "(): Array<string>?", "List cluster node names", "cluster_nodes", "normal", "", "", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"cluster", "__monitor", "(name: string, coro_name?: string): Channel<string>", "Monitor node or remote coroutine", "cluster_monitor_coro_fn", "normal", "", "", "vv", "value", "", "", "", "runtime", "", 0, 2, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"cluster", "__discover", "(): ()", "Start LAN auto-discovery", "cluster_discover_fn", "normal", "", "", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"cluster", "__stop", "(): ()", "Stop cluster node", "cluster_stop_fn", "normal", "", "xrt_cluster_stop", "", "value", "", "cluster.__stop", "", "runtime", "method", XR_CAP_CHANNEL, 0, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"cluster", "__info", "(): ClusterInfo?", "Get cluster status info", "cluster_info_fn", "normal", "", "", "", "value", "", "", "", "runtime", "", 0, 0, XR_STDLIB_TARGET_LEAF_NONE, false},
    {"cluster", "__send", "(topic: string, envelope: move Buffer, hopLimit: i64): ClusterDelivery", "Hand one canonical opaque service envelope, and the hop budget cluster.xr decides, to local and connected transports", "cluster_send_primitive", "normal", "", "xrt_cluster_send", "svv", "enum_i64", "ClusterDelivery", "cluster.__send", "", "runtime", "method", XR_CAP_CHANNEL, 3, XR_STDLIB_TARGET_LEAF_NONE, true},
    {"cluster", "__listen", "(pattern: string, capacity: i64): Channel<Buffer>?", "Create a bounded receiver for opaque canonical service envelopes", "cluster_listen_fn", "normal", "", "xrt_cluster_listen", "sv", "value", "", "cluster.__listen", "", "runtime", "method", XR_CAP_CHANNEL, 2, XR_STDLIB_TARGET_LEAF_NONE, true},
};
#define XR_STDLIB_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_def_entries) / sizeof(xr_stdlib_def_entries[0])))

static const XrStdlibConstDefEntry xr_stdlib_const_def_entries[] = {
    {"math", "PI", ": f64", "Ratio of a circle's circumference to its diameter", "math.PI", "xr_float(M_PI)", "", "float64", "", "", "core", 0, INT64_C(0), 3.14159265358979323846},
    {"math", "E", ": f64", "Euler's number", "math.E", "xr_float(M_E)", "", "float64", "", "", "core", 0, INT64_C(0), 2.71828182845904523536},
    {"math", "TAU", ": f64", "Full-circle radians, 2 * PI", "math.TAU", "xr_float(2.0 * M_PI)", "", "float64", "", "", "core", 0, INT64_C(0), 6.28318530717958647692},
    {"math", "SQRT2", ": f64", "Square root of 2", "math.SQRT2", "xr_float(M_SQRT2)", "", "float64", "", "", "core", 0, INT64_C(0), 1.41421356237309504880},
    {"math", "LN2", ": f64", "Natural logarithm of 2", "math.LN2", "xr_float(M_LN2)", "", "float64", "", "", "core", 0, INT64_C(0), 0.69314718055994530942},
    {"math", "LN10", ": f64", "Natural logarithm of 10", "math.LN10", "xr_float(M_LN10)", "", "float64", "", "", "core", 0, INT64_C(0), 2.30258509299404568402},
    {"math", "LOG2E", ": f64", "Base-2 logarithm of e", "math.LOG2E", "xr_float(M_LOG2E)", "", "float64", "", "", "core", 0, INT64_C(0), 1.44269504088896340736},
    {"math", "LOG10E", ": f64", "Base-10 logarithm of e", "math.LOG10E", "xr_float(M_LOG10E)", "", "float64", "", "", "core", 0, INT64_C(0), 0.43429448190325182765},
    {"math", "EPSILON", ": f64", "Smallest representable difference above 1.0", "math.EPSILON", "xr_float(DBL_EPSILON)", "", "float64", "", "", "core", 0, INT64_C(0), 2.22044604925031308085e-16},
    {"math", "MAX_I64", ": i64", "Largest signed 64-bit integer", "math.MAX_I64", "xr_int(INT64_MAX)", "", "int64", "", "", "core", 0, INT64_MAX, 0.0},
    {"math", "MIN_I64", ": i64", "Smallest signed 64-bit integer", "math.MIN_I64", "xr_int(INT64_MIN)", "", "int64", "", "", "core", 0, INT64_MIN, 0.0},
    {"math", "MAX_F64", ": f64", "Largest finite IEEE-754 double", "math.MAX_F64", "xr_float(DBL_MAX)", "", "float64", "", "", "core", 0, INT64_C(0), 1.79769313486231570815e+308},
    {"math", "INF", ": f64", "Positive infinity", "math.INF", "xr_float(INFINITY)", "", "float64", "", "", "core", 0, INT64_C(0), INFINITY},
    {"math", "NAN", ": f64", "Quiet NaN value", "math.NAN", "xr_float(NAN)", "", "float64", "", "", "core", 0, INT64_C(0), NAN},
};
#define XR_STDLIB_CONST_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_const_def_entries) / sizeof(xr_stdlib_const_def_entries[0])))

static const XrStdlibHandleFieldDefEntry xr_stdlib_object_fields_runtime___RuntimeStats[] = {
    {"runtime", "__RuntimeStats", "liveBytes", "i64", true},
    {"runtime", "__RuntimeStats", "liveObjects", "i64", true},
    {"runtime", "__RuntimeStats", "finalizerCount", "i64", true},
    {"runtime", "__RuntimeStats", "blocks", "i64", true},
    {"runtime", "__RuntimeStats", "freeBlocks", "i64", true},
    {"runtime", "__RuntimeStats", "fullBlocks", "i64", true},
};

static const XrStdlibHandleFieldDefEntry xr_stdlib_object_fields_Coro_CoroStats[] = {
    {"Coro", "CoroStats", "active", "i64", true},
    {"Coro", "CoroStats", "blocked", "i64", true},
    {"Coro", "CoroStats", "ready", "i64", true},
    {"Coro", "CoroStats", "total", "i64", true},
    {"Coro", "CoroStats", "created", "i64", true},
};

static const XrStdlibHandleFieldDefEntry xr_stdlib_object_fields_Coro_CoroInfo[] = {
    {"Coro", "CoroInfo", "id", "i64", true},
    {"Coro", "CoroInfo", "name", "string?", true},
    {"Coro", "CoroInfo", "state", "CoroState", true},
    {"Coro", "CoroInfo", "reductions", "i64", true},
    {"Coro", "CoroInfo", "source", "string?", true},
};

static const XrStdlibHandleFieldDefEntry xr_stdlib_object_fields_Coro_CoroDeadlock[] = {
    {"Coro", "CoroDeadlock", "members", "Array<CoroInfo>", true},
    {"Coro", "CoroDeadlock", "reason", "string", true},
};

static const XrStdlibHandleFieldDefEntry xr_stdlib_object_fields_net___CopyBidirectionalResult[] = {
    {"net", "__CopyBidirectionalResult", "aToB", "i64", true},
    {"net", "__CopyBidirectionalResult", "bToA", "i64", true},
};

static const XrStdlibHandleFieldDefEntry xr_stdlib_object_fields_cluster_ClusterTlsStatus[] = {
    {"cluster", "ClusterTlsStatus", "enabled", "bool", true},
    {"cluster", "ClusterTlsStatus", "clientReady", "bool", true},
    {"cluster", "ClusterTlsStatus", "serverReady", "bool", true},
};

static const XrStdlibHandleFieldDefEntry xr_stdlib_object_fields_cluster_ClusterNodeInfo[] = {
    {"cluster", "ClusterNodeInfo", "name", "string", true},
    {"cluster", "ClusterNodeInfo", "host", "string", true},
    {"cluster", "ClusterNodeInfo", "port", "i64", true},
    {"cluster", "ClusterNodeInfo", "state", "ClusterNodeState", true},
    {"cluster", "ClusterNodeInfo", "framesSent", "i64", true},
    {"cluster", "ClusterNodeInfo", "framesReceived", "i64", true},
    {"cluster", "ClusterNodeInfo", "bytesSent", "i64", true},
    {"cluster", "ClusterNodeInfo", "bytesReceived", "i64", true},
    {"cluster", "ClusterNodeInfo", "sendErrors", "i64", true},
    {"cluster", "ClusterNodeInfo", "slowConsumerEvents", "i64", true},
    {"cluster", "ClusterNodeInfo", "rttMs", "i64", true},
    {"cluster", "ClusterNodeInfo", "outQueueBytes", "i64", true},
    {"cluster", "ClusterNodeInfo", "outQueueFrames", "i64", true},
    {"cluster", "ClusterNodeInfo", "slow", "bool", true},
    {"cluster", "ClusterNodeInfo", "phi", "f64", true},
    {"cluster", "ClusterNodeInfo", "missedHeartbeats", "i64", true},
};

static const XrStdlibHandleFieldDefEntry xr_stdlib_object_fields_cluster_ClusterInfo[] = {
    {"cluster", "ClusterInfo", "self", "string", true},
    {"cluster", "ClusterInfo", "port", "i64", true},
    {"cluster", "ClusterInfo", "running", "bool", true},
    {"cluster", "ClusterInfo", "nodes", "Array<ClusterNodeInfo>", true},
    {"cluster", "ClusterInfo", "listeners", "i64", true},
    {"cluster", "ClusterInfo", "deadNodes", "i64", true},
    {"cluster", "ClusterInfo", "heartbeatIntervalMs", "i64", true},
    {"cluster", "ClusterInfo", "heartbeatTimeoutMs", "i64", true},
    {"cluster", "ClusterInfo", "maxMissedHeartbeats", "i64", true},
    {"cluster", "ClusterInfo", "tls", "ClusterTlsStatus", true},
};

static const XrStdlibObjectShapeDefEntry xr_stdlib_object_shape_def_entries[] = {
    {"runtime", "__RuntimeStats", "Raw counters read in one pass from the current execution-local reclamation domain", xr_stdlib_object_fields_runtime___RuntimeStats, 6, true},
    {"Coro", "CoroStats", "Typed aggregate counters for the coroutine scheduler", xr_stdlib_object_fields_Coro_CoroStats, 5, true},
    {"Coro", "CoroInfo", "Typed diagnostic snapshot for one coroutine", xr_stdlib_object_fields_Coro_CoroInfo, 5, true},
    {"Coro", "CoroDeadlock", "Typed description of a detected coroutine wait cycle", xr_stdlib_object_fields_Coro_CoroDeadlock, 2, true},
    {"net", "__CopyBidirectionalResult", "Byte counts copied in each direction by copyBidirectional", xr_stdlib_object_fields_net___CopyBidirectionalResult, 2, true},
    {"cluster", "ClusterTlsStatus", "Effective TLS posture of a running cluster node", xr_stdlib_object_fields_cluster_ClusterTlsStatus, 3, true},
    {"cluster", "ClusterNodeInfo", "Typed diagnostic snapshot for one remote cluster node", xr_stdlib_object_fields_cluster_ClusterNodeInfo, 16, true},
    {"cluster", "ClusterInfo", "Typed diagnostic snapshot for the local cluster runtime", xr_stdlib_object_fields_cluster_ClusterInfo, 10, true},
};
#define XR_STDLIB_OBJECT_SHAPE_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_object_shape_def_entries) / sizeof(xr_stdlib_object_shape_def_entries[0])))

static const XrStdlibEnumVariantDefEntry xr_stdlib_enum_Coro_CoroState_variants[] = {
    {"Unknown", NULL, 0},
    {"Ready", NULL, 0},
    {"Blocked", NULL, 0},
    {"Running", NULL, 0},
    {"Done", NULL, 0},
};

static const XrStdlibEnumVariantDefEntry xr_stdlib_enum_Coro_CoroGroupKey_variants[] = {
    {"Name", NULL, 0},
    {"State", NULL, 0},
};

static const XrStdlibEnumVariantDefEntry xr_stdlib_enum_Coro_CoroMetric_variants[] = {
    {"Id", NULL, 0},
    {"Reductions", NULL, 0},
};

static const XrStdlibEnumVariantDefEntry xr_stdlib_enum_net_NetError_variants[] = {
    {"Timeout", NULL, 0},
    {"Closed", NULL, 0},
    {"Reset", NULL, 0},
    {"Refused", NULL, 0},
    {"Dns", NULL, 0},
    {"Tls", NULL, 0},
    {"Io", NULL, 0},
    {"Invalid", NULL, 0},
    {"Cancelled", NULL, 0},
    {"OutOfMemory", NULL, 0},
};

static const XrStdlibEnumVariantDefEntry xr_stdlib_enum_cluster_ClusterDelivery_variants[] = {
    {"Accepted", NULL, 0},
    {"InvalidTopic", NULL, 0},
    {"InvalidEnvelope", NULL, 0},
    {"Unavailable", NULL, 0},
    {"Overloaded", NULL, 0},
    {"Disconnected", NULL, 0},
};

static const XrStdlibEnumVariantDefEntry xr_stdlib_enum_cluster_ClusterNodeState_variants[] = {
    {"Idle", NULL, 0},
    {"Connecting", NULL, 0},
    {"Handshaking", NULL, 0},
    {"Connected", NULL, 0},
    {"Closing", NULL, 0},
};

static const XrStdlibEnumDefEntry xr_stdlib_enum_def_entries[] = {
    {"Coro", "CoroState", "Lifecycle state captured in a coroutine diagnostic snapshot", xr_stdlib_enum_Coro_CoroState_variants, 5, UINT32_C(2882116571)},
    {"Coro", "CoroGroupKey", "Stable key used to group coroutine diagnostic snapshots", xr_stdlib_enum_Coro_CoroGroupKey_variants, 2, UINT32_C(2434143071)},
    {"Coro", "CoroMetric", "Metric used to rank coroutine diagnostic snapshots", xr_stdlib_enum_Coro_CoroMetric_variants, 2, UINT32_C(4039818693)},
    {"net", "NetError", "Typed failure from network operations; classification from native codes lives in net.xr", xr_stdlib_enum_net_NetError_variants, 10, UINT32_C(2184710811)},
    {"cluster", "ClusterDelivery", "Outcome of handing one opaque service envelope to the cluster transport", xr_stdlib_enum_cluster_ClusterDelivery_variants, 6, UINT32_C(4282747530)},
    {"cluster", "ClusterNodeState", "Lifecycle state of a remote cluster node", xr_stdlib_enum_cluster_ClusterNodeState_variants, 5, UINT32_C(2784952505)},
};
#define XR_STDLIB_ENUM_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_enum_def_entries) / sizeof(xr_stdlib_enum_def_entries[0])))

static const XrStdlibHandleFieldDefEntry xr_stdlib_handle_fields_os___ExecResult[] = {
    {"os", "__ExecResult", "stdout", "string", true},
    {"os", "__ExecResult", "stderr", "string", true},
    {"os", "__ExecResult", "exitCode", "i64", true},
};

static const XrStdlibHandleFieldDefEntry xr_stdlib_handle_fields_io___FileStat[] = {
    {"io", "__FileStat", "size", "i64", true},
    {"io", "__FileStat", "mode", "i64", true},
    {"io", "__FileStat", "mtime", "i64", true},
    {"io", "__FileStat", "atime", "i64", true},
    {"io", "__FileStat", "ctime", "i64", true},
    {"io", "__FileStat", "uid", "i64", true},
    {"io", "__FileStat", "gid", "i64", true},
    {"io", "__FileStat", "isFile", "bool", true},
    {"io", "__FileStat", "isDir", "bool", true},
    {"io", "__FileStat", "isSymlink", "bool", true},
};

static const XrStdlibHandleDefEntry xr_stdlib_handle_def_entries[] = {
    {"os", "__ExecResult", "Native handle type", xr_stdlib_handle_fields_os___ExecResult, 3},
    {"io", "__FileStat", "Native handle type", xr_stdlib_handle_fields_io___FileStat, 10},
};
#define XR_STDLIB_HANDLE_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_handle_def_entries) / sizeof(xr_stdlib_handle_def_entries[0])))

static const XrStdlibTypeMethodDefEntry xr_stdlib_type_method_def_entries[] = {
    {"sys", "OsMutex", "lock", "(): ()", "Lock the mutex"},
    {"sys", "OsMutex", "unlock", "(): ()", "Unlock the mutex"},
    {"sys", "OsMutex", "tryLock", "(): bool", "Try to lock the mutex"},
    {"sys", "OsRwLock", "rdlock", "(): ()", "Acquire the read side of the read-write lock"},
    {"sys", "OsRwLock", "rdunlock", "(): ()", "Release the read side of the read-write lock"},
    {"sys", "OsRwLock", "wrlock", "(): ()", "Acquire the write side of the read-write lock"},
    {"sys", "OsRwLock", "wrunlock", "(): ()", "Release the write side of the read-write lock"},
    {"sys", "OsCondvar", "wait", "(m: OsMutex): ()", "Wait on the condition variable with an already-locked mutex"},
    {"sys", "OsCondvar", "waitFor", "(m: OsMutex, timeoutNs: i64): bool", "Wait on the condition variable until signalled or timeout elapses"},
    {"sys", "OsCondvar", "signal", "(): ()", "Wake one waiter"},
    {"sys", "OsCondvar", "broadcast", "(): ()", "Wake all waiters"},
    {"sys", "OsBarrier", "wait", "(): bool", "Wait until all parties have arrived"},
    {"sys", "OsOnce", "call", "(body: fn(): ()): ()", "Run the closure exactly once"},
    {"mem", "Buffer", "asBytes", "(): Slice<u8>", "Borrow this buffer as a readonly Slice<u8> view"},
    {"mem", "Buffer", "asMutBytes", "(): Slice<u8>", "Borrow this buffer as a mutable Slice<u8> view"},
    {"mem", "Buffer", "borrowPtr", "(): MutPtr<u8>", "Borrow the underlying mutable pointer; requires unsafe at the call site"},
    {"mem", "Buffer", "resize", "(n: i64): bool", "Resize this buffer; returns false on allocation failure"},
    {"Coro", "CoroLocal", "set", "(value: T): ()", "Set this typed coroutine-local slot for the current coroutine"},
    {"Coro", "CoroLocal", "get", "(): T?", "Get this typed coroutine-local slot for the current coroutine"},
};
#define XR_STDLIB_TYPE_METHOD_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_type_method_def_entries) / sizeof(xr_stdlib_type_method_def_entries[0])))

static const XrStdlibNativeClassDefEntry xr_stdlib_native_class_def_entries[] = {
    {"sys", "OsMutex", "objectClass", "sysMutexClass", "&g_sys_mutex_body_desc", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_SYSMUTEX"},
    {"sys", "OsRwLock", "objectClass", "sysRwLockClass", "&g_sys_rwlock_body_desc", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_SYSRWLOCK"},
    {"sys", "OsCondvar", "objectClass", "sysCondvarClass", "&g_sys_condvar_body_desc", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_SYSCONDVAR"},
    {"sys", "OsBarrier", "objectClass", "sysBarrierClass", "&g_sys_barrier_body_desc", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_SYSBARRIER"},
    {"sys", "OsOnce", "objectClass", "sysOnceClass", "&g_sys_once_body_desc", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_SYSONCE"},
    {"regex", "Regex", "objectClass", "regexClass", "&g_regex_body_desc", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_REGEX"},
    {"mem", "Buffer", "objectClass", "memBufferClass", "&g_mem_buffer_body_desc", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_BUFFER"},
    {"net", "NetConn", "", "netConnClass", "xr_netconn_body_desc()", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_NETCONN"},
    {"net", "NetListener", "", "netListenerClass", "xr_netlistener_body_desc()", "XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY", "XR_BK_NETLISTENER"},
};
#define XR_STDLIB_NATIVE_CLASS_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_native_class_def_entries) / sizeof(xr_stdlib_native_class_def_entries[0])))

static const XrStdlibClassDefEntry xr_stdlib_class_def_entries[] = {
    {"regex", "RegexMatch", "objectClass", "regexMatchClass", "XR_CLASS_BUILTIN | XR_CLASS_FINAL", "XR_BK_REGEX_MATCH"},
};
#define XR_STDLIB_CLASS_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_class_def_entries) / sizeof(xr_stdlib_class_def_entries[0])))

static const XrStdlibClassMethodDefEntry xr_stdlib_class_method_def_entries[] = {
    {"sys", "OsMutex", "lock", "sys_mutex_lock", 0, "0"},
    {"sys", "OsMutex", "unlock", "sys_mutex_unlock", 0, "0"},
    {"sys", "OsMutex", "tryLock", "sys_mutex_try_lock", 0, "0"},
    {"sys", "OsRwLock", "rdlock", "sys_rwlock_rdlock", 0, "0"},
    {"sys", "OsRwLock", "rdunlock", "sys_rwlock_rdunlock", 0, "0"},
    {"sys", "OsRwLock", "wrlock", "sys_rwlock_wrlock", 0, "0"},
    {"sys", "OsRwLock", "wrunlock", "sys_rwlock_wrunlock", 0, "0"},
    {"sys", "OsCondvar", "wait", "sys_condvar_wait", 1, "0"},
    {"sys", "OsCondvar", "waitFor", "sys_condvar_wait_for", 2, "0"},
    {"sys", "OsCondvar", "signal", "sys_condvar_signal", 0, "0"},
    {"sys", "OsCondvar", "broadcast", "sys_condvar_broadcast", 0, "0"},
    {"sys", "OsBarrier", "wait", "sys_barrier_wait", 0, "0"},
    {"sys", "OsOnce", "call", "sys_once_call", 1, "0"},
    {"regex", "Regex", "test", "re_m_test", 1, "0"},
    {"regex", "Regex", "find", "re_m_find", 2, "0"},
    {"regex", "Regex", "findText", "re_m_find_text", 1, "0"},
    {"regex", "Regex", "findGroup", "re_m_find_group", 2, "0"},
    {"regex", "Regex", "findAll", "re_m_find_all", 2, "0"},
    {"regex", "Regex", "replace", "re_m_replace", 2, "0"},
    {"regex", "Regex", "split", "re_m_split", 2, "0"},
    {"mem", "Buffer", "asBytes", "mem_buffer_as_bytes", 0, "0"},
    {"mem", "Buffer", "asMutBytes", "mem_buffer_as_mut_bytes", 0, "0"},
    {"mem", "Buffer", "borrowPtr", "mem_buffer_borrow_ptr", 0, "0"},
    {"mem", "Buffer", "resize", "mem_buffer_resize", 1, "0"},
    {"net", "NetConn", "fd", "conn_method_fd", 0, "0"},
    {"net", "NetConn", "close", "conn_method_close", 0, "0"},
    {"net", "NetConn", "isClosed", "conn_method_is_closed", 0, "0"},
    {"net", "NetConn", "isTLS", "conn_method_is_tls", 0, "0"},
    {"net", "NetListener", "fd", "listener_method_fd", 0, "0"},
    {"net", "NetListener", "port", "listener_method_port", 0, "0"},
    {"net", "NetListener", "close", "listener_method_close", 0, "0"},
    {"net", "NetListener", "isClosed", "listener_method_is_closed", 0, "0"},
};
#define XR_STDLIB_CLASS_METHOD_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_class_method_def_entries) / sizeof(xr_stdlib_class_method_def_entries[0])))

static const XrStdlibClassFieldDefEntry xr_stdlib_class_field_def_entries[] = {
    {"regex", "RegexMatch", "start", "0"},
    {"regex", "RegexMatch", "end", "0"},
    {"regex", "RegexMatch", "text", "0"},
    {"regex", "RegexMatch", "groups", "0"},
};
#define XR_STDLIB_CLASS_FIELD_DEF_ENTRY_COUNT ((uint32_t) (sizeof(xr_stdlib_class_field_def_entries) / sizeof(xr_stdlib_class_field_def_entries[0])))

#endif  /* XSTDLIB_DEFS_GENERATED_H */

/* clang-format on */
