/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/stdlibgen/stdlibgen.py
 *
 * xstdlib_class_bindings_generated.inc.c - VM stdlib class binding shell
 */

/* clang-format off */

/*
 * Include this file from a stdlib module TU after the class method
 * functions and native body descriptor have been declared, then define
 * exactly one XR_STDLIB_VM_BIND_CLASS_<CLASS> macro before including it.
 */

#ifdef XR_STDLIB_VM_BIND_CLASS_LOGGER
static void xr_stdlib_vm_register_logger_class_generated(XrVMRuntime *X) {
    XR_DCHECK(X != NULL, "xr_stdlib_vm_register_logger_class_generated: NULL isolate");
    XrayCoreClasses *core = xr_isolate_get_core_classes(X);
    XR_DCHECK(core != NULL, "xr_stdlib_vm_register_logger_class_generated: core not initialised");
    XR_DCHECK(core->objectClass != NULL, "xr_stdlib_vm_register_logger_class_generated: super class not registered");
    XR_DCHECK(core->loggerClass == NULL, "xr_stdlib_vm_register_logger_class_generated: already registered");
    XrClassBuilder *builder = xr_class_builder_new(X, "Logger", core->objectClass);
    XR_CHECK(builder != NULL, "xr_stdlib_vm_register_logger_class_generated: builder alloc failed");
    xr_class_builder_set_native_body(builder, &g_logger_body_desc);
    xr_class_builder_add_method(builder, "debug", xr_logger_debug, -1, 0);
    xr_class_builder_add_method(builder, "info", xr_logger_info, -1, 0);
    xr_class_builder_add_method(builder, "warn", xr_logger_warn, -1, 0);
    xr_class_builder_add_method(builder, "error", xr_logger_error, -1, 0);
    xr_class_builder_add_method(builder, "fatal", xr_logger_fatal, -1, 0);
    xr_class_builder_add_method(builder, "child", xr_logger_child, -1, 0);
    XrClass *cls = xr_class_builder_finalize(builder);
    XR_CHECK(cls != NULL, "xr_stdlib_vm_register_logger_class_generated: finalize failed");
    cls->flags |= XR_CLASS_BUILTIN | XR_CLASS_HAS_NATIVE_BODY;
    core->loggerClass = cls;
}
#endif  /* XR_STDLIB_VM_BIND_CLASS_LOGGER */

/* clang-format on */
