#!/usr/bin/env python3
"""Generate the compiler-owned target-query enum/member registry."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


class RegistryError(ValueError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RegistryError(message)


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def load_registry(path: Path) -> dict[str, Any]:
    raw = path.read_text(encoding="utf-8", errors="strict")
    value = json.loads(raw)
    require(raw == canonical_json(value), "target-query registry is not canonical two-space JSON")
    require(set(value) == {"schema", "queries"}, "target-query registry shape drifted")
    require(value["schema"] == "xray-target-query-enums/1", "target-query schema drifted")
    queries = value["queries"]
    require(isinstance(queries, list) and len(queries) == 4, "exactly four enum queries required")
    require([row.get("query_id") for row in queries] == [2, 3, 4, 5],
            "target-query ids must be canonical 2..5")
    expected_types = [("TargetOs", 7), ("TargetArch", 8), ("TargetAbi", 9),
                      ("TargetEndian", 10)]
    require([(row.get("type_name"), row.get("core_type_id")) for row in queries] == expected_types,
            "target-query logical type ids drifted")
    require(queries[0].get("members", [None, None, None])[2] == {
        "name": "Darwin", "value": 3, "runtime_symbol": "XR_TARGET_OS_MACOS"
    }, "TargetOs.Darwin must retain the canonical macOS runtime mapping")
    all_runtime_symbols: set[str] = set()
    for row in queries:
        require(set(row) == {"query_id", "query_name", "source_member", "type_name",
                             "core_type_id", "runtime_prefix", "members"},
                f"query {row.get('query_id')} shape drifted")
        for key in ("query_name", "source_member", "type_name", "runtime_prefix"):
            require(isinstance(row[key], str) and row[key], f"query {row['query_id']} missing {key}")
        members = row["members"]
        require(isinstance(members, list) and members, f"query {row['query_id']} has no members")
        require([member.get("value") for member in members] == list(range(1, len(members) + 1)),
                f"query {row['query_id']} values must be dense nonzero ordinals")
        names: set[str] = set()
        for member in members:
            require(set(member) == {"name", "value", "runtime_symbol"},
                    f"query {row['query_id']} member shape drifted")
            require(re.fullmatch(r"[A-Z][A-Za-z0-9_]*", member["name"]) is not None,
                    f"invalid source member {member['name']}")
            require(re.fullmatch(r"XR_TARGET_[A-Z0-9_]+", member["runtime_symbol"]) is not None,
                    f"invalid runtime symbol {member['runtime_symbol']}")
            require(member["name"] not in names, f"duplicate member {member['name']}")
            require(member["runtime_symbol"] not in all_runtime_symbols,
                    f"duplicate runtime symbol {member['runtime_symbol']}")
            names.add(member["name"])
            all_runtime_symbols.add(member["runtime_symbol"])
    return value


def macro_name(runtime_symbol: str) -> str:
    return runtime_symbol.replace("XR_TARGET_", "XR_TARGET_QUERY_VALUE_", 1)


def generate_values_header(registry: dict[str, Any]) -> str:
    lines = [
        "/* AUTO-GENERATED by targetquerygen - DO NOT EDIT */",
        "/* Source: xisa/target/query-enums.json */",
        "#ifndef XR_TARGET_QUERY_VALUES_GEN_H",
        "#define XR_TARGET_QUERY_VALUES_GEN_H",
        "",
        "#include <stdint.h>",
        "",
        "#define XR_TARGET_QUERY_ENUM_SCHEMA_VERSION 1u",
        "",
    ]
    queries = registry["queries"]
    for row in queries:
        for member in row["members"]:
            lines.append(f"#define {macro_name(member['runtime_symbol'])} UINT16_C({member['value']})")
        lines.append(
            f"#define XR_TARGET_QUERY_VALUE_{row['runtime_prefix']}_COUNT "
            f"UINT16_C({len(row['members']) + 1})")
        lines.append("")
    lines.extend(["#endif /* XR_TARGET_QUERY_VALUES_GEN_H */", ""])
    return "\n".join(lines)


def generate_registry_header(registry: dict[str, Any]) -> str:
    lines = [
        "/* AUTO-GENERATED by targetquerygen - DO NOT EDIT */",
        "/* Source: xisa/target/query-enums.json */",
        "#ifndef XR_TARGET_QUERY_REGISTRY_GEN_H",
        "#define XR_TARGET_QUERY_REGISTRY_GEN_H",
        "",
        "#include \"xr_target_query_values_gen.h\"",
        "#include <stddef.h>",
        "#include <string.h>",
        "",
        "#define XR_TARGET_QUERY_ENUM_COUNT 4u",
        "",
    ]
    queries = registry["queries"]
    lines.extend([
        "typedef struct XrTargetQueryEnumMemberDesc {",
        "    const char *source_name;",
        "    uint16_t value;",
        "} XrTargetQueryEnumMemberDesc;",
        "",
        "typedef struct XrTargetQueryEnumDesc {",
        "    uint16_t query_id;",
        "    uint16_t core_type_id;",
        "    const char *source_member;",
        "    const char *type_name;",
        "    const XrTargetQueryEnumMemberDesc *members;",
        "    size_t member_count;",
        "} XrTargetQueryEnumDesc;",
        "",
    ])
    for row in queries:
        lower = row["query_name"].lower()
        lines.append(f"static const XrTargetQueryEnumMemberDesc xr_target_query_{lower}_members[] = {{")
        for member in row["members"]:
            lines.append(f"    {{\"{member['name']}\", {macro_name(member['runtime_symbol'])}}},")
        lines.extend(["};", ""])
    lines.append("static const XrTargetQueryEnumDesc xr_target_query_enum_rows[] = {")
    for row in queries:
        lower = row["query_name"].lower()
        lines.append(
            f"    {{{row['query_id']}u, {row['core_type_id']}u, \"{row['source_member']}\", "
            f"\"{row['type_name']}\", xr_target_query_{lower}_members, "
            f"sizeof(xr_target_query_{lower}_members) / sizeof(xr_target_query_{lower}_members[0])}},")
    lines.extend([
        "};",
        "",
        "static inline const XrTargetQueryEnumDesc *xr_target_query_enum_by_query_id(uint16_t id) {",
        "    for (size_t i = 0; i < XR_TARGET_QUERY_ENUM_COUNT; ++i)",
        "        if (xr_target_query_enum_rows[i].query_id == id)",
        "            return &xr_target_query_enum_rows[i];",
        "    return NULL;",
        "}",
        "",
        "static inline const XrTargetQueryEnumDesc *xr_target_query_enum_by_type_name(const char *name) {",
        "    if (!name)",
        "        return NULL;",
        "    for (size_t i = 0; i < XR_TARGET_QUERY_ENUM_COUNT; ++i)",
        "        if (strcmp(xr_target_query_enum_rows[i].type_name, name) == 0)",
        "            return &xr_target_query_enum_rows[i];",
        "    return NULL;",
        "}",
        "",
        "static inline const XrTargetQueryEnumMemberDesc *xr_target_query_enum_member(",
        "    const XrTargetQueryEnumDesc *owner, const char *name) {",
        "    if (!owner || !name)",
        "        return NULL;",
        "    for (size_t i = 0; i < owner->member_count; ++i)",
        "        if (strcmp(owner->members[i].source_name, name) == 0)",
        "            return &owner->members[i];",
        "    return NULL;",
        "}",
        "",
        "static inline int xr_target_query_enum_value_valid(uint16_t core_type_id, uint16_t value) {",
        "    for (size_t i = 0; i < XR_TARGET_QUERY_ENUM_COUNT; ++i) {",
        "        const XrTargetQueryEnumDesc *row = &xr_target_query_enum_rows[i];",
        "        if (row->core_type_id != core_type_id)",
        "            continue;",
        "        for (size_t member = 0; member < row->member_count; ++member)",
        "            if (row->members[member].value == value)",
        "                return 1;",
        "        return 0;",
        "    }",
        "    return 0;",
        "}",
        "",
        "#endif /* XR_TARGET_QUERY_REGISTRY_GEN_H */",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--generate", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    source = root / "xisa/target/query-enums.json"
    values_output = root / "src/shared/xr_target_query_values_gen.h"
    registry_output = root / "src/shared/xr_target_query_registry_gen.h"
    registry = load_registry(source)
    generated_values = generate_values_header(registry)
    generated_registry = generate_registry_header(registry)
    if args.generate:
        values_output.parent.mkdir(parents=True, exist_ok=True)
        values_output.write_text(generated_values, encoding="utf-8", newline="\n")
        registry_output.write_text(generated_registry, encoding="utf-8", newline="\n")
        print(f"targetquerygen: generated {values_output.relative_to(root)}")
        print(f"targetquerygen: generated {registry_output.relative_to(root)}")
        return 0
    require(values_output.is_file(), "generated target-query value constants are missing")
    require(registry_output.is_file(), "generated target-query compiler registry is missing")
    require(values_output.read_text(encoding="utf-8", errors="strict") == generated_values,
            "generated target-query value constants are stale; run targetquerygen --generate")
    require(registry_output.read_text(encoding="utf-8", errors="strict") == generated_registry,
            "generated target-query compiler registry is stale; run targetquerygen --generate")
    print("targetquerygen: target-query value and compiler registries are canonical and current")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, json.JSONDecodeError, RegistryError) as exc:
        print(f"targetquerygen: error: {exc}", file=sys.stderr)
        raise SystemExit(1)
