# Register original source positives even when the assigned producer rejects them.
add_executable(test_source_product_remaining_source_owned "${CMAKE_CURRENT_LIST_DIR}/test_source_product_remaining_source_owned.c")
target_link_libraries(test_source_product_remaining_source_owned PRIVATE xray_xir_source_product)
target_include_directories(test_source_product_remaining_source_owned PRIVATE "${CMAKE_CURRENT_LIST_DIR}/..")
set_target_properties(test_source_product_remaining_source_owned PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
if(MSVC)
    target_compile_options(test_source_product_remaining_source_owned PRIVATE /utf-8 /W4 /WX)
else()
    target_compile_options(test_source_product_remaining_source_owned PRIVATE -Wall -Wextra -Werror)
endif()

function(xray_add_remaining_source_consumer case expected)
    set(producer "test_source_product_${case}")
    set(native "${producer}_native")
    set(root "${product_consumer_fixture_root}/${case}")
    set(generated "${CMAKE_BINARY_DIR}/generated/source_product_${case}.c")
    set(source "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/test_source_product_remaining_source.c")
    add_executable(${producer} "${source}")
    target_link_libraries(${producer} PRIVATE source_product_consumer_driver)
    file(GLOB source_dependencies "${root}/*.xr")
    if(case STREQUAL "byte_comparison")
        file(GLOB_RECURSE stdlib_dependencies "${CMAKE_SOURCE_DIR}/stdlib/*.xr")
        list(APPEND source_dependencies ${stdlib_dependencies})
    endif()
    add_custom_command(OUTPUT "${generated}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/generated"
        COMMAND $<TARGET_FILE:${producer}> 0 "${generated}"
        DEPENDS ${producer} ${source_dependencies} VERBATIM)
    add_executable(${native} "${source}" "${generated}")
    target_link_libraries(${native} PRIVATE source_product_consumer_driver)
    target_compile_definitions(${native} PRIVATE XR_REMAINING_SOURCE_NATIVE=1)
    foreach(target IN ITEMS ${producer} ${native})
        target_compile_definitions(${target} PRIVATE XR_REMAINING_SOURCE_NAME="${case}"
            XR_REMAINING_SOURCE_ROOT="${root}" XR_REMAINING_SOURCE_EXPECTED=${expected})
        set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
        if(MSVC)
            target_compile_options(${target} PRIVATE /utf-8 /W4 /WX)
        else()
            target_compile_options(${target} PRIVATE -Wall -Wextra -Werror)
        endif()
    endforeach()
    add_test(NAME ${producer}_vm COMMAND ${producer} 0)
    add_test(NAME ${producer}_native COMMAND ${native} 1)
    add_test(NAME ${producer}_mixed_even COMMAND ${native} 2)
    add_test(NAME ${producer}_mixed_odd COMMAND ${native} 3)
    add_test(NAME ${producer}_owned COMMAND test_source_product_remaining_source_owned
        "${root}" "${root}/root.xr" "${CMAKE_SOURCE_DIR}/stdlib" "${case}")
    set_tests_properties(${producer}_vm ${producer}_native ${producer}_mixed_even ${producer}_mixed_odd ${producer}_owned
        PROPERTIES TIMEOUT 120 PROCESSORS 1 LABELS "unit;xir;source-product;program-consumer;original-source;ownership;execution")
    foreach(mode IN ITEMS 0 1 2 3)
        if(mode EQUAL 0)
            set(executable ${producer})
        else()
            set(executable ${native})
        endif()
        foreach(check IN ITEMS axes runtime cancel)
            add_test(NAME ${producer}_${check}_${mode} COMMAND ${executable} ${mode} --${check})
            set_tests_properties(${producer}_${check}_${mode} PROPERTIES TIMEOUT 120 PROCESSORS 1
                LABELS "unit;xir;source-product;program-consumer;ownership;${check}")
            if(check STREQUAL "axes")
                set_tests_properties(${producer}_${check}_${mode} PROPERTIES RUN_SERIAL TRUE)
            endif()
        endforeach()
        add_test(NAME ${producer}_compiler_${mode} COMMAND ${XRAY_PYTHON} -X utf8 "${product_consumer_fault_runner}"
            --binary $<TARGET_FILE:${executable}> --mode ${mode} --jobs 8
            --evidence "${CMAKE_BINARY_DIR}/consumer-fault-evidence/${case}-${mode}")
        set_tests_properties(${producer}_compiler_${mode} PROPERTIES TIMEOUT 600 PROCESSORS 8
            LABELS "unit;xir;source-product;program-consumer;ownership;compiler-faults")
    endforeach()
endfunction()

xray_add_remaining_source_consumer(tuple_array 42)
xray_add_remaining_source_consumer(tuple_repeated 42)
xray_add_remaining_source_consumer(byte_comparison 42)
xray_add_remaining_source_consumer(string_slice 42)
xray_add_remaining_source_consumer(two_modules 42)
xray_add_remaining_source_consumer(generic_constraint_methods 42)
xray_add_remaining_source_consumer(generic_scalar_class 42)
xray_add_remaining_source_consumer(generic_nested_class 42)
