function(source_product_parent_targets)
# Parent-graph positives and root-class runtime controls have separate gates.
set(parent_dir "${CMAKE_CURRENT_LIST_DIR}")
set(parent_root "${parent_dir}/parent_source")
get_filename_component(parent_root "${parent_root}" REALPATH)
add_executable(test_source_product_parent_source "${parent_dir}/test_source_product_parent_source.c")
target_link_libraries(test_source_product_parent_source PRIVATE xray_xir_source_product)
target_include_directories(test_source_product_parent_source PRIVATE "${parent_dir}/..")
add_library(source_product_parent_driver OBJECT "${parent_dir}/test_source_product_consumer.c")
target_link_libraries(source_product_parent_driver PUBLIC xray_xir_source_product xray_xir_runtime_host)
target_compile_definitions(source_product_parent_driver PRIVATE XR_CONSUMER_STDLIB="${CMAKE_SOURCE_DIR}/stdlib")
target_include_directories(source_product_parent_driver PUBLIC "${parent_dir}")
set(parent_targets test_source_product_parent_source source_product_parent_driver)
foreach(case IN ITEMS open_root_empty open_root_fields)
    set(product_consumer_fixture_root "${parent_root}")
    set(expected 42)
    set(consumer_has_native 0)
    set(main "${CMAKE_CURRENT_BINARY_DIR}/parent_${case}_main.c")
    configure_file("${parent_dir}/source_product_consumer_main.c.in" "${main}" @ONLY)
    set(producer "test_source_product_parent_${case}")
    set(native "${producer}_native")
    set(generated "${CMAKE_BINARY_DIR}/generated/parent-source/${case}.c")
    add_executable(${producer} "${main}")
    target_link_libraries(${producer} PRIVATE source_product_parent_driver)
    add_custom_command(OUTPUT "${generated}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/generated/parent-source"
        COMMAND $<TARGET_FILE:${producer}> 0 "${generated}"
        DEPENDS ${producer} "${parent_root}/${case}/root.xr" VERBATIM)
    set(consumer_has_native 1)
    set(native_main "${CMAKE_CURRENT_BINARY_DIR}/parent_${case}_native_main.c")
    configure_file("${parent_dir}/source_product_consumer_main.c.in" "${native_main}" @ONLY)
    add_executable(${native} "${native_main}" "${generated}")
    target_link_libraries(${native} PRIVATE source_product_parent_driver)
    list(APPEND parent_targets ${producer} ${native})
    add_test(NAME ${producer}_vm COMMAND ${producer} 0)
    add_test(NAME ${producer}_native COMMAND ${native} 1)
    add_test(NAME ${producer}_mixed_even COMMAND ${native} 2)
    add_test(NAME ${producer}_mixed_odd COMMAND ${native} 3)
    set_tests_properties(${producer}_vm ${producer}_native ${producer}_mixed_even ${producer}_mixed_odd
        PROPERTIES TIMEOUT 120 PROCESSORS 1 LABELS "unit;xir;source-product;program-consumer;inheritance;ownership;execution")
endforeach()
foreach(target IN LISTS parent_targets)
    set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /W4 /WX)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror)
    endif()
endforeach()
add_test(NAME test_source_product_parent_source COMMAND test_source_product_parent_source "${parent_root}" "${CMAKE_SOURCE_DIR}/stdlib")
add_test(NAME source_product_parent_source_inputs COMMAND ${XRAY_PYTHON} -B -X utf8 "${CMAKE_SOURCE_DIR}/scripts/source_product_consumer_parent_source.py" check)
set_tests_properties(test_source_product_parent_source source_product_parent_source_inputs
    PROPERTIES TIMEOUT 120 PROCESSORS 1 LABELS "unit;xir;source-product;program-consumer;inheritance;admission")
endfunction()
source_product_parent_targets()
