function(source_product_module_ref_targets)
# Module-place positives and local-cell runtime controls have separate gates.
set(module_ref_dir "${CMAKE_CURRENT_LIST_DIR}")
set(module_ref_root "${module_ref_dir}/module_ref_source")
get_filename_component(module_ref_root "${module_ref_root}" REALPATH)
add_executable(test_source_product_module_ref_source "${module_ref_dir}/test_source_product_module_ref_source.c")
target_link_libraries(test_source_product_module_ref_source PRIVATE xray_xir_source_product)
target_include_directories(test_source_product_module_ref_source PRIVATE "${module_ref_dir}/..")
add_library(source_product_module_ref_driver OBJECT "${module_ref_dir}/test_source_product_consumer.c")
target_link_libraries(source_product_module_ref_driver PUBLIC xray_xir_source_product xray_xir_runtime_host)
target_compile_definitions(source_product_module_ref_driver PRIVATE XR_CONSUMER_STDLIB="${CMAKE_SOURCE_DIR}/stdlib")
target_include_directories(source_product_module_ref_driver PUBLIC "${module_ref_dir}")
set(module_ref_targets test_source_product_module_ref_source source_product_module_ref_driver)
foreach(case IN ITEMS local_scalar local_array)
    set(product_consumer_fixture_root "${module_ref_root}")
    set(expected 42)
    set(consumer_has_native 0)
    set(main "${CMAKE_CURRENT_BINARY_DIR}/module_ref_${case}_main.c")
    configure_file("${module_ref_dir}/source_product_consumer_main.c.in" "${main}" @ONLY)
    set(producer "test_source_product_module_ref_${case}")
    set(native "${producer}_native")
    set(generated "${CMAKE_BINARY_DIR}/generated/module-ref-source/${case}.c")
    add_executable(${producer} "${main}")
    target_link_libraries(${producer} PRIVATE source_product_module_ref_driver)
    add_custom_command(OUTPUT "${generated}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/generated/module-ref-source"
        COMMAND $<TARGET_FILE:${producer}> 0 "${generated}"
        DEPENDS ${producer} "${module_ref_root}/${case}/root.xr" VERBATIM)
    set(consumer_has_native 1)
    set(native_main "${CMAKE_CURRENT_BINARY_DIR}/module_ref_${case}_native_main.c")
    configure_file("${module_ref_dir}/source_product_consumer_main.c.in" "${native_main}" @ONLY)
    add_executable(${native} "${native_main}" "${generated}")
    target_link_libraries(${native} PRIVATE source_product_module_ref_driver)
    list(APPEND module_ref_targets ${producer} ${native})
    add_test(NAME ${producer}_vm COMMAND ${producer} 0)
    add_test(NAME ${producer}_native COMMAND ${native} 1)
    add_test(NAME ${producer}_mixed_even COMMAND ${native} 2)
    add_test(NAME ${producer}_mixed_odd COMMAND ${native} 3)
    set_tests_properties(${producer}_vm ${producer}_native ${producer}_mixed_even ${producer}_mixed_odd
        PROPERTIES TIMEOUT 120 PROCESSORS 1 LABELS "unit;xir;source-product;program-consumer;ref;ownership;execution")
endforeach()
foreach(target IN LISTS module_ref_targets)
    set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
    if(MSVC)
        target_compile_options(${target} PRIVATE /utf-8 /W4 /WX)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror)
    endif()
endforeach()
add_test(NAME test_source_product_module_ref_source COMMAND test_source_product_module_ref_source "${module_ref_root}" "${CMAKE_SOURCE_DIR}/stdlib")
add_test(NAME source_product_module_ref_source_inputs COMMAND ${XRAY_PYTHON} -B -X utf8 "${CMAKE_SOURCE_DIR}/scripts/source_product_consumer_module_ref_source.py" check)
set_tests_properties(test_source_product_module_ref_source source_product_module_ref_source_inputs
    PROPERTIES TIMEOUT 120 PROCESSORS 1 LABELS "unit;xir;source-product;program-consumer;ref;admission")
endfunction()
source_product_module_ref_targets()
