/*
 * xisagen — XISA code generator
 *
 * Reads xisa/xm/ops.def and produces:
 *   - src/jit/xm_ops_gen.h  (enum XmOp + XmOpInfo metadata table)
 *
 * Build: cc -o xisagen tools/xisagen/xisagen.c
 * Usage: ./xisagen xisa/xm/ops.def src/jit/xm_ops_gen.h
 */

#include <ctype.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_OPS 512
#define MAX_LINE 512
#define MAX_NAME 64

/* ========== Data Structures ========== */

typedef struct {
    char name[MAX_NAME];    /* e.g. "ADD" */
    char class[MAX_NAME];   /* e.g. "ARITH" */
    int nargs;              /* 0, 1, or 2 */
    char rep[MAX_NAME];     /* result rep: "I64", "F64", "PTR", "TAGGED", "VOID" */
    char effects[MAX_LINE]; /* e.g. "GC|THROW" or "NONE" */
} OpDef;

static OpDef ops[MAX_OPS];
static int nops = 0;

/* ========== Parsing ========== */

static bool parse_line(const char *line, OpDef *op) {
    /* Match: XM_DEF(NAME, CLASS, NARGS, REP, EFFECTS) */
    const char *p = strstr(line, "XM_DEF(");
    if (!p)
        return false;
    p += 7; /* skip "XM_DEF(" */

    /* Parse name */
    int i = 0;
    while (*p && *p != ',' && i < MAX_NAME - 1) {
        if (!isspace((unsigned char) *p))
            op->name[i++] = *p;
        p++;
    }
    op->name[i] = '\0';
    if (*p != ',')
        return false;
    p++;

    /* Parse class */
    i = 0;
    while (*p && *p != ',' && i < MAX_NAME - 1) {
        if (!isspace((unsigned char) *p))
            op->class[i++] = *p;
        p++;
    }
    op->class[i] = '\0';
    if (*p != ',')
        return false;
    p++;

    /* Parse nargs */
    while (*p && isspace((unsigned char) *p))
        p++;
    op->nargs = atoi(p);
    while (*p && *p != ',')
        p++;
    if (*p != ',')
        return false;
    p++;

    /* Parse rep */
    i = 0;
    while (*p && *p != ',' && i < MAX_NAME - 1) {
        if (!isspace((unsigned char) *p))
            op->rep[i++] = *p;
        p++;
    }
    op->rep[i] = '\0';
    if (*p != ',')
        return false;
    p++;

    /* Parse effects (everything until closing paren) */
    i = 0;
    while (*p && *p != ')' && i < MAX_LINE - 1) {
        if (!isspace((unsigned char) *p))
            op->effects[i++] = *p;
        p++;
    }
    op->effects[i] = '\0';

    return true;
}

static int parse_def_file(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "xisagen: cannot open %s\n", path);
        return -1;
    }

    char line[MAX_LINE];
    while (fgets(line, sizeof(line), f)) {
        /* Skip comments and blank lines */
        char *trimmed = line;
        while (*trimmed && isspace((unsigned char) *trimmed))
            trimmed++;
        if (*trimmed == '/' || *trimmed == '\0' || *trimmed == '\n')
            continue;

        OpDef op = {0};
        if (parse_line(trimmed, &op)) {
            if (nops >= MAX_OPS) {
                fprintf(stderr, "xisagen: too many ops (max %d)\n", MAX_OPS);
                fclose(f);
                return -1;
            }
            ops[nops++] = op;
        }
    }

    fclose(f);
    return 0;
}

/* ========== Code Generation ========== */

static const char *rep_to_enum(const char *rep) {
    if (strcmp(rep, "I64") == 0)
        return "XR_REP_I64";
    if (strcmp(rep, "F64") == 0)
        return "XR_REP_F64";
    if (strcmp(rep, "PTR") == 0)
        return "XR_REP_PTR";
    if (strcmp(rep, "TAGGED") == 0)
        return "XR_REP_TAGGED";
    if (strcmp(rep, "VOID") == 0)
        return "XR_REP_VOID";
    return "XR_REP_TAGGED";
}

static const char *class_to_enum(const char *cls) {
    /* Generate XM_CLASS_<cls> */
    static char buf[64];
    snprintf(buf, sizeof(buf), "XM_CLASS_%s", cls);
    return buf;
}

static void emit_effects(FILE *out, const char *effects) {
    if (strcmp(effects, "NONE") == 0) {
        fprintf(out, "0");
        return;
    }
    /* Split on '|' and emit XM_EF_<flag> | ... */
    char buf[MAX_LINE];
    strncpy(buf, effects, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = '\0';

    bool first = true;
    char *tok = strtok(buf, "|");
    while (tok) {
        if (!first)
            fprintf(out, " | ");
        fprintf(out, "XM_EF_%s", tok);
        first = false;
        tok = strtok(NULL, "|");
    }
}

static int generate_header(const char *path) {
    FILE *out = fopen(path, "w");
    if (!out) {
        fprintf(stderr, "xisagen: cannot write %s\n", path);
        return -1;
    }

    fprintf(out, "/* AUTO-GENERATED by xisagen — DO NOT EDIT */\n");
    fprintf(out, "/* Source: xisa/xm/ops.def */\n\n");
    fprintf(out, "#ifndef XM_OPS_GEN_H\n");
    fprintf(out, "#define XM_OPS_GEN_H\n\n");
    fprintf(out, "#include <stdint.h>\n\n");

    /* Effect flags */
    fprintf(out, "/* ========== Effect Flags ========== */\n\n");
    fprintf(out, "#define XM_EF_NONE    0\n");
    fprintf(out, "#define XM_EF_GC      (1u << 0)\n");
    fprintf(out, "#define XM_EF_THROW   (1u << 1)\n");
    fprintf(out, "#define XM_EF_SUSPEND (1u << 2)\n");
    fprintf(out, "#define XM_EF_DEOPT   (1u << 3)\n");
    fprintf(out, "#define XM_EF_WRITE   (1u << 4)\n");
    fprintf(out, "#define XM_EF_READ    (1u << 5)\n\n");

    /* Opcode classes */
    fprintf(out, "/* ========== Opcode Classes ========== */\n\n");
    fprintf(out, "typedef enum {\n");
    const char *classes[] = {"ARITH", "FLOAT", "CONV",  "CMP",    "TAGGED", "MEM",
                             "CONST", "CTRL",  "CALL",  "RT",     "GUARD",  "CORO",
                             "EH",    "ARC",   "UPVAL", "SELECT", "MISC",   NULL};
    for (int i = 0; classes[i]; i++) {
        fprintf(out, "    XM_CLASS_%s = %d,\n", classes[i], i);
    }
    fprintf(out, "    XM_CLASS__COUNT\n");
    fprintf(out, "} XmOpClass;\n\n");

    /* Enum */
    fprintf(out, "/* ========== Xm Opcodes ========== */\n\n");
    fprintf(out, "typedef enum {\n");
    for (int i = 0; i < nops; i++) {
        fprintf(out, "    XM_%s = %d,\n", ops[i].name, i);
    }
    fprintf(out, "\n    XM_OP_COUNT,  /* sentinel */\n\n");
    fprintf(out, "    /* Machine opcodes (filled by isel, share the same XmIns layout) */\n");
    fprintf(out, "    XM_MACH_BASE = 256,\n");
    fprintf(out, "} XmOp;\n\n");

    /* Metadata struct */
    fprintf(out, "/* ========== Op Metadata ========== */\n\n");
    fprintf(out, "typedef struct {\n");
    fprintf(out, "    const char *name;   /* string name (e.g. \"ADD\") */\n");
    fprintf(out, "    uint8_t op_class;   /* XmOpClass */\n");
    fprintf(out, "    uint8_t nargs;      /* number of XmRef arguments */\n");
    fprintf(out, "    uint8_t result_rep; /* XrRep of result */\n");
    fprintf(out, "    uint8_t effects;    /* XM_EF_* bitfield */\n");
    fprintf(out, "} XmOpInfo;\n\n");

    /* Metadata table */
    fprintf(out, "/* ========== Op Info Table (indexed by XmOp) ========== */\n\n");
    fprintf(out, "#ifdef XM_OPS_IMPL\n");
    fprintf(out, "static const XmOpInfo xm_op_info[XM_OP_COUNT] = {\n");
    for (int i = 0; i < nops; i++) {
        fprintf(out, "    [XM_%s] = { \"%s\", %s, %d, %s, ", ops[i].name, ops[i].name,
                class_to_enum(ops[i].class), ops[i].nargs, rep_to_enum(ops[i].rep));
        emit_effects(out, ops[i].effects);
        fprintf(out, " },\n");
    }
    fprintf(out, "};\n");
    fprintf(out, "#else\n");
    fprintf(out, "extern const XmOpInfo xm_op_info[XM_OP_COUNT];\n");
    fprintf(out, "#endif\n\n");

    /* Convenience query functions are in xm.c (XR_FUNC linkage) */

    fprintf(out, "#endif  // XM_OPS_GEN_H\n");

    fclose(out);
    return 0;
}

/* ========== Main ========== */

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: xisagen <ops.def> <output.h>\n");
        return 1;
    }

    if (parse_def_file(argv[1]) < 0)
        return 1;

    printf("xisagen: parsed %d ops from %s\n", nops, argv[1]);

    if (generate_header(argv[2]) < 0)
        return 1;

    printf("xisagen: generated %s\n", argv[2]);
    return 0;
}
