#!/usr/bin/env python3
"""
xisagen — XISA code generator (Python rewrite)

Reads declarative .def and .isa files, generates C headers for the JIT:
  - ops:     xisa/xm/ops.def     → xm_ops_gen.h
  - helpers: xisa/xm/helpers.def → xm_helpers_gen.h
  - isa:     xisa/arch/<arch>/isa.isa → emit helpers, mcattr, disasm, golden

Usage:
  python3 xisagen.py ops     <ops.def>     <output.h>
  python3 xisagen.py helpers <helpers.def> <output.h>
  python3 xisagen.py isa     <isa.isa>     <output_dir>
"""

import sys
import re
import os
from dataclasses import dataclass, field
from typing import Optional

# ============================================================
# Common utilities
# ============================================================

def die(msg: str):
    print(f"xisagen: error: {msg}", file=sys.stderr)
    sys.exit(1)

def read_file(path: str) -> str:
    try:
        with open(path, 'r') as f:
            return f.read()
    except OSError as e:
        die(f"cannot read {path}: {e}")

def write_file(path: str, content: str):
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w') as f:
        f.write(content)

# ============================================================
# L1: ops.def parser + generator
# ============================================================

@dataclass
class OpDef:
    name: str       # e.g. "ADD"
    cls: str        # e.g. "ARITH"
    nargs: int
    rep: str        # "I64", "F64", "PTR", "TAGGED", "VOID"
    flags: list     # ["COMMUTATIVE", "SIDE_EFFECT", ...]

def parse_ops_def(text: str) -> list[OpDef]:
    ops = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#') or line.startswith('//'):
            continue
        # XM_DEF(NAME, CLASS, NARGS, REP, FLAGS) or XM_OP(...)
        m = re.match(r'XM_(?:DEF|OP)\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\d+)\s*,\s*(\w+)\s*,\s*([^)]*)\)', line)
        if not m:
            continue
        name, cls, nargs, rep, flags_str = m.groups()
        flags = [f.strip() for f in flags_str.split('|') if f.strip() and f.strip() != 'NONE']
        ops.append(OpDef(name=name, cls=cls, nargs=int(nargs), rep=rep, flags=flags))
    return ops

def generate_ops_header(ops: list[OpDef]) -> str:
    """Generate xm_ops_gen.h matching the format expected by xm_ops.h consumers."""
    lines = []
    lines.append('/* AUTO-GENERATED by xisagen — DO NOT EDIT */')
    lines.append('/* Source: xisa/xm/ops.def */')
    lines.append('')
    lines.append('#ifndef XM_OPS_GEN_H')
    lines.append('#define XM_OPS_GEN_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')

    # Effect flags (stable bit assignments matching existing code)
    EF_BITS = {'GC': 0, 'THROW': 1, 'SUSPEND': 2, 'DEOPT': 3, 'WRITE': 4, 'READ': 5}
    lines.append('/* ========== Effect Flags ========== */')
    lines.append('')
    lines.append('#define XM_EF_NONE 0')
    for name, bit in EF_BITS.items():
        lines.append(f'#define XM_EF_{name} (1u << {bit})')
    lines.append('')

    # Op classes — preserve insertion order from ops.def
    seen_classes = []
    for op in ops:
        if op.cls not in seen_classes:
            seen_classes.append(op.cls)
    lines.append('/* ========== Opcode Classes ========== */')
    lines.append('')
    lines.append('typedef enum {')
    for i, cls in enumerate(seen_classes):
        lines.append(f'    XM_CLASS_{cls} = {i},')
    lines.append('    XM_CLASS__COUNT')
    lines.append('} XmOpClass;')
    lines.append('')

    # Op enum
    lines.append('/* ========== Xm Opcodes ========== */')
    lines.append('')
    lines.append('typedef enum {')
    for i, op in enumerate(ops):
        lines.append(f'    XM_{op.name} = {i},')
    lines.append('')
    lines.append('    XM_OP_COUNT, /* sentinel */')
    lines.append('')
    lines.append('    /* Machine opcodes (filled by isel, share the same XmIns layout) */')
    lines.append('    XM_MACH_BASE = 256,')
    lines.append('} XmOp;')
    lines.append('')

    # Op metadata struct
    lines.append('/* ========== Op Metadata ========== */')
    lines.append('')
    lines.append('typedef struct {')
    lines.append('    const char *name;   /* string name (e.g. "ADD") */')
    lines.append('    uint8_t op_class;   /* XmOpClass */')
    lines.append('    uint8_t nargs;      /* number of XmRef arguments */')
    lines.append('    uint8_t result_rep; /* XrRep of result */')
    lines.append('    uint8_t effects;    /* XM_EF_* bitfield */')
    lines.append('} XmOpInfo;')
    lines.append('')

    # Op info table
    lines.append('/* ========== Op Info Table (indexed by XmOp) ========== */')
    lines.append('')
    lines.append('#ifdef XM_OPS_IMPL')
    lines.append('static const XmOpInfo xm_op_info[XM_OP_COUNT] = {')
    for op in ops:
        flags_expr = ' | '.join(f'XM_EF_{f}' for f in op.flags) if op.flags else '0'
        lines.append(f'    [XM_{op.name}] = {{"{op.name}", '
                     f'XM_CLASS_{op.cls}, {op.nargs}, XR_REP_{op.rep}, {flags_expr}}},')
    lines.append('};')
    lines.append('#else')
    lines.append('extern const XmOpInfo xm_op_info[XM_OP_COUNT];')
    lines.append('#endif')
    lines.append('')

    lines.append('#endif  // XM_OPS_GEN_H')
    lines.append('')
    return '\n'.join(lines)

# ============================================================
# L2: helpers.def parser + generator
# ============================================================

@dataclass
class HelperDef:
    name: str       # e.g. "call_func"
    nargs: int
    ret_rep: str    # "TAGGED", "PTR", "I64", "F64", "VOID"
    flags: list     # ["GC", "DEOPT", ...]

def parse_helpers_def(text: str) -> list[HelperDef]:
    helpers = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        m = re.match(r'XM_HELPER\(\s*(\w+)\s*,\s*(\d+)\s*,\s*(\w+)\s*,\s*([^)]*)\)', line)
        if not m:
            continue
        name, nargs, ret_rep, flags_str = m.groups()
        flags = [f.strip() for f in flags_str.split('|') if f.strip() and f.strip() != 'NONE']
        helpers.append(HelperDef(name=name, nargs=int(nargs), ret_rep=ret_rep, flags=flags))
    return helpers

def generate_helpers_header(helpers: list[HelperDef]) -> str:
    lines = []
    lines.append('/* AUTO-GENERATED by xisagen — DO NOT EDIT */')
    lines.append('/* Source: xisa/xm/helpers.def */')
    lines.append('')
    lines.append('#ifndef XM_HELPERS_GEN_H')
    lines.append('#define XM_HELPERS_GEN_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('#include <stdbool.h>')
    lines.append('')

    # Flag defines
    lines.append('/* ========== Helper Flags ========== */')
    lines.append('')
    lines.append('#define XM_HF_GC      (1 << 0)')
    lines.append('#define XM_HF_DEOPT   (1 << 1)')
    lines.append('#define XM_HF_THROW   (1 << 2)')
    lines.append('#define XM_HF_SUSPEND (1 << 3)')
    lines.append('')

    # Helper ID enum
    lines.append('/* ========== Helper IDs ========== */')
    lines.append('')
    lines.append('typedef enum {')
    for i, h in enumerate(helpers):
        lines.append(f'    XM_HELPER_{h.name} = {i},')
    lines.append(f'    XM_HELPER__COUNT')
    lines.append('} XmHelperId;')
    lines.append('')

    # Metadata struct
    lines.append('/* ========== Helper Metadata ========== */')
    lines.append('')
    lines.append('typedef struct {')
    lines.append('    void *func;       /* C function pointer (set by xm_helper_table.c) */')
    lines.append('    uint8_t ret_rep;  /* XrRep: return representation */')
    lines.append('    uint8_t nargs;    /* call_arg_pool arguments consumed */')
    lines.append('    uint16_t flags;   /* XM_HF_* */')
    lines.append('} XmHelperInfo;')
    lines.append('')

    # Static metadata table
    lines.append('/* ========== Helper Metadata Table (static, no func ptr) ========== */')
    lines.append('')
    lines.append('#ifdef XM_HELPERS_META_IMPL')
    lines.append('static const struct { uint8_t ret_rep; uint8_t nargs; uint16_t flags; } xm_helper_meta[XM_HELPER__COUNT] = {')
    for h in helpers:
        flags_expr = ' | '.join(f'XM_HF_{f}' for f in h.flags) if h.flags else '0'
        lines.append(f'    [XM_HELPER_{h.name}] = {{ XR_REP_{h.ret_rep}, {h.nargs}, {flags_expr} }},')
    lines.append('};')
    lines.append('#endif')
    lines.append('')

    # X-macro for fn-ptr table
    lines.append('/* ========== X-Macro for fn-ptr table ========== */')
    lines.append('')
    lines.append('#define XM_HELPER_DEF(_) \\')
    for i, h in enumerate(helpers):
        flags_expr = ' | '.join(f'XM_HF_{f}' for f in h.flags) if h.flags else '0'
        cont = ' \\' if i < len(helpers) - 1 else ''
        lines.append(f'    _({h.name}, {h.nargs}, XR_REP_{h.ret_rep}, {flags_expr}){cont}')
    lines.append('')

    lines.append('#endif  // XM_HELPERS_GEN_H')
    lines.append('')
    return '\n'.join(lines)

# ============================================================
# L3: S-expression lexer + parser for .isa files
# ============================================================

@dataclass
class SExpr:
    """S-expression node: either an atom or a list."""
    pass

@dataclass
class SAtom(SExpr):
    value: str          # raw text
    line: int = 0
    col: int = 0

    @property
    def is_keyword(self) -> bool:
        return self.value.startswith(':')

    @property
    def is_variable(self) -> bool:
        return self.value.startswith('$')

    @property
    def is_string(self) -> bool:
        return self.value.startswith('"')

    @property
    def is_number(self) -> bool:
        if not self.value:
            return False
        v = self.value
        if v.startswith('-'):
            v = v[1:]
        if not v:
            return False
        if v.startswith('0x') or v.startswith('0X'):
            return len(v) > 2 and all(c in '0123456789abcdefABCDEF' for c in v[2:])
        if v.startswith('0b') or v.startswith('0B'):
            return len(v) > 2 and all(c in '01' for c in v[2:])
        return v.isdigit()

    @property
    def int_value(self) -> int:
        v = self.value
        if v.startswith('0x') or v.startswith('0X'):
            return int(v, 16)
        if v.startswith('0b') or v.startswith('0B'):
            return int(v, 2)
        if v.startswith('-'):
            return -int(v[1:], 0)
        return int(v)

    @property
    def str_value(self) -> str:
        """Strip quotes from string atoms."""
        if self.is_string:
            return self.value[1:-1]
        return self.value

@dataclass
class SList(SExpr):
    children: list       # list of SExpr
    line: int = 0
    col: int = 0

    @property
    def head(self) -> Optional[SExpr]:
        return self.children[0] if self.children else None

    def get_kw(self, keyword: str) -> Optional[SExpr]:
        """Find value after :keyword in this list."""
        for i, child in enumerate(self.children):
            if isinstance(child, SAtom) and child.value == keyword:
                if i + 1 < len(self.children):
                    return self.children[i + 1]
        return None

    def get_kw_int(self, keyword: str, default: int = 0) -> int:
        v = self.get_kw(keyword)
        if v and isinstance(v, SAtom) and v.is_number:
            return v.int_value
        return default

    def get_kw_str(self, keyword: str, default: str = '') -> str:
        v = self.get_kw(keyword)
        if v and isinstance(v, SAtom):
            return v.str_value
        return default

    def get_kw_list(self, keyword: str) -> Optional['SList']:
        v = self.get_kw(keyword)
        if isinstance(v, SList):
            return v
        return None


def tokenize_sexpr(text: str, path: str = '<input>'):
    """Tokenize S-expression text into (token, line, col) tuples."""
    tokens = []
    i = 0
    line = 1
    line_start = 0

    while i < len(text):
        c = text[i]

        # Whitespace
        if c in ' \t\r':
            i += 1
            continue
        if c == '\n':
            i += 1
            line += 1
            line_start = i
            continue

        # Comment
        if c == ';':
            while i < len(text) and text[i] != '\n':
                i += 1
            continue

        col = i - line_start + 1

        # Parens
        if c == '(':
            tokens.append(('(', line, col))
            i += 1
            continue
        if c == ')':
            tokens.append((')', line, col))
            i += 1
            continue

        # String
        if c == '"':
            start = i
            i += 1
            while i < len(text) and text[i] != '"':
                if text[i] == '\\':
                    i += 1
                i += 1
            if i >= len(text):
                die(f"{path}:{line}:{col}: unterminated string")
            i += 1  # closing "
            tokens.append((text[start:i], line, col))
            continue

        # Number (including negative)
        if c.isdigit() or (c == '-' and i + 1 < len(text) and text[i + 1].isdigit()):
            start = i
            if c == '-':
                i += 1
            if i + 1 < len(text) and text[i] == '0' and text[i + 1] in 'xXbB':
                i += 2
                while i < len(text) and (text[i].isalnum()):
                    i += 1
            else:
                while i < len(text) and text[i].isdigit():
                    i += 1
            tokens.append((text[start:i], line, col))
            continue

        # Symbol / keyword / variable
        # Starts with: letter _ : $ + * /
        if c.isalpha() or c in '_:$+*/':
            start = i
            i += 1
            while i < len(text) and (text[i].isalnum() or text[i] in '_-.'):
                i += 1
            tokens.append((text[start:i], line, col))
            continue

        die(f"{path}:{line}:{col}: unexpected character '{c}'")

    return tokens


def parse_sexpr(tokens: list, path: str = '<input>') -> list[SExpr]:
    """Parse token list into S-expression tree. Returns list of top-level forms."""
    pos = [0]  # mutable index

    def parse_one() -> Optional[SExpr]:
        if pos[0] >= len(tokens):
            return None
        tok, line, col = tokens[pos[0]]

        if tok == ')':
            die(f"{path}:{line}:{col}: unexpected ')'")

        if tok == '(':
            pos[0] += 1
            children = []
            while pos[0] < len(tokens) and tokens[pos[0]][0] != ')':
                child = parse_one()
                if child:
                    children.append(child)
            if pos[0] >= len(tokens):
                die(f"{path}:{line}:{col}: unclosed '('")
            pos[0] += 1  # skip ')'
            return SList(children=children, line=line, col=col)

        # Atom
        pos[0] += 1
        return SAtom(value=tok, line=line, col=col)

    forms = []
    while pos[0] < len(tokens):
        form = parse_one()
        if form:
            forms.append(form)
    return forms


def parse_isa_file(path: str) -> list[SExpr]:
    """Parse a .isa file and return top-level S-expression forms."""
    text = read_file(path)
    tokens = tokenize_sexpr(text, path)
    return parse_sexpr(tokens, path)

# ============================================================
# L3: .isa structured extraction
# ============================================================

@dataclass
class McInsn:
    """Parsed machine instruction definition."""
    name: str
    operands: Optional[SList] = None
    constraints: Optional[SList] = None
    encoding: Optional[SList] = None
    flags: list = field(default_factory=list)
    min_bytes: int = 0
    max_bytes: int = 0
    golden_bytes: list = field(default_factory=list)  # [(regs, hex_str), ...]
    golden_asm: list = field(default_factory=list)
    decode_priority: str = 'normal'
    external_ref: str = ''
    helper: str = ''
    raw: Optional[SList] = None  # original S-expression

@dataclass
class RegClass:
    """Register class definition."""
    name: str
    regs: list          # register names
    encoding_bits: int

def extract_mcinsn(form: SList) -> McInsn:
    """Extract McInsn from a (define-mcinsn ...) form."""
    children = form.children
    assert len(children) >= 2
    name = children[1].value if isinstance(children[1], SAtom) else '???'

    insn = McInsn(name=name, raw=form)
    insn.operands = form.get_kw_list(':operands')
    insn.constraints = form.get_kw_list(':constraints')
    insn.encoding = form.get_kw_list(':encoding')
    insn.min_bytes = form.get_kw_int(':min-bytes')
    insn.max_bytes = form.get_kw_int(':max-bytes')
    insn.decode_priority = form.get_kw_str(':decode-priority', 'normal')
    insn.external_ref = form.get_kw_str(':external-reference', '')
    insn.helper = form.get_kw_str(':helper', '')

    # Flags
    flags_list = form.get_kw_list(':flags')
    if flags_list:
        insn.flags = [c.value for c in flags_list.children if isinstance(c, SAtom)]

    # Golden bytes: (((regs...) "hex") ...)
    gb = form.get_kw_list(':golden-bytes')
    if gb:
        for entry in gb.children:
            if isinstance(entry, SList) and len(entry.children) >= 2:
                regs_node = entry.children[0]
                hex_node = entry.children[1]
                regs = []
                if isinstance(regs_node, SList):
                    regs = [c.value if isinstance(c, SAtom) else str(c)
                            for c in regs_node.children]
                hex_str = hex_node.str_value if isinstance(hex_node, SAtom) else ''
                insn.golden_bytes.append((regs, hex_str))

    # Golden asm
    ga = form.get_kw_list(':golden-asm')
    if ga:
        for entry in ga.children:
            if isinstance(entry, SList) and len(entry.children) >= 2:
                regs_node = entry.children[0]
                asm_node = entry.children[1]
                regs = []
                if isinstance(regs_node, SList):
                    regs = [c.value if isinstance(c, SAtom) else str(c)
                            for c in regs_node.children]
                asm_str = asm_node.str_value if isinstance(asm_node, SAtom) else ''
                insn.golden_asm.append((regs, asm_str))

    return insn

def extract_regclass(form: SList) -> RegClass:
    """Extract RegClass from a (define-regclass ...) form."""
    name = form.children[1].value if len(form.children) >= 2 and isinstance(form.children[1], SAtom) else '???'
    regs = []
    regs_list = form.get_kw_list(':regs')
    if regs_list:
        regs = [c.value for c in regs_list.children if isinstance(c, SAtom)]
    bits = form.get_kw_int(':encoding-bits', 4)
    return RegClass(name=name, regs=regs, encoding_bits=bits)

def load_isa(path: str) -> tuple[list[RegClass], list[McInsn]]:
    """Load and parse a .isa file, returning regclasses and mcinsns."""
    forms = parse_isa_file(path)
    regclasses = []
    mcinsns = []
    for form in forms:
        if not isinstance(form, SList) or not form.children:
            continue
        head = form.head
        if isinstance(head, SAtom):
            if head.value == 'define-mcinsn':
                mcinsns.append(extract_mcinsn(form))
            elif head.value == 'define-regclass':
                regclasses.append(extract_regclass(form))
    return regclasses, mcinsns

# ============================================================
# CLI
# ============================================================

def cmd_ops(args: list[str]):
    if len(args) != 2:
        die("usage: xisagen.py ops <ops.def> <output.h>")
    ops = parse_ops_def(read_file(args[0]))
    if not ops:
        die(f"no ops parsed from {args[0]}")
    content = generate_ops_header(ops)
    write_file(args[1], content)
    print(f"xisagen: parsed {len(ops)} ops from {args[0]}", file=sys.stderr)
    print(f"xisagen: generated {args[1]}", file=sys.stderr)

def cmd_helpers(args: list[str]):
    if len(args) != 2:
        die("usage: xisagen.py helpers <helpers.def> <output.h>")
    helpers = parse_helpers_def(read_file(args[0]))
    if not helpers:
        die(f"no helpers parsed from {args[0]}")
    content = generate_helpers_header(helpers)
    write_file(args[1], content)
    print(f"xisagen: parsed {len(helpers)} helpers from {args[0]}", file=sys.stderr)
    print(f"xisagen: generated {args[1]}", file=sys.stderr)

def cmd_isa(args: list[str]):
    if len(args) < 1:
        die("usage: xisagen.py isa <isa.isa> [output_dir]")
    path = args[0]
    regclasses, mcinsns = load_isa(path)
    print(f"xisagen: parsed {path}: {len(regclasses)} regclasses, {len(mcinsns)} mcinsns",
          file=sys.stderr)

    # Validate golden bytes
    total_golden = sum(len(m.golden_bytes) for m in mcinsns)
    total_golden_asm = sum(len(m.golden_asm) for m in mcinsns)
    print(f"xisagen: {total_golden} golden-bytes, {total_golden_asm} golden-asm entries",
          file=sys.stderr)

    for insn in mcinsns:
        if insn.min_bytes <= 0:
            die(f"{path}: {insn.name}: missing :min-bytes")
        if insn.max_bytes < insn.min_bytes:
            die(f"{path}: {insn.name}: :max-bytes < :min-bytes")
        if not insn.golden_bytes:
            die(f"{path}: {insn.name}: no :golden-bytes")

def cmd_test(args: list[str]):
    """Run self-tests."""
    print("xisagen self-test:", file=sys.stderr)
    _test_sexpr_parser()
    _test_ops_parser()
    _test_helpers_parser()
    _test_isa_parser()
    print("All xisagen self-tests passed.", file=sys.stderr)

def _test_sexpr_parser():
    print("  test_sexpr_parser...", end='', file=sys.stderr)
    tokens = tokenize_sexpr('(add 1 2)')
    forms = parse_sexpr(tokens)
    assert len(forms) == 1
    assert isinstance(forms[0], SList)
    assert len(forms[0].children) == 3
    assert isinstance(forms[0].children[0], SAtom) and forms[0].children[0].value == 'add'
    assert forms[0].children[1].int_value == 1
    assert forms[0].children[2].int_value == 2

    # Keywords and variables
    tokens = tokenize_sexpr('(:key $var "str" 0xFF 0b1101)')
    forms = parse_sexpr(tokens)
    lst = forms[0]
    assert lst.children[0].is_keyword
    assert lst.children[1].is_variable
    assert lst.children[2].is_string
    assert lst.children[3].int_value == 255
    assert lst.children[4].int_value == 13

    # Comments
    tokens = tokenize_sexpr('foo ; comment\nbar')
    forms = parse_sexpr(tokens)
    assert len(forms) == 2

    # Nested
    tokens = tokenize_sexpr('(a (b c) d)')
    forms = parse_sexpr(tokens)
    assert len(forms[0].children) == 3
    assert isinstance(forms[0].children[1], SList)

    # Keyword lookup
    tokens = tokenize_sexpr('(foo :min-bytes 3 :name "test")')
    forms = parse_sexpr(tokens)
    lst = forms[0]
    assert lst.get_kw_int(':min-bytes') == 3
    assert lst.get_kw_str(':name') == 'test'

    print(" PASS", file=sys.stderr)

def _test_ops_parser():
    print("  test_ops_parser...", end='', file=sys.stderr)
    text = 'XM_OP(ADD, ARITH, 2, I64, COMMUTATIVE)\nXM_OP(RET, CF, 0, VOID, NONE)\n'
    ops = parse_ops_def(text)
    assert len(ops) == 2
    assert ops[0].name == 'ADD' and ops[0].cls == 'ARITH'
    assert ops[0].flags == ['COMMUTATIVE']
    assert ops[1].flags == []
    header = generate_ops_header(ops)
    assert 'XM_ADD = 0' in header
    assert 'XM_RET = 1' in header
    print(" PASS", file=sys.stderr)

def _test_helpers_parser():
    print("  test_helpers_parser...", end='', file=sys.stderr)
    text = 'XM_HELPER(call_func, 0, TAGGED, GC|DEOPT)\nXM_HELPER(rt_add, 2, TAGGED, GC)\n'
    helpers = parse_helpers_def(text)
    assert len(helpers) == 2
    assert helpers[0].name == 'call_func'
    assert helpers[0].flags == ['GC', 'DEOPT']
    header = generate_helpers_header(helpers)
    assert 'XM_HELPER_call_func = 0' in header
    assert 'XM_HF_GC | XM_HF_DEOPT' in header
    print(" PASS", file=sys.stderr)

def _test_isa_parser():
    print("  test_isa_parser...", end='', file=sys.stderr)
    text = '''
    (define-regclass x64.gpr64
      :regs (rax rcx rdx rbx)
      :encoding-bits 4)
    (define-mcinsn x64.add.rr
      :operands       (($dst reg:gpr64) ($src reg:gpr64))
      :constraints    ((same $dst $src))
      :encoding       (rex.w 0x01 (modrm 0b11 $src $dst))
      :flags          ()
      :min-bytes      3
      :max-bytes      3
      :golden-bytes   (((rax rbx) "48 01 d8"))
      :golden-asm     (((rax rbx) "add rax, rbx"))
      :external-reference llvm-mc)
    '''
    tokens = tokenize_sexpr(text, 'test.isa')
    forms = parse_sexpr(tokens, 'test.isa')
    assert len(forms) == 2

    # Extract
    rc = extract_regclass(forms[0])
    assert rc.name == 'x64.gpr64'
    assert len(rc.regs) == 4
    assert rc.encoding_bits == 4

    insn = extract_mcinsn(forms[1])
    assert insn.name == 'x64.add.rr'
    assert insn.min_bytes == 3
    assert insn.max_bytes == 3
    assert len(insn.golden_bytes) == 1
    assert insn.golden_bytes[0] == (['rax', 'rbx'], '48 01 d8')
    assert insn.golden_asm[0] == (['rax', 'rbx'], 'add rax, rbx')
    assert insn.external_ref == 'llvm-mc'

    print(" PASS", file=sys.stderr)


def main():
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    cmd = sys.argv[1]
    args = sys.argv[2:]

    commands = {
        'ops': cmd_ops,
        'helpers': cmd_helpers,
        'isa': cmd_isa,
        'test': cmd_test,
    }

    if cmd not in commands:
        die(f"unknown command '{cmd}'. Available: {', '.join(commands)}")

    commands[cmd](args)


if __name__ == '__main__':
    main()
