#!/usr/bin/env python3
"""
xisagen — XISA code generator (Python rewrite)

Reads declarative .def and .isa files, generates C headers for the JIT:
  - ops:     xisa/xm/ops.def     → xm_ops_gen.h
  - helpers: xisa/xm/helpers.def → xm_helpers_gen.h
  - isa:     xisa/arch/<arch>/isa.isa → emit helpers, mcattr, disasm, golden

Usage:
  python3 xisagen.py ops     <ops.def>     <output.h>
  python3 xisagen.py helpers <helpers.def> <output.h>
  python3 xisagen.py isa     <isa.isa>     <output_dir>
"""

import sys
import re
import os
from dataclasses import dataclass, field
from typing import Optional

# ============================================================
# Common utilities
# ============================================================

def die(msg: str):
    print(f"xisagen: error: {msg}", file=sys.stderr)
    sys.exit(1)

def read_file(path: str) -> str:
    try:
        with open(path, 'r') as f:
            return f.read()
    except OSError as e:
        die(f"cannot read {path}: {e}")

def write_file(path: str, content: str):
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w') as f:
        f.write(content)

# ============================================================
# L1: ops.def parser + generator
# ============================================================

@dataclass
class OpDef:
    name: str       # e.g. "ADD"
    cls: str        # e.g. "ARITH"
    nargs: int
    rep: str        # "I64", "F64", "PTR", "TAGGED", "VOID"
    flags: list     # ["COMMUTATIVE", "SIDE_EFFECT", ...]

def parse_ops_def(text: str) -> list[OpDef]:
    ops = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#') or line.startswith('//'):
            continue
        # XM_DEF(NAME, CLASS, NARGS, REP, FLAGS) or XM_OP(...)
        m = re.match(r'XM_(?:DEF|OP)\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\d+)\s*,\s*(\w+)\s*,\s*([^)]*)\)', line)
        if not m:
            continue
        name, cls, nargs, rep, flags_str = m.groups()
        flags = [f.strip() for f in flags_str.split('|') if f.strip() and f.strip() != 'NONE']
        ops.append(OpDef(name=name, cls=cls, nargs=int(nargs), rep=rep, flags=flags))
    return ops

def generate_ops_header(ops: list[OpDef]) -> str:
    """Generate xm_ops_gen.h matching the format expected by xm_ops.h consumers."""
    lines = []
    lines.append('/* AUTO-GENERATED by xisagen — DO NOT EDIT */')
    lines.append('/* Source: xisa/xm/ops.def */')
    lines.append('')
    lines.append('#ifndef XM_OPS_GEN_H')
    lines.append('#define XM_OPS_GEN_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')

    # Effect flags (stable bit assignments matching existing code)
    EF_BITS = {'GC': 0, 'THROW': 1, 'SUSPEND': 2, 'DEOPT': 3, 'WRITE': 4, 'READ': 5}
    lines.append('/* ========== Effect Flags ========== */')
    lines.append('')
    lines.append('#define XM_EF_NONE 0')
    for name, bit in EF_BITS.items():
        lines.append(f'#define XM_EF_{name} (1u << {bit})')
    lines.append('')

    # Op classes — preserve insertion order from ops.def
    seen_classes = []
    for op in ops:
        if op.cls not in seen_classes:
            seen_classes.append(op.cls)
    lines.append('/* ========== Opcode Classes ========== */')
    lines.append('')
    lines.append('typedef enum {')
    for i, cls in enumerate(seen_classes):
        lines.append(f'    XM_CLASS_{cls} = {i},')
    lines.append('    XM_CLASS__COUNT')
    lines.append('} XmOpClass;')
    lines.append('')

    # Op enum
    lines.append('/* ========== Xm Opcodes ========== */')
    lines.append('')
    lines.append('typedef enum {')
    for i, op in enumerate(ops):
        lines.append(f'    XM_{op.name} = {i},')
    lines.append('')
    lines.append('    XM_OP_COUNT, /* sentinel */')
    lines.append('')
    lines.append('    /* Machine opcodes (filled by isel, share the same XmIns layout) */')
    lines.append('    XM_MACH_BASE = 256,')
    lines.append('} XmOp;')
    lines.append('')

    # Op metadata struct
    lines.append('/* ========== Op Metadata ========== */')
    lines.append('')
    lines.append('typedef struct {')
    lines.append('    const char *name;   /* string name (e.g. "ADD") */')
    lines.append('    uint8_t op_class;   /* XmOpClass */')
    lines.append('    uint8_t nargs;      /* number of XmRef arguments */')
    lines.append('    uint8_t result_rep; /* XrRep of result */')
    lines.append('    uint8_t effects;    /* XM_EF_* bitfield */')
    lines.append('} XmOpInfo;')
    lines.append('')

    # Op info table
    lines.append('/* ========== Op Info Table (indexed by XmOp) ========== */')
    lines.append('')
    lines.append('#ifdef XM_OPS_IMPL')
    lines.append('static const XmOpInfo xm_op_info[XM_OP_COUNT] = {')
    for op in ops:
        flags_expr = ' | '.join(f'XM_EF_{f}' for f in op.flags) if op.flags else '0'
        lines.append(f'    [XM_{op.name}] = {{"{op.name}", '
                     f'XM_CLASS_{op.cls}, {op.nargs}, XR_REP_{op.rep}, {flags_expr}}},')
    lines.append('};')
    lines.append('#else')
    lines.append('extern const XmOpInfo xm_op_info[XM_OP_COUNT];')
    lines.append('#endif')
    lines.append('')

    lines.append('#endif  // XM_OPS_GEN_H')
    lines.append('')
    return '\n'.join(lines)

# ============================================================
# L2: helpers.def parser + generator
# ============================================================

@dataclass
class HelperDef:
    name: str       # e.g. "call_func"
    nargs: int
    ret_rep: str    # "TAGGED", "PTR", "I64", "F64", "VOID"
    flags: list     # ["GC", "DEOPT", ...]

def parse_helpers_def(text: str) -> list[HelperDef]:
    helpers = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        m = re.match(r'XM_HELPER\(\s*(\w+)\s*,\s*(\d+)\s*,\s*(\w+)\s*,\s*([^)]*)\)', line)
        if not m:
            continue
        name, nargs, ret_rep, flags_str = m.groups()
        flags = [f.strip() for f in flags_str.split('|') if f.strip() and f.strip() != 'NONE']
        helpers.append(HelperDef(name=name, nargs=int(nargs), ret_rep=ret_rep, flags=flags))
    return helpers

def generate_helpers_header(helpers: list[HelperDef]) -> str:
    lines = []
    lines.append('/* AUTO-GENERATED by xisagen — DO NOT EDIT */')
    lines.append('/* Source: xisa/xm/helpers.def */')
    lines.append('')
    lines.append('#ifndef XM_HELPERS_GEN_H')
    lines.append('#define XM_HELPERS_GEN_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('#include <stdbool.h>')
    lines.append('')

    # Flag defines
    lines.append('/* ========== Helper Flags ========== */')
    lines.append('')
    lines.append('#define XM_HF_GC      (1 << 0)')
    lines.append('#define XM_HF_DEOPT   (1 << 1)')
    lines.append('#define XM_HF_THROW   (1 << 2)')
    lines.append('#define XM_HF_SUSPEND (1 << 3)')
    lines.append('')

    # Helper ID enum
    lines.append('/* ========== Helper IDs ========== */')
    lines.append('')
    lines.append('typedef enum {')
    for i, h in enumerate(helpers):
        lines.append(f'    XM_HELPER_{h.name} = {i},')
    lines.append(f'    XM_HELPER__COUNT')
    lines.append('} XmHelperId;')
    lines.append('')

    # Metadata struct
    lines.append('/* ========== Helper Metadata ========== */')
    lines.append('')
    lines.append('typedef struct {')
    lines.append('    void *func;       /* C function pointer (set by xm_helper_table.c) */')
    lines.append('    uint8_t ret_rep;  /* XrRep: return representation */')
    lines.append('    uint8_t nargs;    /* call_arg_pool arguments consumed */')
    lines.append('    uint16_t flags;   /* XM_HF_* */')
    lines.append('} XmHelperInfo;')
    lines.append('')

    # Static metadata table
    lines.append('/* ========== Helper Metadata Table (static, no func ptr) ========== */')
    lines.append('')
    lines.append('#ifdef XM_HELPERS_META_IMPL')
    lines.append('static const struct { uint8_t ret_rep; uint8_t nargs; uint16_t flags; } xm_helper_meta[XM_HELPER__COUNT] = {')
    for h in helpers:
        flags_expr = ' | '.join(f'XM_HF_{f}' for f in h.flags) if h.flags else '0'
        lines.append(f'    [XM_HELPER_{h.name}] = {{ XR_REP_{h.ret_rep}, {h.nargs}, {flags_expr} }},')
    lines.append('};')
    lines.append('#endif')
    lines.append('')

    # X-macro for fn-ptr table
    lines.append('/* ========== X-Macro for fn-ptr table ========== */')
    lines.append('')
    lines.append('#define XM_HELPER_DEF(_) \\')
    for i, h in enumerate(helpers):
        flags_expr = ' | '.join(f'XM_HF_{f}' for f in h.flags) if h.flags else '0'
        cont = ' \\' if i < len(helpers) - 1 else ''
        lines.append(f'    _({h.name}, {h.nargs}, XR_REP_{h.ret_rep}, {flags_expr}){cont}')
    lines.append('')

    lines.append('#endif  // XM_HELPERS_GEN_H')
    lines.append('')
    return '\n'.join(lines)

# ============================================================
# L3: S-expression lexer + parser for .isa files
# ============================================================

@dataclass
class SExpr:
    """S-expression node: either an atom or a list."""
    pass

@dataclass
class SAtom(SExpr):
    value: str          # raw text
    line: int = 0
    col: int = 0

    @property
    def is_keyword(self) -> bool:
        return self.value.startswith(':')

    @property
    def is_variable(self) -> bool:
        return self.value.startswith('$')

    @property
    def is_string(self) -> bool:
        return self.value.startswith('"')

    @property
    def is_number(self) -> bool:
        if not self.value:
            return False
        v = self.value
        if v.startswith('-'):
            v = v[1:]
        if not v:
            return False
        if v.startswith('0x') or v.startswith('0X'):
            return len(v) > 2 and all(c in '0123456789abcdefABCDEF' for c in v[2:])
        if v.startswith('0b') or v.startswith('0B'):
            return len(v) > 2 and all(c in '01' for c in v[2:])
        return v.isdigit()

    @property
    def int_value(self) -> int:
        v = self.value
        if v.startswith('0x') or v.startswith('0X'):
            return int(v, 16)
        if v.startswith('0b') or v.startswith('0B'):
            return int(v, 2)
        if v.startswith('-'):
            return -int(v[1:], 0)
        return int(v)

    @property
    def str_value(self) -> str:
        """Strip quotes from string atoms."""
        if self.is_string:
            return self.value[1:-1]
        return self.value

@dataclass
class SList(SExpr):
    children: list       # list of SExpr
    line: int = 0
    col: int = 0

    @property
    def head(self) -> Optional[SExpr]:
        return self.children[0] if self.children else None

    def get_kw(self, keyword: str) -> Optional[SExpr]:
        """Find value after :keyword in this list."""
        for i, child in enumerate(self.children):
            if isinstance(child, SAtom) and child.value == keyword:
                if i + 1 < len(self.children):
                    return self.children[i + 1]
        return None

    def get_kw_int(self, keyword: str, default: int = 0) -> int:
        v = self.get_kw(keyword)
        if v and isinstance(v, SAtom) and v.is_number:
            return v.int_value
        return default

    def get_kw_str(self, keyword: str, default: str = '') -> str:
        v = self.get_kw(keyword)
        if v and isinstance(v, SAtom):
            return v.str_value
        return default

    def get_kw_list(self, keyword: str) -> Optional['SList']:
        v = self.get_kw(keyword)
        if isinstance(v, SList):
            return v
        return None


def tokenize_sexpr(text: str, path: str = '<input>'):
    """Tokenize S-expression text into (token, line, col) tuples."""
    tokens = []
    i = 0
    line = 1
    line_start = 0

    while i < len(text):
        c = text[i]

        # Whitespace
        if c in ' \t\r':
            i += 1
            continue
        if c == '\n':
            i += 1
            line += 1
            line_start = i
            continue

        # Comment
        if c == ';':
            while i < len(text) and text[i] != '\n':
                i += 1
            continue

        col = i - line_start + 1

        # Parens
        if c == '(':
            tokens.append(('(', line, col))
            i += 1
            continue
        if c == ')':
            tokens.append((')', line, col))
            i += 1
            continue

        # String
        if c == '"':
            start = i
            i += 1
            while i < len(text) and text[i] != '"':
                if text[i] == '\\':
                    i += 1
                i += 1
            if i >= len(text):
                die(f"{path}:{line}:{col}: unterminated string")
            i += 1  # closing "
            tokens.append((text[start:i], line, col))
            continue

        # Number (including negative)
        if c.isdigit() or (c == '-' and i + 1 < len(text) and text[i + 1].isdigit()):
            start = i
            if c == '-':
                i += 1
            if i + 1 < len(text) and text[i] == '0' and text[i + 1] in 'xXbB':
                i += 2
                while i < len(text) and (text[i].isalnum()):
                    i += 1
            else:
                while i < len(text) and text[i].isdigit():
                    i += 1
            tokens.append((text[start:i], line, col))
            continue

        # Symbol / keyword / variable
        # Starts with: letter _ : $ + * /
        if c.isalpha() or c in '_:$+*/':
            start = i
            i += 1
            while i < len(text) and (text[i].isalnum() or text[i] in '_-.:'):
                i += 1
            tokens.append((text[start:i], line, col))
            continue

        die(f"{path}:{line}:{col}: unexpected character '{c}'")

    return tokens


def parse_sexpr(tokens: list, path: str = '<input>') -> list[SExpr]:
    """Parse token list into S-expression tree. Returns list of top-level forms."""
    pos = [0]  # mutable index

    def parse_one() -> Optional[SExpr]:
        if pos[0] >= len(tokens):
            return None
        tok, line, col = tokens[pos[0]]

        if tok == ')':
            die(f"{path}:{line}:{col}: unexpected ')'")

        if tok == '(':
            pos[0] += 1
            children = []
            while pos[0] < len(tokens) and tokens[pos[0]][0] != ')':
                child = parse_one()
                if child:
                    children.append(child)
            if pos[0] >= len(tokens):
                die(f"{path}:{line}:{col}: unclosed '('")
            pos[0] += 1  # skip ')'
            return SList(children=children, line=line, col=col)

        # Atom
        pos[0] += 1
        return SAtom(value=tok, line=line, col=col)

    forms = []
    while pos[0] < len(tokens):
        form = parse_one()
        if form:
            forms.append(form)
    return forms


def parse_isa_file(path: str) -> list[SExpr]:
    """Parse a .isa file and return top-level S-expression forms."""
    text = read_file(path)
    tokens = tokenize_sexpr(text, path)
    return parse_sexpr(tokens, path)

# ============================================================
# L3: .isa structured extraction
# ============================================================

@dataclass
class McInsn:
    """Parsed machine instruction definition."""
    name: str
    operands: Optional[SList] = None
    constraints: Optional[SList] = None
    encoding: Optional[SList] = None
    flags: list = field(default_factory=list)
    min_bytes: int = 0
    max_bytes: int = 0
    golden_bytes: list = field(default_factory=list)  # [(regs, hex_str), ...]
    golden_asm: list = field(default_factory=list)
    decode_priority: str = 'normal'
    external_ref: str = ''
    helper: str = ''
    raw: Optional[SList] = None  # original S-expression

@dataclass
class RegClass:
    """Register class definition."""
    name: str
    regs: list          # register names
    encoding_bits: int

def extract_mcinsn(form: SList) -> McInsn:
    """Extract McInsn from a (define-mcinsn ...) form."""
    children = form.children
    assert len(children) >= 2
    name = children[1].value if isinstance(children[1], SAtom) else '???'

    insn = McInsn(name=name, raw=form)
    insn.operands = form.get_kw_list(':operands')
    insn.constraints = form.get_kw_list(':constraints')
    insn.encoding = form.get_kw_list(':encoding')
    insn.min_bytes = form.get_kw_int(':min-bytes')
    insn.max_bytes = form.get_kw_int(':max-bytes')
    insn.decode_priority = form.get_kw_str(':decode-priority', 'normal')
    insn.external_ref = form.get_kw_str(':external-reference', '')
    insn.helper = form.get_kw_str(':helper', '')

    # Flags
    flags_list = form.get_kw_list(':flags')
    if flags_list:
        insn.flags = [c.value for c in flags_list.children if isinstance(c, SAtom)]

    # Golden bytes: (((regs...) "hex") ...)
    gb = form.get_kw_list(':golden-bytes')
    if gb:
        for entry in gb.children:
            if isinstance(entry, SList) and len(entry.children) >= 2:
                regs_node = entry.children[0]
                hex_node = entry.children[1]
                regs = []
                if isinstance(regs_node, SList):
                    regs = [c.value if isinstance(c, SAtom) else str(c)
                            for c in regs_node.children]
                hex_str = hex_node.str_value if isinstance(hex_node, SAtom) else ''
                insn.golden_bytes.append((regs, hex_str))

    # Golden asm
    ga = form.get_kw_list(':golden-asm')
    if ga:
        for entry in ga.children:
            if isinstance(entry, SList) and len(entry.children) >= 2:
                regs_node = entry.children[0]
                asm_node = entry.children[1]
                regs = []
                if isinstance(regs_node, SList):
                    regs = [c.value if isinstance(c, SAtom) else str(c)
                            for c in regs_node.children]
                asm_str = asm_node.str_value if isinstance(asm_node, SAtom) else ''
                insn.golden_asm.append((regs, asm_str))

    return insn

def extract_regclass(form: SList) -> RegClass:
    """Extract RegClass from a (define-regclass ...) form."""
    name = form.children[1].value if len(form.children) >= 2 and isinstance(form.children[1], SAtom) else '???'
    regs = []
    regs_list = form.get_kw_list(':regs')
    if regs_list:
        regs = [c.value for c in regs_list.children if isinstance(c, SAtom)]
    bits = form.get_kw_int(':encoding-bits', 4)
    return RegClass(name=name, regs=regs, encoding_bits=bits)

def load_isa_text(text: str, name: str = '<text>') -> tuple[list[RegClass], list[McInsn]]:
    """Parse .isa from a string, returning regclasses and mcinsns."""
    tokens = tokenize_sexpr(text, name)
    forms = parse_sexpr(tokens, name)
    regclasses = []
    mcinsns = []
    for form in forms:
        if not isinstance(form, SList) or not form.children:
            continue
        head = form.head
        if isinstance(head, SAtom):
            if head.value == 'define-mcinsn':
                mcinsns.append(extract_mcinsn(form))
            elif head.value == 'define-regclass':
                regclasses.append(extract_regclass(form))
    return regclasses, mcinsns

def load_isa(path: str) -> tuple[list[RegClass], list[McInsn]]:
    """Load and parse a .isa file, returning regclasses and mcinsns."""
    forms = parse_isa_file(path)
    regclasses = []
    mcinsns = []
    for form in forms:
        if not isinstance(form, SList) or not form.children:
            continue
        head = form.head
        if isinstance(head, SAtom):
            if head.value == 'define-mcinsn':
                mcinsns.append(extract_mcinsn(form))
            elif head.value == 'define-regclass':
                regclasses.append(extract_regclass(form))
    return regclasses, mcinsns

# ============================================================
# L4: Emit-helper code generation (.isa → C emit functions)
# ============================================================

def _c_ident(name: str) -> str:
    """Convert dotted ISA name to C identifier: x64.add.rr → x64_add_rr"""
    return name.replace('.', '_').replace('-', '_')

def _detect_arch(mcinsns: list[McInsn]) -> str:
    """Detect architecture from instruction name prefix."""
    if mcinsns and mcinsns[0].name.startswith('arm64.'):
        return 'arm64'
    if mcinsns and mcinsns[0].name.startswith('riscv64.'):
        return 'riscv64'
    return 'x64'

# ---------- Operand extraction ----------

@dataclass
class OperandInfo:
    name: str       # $dst, $src, $imm
    kind: str       # "reg" or "imm"
    subtype: str    # "gpr64", "i8", "i32", etc.

def extract_operands(insn: McInsn) -> list[OperandInfo]:
    """Extract typed operand list from a McInsn."""
    ops = []
    if not insn.operands:
        return ops
    for child in insn.operands.children:
        if isinstance(child, SList) and len(child.children) >= 2:
            var = child.children[0]
            typ = child.children[1]
            if isinstance(var, SAtom) and isinstance(typ, SAtom):
                var_name = var.value  # $dst
                type_str = typ.value  # reg:gpr64 or imm:i32
                parts = type_str.split(':')
                kind = parts[0]  # "reg" or "imm" or "cc"
                subtype = parts[1] if len(parts) > 1 else ''
                ops.append(OperandInfo(name=var_name, kind=kind, subtype=subtype))
    return ops

def _c_param_type(op: OperandInfo) -> str:
    """Return C parameter type for an operand."""
    if op.kind == 'reg':
        return 'uint8_t'
    if op.kind == 'cc':
        return 'uint8_t'
    if op.subtype in ('i8', 'u8'):
        return 'int8_t' if op.subtype == 'i8' else 'uint8_t'
    if op.subtype in ('i16', 'u16'):
        return 'int16_t' if op.subtype == 'i16' else 'uint16_t'
    if op.subtype in ('i32', 'rel32', 'u32'):
        return 'int32_t' if op.subtype in ('i32', 'rel32') else 'uint32_t'
    if op.subtype in ('i64', 'u64'):
        return 'int64_t' if op.subtype == 'i64' else 'uint64_t'
    # Default: signed imm or rel
    if 'rel' in op.subtype:
        return 'int32_t'
    return 'int32_t'

def _c_param_name(op: OperandInfo) -> str:
    """Operand $dst → dst"""
    return op.name.lstrip('$')

# ---------- x64 emit generator ----------

def _gen_x64_emit(insn: McInsn, operands: list[OperandInfo]) -> list[str]:
    """Generate x64 emit function body lines."""
    if not insn.encoding:
        return ['    /* no encoding specified */', '    return 0;']

    enc = insn.encoding.children
    lines = []
    byte_idx = 0

    # Scan encoding for structural elements
    has_rex_w = False
    has_modrm = False
    has_plus_rd = False
    opcode_bytes = []
    modrm_info = None   # (mod, reg_or_ext, rm)
    plus_info = None    # (base_byte, reg_operand)
    imm_parts = []      # [(type, operand_name)]

    for elem in enc:
        if isinstance(elem, SAtom):
            if elem.value == 'rex.w':
                has_rex_w = True
            elif elem.is_number:
                opcode_bytes.append(elem.int_value)
            # else: symbol like "rex", skip for now
        elif isinstance(elem, SList) and elem.children:
            head_val = elem.children[0].value if isinstance(elem.children[0], SAtom) else ''
            if head_val == 'modrm':
                has_modrm = True
                ch = elem.children
                modrm_mod = ch[1].int_value if len(ch) > 1 and isinstance(ch[1], SAtom) and ch[1].is_number else 0b11
                modrm_reg = ch[2] if len(ch) > 2 else None  # number or $var
                modrm_rm = ch[3] if len(ch) > 3 else None    # $var
                modrm_info = (modrm_mod, modrm_reg, modrm_rm)
            elif head_val == '+':
                has_plus_rd = True
                base = elem.children[1].int_value if len(elem.children) > 1 and isinstance(elem.children[1], SAtom) else 0
                reg_part = elem.children[2] if len(elem.children) > 2 else None
                plus_info = (base, reg_part)
            elif head_val in ('imm8', 'imm16', 'imm32', 'imm64', 'rel8', 'rel32'):
                imm_type = head_val
                imm_var = elem.children[1].value.lstrip('$') if len(elem.children) > 1 and isinstance(elem.children[1], SAtom) else ''
                imm_parts.append((imm_type, imm_var))
            elif head_val == 'reg3':
                pass  # handled inside '+'

    # Build function body
    # Capacity check
    lines.append(f'    if (cap < {insn.max_bytes}) return 0;')
    lines.append(f'    uint8_t *p = buf;')

    # REX prefix
    if has_rex_w:
        # Collect register operands that need REX.R/REX.B extension
        rex_parts = ['0x48']  # REX.W
        if has_modrm and modrm_info:
            _, mreg, mrm = modrm_info
            if mreg and isinstance(mreg, SAtom) and mreg.is_variable:
                reg_name = mreg.value.lstrip('$')
                rex_parts.append(f'(({reg_name} >> 3) << 2)')  # REX.R
            if mrm and isinstance(mrm, SAtom) and mrm.is_variable:
                rm_name = mrm.value.lstrip('$')
                rex_parts.append(f'(({rm_name} >> 3) << 0)')   # REX.B
        elif has_plus_rd and plus_info:
            _, reg_part = plus_info
            if reg_part and isinstance(reg_part, SList) and reg_part.children:
                reg_var = reg_part.children[1] if len(reg_part.children) > 1 else None
                if reg_var and isinstance(reg_var, SAtom) and reg_var.is_variable:
                    rn = reg_var.value.lstrip('$')
                    rex_parts.append(f'(({rn} >> 3) << 0)')  # REX.B
        lines.append(f'    *p++ = (uint8_t)({" | ".join(rex_parts)});')

    # Opcode bytes
    if has_plus_rd and plus_info:
        base, reg_part = plus_info
        if reg_part and isinstance(reg_part, SList):
            reg_var = reg_part.children[1] if len(reg_part.children) > 1 else None
            if reg_var and isinstance(reg_var, SAtom) and reg_var.is_variable:
                rn = reg_var.value.lstrip('$')
                lines.append(f'    *p++ = (uint8_t)(0x{base:02x} + ({rn} & 7));')
            else:
                lines.append(f'    *p++ = 0x{base:02x};')
        else:
            lines.append(f'    *p++ = 0x{base:02x};')
    else:
        for b in opcode_bytes:
            lines.append(f'    *p++ = 0x{b:02x};')

    # ModRM
    if has_modrm and modrm_info:
        mod, mreg, mrm = modrm_info
        reg_expr = '0'
        rm_expr = '0'
        if isinstance(mreg, SAtom):
            if mreg.is_number:
                reg_expr = str(mreg.int_value)
            elif mreg.is_variable:
                reg_expr = f'({mreg.value.lstrip("$")} & 7)'
        if isinstance(mrm, SAtom):
            if mrm.is_variable:
                rm_expr = f'({mrm.value.lstrip("$")} & 7)'
            elif mrm.is_number:
                rm_expr = str(mrm.int_value)
        lines.append(f'    *p++ = (uint8_t)(0x{mod:02x} << 6 | ({reg_expr}) << 3 | ({rm_expr}));')

    # Immediates
    for imm_type, imm_var in imm_parts:
        if imm_type in ('imm8', 'rel8'):
            lines.append(f'    *p++ = (uint8_t){imm_var};')
        elif imm_type == 'imm16':
            lines.append(f'    memcpy(p, &(uint16_t){{{imm_var}}}, 2); p += 2;')
        elif imm_type in ('imm32', 'rel32'):
            lines.append(f'    {{ int32_t v = {imm_var}; memcpy(p, &v, 4); p += 4; }}')
        elif imm_type == 'imm64':
            lines.append(f'    {{ int64_t v = {imm_var}; memcpy(p, &v, 8); p += 8; }}')

    lines.append(f'    return (int)(p - buf);')
    return lines

# ---------- arm64 emit generator ----------

def _gen_arm64_emit(insn: McInsn, operands: list[OperandInfo]) -> list[str]:
    """Generate arm64 emit function body (fixed 32-bit, little-endian)."""
    if not insn.encoding:
        return ['    /* no encoding specified */', '    return 0;']

    enc = insn.encoding.children
    lines = []
    lines.append(f'    if (cap < 4) return 0;')

    # First element should be the base opcode (32-bit number)
    base_opcode = 0
    fields = []  # (bit_offset, width, operand_name_or_value)

    for elem in enc:
        if isinstance(elem, SAtom) and elem.is_number:
            base_opcode = elem.int_value
        elif isinstance(elem, SList) and elem.children:
            head_val = elem.children[0].value if isinstance(elem.children[0], SAtom) else ''
            if head_val == 'field':
                ch = elem.children
                bit_off = ch[1].int_value if len(ch) > 1 and isinstance(ch[1], SAtom) else 0
                width = ch[2].int_value if len(ch) > 2 and isinstance(ch[2], SAtom) else 0
                operand = ch[3] if len(ch) > 3 else None
                if operand and isinstance(operand, SAtom):
                    if operand.is_variable:
                        fields.append((bit_off, width, operand.value.lstrip('$')))
                    elif operand.is_number:
                        fields.append((bit_off, width, str(operand.int_value)))

    lines.append(f'    uint32_t insn = 0x{base_opcode:08x}u;')
    for bit_off, width, val in fields:
        mask = (1 << width) - 1
        lines.append(f'    insn |= ((uint32_t)({val}) & 0x{mask:x}u) << {bit_off};')
    lines.append(f'    memcpy(buf, &insn, 4);')
    lines.append(f'    return 4;')
    return lines

# ---------- riscv64 emit generator ----------

def _gen_riscv64_emit(insn: McInsn, operands: list[OperandInfo]) -> list[str]:
    """Generate riscv64 emit function body (fixed 32-bit, little-endian)."""
    if not insn.encoding:
        return ['    /* no encoding specified */', '    return 0;']

    enc = insn.encoding.children
    lines = []
    lines.append(f'    if (cap < 4) return 0;')

    # Detect format from first symbol
    if not enc:
        return ['    return 0;']

    head = enc[0]
    if isinstance(head, SAtom) and head.is_number:
        # Raw 32-bit constant (nop, ebreak)
        val = head.int_value
        lines.append(f'    uint32_t insn = 0x{val:08x}u;')
        lines.append(f'    memcpy(buf, &insn, 4);')
        lines.append(f'    return 4;')
        return lines

    fmt = head.value if isinstance(head, SAtom) else ''

    def _rv_var(idx):
        """Get operand name from encoding child at index."""
        if idx < len(enc) and isinstance(enc[idx], SAtom) and enc[idx].is_variable:
            return enc[idx].value.lstrip('$')
        return '0'

    def _rv_imm(idx):
        """Get immediate value (number or variable) from encoding child."""
        if idx < len(enc) and isinstance(enc[idx], SAtom):
            if enc[idx].is_number:
                return str(enc[idx].int_value)
            if enc[idx].is_variable:
                return enc[idx].value.lstrip('$')
        return '0'

    if fmt == 'r-type':
        # (r-type opcode funct3 funct7 rd rs1 rs2)
        opcode = _rv_imm(1)
        funct3 = _rv_imm(2)
        funct7 = _rv_imm(3)
        rd = _rv_var(4)
        rs1 = _rv_var(5)
        rs2 = _rv_var(6)
        lines.append(f'    uint32_t insn = ({opcode}u)')
        lines.append(f'        | ((uint32_t)({rd}) << 7)')
        lines.append(f'        | ((uint32_t)({funct3}u) << 12)')
        lines.append(f'        | ((uint32_t)({rs1}) << 15)')
        lines.append(f'        | ((uint32_t)({rs2}) << 20)')
        lines.append(f'        | ((uint32_t)({funct7}u) << 25);')
        lines.append(f'    memcpy(buf, &insn, 4);')
        lines.append(f'    return 4;')

    elif fmt == 'i-type':
        # (i-type opcode funct3 rd rs1 imm)
        opcode = _rv_imm(1)
        funct3 = _rv_imm(2)
        rd = _rv_var(3)
        rs1 = _rv_var(4)
        imm = _rv_imm(5)
        lines.append(f'    uint32_t insn = ({opcode}u)')
        lines.append(f'        | ((uint32_t)({rd}) << 7)')
        lines.append(f'        | ((uint32_t)({funct3}u) << 12)')
        lines.append(f'        | ((uint32_t)({rs1}) << 15)')
        lines.append(f'        | ((uint32_t)((int32_t)({imm}) & 0xfff) << 20);')
        lines.append(f'    memcpy(buf, &insn, 4);')
        lines.append(f'    return 4;')

    elif fmt == 's-type':
        # (s-type opcode funct3 rs1 rs2 imm)
        opcode = _rv_imm(1)
        funct3 = _rv_imm(2)
        rs1 = _rv_var(3)
        rs2 = _rv_var(4)
        imm = _rv_imm(5)
        lines.append(f'    int32_t imm_val = (int32_t)({imm});')
        lines.append(f'    uint32_t insn = ({opcode}u)')
        lines.append(f'        | ((uint32_t)(imm_val & 0x1f) << 7)')
        lines.append(f'        | ((uint32_t)({funct3}u) << 12)')
        lines.append(f'        | ((uint32_t)({rs1}) << 15)')
        lines.append(f'        | ((uint32_t)({rs2}) << 20)')
        lines.append(f'        | ((uint32_t)((imm_val >> 5) & 0x7f) << 25);')
        lines.append(f'    memcpy(buf, &insn, 4);')
        lines.append(f'    return 4;')

    elif fmt == 'b-type':
        # (b-type opcode funct3 rs1 rs2 imm)
        opcode = _rv_imm(1)
        funct3 = _rv_imm(2)
        rs1 = _rv_var(3)
        rs2 = _rv_var(4)
        imm = _rv_imm(5)
        lines.append(f'    int32_t imm_val = (int32_t)({imm});')
        lines.append(f'    uint32_t insn = ({opcode}u)')
        lines.append(f'        | ((uint32_t)((imm_val >> 11) & 1) << 7)')
        lines.append(f'        | ((uint32_t)((imm_val >> 1) & 0xf) << 8)')
        lines.append(f'        | ((uint32_t)({funct3}u) << 12)')
        lines.append(f'        | ((uint32_t)({rs1}) << 15)')
        lines.append(f'        | ((uint32_t)({rs2}) << 20)')
        lines.append(f'        | ((uint32_t)((imm_val >> 5) & 0x3f) << 25)')
        lines.append(f'        | ((uint32_t)((imm_val >> 12) & 1) << 31);')
        lines.append(f'    memcpy(buf, &insn, 4);')
        lines.append(f'    return 4;')

    elif fmt == 'u-type':
        # (u-type opcode rd imm)
        opcode = _rv_imm(1)
        rd = _rv_var(2)
        imm = _rv_imm(3)
        lines.append(f'    uint32_t insn = ({opcode}u)')
        lines.append(f'        | ((uint32_t)({rd}) << 7)')
        lines.append(f'        | ((uint32_t)({imm}) << 12);')
        lines.append(f'    memcpy(buf, &insn, 4);')
        lines.append(f'    return 4;')

    elif fmt == 'j-type':
        # (j-type opcode rd imm)
        opcode = _rv_imm(1)
        rd = _rv_var(2)
        imm = _rv_imm(3)
        lines.append(f'    int32_t imm_val = (int32_t)({imm});')
        lines.append(f'    uint32_t insn = ({opcode}u)')
        lines.append(f'        | ((uint32_t)({rd}) << 7)')
        lines.append(f'        | ((uint32_t)((imm_val >> 12) & 0xff) << 12)')
        lines.append(f'        | ((uint32_t)((imm_val >> 11) & 1) << 20)')
        lines.append(f'        | ((uint32_t)((imm_val >> 1) & 0x3ff) << 21)')
        lines.append(f'        | ((uint32_t)((imm_val >> 20) & 1) << 31);')
        lines.append(f'    memcpy(buf, &insn, 4);')
        lines.append(f'    return 4;')

    else:
        lines.append(f'    /* unknown riscv64 format: {fmt} */')
        lines.append(f'    return 0;')

    return lines

# ---------- Emit file generator ----------

def generate_emit_header(arch: str, regclasses: list[RegClass],
                         mcinsns: list[McInsn]) -> str:
    """Generate complete C header with emit helpers for one architecture."""
    guard = f'XISA_{arch.upper()}_EMIT_H'
    lines = []
    lines.append('/* AUTO-GENERATED by xisagen — DO NOT EDIT */')
    lines.append(f'/* Source: xisa/arch/{arch}.isa */')
    lines.append('')
    lines.append(f'#ifndef {guard}')
    lines.append(f'#define {guard}')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('#include <string.h>')
    lines.append('')

    # Register encoding tables (prefixed by arch to avoid cross-arch collision)
    for rc in regclasses:
        cname = _c_ident(rc.name)
        prefix = arch.upper()
        lines.append(f'/* Register class: {rc.name} ({len(rc.regs)} regs, {rc.encoding_bits}-bit encoding) */')
        lines.append(f'enum {{')
        for i, reg in enumerate(rc.regs):
            lines.append(f'    XISA_{prefix}_REG_{reg.upper()} = {i},')
        lines.append(f'}};')
        lines.append('')

    # Emit functions
    gen_fn = {'x64': _gen_x64_emit, 'arm64': _gen_arm64_emit, 'riscv64': _gen_riscv64_emit}
    emit_fn = gen_fn.get(arch, _gen_x64_emit)

    for insn in mcinsns:
        operands = extract_operands(insn)
        fname = f'xisa_emit_{_c_ident(insn.name)}'

        # Build parameter list
        params = ['uint8_t *buf', 'int cap']
        for op in operands:
            params.append(f'{_c_param_type(op)} {_c_param_name(op)}')

        sig = f'static inline int {fname}({", ".join(params)})'
        lines.append(f'/* {insn.name}: {insn.min_bytes}-{insn.max_bytes} bytes */')
        lines.append(sig)
        lines.append('{')
        body = emit_fn(insn, operands)
        lines.extend(body)
        lines.append('}')
        lines.append('')

    # Instruction metadata struct (guarded against redefinition)
    lines.append('/* ========== Instruction Metadata ========== */')
    lines.append('')
    lines.append('#ifndef XISA_MCINSN_INFO_DEFINED')
    lines.append('#define XISA_MCINSN_INFO_DEFINED')
    lines.append(f'typedef struct {{')
    lines.append(f'    const char *name;')
    lines.append(f'    uint8_t min_bytes;')
    lines.append(f'    uint8_t max_bytes;')
    lines.append(f'    uint8_t noperands;')
    lines.append(f'    uint16_t flags;  /* bitmask of XISA_F_* */')
    lines.append(f'}} XisaMcInsnInfo;')
    lines.append('#endif')
    lines.append('')

    # Flag defines (arch-prefixed)
    all_flags = sorted(set(f for insn in mcinsns for f in insn.flags))
    for i, flag in enumerate(all_flags):
        lines.append(f'#ifndef XISA_F_{flag.upper()}')
        lines.append(f'#define XISA_F_{flag.upper()} (1u << {i})')
        lines.append(f'#endif')
    lines.append('')

    lines.append(f'#ifdef XISA_{arch.upper()}_IMPL')
    lines.append(f'static const XisaMcInsnInfo xisa_{arch}_mcinsn_info[] = {{')
    for insn in mcinsns:
        operands = extract_operands(insn)
        flags_expr = ' | '.join(f'XISA_F_{f.upper()}' for f in insn.flags) if insn.flags else '0'
        lines.append(f'    {{"{insn.name}", {insn.min_bytes}, {insn.max_bytes}, '
                     f'{len(operands)}, {flags_expr}}},')
    lines.append(f'}};')
    lines.append(f'#endif')
    lines.append('')

    lines.append(f'#endif  // {guard}')
    lines.append('')
    return '\n'.join(lines)

# ============================================================
# L6: X64Buf-based emit generator (replaces hand-written xm_x64.c)
# ============================================================

# Maps ISA instruction name to the C function name and signature
# from xm_x64.h. ISA name → (c_func_name, [(param_name, C_type)...])
# Only instructions in this table get generated; the rest are
# handled by the standalone emit header.

def _x64_c_name(isa_name: str) -> str:
    """x64.add.rr → x64_add_rr (strip arch prefix, collapse dots)."""
    return isa_name.replace('.', '_')

def _resolve_enc_head(enc):
    """Get head symbol from encoding S-expression."""
    if not enc or not enc.children:
        return ''
    first = enc.children[0]
    return first.value if isinstance(first, SAtom) else ''

def _is_enc_pattern(enc, *heads):
    """Check if encoding starts with one of the given head symbols."""
    h = _resolve_enc_head(enc)
    return h in heads

def _gen_x64buf_body(insn: McInsn, operands: list[OperandInfo]) -> list[str]:
    """Generate X64Buf-based function body from ISA encoding DSL.
    Returns list of C statement lines (without function wrapper)."""
    if not insn.encoding:
        return ['    /* no encoding specified */']

    enc = insn.encoding.children
    lines = []
    head = enc[0].value if enc and isinstance(enc[0], SAtom) else ''

    # Helper: get operand C name
    def _var(node):
        if isinstance(node, SAtom) and node.is_variable:
            return node.value.lstrip('$')
        return None

    def _num(node):
        if isinstance(node, SAtom) and node.is_number:
            return node.int_value
        return None

    # ---- Pattern: (sse-rr PREFIX OP1 OP2 $dst $src) ----
    if head == 'sse-rr':
        prefix = _num(enc[1])
        op1 = _num(enc[2])
        op2 = _num(enc[3])
        dst = _var(enc[4])
        src = _var(enc[5])
        lines.append(f'    x64_emit8(buf, 0x{prefix:02x});')
        lines.append(f'    {{ bool r = ((int){dst} > 7); bool b = ((int){src} > 7);')
        lines.append(f'      if (r || b) x64_rex(buf, false, r, false, b); }}')
        lines.append(f'    x64_emit8(buf, 0x{op1:02x});')
        lines.append(f'    x64_emit8(buf, 0x{op2:02x});')
        lines.append(f'    x64_modrm(buf, 0x3, (uint8_t){dst} & 7, (uint8_t){src} & 7);')
        return lines

    # ---- Pattern: (sse-rm PREFIX OP1 OP2 $xmm $base $disp) ----
    if head == 'sse-rm':
        prefix = _num(enc[1])
        op1 = _num(enc[2])
        op2 = _num(enc[3])
        xmm = _var(enc[4])
        base = _var(enc[5])
        disp = _var(enc[6])
        lines.append(f'    x64_emit8(buf, 0x{prefix:02x});')
        lines.append(f'    {{ bool r = ((int){xmm} > 7); bool b = ({base} > 7);')
        lines.append(f'      if (r || b) x64_rex(buf, false, r, false, b); }}')
        lines.append(f'    x64_emit8(buf, 0x{op1:02x});')
        lines.append(f'    x64_emit8(buf, 0x{op2:02x});')
        lines.append(f'    x64_modrm_mem(buf, (X64Reg)((int){xmm} & 7), {base}, {disp});')
        return lines

    # ---- Pattern: (sse-gp PREFIX rex.w OP1 OP2 $r1 $r2) ----
    if head == 'sse-gp':
        prefix = _num(enc[1])
        # enc[2] is 'rex.w'
        op1 = _num(enc[3])
        op2 = _num(enc[4])
        r1 = _var(enc[5])
        r2 = _var(enc[6])
        lines.append(f'    x64_emit8(buf, 0x{prefix:02x});')
        lines.append(f'    x64_rex(buf, true, (int){r1} > 7, false, (int){r2} > 7);')
        lines.append(f'    x64_emit8(buf, 0x{op1:02x});')
        lines.append(f'    x64_emit8(buf, 0x{op2:02x});')
        lines.append(f'    x64_modrm(buf, 0x3, (uint8_t){r1} & 7, (uint8_t){r2} & 7);')
        return lines

    # ---- Pattern: (rex-if-ext $reg (+ BASE (reg3 $reg)) (imm32 $imm)) ----
    if head == 'rex-if-ext':
        reg = _var(enc[1])
        # enc[2] is the (+ BASE (reg3 $reg)) list
        plus = enc[2]
        base_byte = _num(plus.children[1]) if isinstance(plus, SList) else 0xB8
        imm_node = enc[3]
        imm_type = imm_node.children[0].value if isinstance(imm_node, SList) else 'imm32'
        imm_var = _var(imm_node.children[1]) if isinstance(imm_node, SList) else 'imm'
        lines.append(f'    if ({reg} > 7)')
        lines.append(f'        x64_rex(buf, false, false, false, true);')
        lines.append(f'    x64_emit8(buf, 0x{base_byte:02x} + ((uint8_t){reg} & 7));')
        if imm_type == 'imm32':
            lines.append(f'    x64_emit32(buf, (uint32_t){imm_var});')
        elif imm_type == 'imm64':
            lines.append(f'    x64_emit64(buf, {imm_var});')
        return lines

    # ---- Pattern: (rex-if-ext2 $reg $base OPCODE (modrm-mem ...)) ----
    if head == 'rex-if-ext2':
        reg = _var(enc[1])
        base = _var(enc[2])
        opcode = _num(enc[3])
        mm = enc[4]  # (modrm-mem $reg $base $disp)
        disp = _var(mm.children[3]) if isinstance(mm, SList) and len(mm.children) > 3 else '0'
        lines.append(f'    if ({reg} > 7 || {base} > 7)')
        lines.append(f'        x64_rex(buf, false, {reg} > 7, false, {base} > 7);')
        lines.append(f'    x64_emit8(buf, 0x{opcode:02x});')
        lines.append(f'    x64_modrm_mem(buf, {reg}, {base}, {disp});')
        return lines

    # ---- Pattern: (rex-for-byte $src $base OPCODE (modrm-mem ...)) ----
    if head == 'rex-for-byte':
        src = _var(enc[1])
        base = _var(enc[2])
        opcode = _num(enc[3])
        mm = enc[4]
        disp = _var(mm.children[3]) if isinstance(mm, SList) and len(mm.children) > 3 else '0'
        lines.append(f'    if ({src} > 7 || {src} >= 4 || {base} > 7)')
        lines.append(f'        x64_rex(buf, false, {src} > 7, false, {base} > 7);')
        lines.append(f'    x64_emit8(buf, 0x{opcode:02x});')
        lines.append(f'    x64_modrm_mem(buf, {src}, {base}, {disp});')
        return lines

    # ---- Pattern: (rex-if-ext-r $reg OPCODES... (modrm ...)) ----
    if head == 'rex-if-ext-r':
        reg = _var(enc[1])
        opcodes = []
        modrm_node = None
        for e in enc[2:]:
            if isinstance(e, SAtom) and e.is_number:
                opcodes.append(e.int_value)
            elif isinstance(e, SList):
                h2 = e.children[0].value if isinstance(e.children[0], SAtom) else ''
                if h2 == 'modrm':
                    modrm_node = e
        lines.append(f'    if ({reg} > 7)')
        lines.append(f'        x64_rex(buf, false, false, false, true);')
        for op in opcodes:
            lines.append(f'    x64_emit8(buf, 0x{op:02x});')
        if modrm_node:
            mod = _num(modrm_node.children[1])
            reg_f = modrm_node.children[2]
            rm_f = modrm_node.children[3]
            reg_expr = str(_num(reg_f)) if _num(reg_f) is not None else f'(uint8_t){_var(reg_f)}'
            rm_expr = _var(rm_f) if _var(rm_f) else str(_num(rm_f))
            lines.append(f'    x64_modrm(buf, 0x{mod:x}, {reg_expr}, (uint8_t){rm_expr});')
        return lines

    # ---- Pattern: (rex-for-byte-r $reg OPCODES... (modrm ...)) ----
    if head == 'rex-for-byte-r':
        reg = _var(enc[1])
        # Collect opcode bytes and modrm
        opcodes = []
        modrm_node = None
        for e in enc[2:]:
            if isinstance(e, SAtom) and e.is_number:
                opcodes.append(e.int_value)
            elif isinstance(e, SList):
                h2 = e.children[0].value if isinstance(e.children[0], SAtom) else ''
                if h2 == 'modrm':
                    modrm_node = e
                elif h2 == '+':
                    # (+  0x90 $cc) style
                    base_val = _num(e.children[1])
                    cc_var = _var(e.children[2])
                    opcodes.append(('plus', base_val, cc_var))
        lines.append(f'    if ({reg} > 7 || {reg} >= 4)')
        lines.append(f'        x64_rex(buf, false, false, false, {reg} > 7);')
        for op in opcodes:
            if isinstance(op, tuple) and op[0] == 'plus':
                lines.append(f'    x64_emit8(buf, 0x{op[1]:02x} + (uint8_t){op[2]});')
            else:
                lines.append(f'    x64_emit8(buf, 0x{op:02x});')
        if modrm_node:
            mod = _num(modrm_node.children[1])
            reg_f = modrm_node.children[2]
            rm_f = modrm_node.children[3]
            reg_expr = str(_num(reg_f)) if _num(reg_f) is not None else f'(uint8_t){_var(reg_f)}'
            rm_expr = _var(rm_f) if _var(rm_f) else str(_num(rm_f))
            lines.append(f'    x64_modrm(buf, 0x{mod:x}, {reg_expr}, (uint8_t){rm_expr});')
        return lines

    # ---- Pattern: (prefix-66 rex-if-ext2 ...) ----
    if head == 'prefix-66':
        lines.append(f'    x64_emit8(buf, 0x66);')
        # Rest follows rex-if-ext2 pattern
        reg = _var(enc[2])
        base = _var(enc[3])
        opcode = _num(enc[4])
        mm = enc[5]
        disp = _var(mm.children[3]) if isinstance(mm, SList) and len(mm.children) > 3 else '0'
        lines.append(f'    if ({reg} > 7 || {base} > 7)')
        lines.append(f'        x64_rex(buf, false, {reg} > 7, false, {base} > 7);')
        lines.append(f'    x64_emit8(buf, 0x{opcode:02x});')
        lines.append(f'    x64_modrm_mem(buf, {reg}, {base}, {disp});')
        return lines

    # ---- Standard patterns: rex.w, opcode+rd, nullary, branch ----

    # Analyze encoding structure
    has_rex_w = False
    opcode_bytes = []
    modrm_info = None       # (mod, reg_expr, rm_expr) for modrm 0b11
    modrm_mem_info = None   # (reg, base, disp) for modrm-mem
    plus_info = None        # (base_byte, reg_var) for opcode+rd
    imm_parts = []          # [(type, var_name)]
    plus_cc = None          # (base_byte, cc_var) for (+ 0x80 $cc) style

    for elem in enc:
        if isinstance(elem, SAtom):
            if elem.value == 'rex.w':
                has_rex_w = True
            elif elem.is_number:
                opcode_bytes.append(elem.int_value)
        elif isinstance(elem, SList) and elem.children:
            h2 = elem.children[0].value if isinstance(elem.children[0], SAtom) else ''
            if h2 == 'modrm':
                ch = elem.children
                mod = _num(ch[1]) if len(ch) > 1 else 0b11
                mreg = ch[2] if len(ch) > 2 else None
                mrm = ch[3] if len(ch) > 3 else None
                modrm_info = (mod, mreg, mrm)
            elif h2 == 'modrm-mem':
                ch = elem.children
                mm_reg = _var(ch[1]) if len(ch) > 1 else None
                mm_base = _var(ch[2]) if len(ch) > 2 else None
                mm_disp = _var(ch[3]) if len(ch) > 3 else None
                modrm_mem_info = (mm_reg, mm_base, mm_disp)
            elif h2 == '+':
                ch = elem.children
                base_val = _num(ch[1])
                operand = ch[2] if len(ch) > 2 else None
                if operand and isinstance(operand, SList):
                    # (+ 0xb8 (reg3 $dst))
                    rv = _var(operand.children[1]) if len(operand.children) > 1 else None
                    plus_info = (base_val, rv)
                elif operand and isinstance(operand, SAtom) and operand.is_variable:
                    # (+ 0x80 $cc)
                    plus_cc = (base_val, _var(operand))
            elif h2 in ('imm8', 'imm16', 'imm32', 'imm64', 'rel8', 'rel32'):
                iv = _var(elem.children[1]) if len(elem.children) > 1 else ''
                imm_parts.append((h2, iv))

    # ---- Emit REX prefix ----
    if has_rex_w:
        if modrm_info and modrm_info[0] == 0b11:
            _, mreg, mrm = modrm_info
            mreg_var = _var(mreg)
            mrm_var = _var(mrm)
            if mreg_var and mrm_var:
                lines.append(f'    x64_rex_rr(buf, true, {mreg_var}, {mrm_var});')
            elif mrm_var:
                lines.append(f'    x64_rex(buf, true, false, false, {mrm_var} > 7);')
            else:
                lines.append(f'    x64_rex(buf, true, false, false, false);')
        elif modrm_mem_info:
            reg, base, disp = modrm_mem_info
            lines.append(f'    x64_rex(buf, true, {reg} > 7, false, {base} > 7);')
        elif plus_info:
            _, rv = plus_info
            if rv:
                lines.append(f'    x64_rex(buf, true, false, false, {rv} > 7);')
            else:
                lines.append(f'    x64_rex(buf, true, false, false, false);')
        else:
            lines.append(f'    x64_rex(buf, true, false, false, false);')
    elif not has_rex_w and plus_info:
        # opcode+rd without REX.W (push/pop): emit REX.B only if needed
        _, rv = plus_info
        if rv:
            lines.append(f'    if ({rv} > 7)')
            lines.append(f'        x64_rex(buf, false, false, false, true);')

    # ---- Emit opcode bytes ----
    for b in opcode_bytes:
        lines.append(f'    x64_emit8(buf, 0x{b:02x});')

    # ---- Emit parameterized opcode: (+ BASE $cc) ----
    if plus_cc:
        base_val, cc_var = plus_cc
        lines.append(f'    x64_emit8(buf, 0x{base_val:02x} + (uint8_t){cc_var});')

    # ---- Emit opcode+rd: (+ BASE (reg3 $r)) ----
    if plus_info:
        base_val, rv = plus_info
        if rv:
            lines.append(f'    x64_emit8(buf, 0x{base_val:02x} + ((uint8_t){rv} & 7));')

    # ---- Emit ModRM (register-register) ----
    if modrm_info:
        mod, mreg, mrm = modrm_info
        if mod == 0b11:
            mreg_var = _var(mreg)
            mrm_var = _var(mrm)
            mreg_num = _num(mreg)
            mrm_num = _num(mrm)
            reg_expr = f'(uint8_t){mreg_var}' if mreg_var else str(mreg_num)
            rm_expr = f'(uint8_t){mrm_var}' if mrm_var else str(mrm_num)
            if mreg_var and mrm_var:
                lines.append(f'    x64_modrm_rr(buf, {mreg_var}, {mrm_var});')
            else:
                lines.append(f'    x64_modrm(buf, 0x3, {reg_expr}, {rm_expr});')

    # ---- Emit ModRM (memory) ----
    if modrm_mem_info:
        reg, base, disp = modrm_mem_info
        lines.append(f'    x64_modrm_mem(buf, {reg}, {base}, {disp});')

    # ---- Emit immediates ----
    for imm_type, imm_var in imm_parts:
        if imm_type in ('imm8', 'rel8'):
            lines.append(f'    x64_emit8(buf, (uint8_t){imm_var});')
        elif imm_type in ('imm32', 'rel32'):
            lines.append(f'    x64_emit32(buf, (uint32_t){imm_var});')
        elif imm_type == 'imm64':
            lines.append(f'    x64_emit64(buf, {imm_var});')

    if not lines:
        lines.append(f'    /* empty encoding */')

    return lines

# C type mapping for X64Buf-based emit functions
_X64BUF_PARAM_TYPES = {
    'reg:gpr64': 'X64Reg',
    'reg:gpr32': 'X64Reg',
    'reg:xmm': 'X64Xmm',
    'cc': 'X64Cond',
    'imm:i8': 'int8_t',
    'imm:u8': 'uint8_t',
    'imm:i32': 'int32_t',
    'imm:u32': 'uint32_t',
    'imm:i64': 'int64_t',
    'imm:u64': 'uint64_t',
    'imm:rel32': 'int32_t',
    'imm:rel8': 'int8_t',
}

# ISA name → hand-written C function name override table.
# Names not in this table use the default: x64.foo.bar → x64_foo_bar
_X64_NAME_MAP = {
    'x64.load.bd32': None,    # skip: superseded by x64.mov.rm
    'x64.store.bd32': None,   # skip: superseded by x64.mov.mr
    'x64.lea.bd32': None,     # skip: superseded by x64.lea
    'x64.int3': None,         # no hand-written counterpart
    # Combined ri wrappers are generated separately
    'x64.add.ri8': None,
    'x64.add.ri32': None,
    'x64.sub.ri8': None,
    'x64.sub.ri32': None,
    'x64.and.ri8': None,
    'x64.and.ri32': None,
    'x64.or.ri8': None,
    'x64.or.ri32': None,
    'x64.cmp.ri8': None,
    'x64.cmp.ri32': None,
    'x64.test.ri32': None,
}

# Pairs of (ri8, ri32, ext) for combined wrapper generation
_X64_RI_PAIRS = [
    ('x64.add.ri8', 'x64.add.ri32', 0, 'x64_add_ri', 'dst'),
    ('x64.sub.ri8', 'x64.sub.ri32', 5, 'x64_sub_ri', 'dst'),
    ('x64.and.ri8', 'x64.and.ri32', 4, 'x64_and_ri', 'dst'),
    ('x64.or.ri8', 'x64.or.ri32', 1, 'x64_or_ri', 'dst'),
    ('x64.cmp.ri8', 'x64.cmp.ri32', 7, 'x64_cmp_ri', 'lhs'),
]

def _gen_ri_wrapper(c_name: str, ext: int, reg_param: str) -> list[str]:
    """Generate combined add_ri/sub_ri/... wrapper with imm8/imm32 branching."""
    lines = []
    lines.append(f'void {c_name}(X64Buf *buf, X64Reg {reg_param}, int32_t imm) {{')
    lines.append(f'    XR_DCHECK(buf != NULL, "{c_name}: NULL buf");')
    lines.append(f'    x64_rex(buf, true, false, false, {reg_param} > 7);')
    lines.append(f'    if (imm >= -128 && imm <= 127) {{')
    lines.append(f'        x64_emit8(buf, 0x83);')
    lines.append(f'        x64_modrm(buf, 0x3, {ext}, (uint8_t){reg_param});')
    lines.append(f'        x64_emit8(buf, (uint8_t)(int8_t)imm);')
    lines.append(f'    }} else {{')
    lines.append(f'        x64_emit8(buf, 0x81);')
    lines.append(f'        x64_modrm(buf, 0x3, {ext}, (uint8_t){reg_param});')
    lines.append(f'        x64_emit32(buf, (uint32_t)imm);')
    lines.append(f'    }}')
    lines.append(f'}}')
    return lines

def generate_x64_impl(regclasses: list[RegClass], mcinsns: list[McInsn]) -> str:
    """Generate xm_x64_gen.c — drop-in replacement for hand-written xm_x64.c."""
    lines = []
    lines.append('/* AUTO-GENERATED by xisagen — DO NOT EDIT */')
    lines.append('/* Source: xisa/arch/x64.isa */')
    lines.append('')
    lines.append('#if defined(__x86_64__) || defined(_M_X64)')
    lines.append('')
    lines.append('#include "xm_x64.h"')
    lines.append('')

    insn_map = {m.name: m for m in mcinsns}

    for insn in mcinsns:
        # Skip instructions that are superseded or handled as ri pairs
        if insn.name in _X64_NAME_MAP and _X64_NAME_MAP[insn.name] is None:
            continue

        c_name = _x64_c_name(insn.name)
        operands = extract_operands(insn)

        # Build parameter list matching xm_x64.h signatures
        params = ['X64Buf *buf']
        for op in operands:
            type_key = f'{op.kind}:{op.subtype}' if op.subtype else op.kind
            c_type = _X64BUF_PARAM_TYPES.get(type_key, 'int32_t')
            params.append(f'{c_type} {_c_param_name(op)}')

        sig = f'void {c_name}({", ".join(params)})'
        lines.append(f'/* {insn.name} */')
        lines.append(sig + ' {')
        lines.append(f'    XR_DCHECK(buf != NULL, "{c_name}: NULL buf");')
        body = _gen_x64buf_body(insn, operands)
        lines.extend(body)
        lines.append('}')
        lines.append('')

    # Generate combined ri wrappers
    lines.append('/* ========== Combined imm8/imm32 Wrappers ========== */')
    lines.append('')
    for ri8_name, ri32_name, ext, c_name, reg_param in _X64_RI_PAIRS:
        wrapper = _gen_ri_wrapper(c_name, ext, reg_param)
        lines.extend(wrapper)
        lines.append('')

    # test_ri is special: always 32-bit, no branching
    lines.append('/* x64.test.ri32 — always imm32, no imm8 form */')
    lines.append('void x64_test_ri(X64Buf *buf, X64Reg dst, int32_t imm) {')
    lines.append('    XR_DCHECK(buf != NULL, "x64_test_ri: NULL buf");')
    lines.append('    x64_rex(buf, true, false, false, dst > 7);')
    lines.append('    x64_emit8(buf, 0xf7);')
    lines.append('    x64_modrm(buf, 0x3, 0, (uint8_t)dst);')
    lines.append('    x64_emit32(buf, (uint32_t)imm);')
    lines.append('}')
    lines.append('')

    lines.append('#endif  // __x86_64__ || _M_X64')
    lines.append('')
    return '\n'.join(lines)

# ============================================================
# L5: Typecheck — validate .isa internal consistency
# ============================================================

@dataclass
class IsaDiag:
    level: str   # "error" or "warn"
    insn: str
    msg: str

def typecheck_isa(regclasses: list[RegClass], mcinsns: list[McInsn]) -> list[IsaDiag]:
    """Validate internal consistency of parsed .isa definitions."""
    diags = []

    # Build register name set from all regclasses
    all_regs = set()
    for rc in regclasses:
        for r in rc.regs:
            all_regs.add(r)

    # Build regclass name → RegClass map
    rc_map = {rc.name: rc for rc in regclasses}

    seen_names = set()
    for insn in mcinsns:
        # Duplicate name check
        if insn.name in seen_names:
            diags.append(IsaDiag('error', insn.name, 'duplicate mcinsn name'))
        seen_names.add(insn.name)

        # min/max bytes
        if insn.min_bytes <= 0:
            diags.append(IsaDiag('error', insn.name, ':min-bytes must be > 0'))
        if insn.max_bytes < insn.min_bytes:
            diags.append(IsaDiag('error', insn.name, ':max-bytes < :min-bytes'))

        # Operand extraction
        operands = extract_operands(insn)
        op_names = {op.name for op in operands}

        # Check encoding references valid operands
        if insn.encoding:
            enc_vars = _collect_variables(insn.encoding)
            for var in enc_vars:
                if var not in op_names:
                    diags.append(IsaDiag('error', insn.name,
                                         f'encoding references undefined operand {var}'))

        # Golden bytes: at least 1 entry (warn only — memory-mode insns may skip)
        if not insn.golden_bytes:
            diags.append(IsaDiag('warn', insn.name, 'no :golden-bytes entries'))

        # Golden bytes: validate hex string format
        for regs, hex_str in insn.golden_bytes:
            hex_bytes = hex_str.split()
            for hb in hex_bytes:
                if len(hb) != 2 or not all(c in '0123456789abcdefABCDEF' for c in hb):
                    diags.append(IsaDiag('error', insn.name,
                                         f'invalid hex byte "{hb}" in :golden-bytes'))
            # Check byte count vs min/max
            n_bytes = len(hex_bytes)
            if n_bytes < insn.min_bytes or n_bytes > insn.max_bytes:
                diags.append(IsaDiag('warn', insn.name,
                                     f'golden-bytes length {n_bytes} outside '
                                     f'[{insn.min_bytes}, {insn.max_bytes}]'))

        # Golden bytes: register names should be in regclass (if regs provided)
        for regs, _ in insn.golden_bytes:
            for r in regs:
                # Skip numeric immediate values
                try:
                    int(r, 0)
                    continue
                except ValueError:
                    pass
                if r.startswith('-'):
                    try:
                        int(r, 0)
                        continue
                    except ValueError:
                        pass
                if all_regs and r not in all_regs:
                    diags.append(IsaDiag('warn', insn.name,
                                         f'golden-bytes register "{r}" not in any regclass'))

    return diags

def _collect_variables(node: SExpr) -> set[str]:
    """Recursively collect all $variable names from an S-expression tree."""
    result = set()
    if isinstance(node, SAtom):
        if node.is_variable:
            result.add(node.value)
    elif isinstance(node, SList):
        for child in node.children:
            result.update(_collect_variables(child))
    return result

# ============================================================
# CLI
# ============================================================

def cmd_ops(args: list[str]):
    if len(args) != 2:
        die("usage: xisagen.py ops <ops.def> <output.h>")
    ops = parse_ops_def(read_file(args[0]))
    if not ops:
        die(f"no ops parsed from {args[0]}")
    content = generate_ops_header(ops)
    write_file(args[1], content)
    print(f"xisagen: parsed {len(ops)} ops from {args[0]}", file=sys.stderr)
    print(f"xisagen: generated {args[1]}", file=sys.stderr)

def cmd_helpers(args: list[str]):
    if len(args) != 2:
        die("usage: xisagen.py helpers <helpers.def> <output.h>")
    helpers = parse_helpers_def(read_file(args[0]))
    if not helpers:
        die(f"no helpers parsed from {args[0]}")
    content = generate_helpers_header(helpers)
    write_file(args[1], content)
    print(f"xisagen: parsed {len(helpers)} helpers from {args[0]}", file=sys.stderr)
    print(f"xisagen: generated {args[1]}", file=sys.stderr)

def cmd_isa(args: list[str]):
    if len(args) < 1:
        die("usage: xisagen.py isa <isa.isa> [output_dir]")
    path = args[0]
    output_dir = args[1] if len(args) > 1 else None
    regclasses, mcinsns = load_isa(path)
    arch = _detect_arch(mcinsns)
    print(f"xisagen: parsed {path}: {len(regclasses)} regclasses, {len(mcinsns)} mcinsns ({arch})",
          file=sys.stderr)

    # Validate golden bytes
    total_golden = sum(len(m.golden_bytes) for m in mcinsns)
    total_golden_asm = sum(len(m.golden_asm) for m in mcinsns)
    print(f"xisagen: {total_golden} golden-bytes, {total_golden_asm} golden-asm entries",
          file=sys.stderr)

    for insn in mcinsns:
        if insn.min_bytes <= 0:
            die(f"{path}: {insn.name}: missing :min-bytes")
        if insn.max_bytes < insn.min_bytes:
            die(f"{path}: {insn.name}: :max-bytes < :min-bytes")

    # Typecheck
    diags = typecheck_isa(regclasses, mcinsns)
    errors = [d for d in diags if d.level == 'error']
    warns = [d for d in diags if d.level == 'warn']
    for d in warns:
        print(f"xisagen: warn: {d.insn}: {d.msg}", file=sys.stderr)
    for d in errors:
        print(f"xisagen: error: {d.insn}: {d.msg}", file=sys.stderr)
    if errors:
        die(f"{len(errors)} typecheck error(s) in {path}")

    # Generate emit header if output_dir given
    if output_dir:
        header = generate_emit_header(arch, regclasses, mcinsns)
        out_path = os.path.join(output_dir, f'xisa_{arch}_emit.h')
        write_file(out_path, header)
        print(f"xisagen: generated {out_path}", file=sys.stderr)

def cmd_x64impl(args: list[str]):
    """Generate xm_x64_gen.c from x64.isa.
    Usage: xisagen x64impl <isa-file> <output-dir>"""
    if len(args) < 2:
        die('usage: xisagen x64impl <isa-file> <output-dir>')
    path, output_dir = args[0], args[1]
    regclasses, mcinsns = load_isa(path)
    impl = generate_x64_impl(regclasses, mcinsns)
    out_path = os.path.join(output_dir, 'xm_x64_gen.c')
    write_file(out_path, impl)
    print(f"xisagen: generated {out_path}", file=sys.stderr)

def cmd_test(args: list[str]):
    """Run self-tests."""
    print("xisagen self-test:", file=sys.stderr)
    _test_sexpr_parser()
    _test_ops_parser()
    _test_helpers_parser()
    _test_isa_parser()
    _test_emit_generator()
    _test_typecheck()
    _test_error_paths()
    print("All xisagen self-tests passed.", file=sys.stderr)

def _test_sexpr_parser():
    print("  test_sexpr_parser...", end='', file=sys.stderr)
    tokens = tokenize_sexpr('(add 1 2)')
    forms = parse_sexpr(tokens)
    assert len(forms) == 1
    assert isinstance(forms[0], SList)
    assert len(forms[0].children) == 3
    assert isinstance(forms[0].children[0], SAtom) and forms[0].children[0].value == 'add'
    assert forms[0].children[1].int_value == 1
    assert forms[0].children[2].int_value == 2

    # Keywords and variables
    tokens = tokenize_sexpr('(:key $var "str" 0xFF 0b1101)')
    forms = parse_sexpr(tokens)
    lst = forms[0]
    assert lst.children[0].is_keyword
    assert lst.children[1].is_variable
    assert lst.children[2].is_string
    assert lst.children[3].int_value == 255
    assert lst.children[4].int_value == 13

    # Comments
    tokens = tokenize_sexpr('foo ; comment\nbar')
    forms = parse_sexpr(tokens)
    assert len(forms) == 2

    # Nested
    tokens = tokenize_sexpr('(a (b c) d)')
    forms = parse_sexpr(tokens)
    assert len(forms[0].children) == 3
    assert isinstance(forms[0].children[1], SList)

    # Keyword lookup
    tokens = tokenize_sexpr('(foo :min-bytes 3 :name "test")')
    forms = parse_sexpr(tokens)
    lst = forms[0]
    assert lst.get_kw_int(':min-bytes') == 3
    assert lst.get_kw_str(':name') == 'test'

    print(" PASS", file=sys.stderr)

def _test_ops_parser():
    print("  test_ops_parser...", end='', file=sys.stderr)
    text = 'XM_OP(ADD, ARITH, 2, I64, COMMUTATIVE)\nXM_OP(RET, CF, 0, VOID, NONE)\n'
    ops = parse_ops_def(text)
    assert len(ops) == 2
    assert ops[0].name == 'ADD' and ops[0].cls == 'ARITH'
    assert ops[0].flags == ['COMMUTATIVE']
    assert ops[1].flags == []
    header = generate_ops_header(ops)
    assert 'XM_ADD = 0' in header
    assert 'XM_RET = 1' in header
    print(" PASS", file=sys.stderr)

def _test_helpers_parser():
    print("  test_helpers_parser...", end='', file=sys.stderr)
    text = 'XM_HELPER(call_func, 0, TAGGED, GC|DEOPT)\nXM_HELPER(rt_add, 2, TAGGED, GC)\n'
    helpers = parse_helpers_def(text)
    assert len(helpers) == 2
    assert helpers[0].name == 'call_func'
    assert helpers[0].flags == ['GC', 'DEOPT']
    header = generate_helpers_header(helpers)
    assert 'XM_HELPER_call_func = 0' in header
    assert 'XM_HF_GC | XM_HF_DEOPT' in header
    print(" PASS", file=sys.stderr)

def _test_isa_parser():
    print("  test_isa_parser...", end='', file=sys.stderr)
    text = '''
    (define-regclass x64.gpr64
      :regs (rax rcx rdx rbx)
      :encoding-bits 4)
    (define-mcinsn x64.add.rr
      :operands       (($dst reg:gpr64) ($src reg:gpr64))
      :constraints    ((same $dst $src))
      :encoding       (rex.w 0x01 (modrm 0b11 $src $dst))
      :flags          ()
      :min-bytes      3
      :max-bytes      3
      :golden-bytes   (((rax rbx) "48 01 d8"))
      :golden-asm     (((rax rbx) "add rax, rbx"))
      :external-reference llvm-mc)
    '''
    tokens = tokenize_sexpr(text, 'test.isa')
    forms = parse_sexpr(tokens, 'test.isa')
    assert len(forms) == 2

    # Extract
    rc = extract_regclass(forms[0])
    assert rc.name == 'x64.gpr64'
    assert len(rc.regs) == 4
    assert rc.encoding_bits == 4

    insn = extract_mcinsn(forms[1])
    assert insn.name == 'x64.add.rr'
    assert insn.min_bytes == 3
    assert insn.max_bytes == 3
    assert len(insn.golden_bytes) == 1
    assert insn.golden_bytes[0] == (['rax', 'rbx'], '48 01 d8')
    assert insn.golden_asm[0] == (['rax', 'rbx'], 'add rax, rbx')
    assert insn.external_ref == 'llvm-mc'

    print(" PASS", file=sys.stderr)

def _test_emit_generator():
    print("  test_emit_generator...", end='', file=sys.stderr)
    # x64 emit
    text_x64 = '''
    (define-regclass x64.gpr64
      :regs (rax rcx rdx rbx rsp rbp rsi rdi r8 r9 r10 r11 r12 r13 r14 r15)
      :encoding-bits 4)
    (define-mcinsn x64.nop
      :operands () :constraints () :encoding (0x90) :flags ()
      :min-bytes 1 :max-bytes 1 :golden-bytes ((() "90")))
    (define-mcinsn x64.add.rr
      :operands (($dst reg:gpr64) ($src reg:gpr64))
      :constraints ((same $dst $src))
      :encoding (rex.w 0x01 (modrm 0b11 $src $dst))
      :flags () :min-bytes 3 :max-bytes 3
      :golden-bytes (((rax rbx) "48 01 d8")))
    '''
    rc, insns = load_isa_text(text_x64, 'test_x64')
    header = generate_emit_header('x64', rc, insns)
    assert 'xisa_emit_x64_nop' in header
    assert 'xisa_emit_x64_add_rr' in header
    assert 'static inline int' in header
    assert '0x48' in header  # REX.W
    assert '0x90' in header  # NOP opcode

    # arm64 emit
    text_arm64 = '''
    (define-regclass arm64.gpr64
      :regs (x0 x1 x2) :encoding-bits 5)
    (define-mcinsn arm64.add.rrr
      :operands (($rd reg:gpr64) ($rn reg:gpr64) ($rm reg:gpr64))
      :constraints () :flags () :min-bytes 4 :max-bytes 4
      :encoding (0x8b000000 (field 0 5 $rd) (field 5 5 $rn) (field 16 5 $rm))
      :golden-bytes (((x0 x1 x2) "20 00 02 8b")))
    '''
    rc, insns = load_isa_text(text_arm64, 'test_arm64')
    header = generate_emit_header('arm64', rc, insns)
    assert 'xisa_emit_arm64_add_rrr' in header
    assert '0x8b000000u' in header

    # riscv64 emit
    text_rv = '''
    (define-regclass riscv64.gpr :regs (x0 x1 x2) :encoding-bits 5)
    (define-mcinsn riscv64.add
      :operands (($rd reg:gpr) ($rs1 reg:gpr) ($rs2 reg:gpr))
      :constraints () :flags () :min-bytes 4 :max-bytes 4
      :encoding (r-type 0x33 0x0 0x00 $rd $rs1 $rs2)
      :golden-bytes (((x1 x2 x3) "b3 00 31 00")))
    '''
    rc, insns = load_isa_text(text_rv, 'test_rv')
    header = generate_emit_header('riscv64', rc, insns)
    assert 'xisa_emit_riscv64_add' in header
    assert 'r-type' not in header  # encoding format should not appear in output

    print(" PASS", file=sys.stderr)

def _test_typecheck():
    print("  test_typecheck...", end='', file=sys.stderr)

    # Valid definition — should produce no errors
    text_ok = '''
    (define-regclass x64.gpr64
      :regs (rax rcx rdx rbx) :encoding-bits 4)
    (define-mcinsn x64.add.rr
      :operands (($dst reg:gpr64) ($src reg:gpr64))
      :constraints () :flags () :min-bytes 3 :max-bytes 3
      :encoding (rex.w 0x01 (modrm 0b11 $src $dst))
      :golden-bytes (((rax rbx) "48 01 d8")))
    '''
    rc, insns = load_isa_text(text_ok)
    diags = typecheck_isa(rc, insns)
    errors = [d for d in diags if d.level == 'error']
    assert len(errors) == 0, f"expected 0 errors, got {errors}"

    # Undefined operand in encoding
    text_bad_ref = '''
    (define-mcinsn x64.bad
      :operands (($dst reg:gpr64))
      :constraints () :flags () :min-bytes 3 :max-bytes 3
      :encoding (rex.w 0x01 (modrm 0b11 $ghost $dst))
      :golden-bytes (((rax) "48 01 c0")))
    '''
    _, insns2 = load_isa_text(text_bad_ref)
    diags2 = typecheck_isa([], insns2)
    errs2 = [d for d in diags2 if d.level == 'error' and 'undefined operand' in d.msg]
    assert len(errs2) == 1, f"expected 1 undefined-operand error, got {errs2}"

    # Duplicate name
    text_dup = '''
    (define-mcinsn x64.dup :operands () :constraints () :flags ()
      :min-bytes 1 :max-bytes 1 :encoding (0x90) :golden-bytes ((() "90")))
    (define-mcinsn x64.dup :operands () :constraints () :flags ()
      :min-bytes 1 :max-bytes 1 :encoding (0x90) :golden-bytes ((() "90")))
    '''
    _, insns3 = load_isa_text(text_dup)
    diags3 = typecheck_isa([], insns3)
    dup_errs = [d for d in diags3 if 'duplicate' in d.msg]
    assert len(dup_errs) == 1

    # max < min
    text_range = '''
    (define-mcinsn x64.bad_range :operands () :constraints () :flags ()
      :min-bytes 5 :max-bytes 3 :encoding (0x90) :golden-bytes ((() "90")))
    '''
    _, insns4 = load_isa_text(text_range)
    diags4 = typecheck_isa([], insns4)
    range_errs = [d for d in diags4 if d.level == 'error' and 'max-bytes' in d.msg]
    assert len(range_errs) == 1

    # Bad hex in golden-bytes
    text_hex = '''
    (define-mcinsn x64.bad_hex :operands () :constraints () :flags ()
      :min-bytes 1 :max-bytes 1 :encoding (0x90) :golden-bytes ((() "ZZ")))
    '''
    _, insns5 = load_isa_text(text_hex)
    diags5 = typecheck_isa([], insns5)
    hex_errs = [d for d in diags5 if d.level == 'error' and 'invalid hex' in d.msg]
    assert len(hex_errs) == 1

    print(" PASS", file=sys.stderr)

def _test_error_paths():
    print("  test_error_paths...", end='', file=sys.stderr)

    # Unterminated string
    try:
        tokenize_sexpr('"hello', 'test')
        assert False, "should have died"
    except SystemExit:
        pass

    # Unclosed paren
    try:
        tokens = tokenize_sexpr('(a b', 'test')
        parse_sexpr(tokens, 'test')
        assert False, "should have died"
    except SystemExit:
        pass

    # Unexpected )
    try:
        tokens = tokenize_sexpr(')', 'test')
        parse_sexpr(tokens, 'test')
        assert False, "should have died"
    except SystemExit:
        pass

    # Unexpected character
    try:
        tokenize_sexpr('`', 'test')
        assert False, "should have died"
    except SystemExit:
        pass

    print(" PASS", file=sys.stderr)


def main():
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    cmd = sys.argv[1]
    args = sys.argv[2:]

    commands = {
        'ops': cmd_ops,
        'helpers': cmd_helpers,
        'isa': cmd_isa,
        'x64impl': cmd_x64impl,
        'test': cmd_test,
    }

    if cmd not in commands:
        die(f"unknown command '{cmd}'. Available: {', '.join(commands)}")

    commands[cmd](args)


if __name__ == '__main__':
    main()
