/* AUTO-GENERATED by programgen - DO NOT EDIT */
/* Source: xisa/program/xi-source-projection.json */
#ifndef XR_PROGRAM_XI_PROJECTION_GEN_H
#define XR_PROGRAM_XI_PROJECTION_GEN_H

#include "core/xr_core_spec_gen.h"
#include <stdbool.h>
#include <stdint.h>

#define XR_PROGRAM_XI_ANY_RESULT_TYPE UINT16_MAX

typedef enum XrProgramXiProjectionKind {
    XR_PROGRAM_XI_PROJECTION_CONSTANT = 1,
    XR_PROGRAM_XI_PROJECTION_BINARY_ARITHMETIC = 2,
    XR_PROGRAM_XI_PROJECTION_COMPARE = 3,
    XR_PROGRAM_XI_PROJECTION_SEALED_DIRECT_CALL = 4,
    XR_PROGRAM_XI_PROJECTION_AGGREGATE_CONSTRUCT = 5,
    XR_PROGRAM_XI_PROJECTION_AGGREGATE_PROJECT = 6,
    XR_PROGRAM_XI_PROJECTION_AGGREGATE_UPDATE = 7,
    XR_PROGRAM_XI_PROJECTION_VARIANT_CONSTRUCT = 8,
    XR_PROGRAM_XI_PROJECTION_VARIANT_TEST = 9,
    XR_PROGRAM_XI_PROJECTION_VARIANT_PROJECT = 10,
    XR_PROGRAM_XI_PROJECTION_OWNER_COPY = 11,
    XR_PROGRAM_XI_PROJECTION_OWNER_MOVE = 12,
    XR_PROGRAM_XI_PROJECTION_PLACE_LOCAL = 13,
    XR_PROGRAM_XI_PROJECTION_PLACE_LOAD = 14,
    XR_PROGRAM_XI_PROJECTION_PLACE_STORE = 15,
    XR_PROGRAM_XI_PROJECTION_CALLABLE_PACK = 16,
} XrProgramXiProjectionKind;

typedef struct XrProgramXiProjection {
    uint16_t core_operation_id;
    uint16_t result_type_id;
    uint32_t immediate_u32;
    XrProgramXiProjectionKind kind;
} XrProgramXiProjection;

bool xr_program_xi_projection(uint16_t xi_operation, uint16_t result_type_id,
                              XrProgramXiProjection *projection_out);
bool xr_program_xi_operation_contract(uint16_t xi_operation, uint32_t *effect_mask_out,
                                      uint32_t *capability_mask_out);
bool xr_program_xi_value_is_materialized(uint16_t xi_operation);

#endif /* XR_PROGRAM_XI_PROJECTION_GEN_H */
