/* AUTO-GENERATED by programgen - DO NOT EDIT */
/* Source: xisa/program/xi-source-projection.json */
#include "program/xr_program_xi_projection_gen.h"
#include "core/xr_core_spec_gen.h"
#include "ir/xi.h"

#define XR_PROGRAM_XI_INTEGER_RESULT_TYPE UINT16_C(65534)

typedef struct XrProgramXiProjectionRow {
    uint16_t xi_operation;
    uint16_t result_type_id;
    uint16_t core_operation_id;
    uint32_t immediate_u32;
    XrProgramXiProjectionKind kind;
} XrProgramXiProjectionRow;

typedef struct XrProgramXiSemanticProjectionRow {
    uint16_t xi_operation;
    uint8_t xi_existential_kind;
    uint16_t core_operation_id;
    XrProgramXiSemanticProjectionKind kind;
    XrProgramXiFirstOperandPolicy first_operand_policy;
} XrProgramXiSemanticProjectionRow;

static const XrProgramXiProjectionRow xr_program_xi_projection_rows[] = {
    {
        XI_CONST,
        XR_CORE_TYPE_I64,
        XR_CORE_OP_CORE_CONSTANT_I64,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_CONSTANT,
    },
    {
        XI_CONST,
        XR_CORE_TYPE_F64,
        XR_CORE_OP_CORE_CONSTANT_F64,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_CONSTANT,
    },
    {
        XI_CONST,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_CONSTANT_BOOL,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_CONSTANT,
    },
    {
        XI_CONST,
        XR_CORE_TYPE_STRING,
        XR_CORE_OP_CORE_CONSTANT_STRING,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_CONSTANT,
    },
    {
        XI_CONST,
        XR_CORE_TYPE_RUNE,
        XR_CORE_OP_CORE_CONSTANT_RUNE,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_CONSTANT,
    },
    {
        XI_CONST,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_CONSTANT_I64,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_CONSTANT,
    },
    {
        XI_ADD,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_ADD_I64,
        UINT32_C(1),
        XR_PROGRAM_XI_PROJECTION_INTEGER_WRAPPING,
    },
    {
        XI_SUB,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_SUB_I64,
        UINT32_C(1),
        XR_PROGRAM_XI_PROJECTION_INTEGER_WRAPPING,
    },
    {
        XI_MUL,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_MUL_I64,
        UINT32_C(1),
        XR_PROGRAM_XI_PROJECTION_INTEGER_WRAPPING,
    },
    {
        XI_DIV,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_DIVMOD,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_DIVMOD,
    },
    {
        XI_MOD,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_DIVMOD,
        UINT32_C(1),
        XR_PROGRAM_XI_PROJECTION_INTEGER_DIVMOD,
    },
    {
        XI_NOT,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_LOGICAL_NOT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_LOGICAL_UNARY,
    },
    {
        XI_BAND,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_LOGICAL_AND,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_LOGICAL_BINARY,
    },
    {
        XI_BOR,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_LOGICAL_OR,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_LOGICAL_BINARY,
    },
    {
        XI_EQ,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_COMPARE_I64,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_COMPARE,
    },
    {
        XI_NE,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_COMPARE_I64,
        UINT32_C(1),
        XR_PROGRAM_XI_PROJECTION_COMPARE,
    },
    {
        XI_LT,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_COMPARE_I64,
        UINT32_C(2),
        XR_PROGRAM_XI_PROJECTION_COMPARE,
    },
    {
        XI_LE,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_COMPARE_I64,
        UINT32_C(3),
        XR_PROGRAM_XI_PROJECTION_COMPARE,
    },
    {
        XI_GT,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_COMPARE_I64,
        UINT32_C(4),
        XR_PROGRAM_XI_PROJECTION_COMPARE,
    },
    {
        XI_GE,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_COMPARE_I64,
        UINT32_C(5),
        XR_PROGRAM_XI_PROJECTION_COMPARE,
    },
    {
        XI_CALL,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_CALL_SEALED_DIRECT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_SEALED_DIRECT_CALL,
    },
    {
        XI_CALL_METHOD,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_CALL_SEALED_DIRECT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_SEALED_DIRECT_CALL,
    },
    {
        XI_CALL_METHOD_DIRECT,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_CALL_SEALED_DIRECT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_SEALED_DIRECT_CALL,
    },
    {
        XI_TUPLE_NEW,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_AGGREGATE_CONSTRUCT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_AGGREGATE_CONSTRUCT,
    },
    {
        XI_TUPLE_GET,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_AGGREGATE_PROJECT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_AGGREGATE_PROJECT,
    },
    {
        XI_AGG_GET,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_AGGREGATE_PROJECT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_AGGREGATE_PROJECT,
    },
    {
        XI_LOAD_UPVAL,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_AGGREGATE_PROJECT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_AGGREGATE_PROJECT,
    },
    {
        XI_AGG_UPDATE,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_AGGREGATE_UPDATE,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_AGGREGATE_UPDATE,
    },
    {
        XI_VARIANT_CONSTRUCT,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_VARIANT_CONSTRUCT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_VARIANT_CONSTRUCT,
    },
    {
        XI_SUM_INJECT,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_VARIANT_CONSTRUCT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_VARIANT_CONSTRUCT,
    },
    {
        XI_VARIANT_TEST,
        XR_CORE_TYPE_BOOL,
        XR_CORE_OP_CORE_VARIANT_TEST,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_VARIANT_TEST,
    },
    {
        XI_VARIANT_PROJECT,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_VARIANT_PROJECT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_VARIANT_PROJECT,
    },
    {
        XI_CALL_BUILTIN,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_OWNER_COPY,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_OWNER_COPY,
    },
    {
        XI_COPY,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_OWNER_COPY,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_OWNER_COPY,
    },
    {
        XI_SOURCE_MOVE,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_OWNER_MOVE,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_OWNER_MOVE,
    },
    {
        XI_OWNER_FORWARD,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_OWNER_MOVE,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_OWNER_MOVE,
    },
    {
        XI_LOCAL_ADDR,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_PLACE_LOCAL,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_PLACE_LOCAL,
    },
    {
        XI_PLACE_LOAD,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_PLACE_LOAD,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_PLACE_LOAD,
    },
    {
        XI_PLACE_STORE,
        XR_CORE_TYPE_VOID,
        XR_CORE_OP_CORE_PLACE_STORE,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_PLACE_STORE,
    },
    {
        XI_CLOSURE_NEW,
        XR_PROGRAM_XI_ANY_RESULT_TYPE,
        XR_CORE_OP_CORE_CALLABLE_PACK,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_CALLABLE_PACK,
    },
    {
        XI_TARGET_POINTER_BITS,
        XR_CORE_TYPE_U16,
        XR_CORE_OP_CORE_TARGET_POINTER_WIDTH,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_TARGET_QUERY,
    },
    {
        XI_TARGET_OPERATING_SYSTEM,
        XR_CORE_TYPE_TARGET_OS,
        XR_CORE_OP_CORE_TARGET_OPERATING_SYSTEM,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_TARGET_QUERY,
    },
    {
        XI_TARGET_ARCHITECTURE,
        XR_CORE_TYPE_TARGET_ARCH,
        XR_CORE_OP_CORE_TARGET_ARCHITECTURE,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_TARGET_QUERY,
    },
    {
        XI_TARGET_NATIVE_ABI,
        XR_CORE_TYPE_TARGET_ABI,
        XR_CORE_OP_CORE_TARGET_NATIVE_ABI,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_TARGET_QUERY,
    },
    {
        XI_TARGET_ENDIANNESS,
        XR_CORE_TYPE_TARGET_ENDIAN,
        XR_CORE_OP_CORE_TARGET_ENDIANNESS,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_TARGET_QUERY,
    },
    {
        XI_YIELD,
        XR_CORE_TYPE_VOID,
        XR_CORE_OP_CORE_COROUTINE_YIELD,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_COROUTINE_YIELD,
    },
    {
        XI_PRINT,
        XR_CORE_TYPE_VOID,
        XR_CORE_OP_CORE_OUTPUT_GROUP,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_OUTPUT_GROUP,
    },
    {
        XI_STR_CONCAT,
        XR_CORE_TYPE_STRING,
        XR_CORE_OP_CORE_STRING_CONCAT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_STRING_CONCAT,
    },
    {
        XI_CONVERT,
        XR_CORE_TYPE_STRING,
        XR_CORE_OP_CORE_STRING_FROM_SCALAR,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_STRING_FROM_SCALAR,
    },
    {
        XI_CONVERT,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_NARROW_I8,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_NARROW_U8,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_NARROW_I16,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_NARROW_U16,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_NARROW_I32,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_NARROW_U32,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_WIDEN_I8,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_WIDEN_U8,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_WIDEN_I16,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_WIDEN_U16,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_WIDEN_I32,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_WIDEN_U32,
        XR_PROGRAM_XI_INTEGER_RESULT_TYPE,
        XR_CORE_OP_CORE_INTEGER_CONVERT,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_INTEGER_CONVERT,
    },
    {
        XI_LEN,
        XR_CORE_TYPE_I64,
        XR_CORE_OP_CORE_SEQUENCE_LENGTH,
        UINT32_C(0),
        XR_PROGRAM_XI_PROJECTION_SEQUENCE_LENGTH,
    },
};

static const XrProgramXiSemanticProjectionRow
    xr_program_xi_semantic_projection_rows[] = {
    {
        XI_COPY,
        XI_EXISTENTIAL_PACK,
        XR_CORE_OP_CORE_EXISTENTIAL_PACK,
        XR_PROGRAM_XI_SEMANTIC_EXISTENTIAL_PACK,
        XR_PROGRAM_XI_FIRST_OPERAND_CONCRETE_BY_INTERFACE_USE,
    },
    {
        XI_COPY,
        XI_EXISTENTIAL_REBORROW_READ,
        XR_CORE_OP_CORE_EXISTENTIAL_REBORROW_READ,
        XR_PROGRAM_XI_SEMANTIC_EXISTENTIAL_REBORROW_READ,
        XR_PROGRAM_XI_FIRST_OPERAND_BORROW,
    },
    {
        XI_IS,
        XI_EXISTENTIAL_TEST,
        XR_CORE_OP_CORE_EXISTENTIAL_TEST,
        XR_PROGRAM_XI_SEMANTIC_EXISTENTIAL_TEST,
        XR_PROGRAM_XI_FIRST_OPERAND_BORROW,
    },
    {
        XI_AS,
        XI_EXISTENTIAL_PROJECT,
        XR_CORE_OP_CORE_EXISTENTIAL_PROJECT,
        XR_PROGRAM_XI_SEMANTIC_EXISTENTIAL_PROJECT,
        XR_PROGRAM_XI_FIRST_OPERAND_EXISTENTIAL_BY_INTERFACE_USE,
    },
    {
        XI_CALL_METHOD,
        XI_EXISTENTIAL_WITNESS_DIRECT,
        XR_CORE_OP_CORE_CALL_WITNESS_DIRECT,
        XR_PROGRAM_XI_SEMANTIC_WITNESS_DIRECT,
        XR_PROGRAM_XI_FIRST_OPERAND_RECEIVER_BY_INTERFACE_USE,
    },
    {
        XI_CALL_METHOD_DIRECT,
        XI_EXISTENTIAL_WITNESS_DIRECT,
        XR_CORE_OP_CORE_CALL_WITNESS_DIRECT,
        XR_PROGRAM_XI_SEMANTIC_WITNESS_DIRECT,
        XR_PROGRAM_XI_FIRST_OPERAND_RECEIVER_BY_INTERFACE_USE,
    },
    {
        XI_CALL_METHOD,
        XI_EXISTENTIAL_WITNESS_INVOKE,
        XR_CORE_OP_CORE_CALL_WITNESS_INVOKE,
        XR_PROGRAM_XI_SEMANTIC_WITNESS_INVOKE,
        XR_PROGRAM_XI_FIRST_OPERAND_RECEIVER_BY_INTERFACE_USE,
    },
    {
        XI_CALL_METHOD_DIRECT,
        XI_EXISTENTIAL_WITNESS_INVOKE,
        XR_CORE_OP_CORE_CALL_WITNESS_INVOKE,
        XR_PROGRAM_XI_SEMANTIC_WITNESS_INVOKE,
        XR_PROGRAM_XI_FIRST_OPERAND_RECEIVER_BY_INTERFACE_USE,
    },
};

bool xr_program_xi_projection(uint16_t xi_operation, uint16_t result_type_id,
                              XrProgramXiProjection *projection_out) {
    if (!projection_out)
        return false;
    for (uint32_t index = 0;
         index < sizeof(xr_program_xi_projection_rows) / sizeof(xr_program_xi_projection_rows[0]);
         ++index) {
        const XrProgramXiProjectionRow *row = &xr_program_xi_projection_rows[index];
        if (row->xi_operation != xi_operation)
            continue;
        if (row->result_type_id == XR_PROGRAM_XI_INTEGER_RESULT_TYPE) {
            if (!xr_core_spec_integer_type(result_type_id))
                continue;
        } else if (row->result_type_id != XR_PROGRAM_XI_ANY_RESULT_TYPE &&
                   row->result_type_id != result_type_id) {
            continue;
        }
        projection_out->core_operation_id = row->core_operation_id;
        projection_out->result_type_id = result_type_id;
        projection_out->immediate_u32 = row->immediate_u32;
        projection_out->kind = row->kind;
        return true;
    }
    return false;
}

bool xr_program_xi_semantic_projection(
    uint16_t xi_operation, uint8_t xi_existential_kind,
    XrProgramXiSemanticProjection *projection_out) {
    if (!projection_out || xi_existential_kind == XI_EXISTENTIAL_NONE)
        return false;
    for (uint32_t index = 0;
         index < sizeof(xr_program_xi_semantic_projection_rows) /
                     sizeof(xr_program_xi_semantic_projection_rows[0]);
         ++index) {
        const XrProgramXiSemanticProjectionRow *row =
            &xr_program_xi_semantic_projection_rows[index];
        if (row->xi_operation != xi_operation ||
            row->xi_existential_kind != xi_existential_kind)
            continue;
        projection_out->core_operation_id = row->core_operation_id;
        projection_out->kind = row->kind;
        projection_out->first_operand_policy = row->first_operand_policy;
        return true;
    }
    return false;
}

bool xr_program_xi_semantic_operation_kind(
    uint16_t core_operation_id, XrProgramXiSemanticProjectionKind *kind_out) {
    if (!kind_out)
        return false;
    bool found = false;
    XrProgramXiSemanticProjectionKind kind = 0;
    for (uint32_t index = 0;
         index < sizeof(xr_program_xi_semantic_projection_rows) /
                     sizeof(xr_program_xi_semantic_projection_rows[0]);
         ++index) {
        const XrProgramXiSemanticProjectionRow *row =
            &xr_program_xi_semantic_projection_rows[index];
        if (row->core_operation_id != core_operation_id)
            continue;
        if (found && kind != row->kind)
            return false;
        found = true;
        kind = row->kind;
    }
    if (!found)
        return false;
    *kind_out = kind;
    return true;
}

bool xr_program_xi_semantic_first_operand_consumption(uint16_t core_operation_id,
                                                      uint8_t interface_use_kind,
                                                      bool *consumed_out) {
    if (!consumed_out)
        return false;
    bool found = false;
    XrProgramXiFirstOperandPolicy policy = 0;
    for (uint32_t index = 0;
         index < sizeof(xr_program_xi_semantic_projection_rows) /
                     sizeof(xr_program_xi_semantic_projection_rows[0]);
         ++index) {
        const XrProgramXiSemanticProjectionRow *row =
            &xr_program_xi_semantic_projection_rows[index];
        if (row->core_operation_id != core_operation_id)
            continue;
        if (found && policy != row->first_operand_policy)
            return false;
        found = true;
        policy = row->first_operand_policy;
    }
    if (!found || interface_use_kind < XI_INTERFACE_USE_READ ||
        interface_use_kind > XI_INTERFACE_USE_OWNED_STORAGE)
        return false;
    switch (policy) {
        case XR_PROGRAM_XI_FIRST_OPERAND_BORROW:
            *consumed_out = false;
            return true;
        case XR_PROGRAM_XI_FIRST_OPERAND_CONCRETE_BY_INTERFACE_USE:
        case XR_PROGRAM_XI_FIRST_OPERAND_EXISTENTIAL_BY_INTERFACE_USE:
            *consumed_out = interface_use_kind == XI_INTERFACE_USE_MOVE ||
                            interface_use_kind == XI_INTERFACE_USE_OWNED_STORAGE;
            return true;
        case XR_PROGRAM_XI_FIRST_OPERAND_RECEIVER_BY_INTERFACE_USE:
            if (interface_use_kind == XI_INTERFACE_USE_OWNED_STORAGE)
                return false;
            *consumed_out = interface_use_kind == XI_INTERFACE_USE_MOVE;
            return true;
        default:
            return false;
    }
}

bool xr_program_xi_operation_contract(uint16_t xi_operation, uint32_t *effect_mask_out,
                                      uint32_t *capability_mask_out) {
    if (!effect_mask_out || !capability_mask_out)
        return false;
    bool found = false;
    uint32_t effects = 0u;
    uint32_t capabilities = 0u;
    for (uint32_t index = 0;
         index < sizeof(xr_program_xi_projection_rows) / sizeof(xr_program_xi_projection_rows[0]);
         ++index) {
        const XrProgramXiProjectionRow *row = &xr_program_xi_projection_rows[index];
        if (row->xi_operation != xi_operation)
            continue;
        const XrCoreOperationSpec *operation =
            xr_core_spec_operation_by_id(row->core_operation_id);
        if (!operation)
            return false;
        if (found && (effects != operation->effect_mask ||
                      capabilities != operation->capability_mask))
            return false;
        found = true;
        effects = operation->effect_mask;
        capabilities = operation->capability_mask;
    }
    if (!found)
        return false;
    *effect_mask_out = effects;
    *capability_mask_out = capabilities;
    return true;
}

bool xr_program_xi_semantic_operation_contract(uint16_t xi_operation,
                                                uint8_t xi_existential_kind,
                                                uint32_t *effect_mask_out,
                                                uint32_t *capability_mask_out) {
    if (!effect_mask_out || !capability_mask_out)
        return false;
    XrProgramXiSemanticProjection projection;
    if (!xr_program_xi_semantic_projection(xi_operation, xi_existential_kind,
                                           &projection))
        return false;
    const XrCoreOperationSpec *operation =
        xr_core_spec_operation_by_id(projection.core_operation_id);
    if (!operation)
        return false;
    *effect_mask_out = operation->effect_mask;
    *capability_mask_out = operation->capability_mask;
    return true;
}

bool xr_program_xi_value_is_materialized(uint16_t xi_operation) {
    for (uint32_t index = 0;
         index < sizeof(xr_program_xi_projection_rows) / sizeof(xr_program_xi_projection_rows[0]);
         ++index) {
        if (xr_program_xi_projection_rows[index].xi_operation == xi_operation)
            return true;
    }
    return xi_operation == XI_PARAM || xi_operation == XI_PHI;
}
