# Shared registration for the production build and isolated allocator tests.
get_filename_component(XR_RESOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
add_library(compile_resources_production OBJECT "${XR_RESOURCE_ROOT}/src/base/xcompile_resources.c")
add_executable(test_compile_resources "${CMAKE_CURRENT_LIST_DIR}/test_compile_resources.c")
target_include_directories(test_compile_resources PRIVATE "${XR_RESOURCE_ROOT}/src")
foreach(resource_target compile_resources_production test_compile_resources)
    target_compile_features(${resource_target} PRIVATE c_std_11)
    if(MSVC)
        target_compile_definitions(${resource_target} PRIVATE _CRT_SECURE_NO_WARNINGS)
        target_compile_options(${resource_target} PRIVATE /W4 /WX /utf-8)
    else()
        target_compile_options(${resource_target} PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
endforeach()
add_test(NAME test_compile_resources COMMAND test_compile_resources)
set_tests_properties(test_compile_resources PROPERTIES LABELS "unit;compiler;ownership;budget")
