# Shared registration for the production build and isolated allocator tests.
get_filename_component(XR_RESOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
add_library(compile_resources_production OBJECT "${XR_RESOURCE_ROOT}/src/base/xcompile_resources.c")
add_executable(test_compile_resources "${CMAKE_CURRENT_LIST_DIR}/test_compile_resources.c")
add_executable(test_compile_resources_concurrency "${CMAKE_CURRENT_LIST_DIR}/test_compile_resources_concurrency.c")
add_executable(test_compile_resources_scan "${CMAKE_CURRENT_LIST_DIR}/test_compile_resources_scan.c")
foreach(resource_target compile_resources_production test_compile_resources test_compile_resources_concurrency test_compile_resources_scan)
    target_include_directories(${resource_target} PRIVATE "${XR_RESOURCE_ROOT}/src")
    target_compile_features(${resource_target} PRIVATE c_std_11)
    if(MSVC)
        target_compile_definitions(${resource_target} PRIVATE _CRT_SECURE_NO_WARNINGS)
        target_compile_options(${resource_target} PRIVATE /W4 /WX /utf-8)
        if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${resource_target} PRIVATE /experimental:c11atomics)
        endif()
    else()
        target_compile_options(${resource_target} PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
endforeach()
if(NOT WIN32)
    find_package(Threads REQUIRED)
    target_link_libraries(test_compile_resources_concurrency PRIVATE Threads::Threads)
    target_link_libraries(test_compile_resources_scan PRIVATE Threads::Threads)
endif()
add_test(NAME test_compile_resources COMMAND test_compile_resources)
add_test(NAME test_compile_resources_concurrency COMMAND test_compile_resources_concurrency)
set_tests_properties(test_compile_resources_concurrency PROPERTIES LABELS "unit;compiler;ownership;budget;concurrency" TIMEOUT 60)
set_tests_properties(test_compile_resources PROPERTIES LABELS "unit;compiler;ownership;budget")

add_test(NAME test_compile_resources_scan COMMAND test_compile_resources_scan)
set_tests_properties(test_compile_resources_scan PROPERTIES LABELS "unit;compiler;ownership;budget;concurrency" TIMEOUT 60)
