get_filename_component(XR_PARSER_OWNER_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
add_executable(test_parser_resources "${CMAKE_CURRENT_LIST_DIR}/test_parser_resources.c")
target_link_libraries(test_parser_resources PRIVATE xray_compiler_parser)

target_include_directories(test_parser_resources PRIVATE "${XR_PARSER_OWNER_ROOT}/src" "${XR_PARSER_OWNER_ROOT}/src/base" "${XR_PARSER_OWNER_ROOT}/include")
target_compile_features(test_parser_resources PRIVATE c_std_11)
if(MSVC)
    target_compile_definitions(test_parser_resources PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
    target_compile_options(test_parser_resources PRIVATE /W4 /WX /utf-8 /Gy)
    if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
        target_compile_options(test_parser_resources PRIVATE /experimental:c11atomics)
    endif()
endif()
add_test(NAME test_parser_resources COMMAND test_parser_resources)
