/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 *
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * xthread_obj.h - sys.Thread native heap type (real OS thread handle)
 *
 * KEY CONCEPT (task 147 §5.1 / §0.14):
 *   A `Thread` is a real OS thread (not a coroutine). The spawned thread runs
 *   a user closure to completion on its own execution context; join() blocks
 *   the caller until it finishes and returns the closure's value.
 *
 *   IMPLEMENTATION FORM (decided 2026-07-02, task 147 §0.14 candidate A):
 *   sys.Thread.spawn is lowered as a language/IR construct (a `go`-like op)
 *   rather than a native method taking a closure. Reason: the closure call on
 *   the fresh OS thread differs by backend and cannot be done from this shared
 *   coro runtime — `XrClosure` (VM bytecode) vs `xrt_closure_t` (AOT C fn); the
 *   backend vtable `call_closure` is NULL for the native/AOT backends, and the
 *   AOT `c->fn(c)` path lives in src/aot/ (not in this shared library). So the
 *   closure invocation is generated by cgen (reusing `go`'s mature closure
 *   lowering), giving VM/AOT parity for free.
 *
 *   Under that form this XrThread stays a thin runtime handle: it holds the
 *   `xr_thread_t`, drives one coroutine pinned to a dedicated OS thread to
 *   completion, and exposes join()/detach(). The VM side still needs a
 *   dedicated per-thread VM execution context (its own stack/frames) because
 *   `xr_vm_current_ctx` resolves via thread-local worker/coro state and the
 *   shared static fallback `&isolate->vm_ctx` is not concurrency-safe.
 */

#ifndef XTHREAD_OBJ_H
#define XTHREAD_OBJ_H

#include <stdbool.h>
#include <stdint.h>
#include <stdatomic.h>

#include "../base/xdefs.h"
#include "../base/xconstants.h"
#include "../os/os_thread.h"
#include "../runtime/mem/xobj_header.h"
#include "../runtime/value/xvalue.h"

struct XrVMRuntime;
struct XrCoroutine;
struct XrCoroHeap;
struct XrRuntimeCore;

/* Lifecycle state. `state` is atomic so join()/detach()/destroy race safely. */
typedef enum XrThreadState {
    XR_THREAD_CREATED = 0, /* handle populated, entry may or may not have started */
    XR_THREAD_JOINING,     /* one joiner owns xr_thread_join; others wait for JOINED */
    XR_THREAD_JOINED,      /* successfully joined; retval read */
    XR_THREAD_DETACHED,    /* detached; must not be joined */
} XrThreadState;

typedef struct XrThread {
    XrObjHeader hdr;
    xr_thread_t handle; /* OS thread handle */
    struct XrCoroutine *coro;
    struct XrVMRuntime *isolate;
    struct XrRuntimeCore *core;
    const char *name;
    uint32_t affinity_cpus[XR_THREAD_AFFINITY_MAX];
    uint8_t affinity_count;
    _Atomic(int) state;     /* XrThreadState */
    _Atomic(bool) finished; /* entry set the return slot */
    _Atomic(bool) failed;
    bool error_is_value;
    XrValue retval; /* closure result; join deep-copies pointer payloads to caller */
    XrValue error;
} XrThread;

/* Spawn a real OS thread that drives `coro` to completion. `name`/`stack_size`
 * are best-effort (0/NULL = platform default). Returns NULL on allocation/spawn
 * failure. The returned handle is a system-heap shared object. */
XR_FUNC XrThread *xr_thread_obj_spawn_vm(struct XrVMRuntime *isolate, struct XrCoroutine *coro,
                                         const char *name, size_t stack_size,
                                         const uint32_t *affinity_cpus, uint16_t affinity_count);

/* Block until the thread finishes; returns the closure's return value. Idempotent
 * after the first successful join (subsequent calls return the cached retval). */
XR_FUNC XrValue xr_thread_obj_join(XrThread *thread);

/* Detach: the OS thread's resources are reclaimed on exit; must not be joined. */
XR_FUNC void xr_thread_obj_detach(XrThread *thread);

XR_FUNC void xr_obj_destroy_thread(XrObjHeader *obj, struct XrCoroHeap *owner_heap);
XR_FUNC void xr_thread_register_native_type(struct XrVMRuntime *isolate);

static inline bool xr_value_is_thread(XrValue v) {
    return XR_IS_PTR(v) && XR_HEAP_TYPE(v) == XR_TTHREAD;
}

static inline XrThread *xr_value_to_thread(XrValue v) {
    return xr_value_is_thread(v) ? (XrThread *) XR_TO_PTR(v) : NULL;
}

static inline XrValue xr_value_from_thread(XrThread *thread) {
    return XR_FROM_PTR(thread);
}

#endif  // XTHREAD_OBJ_H
