# Native input observations have one production owner and resource ledger.
add_library(xray_xir_pe_version STATIC ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_pe_version.c)
target_link_libraries(xray_xir_pe_version PUBLIC xray_compile_resources)
target_compile_features(xray_xir_pe_version PUBLIC c_std_11)
set_target_properties(xray_xir_pe_version PROPERTIES C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
if(MSVC)
    target_compile_options(xray_xir_pe_version PRIVATE /W4 /WX /utf-8)
else()
    target_compile_options(xray_xir_pe_version PRIVATE -Wall -Wextra -Werror -pedantic)
endif()
if(WIN32)
    include("${CMAKE_CURRENT_LIST_DIR}/xir_process.cmake")
    add_library(xray_toolchain_dependencies STATIC ${CMAKE_CURRENT_LIST_DIR}/xtc_dependencies.c)
    target_link_libraries(xray_toolchain_dependencies PUBLIC xray_json_cursor xray_compile_resources)
    target_compile_features(xray_toolchain_dependencies PUBLIC c_std_11)
    set_target_properties(xray_toolchain_dependencies PROPERTIES C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
    if(MSVC)
        target_compile_options(xray_toolchain_dependencies PRIVATE /W4 /WX /utf-8)
    else()
        target_compile_options(xray_toolchain_dependencies PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
    add_library(xray_xir_target STATIC
        ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_target.c
        ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_sysroot.c
        ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_images.c
        ${CMAKE_CURRENT_LIST_DIR}/../../base/xsha256.c
        ${CMAKE_CURRENT_LIST_DIR}/../../base/xutf8.c)
    target_link_libraries(xray_xir_target PUBLIC xray_compile_resources)
    target_compile_features(xray_xir_target PUBLIC c_std_11)
    set_target_properties(xray_xir_target PROPERTIES C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
    target_compile_definitions(xray_xir_target PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        target_compile_options(xray_xir_target PRIVATE /W4 /WX /utf-8)
    else()
        target_compile_options(xray_xir_target PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
    add_library(xray_xir_publication STATIC ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_publication.c
        ${CMAKE_CURRENT_LIST_DIR}/../../base/xio_policy.c)
    target_link_libraries(xray_xir_publication PUBLIC xray_xir_target bcrypt)
    target_compile_features(xray_xir_publication PUBLIC c_std_11)
    set_target_properties(xray_xir_publication PROPERTIES C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
    target_compile_definitions(xray_xir_publication PRIVATE
        WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        target_compile_options(xray_xir_publication PRIVATE /W4 /WX /utf-8)
    else()
        target_compile_options(xray_xir_publication PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
    add_library(xray_xir_invocation STATIC ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_invocation.c)
    target_link_libraries(xray_xir_invocation PUBLIC
        xray_toolchain_process xray_toolchain_dependencies xray_xir_target
        xray_xir_native_projection xray_xir_runtime_sdk xray_xir_pe_version)
    target_compile_features(xray_xir_invocation PUBLIC c_std_11)
    set_target_properties(xray_xir_invocation PROPERTIES C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
    target_compile_definitions(xray_xir_invocation PRIVATE
        WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        target_compile_options(xray_xir_invocation PRIVATE /W4 /WX /utf-8)
    else()
        target_compile_options(xray_xir_invocation PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
    include("${CMAKE_CURRENT_LIST_DIR}/xir_workspace.cmake")
    add_library(xray_xir_native_operation STATIC ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_native_operation.c)
    target_link_libraries(xray_xir_native_operation PUBLIC xray_xir_invocation xray_xir_workspace)
    target_compile_features(xray_xir_native_operation PUBLIC c_std_11)
    set_target_properties(xray_xir_native_operation PROPERTIES C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
    target_compile_definitions(xray_xir_native_operation PRIVATE
        WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        target_compile_options(xray_xir_native_operation PRIVATE /W4 /WX /utf-8)
    else()
        target_compile_options(xray_xir_native_operation PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
    add_library(xray_xir_native_admission STATIC ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_native_admission.c)
    target_link_libraries(xray_xir_native_admission PUBLIC xray_xir_native_operation)
    add_library(xray_xir_local_toolchain STATIC ${CMAKE_CURRENT_LIST_DIR}/xtc_xir_local_toolchain.c
        ${CMAKE_CURRENT_LIST_DIR}/../../base/xio_policy.c
        ${CMAKE_CURRENT_LIST_DIR}/../../base/xfileio.c
        ${CMAKE_CURRENT_LIST_DIR}/../../os/win/fs_win.c)
    target_link_libraries(xray_xir_local_toolchain PUBLIC xray_toolchain_process
        xray_xir_target xray_xir_runtime_sdk xray_json_cursor)
    foreach(target xray_xir_native_admission xray_xir_local_toolchain)
        target_compile_features(${target} PUBLIC c_std_11)
        set_target_properties(${target} PROPERTIES C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
        target_compile_definitions(${target} PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
        if(MSVC)
            target_compile_options(${target} PRIVATE /W4 /WX /utf-8)
        else()
            target_compile_options(${target} PRIVATE -Wall -Wextra -Werror -pedantic)
        endif()
    endforeach()
endif()
