/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * xxir_native_cache_registry_internal.h - Trusted static image build records
 */
#ifndef XXIR_NATIVE_CACHE_REGISTRY_INTERNAL_H
#define XXIR_NATIVE_CACHE_REGISTRY_INTERNAL_H
#include "xxir_program.h"
typedef struct XirNativeCacheComponent {
    const uint8_t *bytes;
    size_t length;
    uint8_t digest[32];
} XirNativeCacheComponent;
typedef struct XirNativeCacheRegistry {
    uint32_t schema;
    XirNativeCacheComponent checked, native_object, generated_c;
    uint8_t semantic_id[32], runtime_layout[32], sdk_identity[32], binding_digest[32];
    const char *variant;
    uint32_t architecture, value_abi, call_abi, program_abi;
    uint32_t leaf_indices[2];
    uint8_t leaf_digests[2][32];
    const XrXirCallEntry *entries;
    uint32_t entry_count;
} XirNativeCacheRegistry;
/* This symbol is generated by the same-source build, never supplied by a caller. */
extern const XirNativeCacheRegistry xir_native_cache_registry;
#endif
