get_filename_component(PACKAGE_RESOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include(CheckCSourceCompiles)
include(CMakePushCheckState)
function(package_reject_unowned_calls)
    cmake_push_check_state(RESET)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_REQUIRED_INCLUDES "${PACKAGE_RESOURCE_ROOT}/src")
    set(CMAKE_REQUIRED_DEFINITIONS -D_CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        set(CMAKE_REQUIRED_FLAGS "/std:c11 /W4 /WX /utf-8")
    else()
        set(CMAKE_REQUIRED_FLAGS "-std=c11 -Werror")
    endif()
    unset(PACKAGE_RESOURCE_CURRENT_COMPILES CACHE)
    check_c_source_compiles("#include <module/xlockfile.h>\n#include <module/xsemver.h>\nvoid good(const XrOsIoPolicy *p) { (void)xr_lockfile_find_owned(p, 0, 0, 0); (void)xr_lockfile_verify_checksum_owned(p, 0, 0, 0); (void)xr_semver_is_valid_owned(p, 0, 0); }" PACKAGE_RESOURCE_CURRENT_COMPILES)
    if(NOT PACKAGE_RESOURCE_CURRENT_COMPILES)
        message(FATAL_ERROR "Current owned package prototypes failed")
    endif()
    foreach(symbol xr_lockfile_find xr_lockfile_verify_checksum xr_semver_is_valid)
        foreach(kind retired missing_policy)
            if(kind STREQUAL "retired")
                set(source "#include <module/xlockfile.h>\n#include <module/xsemver.h>\nvoid bad(void) { (void)&${symbol}; }")
            elseif(symbol STREQUAL "xr_semver_is_valid")
                set(source "#include <module/xsemver.h>\nvoid bad(void) { (void)${symbol}_owned(0, 0); }")
            else()
                set(source "#include <module/xlockfile.h>\nvoid bad(void) { (void)${symbol}_owned(0, 0, 0); }")
            endif()
            unset(PACKAGE_${symbol}_${kind}_COMPILES CACHE)
            check_c_source_compiles("${source}" PACKAGE_${symbol}_${kind}_COMPILES)
            if(PACKAGE_${symbol}_${kind}_COMPILES)
                message(FATAL_ERROR "Unowned call ${symbol}/${kind} compiled")
            endif()
        endforeach()
    endforeach()
    cmake_pop_check_state()
endfunction()
package_reject_unowned_calls()
set(PACKAGE_RESOURCE_COMMON
    "${PACKAGE_RESOURCE_ROOT}/src/base/xio_policy.c")
add_executable(test_semver_compile_resources
    "${CMAKE_CURRENT_LIST_DIR}/test_semver_compile_resources.c"
    "${PACKAGE_RESOURCE_ROOT}/src/module/xsemver.c" ${PACKAGE_RESOURCE_COMMON})
if(WIN32)
    set(PACKAGE_RESOURCE_PLATFORM win)
else()
    set(PACKAGE_RESOURCE_PLATFORM unix)
endif()
add_executable(test_lockfile_compile_resources
    "${CMAKE_CURRENT_LIST_DIR}/test_lockfile_compile_resources.c"
    "${PACKAGE_RESOURCE_ROOT}/src/base/xfileio.c"
    "${PACKAGE_RESOURCE_ROOT}/src/base/xsha256.c"
    "${PACKAGE_RESOURCE_ROOT}/src/os/${PACKAGE_RESOURCE_PLATFORM}/dir_${PACKAGE_RESOURCE_PLATFORM}.c"
    "${PACKAGE_RESOURCE_ROOT}/src/os/${PACKAGE_RESOURCE_PLATFORM}/proc_self_${PACKAGE_RESOURCE_PLATFORM}.c"
    ${PACKAGE_RESOURCE_COMMON})
add_library(package_resource_production OBJECT
    "${PACKAGE_RESOURCE_ROOT}/src/module/xlockfile.c"
    "${PACKAGE_RESOURCE_ROOT}/src/base/xcompile_resources.c"
    "${PACKAGE_RESOURCE_ROOT}/src/os/${PACKAGE_RESOURCE_PLATFORM}/fs_${PACKAGE_RESOURCE_PLATFORM}.c")
foreach(target test_semver_compile_resources test_lockfile_compile_resources package_resource_production)
    target_include_directories(${target} PRIVATE "${PACKAGE_RESOURCE_ROOT}/src" "${PACKAGE_RESOURCE_ROOT}/src/base")
    target_compile_definitions(${target} PRIVATE _CRT_SECURE_NO_WARNINGS)
    target_compile_features(${target} PRIVATE c_std_11)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /WX /utf-8)
        if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${target} PRIVATE /experimental:c11atomics)
        endif()
    else()
        target_compile_definitions(${target} PRIVATE _POSIX_C_SOURCE=200809L _DEFAULT_SOURCE)
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
endforeach()
foreach(name semver lockfile)
    add_test(NAME test_${name}_compile_resources COMMAND test_${name}_compile_resources)
    set_tests_properties(test_${name}_compile_resources PROPERTIES LABELS "unit;module;ownership;budget" TIMEOUT 120)
endforeach()
