/* Generated by scripts/gen_unicode_grapheme_tables.py; do not edit. */
#ifndef XR_UNICODE_GRAPHEME_VERSION_H
#define XR_UNICODE_GRAPHEME_VERSION_H

#include <stdint.h>

#define XR_UNICODE_GRAPHEME_VERSION "17.0.0"
#define XR_UNICODE_GRAPHEME_UAX29_REVISION 47
#define XR_UNICODE_GRAPHEME_PROFILE "UAX29-C1-1"
#define XR_UNICODE_GRAPHEME_GENERATOR_REVISION 1
#define XR_UNICODE_GRAPHEME_BLOCK_COUNT 111
#define XR_UNICODE_GRAPHEME_PROPERTY_SHA256                                                        \
    "68933ebcac6e677a9be09cf60fc269408a8a19269e2962906d03688663e444d1"
#define XR_UNICODE_GRAPHEME_PROPERTY_FNV1A64 UINT64_C(0x2a9858cec40ce8d6)
#define XR_UNICODE_GRAPHEME_GCB_SHA256                                                             \
    "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89"
#define XR_UNICODE_GRAPHEME_INCB_SHA256                                                            \
    "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08"
#define XR_UNICODE_GRAPHEME_EMOJI_SHA256                                                           \
    "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b"
#define XR_UNICODE_GRAPHEME_TEST_SHA256                                                            \
    "e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec"

#endif /* XR_UNICODE_GRAPHEME_VERSION_H */
