add_library(xray_xir_runtime_host STATIC xr_xir_host_execution.c xr_xir_host_cli.c xr_xir_host_time.c)
if(WIN32)
    target_sources(xray_xir_runtime_host PRIVATE ../os/win/time_win.c)
else()
    target_sources(xray_xir_runtime_host PRIVATE ../os/unix/time_unix.c)
endif()
target_link_libraries(xray_xir_runtime_host PUBLIC xray_xir_scalar)
if(MSVC)
    target_compile_options(xray_xir_runtime_host PRIVATE /W4 /WX)
else()
    target_compile_options(xray_xir_runtime_host PRIVATE -Wall -Wextra -Werror)
endif()
