/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 *
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * xanalyzer.h - Static type analyzer public interface
 *
 * KEY CONCEPT:
 *   The analyzer performs multi-pass analysis on AST:
 *   1. Symbol collection - gather all declarations
 *   2. Type inference - compute types for expressions
 *   3. Type checking - verify type compatibility
 *
 * WHY THIS DESIGN:
 *   - Unified API for compiler and LSP
 *   - Incremental analysis support for IDE responsiveness
 *   - Lazy type computation for performance
 */

#ifndef XANALYZER_H
#define XANALYZER_H

#include "../../runtime/value/xtype.h"
#include "xanalyzer_symbol.h"
#include "../../runtime/value/xtype_pool.h"
#include "../../runtime/xerror.h"
#include <stdbool.h>
#include "../../base/xdefs.h"

// Forward declarations
typedef struct XaAnalyzer XaAnalyzer;
typedef struct AstNode XrAstNode;
typedef struct XrayIsolate XrayIsolate;

// Diagnostic severity (matches LSP XrLspDiagnosticSeverity values)
typedef enum XrDiagSeverity {
    XR_DIAG_SEV_ERROR = 1,
    XR_DIAG_SEV_WARNING = 2,
    XR_DIAG_SEV_INFO = 3,
    XR_DIAG_SEV_HINT = 4,
} XrDiagSeverity;

// Diagnostic message
typedef struct XaDiagnostic {
    XrDiagSeverity severity;
    const char *message;
    int code;                   // Error code (XrErrorCode from xerror.h)
    XrLocation location;
    bool reported;              // Set after xr_diag_print to avoid duplicates
    struct XaDiagnostic *next;
} XaDiagnostic;

// File entry for multi-file support
typedef struct XaFileEntry {
    const char *path;           // File path
    XaScope *file_scope;        // File's top-level scope
    uint64_t content_hash;      // Hash for change detection
    bool dirty;                 // Needs re-analysis
    struct XaFileEntry *next;
} XaFileEntry;

// Analyzer context
struct XaAnalyzer {
    // Owning isolate (explicit, no TLS)
    XrayIsolate *isolate;

    // Type pool (per-analyzer, no global state)
    XrTypePool *type_pool;

    // Symbol ID counter (per-analyzer, thread-safe)
    uint32_t next_symbol_id;

    // Global scope
    XaScope *global_scope;

    // Current analysis scope
    XaScope *current_scope;

    // Current file being analyzed
    const char *current_file;

    // Symbol registry (id -> XaSymbol*) for O(1) ID lookup
    void *symbols_by_id;        // XrIntMap internally

    // Multi-file support
    XaFileEntry *files;         // Linked list for ordered traversal
    void *files_map;            // XrHashMap*: path -> XaFileEntry* for O(1) lookup
    int file_count;

    // Diagnostics list (tail pointer keeps append O(1) and preserves source order)
    XaDiagnostic *diagnostics;
    XaDiagnostic *diagnostics_tail;
    int diagnostic_count;

    // Analysis options
    bool strict_null_checks;    // Treat null as distinct type
    bool strict_mode;           // Enable all strict checks
    bool infer_return_types;    // Infer function return types

    // Caches
    void *type_cache;           // Cache for computed types
    void *flow_cache;           // Cache for flow analysis

    // Incremental analysis support
    void *incremental;          // XaIncrementalCtx* (forward declared)

    // JIT/AOT metadata (generated by Pass 3, NULL when JIT disabled)
    void *jit_metadata;         // XaJitMetadata* (forward declared)
};

// API: Analyzer lifecycle
XR_FUNC XaAnalyzer *xa_analyzer_new(XrayIsolate *X);
XR_FUNC void xa_analyzer_free(XaAnalyzer *analyzer);

// API: Configuration
XR_FUNC void xa_analyzer_set_strict_null(XaAnalyzer *analyzer, bool enable);
XR_FUNC void xa_analyzer_set_strict_mode(XaAnalyzer *analyzer, bool enable);

// API: Analysis
XR_FUNC void xa_analyzer_analyze(XaAnalyzer *analyzer, const char *file, XrAstNode *ast);
XR_FUNC void xa_analyzer_update(XaAnalyzer *analyzer, const char *file, XrAstNode *ast);
XR_FUNC void xa_analyzer_update_incremental(XaAnalyzer *analyzer, const char *file,
                                     XrAstNode *ast, uint64_t content_hash);
XR_FUNC void xa_analyzer_remove_file(XaAnalyzer *analyzer, const char *file);

// API: Cross-file incremental analysis
XR_FUNC const char **xa_analyzer_get_dirty_files(XaAnalyzer *analyzer, int *count);
XR_FUNC void xa_analyzer_mark_file_dirty(XaAnalyzer *analyzer, const char *file);

// API: Symbol lookup
XR_FUNC XaSymbol *xa_analyzer_lookup(XaAnalyzer *analyzer, const char *name);
XR_FUNC XaSymbol *xa_analyzer_lookup_in_scope(XaAnalyzer *analyzer, const char *name, XaScope *scope);
XR_FUNC XaSymbol *xa_analyzer_lookup_at(XaAnalyzer *analyzer, const char *file,
                                 uint32_t line, uint32_t column);
XR_FUNC XaSymbol *xa_analyzer_lookup_deep(XaAnalyzer *analyzer, const char *name);

// API: Type queries
XR_FUNC XrType *xa_analyzer_get_type(XaAnalyzer *analyzer, XaSymbol *symbol);
XR_FUNC XrType *xa_analyzer_get_type_at(XaAnalyzer *analyzer, const char *file,
                                 uint32_t line, uint32_t column);
XR_FUNC XrType *xa_analyzer_infer_expr_type(XaAnalyzer *analyzer, XrAstNode *expr);

// Symbol links are now embedded directly in XaSymbol; no intmap lookup required.
static inline XaSymbolLinks *xa_analyzer_get_links(XaAnalyzer *analyzer, XaSymbol *symbol) {
    (void)analyzer;
    return symbol ? &symbol->links : NULL;
}

// API: Class lookup
XR_FUNC XrClassInfo *xa_analyzer_get_class(XaAnalyzer *analyzer, const char *name);

// API: Member completions (for LSP)
XR_FUNC XaSymbol **xa_analyzer_get_members(XaAnalyzer *analyzer, XrType *type, int *count);
XR_FUNC XaSymbol **xa_analyzer_get_scope_symbols(XaAnalyzer *analyzer, XaScope *scope, int *count);

// API: Diagnostics
XR_FUNC XaDiagnostic *xa_analyzer_get_diagnostics(XaAnalyzer *analyzer, int *count);
XR_FUNC void xa_analyzer_clear_diagnostics(XaAnalyzer *analyzer);

// API: Type checking
XR_FUNC bool xa_analyzer_check_assignment(XaAnalyzer *analyzer, XrType *target,
                                   XrType *source, XrLocation *loc);
XR_FUNC bool xa_analyzer_check_call(XaAnalyzer *analyzer, XrType *func_type,
                             XrType **arg_types, int arg_count, XrLocation *loc);

// API: Iterable/Iterator structural type checking
// Check if type satisfies Iterator<T> (has hasNext(): bool and next(): T)
XR_FUNC bool xa_analyzer_is_iterator(XaAnalyzer *analyzer, XrType *type, XrType **out_element_type);
// Check if type satisfies Iterable<T> (built-in or has iterator() -> Iterator<T>)
XR_FUNC bool xa_analyzer_is_iterable(XaAnalyzer *analyzer, XrType *type, XrType **out_element_type);

// Internal: Add diagnostic
XR_FUNC void xa_analyzer_add_diagnostic(XaAnalyzer *analyzer, XrDiagSeverity severity,
                                 int code, const char *message, XrLocation *loc);

// Internal: Enter/exit scope (ast_node can be NULL)
XR_FUNC void xa_analyzer_enter_scope(XaAnalyzer *analyzer, XaScopeKind kind, void *ast_node);
XR_FUNC void xa_analyzer_exit_scope(XaAnalyzer *analyzer);

// API: Variable operations (compatible with ct_infer)
XR_FUNC XrType *xa_analyzer_lookup_var(XaAnalyzer *analyzer, const char *name);
XR_FUNC void xa_analyzer_define_var(XaAnalyzer *analyzer, const char *name, XrType *type);

// ============================================================================
// LSP Support: Find References and Rename
// ============================================================================

// Symbol reference location
typedef struct XaSymbolRef {
    const char *file;       // File path
    uint32_t line;          // 1-indexed line
    uint32_t column;        // 1-indexed column
    uint32_t end_column;    // End column (for highlight range)
    bool is_definition;     // true if this is the definition
    bool is_write;          // true if this is a write access
    struct XaSymbolRef *next;
} XaSymbolRef;

// Find all references to a symbol by name (uses dependency graph)
XR_FUNC XaSymbolRef *xa_analyzer_find_references(XaAnalyzer *analyzer,
                                          const char *name,
                                          bool include_definition,
                                          int *count);

// Find all references to symbol at position
XR_FUNC XaSymbolRef *xa_analyzer_find_references_at(XaAnalyzer *analyzer,
                                             const char *file,
                                             uint32_t line,
                                             uint32_t column,
                                             int *count);

// Free reference list
XR_FUNC void xa_analyzer_free_references(XaSymbolRef *refs);

// Prepare rename: check if symbol at position can be renamed
XR_FUNC bool xa_analyzer_can_rename(XaAnalyzer *analyzer,
                            const char *file,
                            uint32_t line,
                            uint32_t column,
                            char **out_symbol_name);

#endif // XANALYZER_H
