/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/gen_stdlib_types.py
 * Sources: stdlib definition files
 *
 * xanalyzer_builtins_generated.h - Generated builtin type declarations
 */

#ifndef XANALYZER_BUILTINS_GENERATED_H
#define XANALYZER_BUILTINS_GENERATED_H

#include "xanalyzer_builtins.h"

/* clang-format off */

// ======== Builtin Type Members ========

// Buffer methods
static const XaBuiltinMember g_gen_buffer_members[] = {
    {"length", "(): int", "Return the buffer length in bytes", true, false, false, false},
    {"asSpan", "(): ByteSpan", "Borrow this buffer as a mutable ByteSpan value", true, false, false, false},
    {"ptrUnchecked", "(): RawMut<uint8>", "Return the underlying raw pointer; unsafe escape hatch", true, false, false, false},
    {"resize", "(n: int): bool", "Resize this buffer; returns false on allocation failure", true, false, false, false},
};
#define GEN_BUFFER_MEMBER_COUNT 4

// OsBarrier methods
static const XaBuiltinMember g_gen_osbarrier_members[] = {
    {"wait", "(): bool", "Wait until all parties have arrived", true, false, false, false},
};
#define GEN_OSBARRIER_MEMBER_COUNT 1

// OsCondvar methods
static const XaBuiltinMember g_gen_oscondvar_members[] = {
    {"wait", "(m: OsMutex): ()", "Wait on the condition variable with an already-locked mutex", true, false, false, false},
    {"waitFor", "(m: OsMutex, timeoutNs: int): bool", "Wait on the condition variable until signalled or timeout elapses", true, false, false, false},
    {"signal", "(): ()", "Wake one waiter", true, false, false, false},
    {"broadcast", "(): ()", "Wake all waiters", true, false, false, false},
};
#define GEN_OSCONDVAR_MEMBER_COUNT 4

// OsMutex methods
static const XaBuiltinMember g_gen_osmutex_members[] = {
    {"lock", "(): ()", "Lock the mutex", true, false, false, false},
    {"unlock", "(): ()", "Unlock the mutex", true, false, false, false},
    {"tryLock", "(): bool", "Try to lock the mutex", true, false, false, false},
};
#define GEN_OSMUTEX_MEMBER_COUNT 3

// OsOnce methods
static const XaBuiltinMember g_gen_osonce_members[] = {
    {"call", "(body: fn(): ()): ()", "Run the closure exactly once", true, false, false, false},
};
#define GEN_OSONCE_MEMBER_COUNT 1

// OsRwLock methods
static const XaBuiltinMember g_gen_osrwlock_members[] = {
    {"rdlock", "(): ()", "Acquire the read side of the read-write lock", true, false, false, false},
    {"rdunlock", "(): ()", "Release the read side of the read-write lock", true, false, false, false},
    {"wrlock", "(): ()", "Acquire the write side of the read-write lock", true, false, false, false},
    {"wrunlock", "(): ()", "Release the write side of the read-write lock", true, false, false, false},
};
#define GEN_OSRWLOCK_MEMBER_COUNT 4

// ======== C Module Declarations ========

// cluster module functions
static const XaBuiltinMember g_gen_cluster_functions[] = {
    {"start", "(config: Json): ()", "Start cluster node", true, false, false, false},
    {"join", "(addr: string): bool", "Join cluster by address", true, false, false, false},
    {"self", "(): string", "Get own node name", true, false, false, false},
    {"nodes", "(): Array<string>", "List cluster node names", true, false, false, false},
    {"channel", "(name: string, size?: int): Channel", "Create or get named distributed channel", true, false, false, false},
    {"serve", "(name: string): Channel", "Register service and return request channel", true, false, false, false},
    {"reply", "(req: Json, result: Json): bool", "Reply to service request", true, false, false, false},
    {"call", "(service: string, args: Json, timeout?: int): Json", "Call remote service", true, false, false, false},
    {"monitor", "(name: string, coro_name?: string): Channel", "Monitor node or remote coroutine", true, false, false, false},
    {"discover", "(): ()", "Start LAN auto-discovery", true, false, false, false},
    {"stop", "(): ()", "Stop cluster node", true, false, false, false},
    {"info", "(): Json", "Get cluster status info", true, false, false, false},
    {"publish", "(topic: string, value: Json): bool", "Publish to topic", true, false, false, false},
    {"subscribe", "(pattern: string): Channel", "Subscribe to topic pattern", true, false, false, false},
};
#define GEN_CLUSTER_FUNCTION_COUNT 14

// compress module functions
static const XaBuiltinMember g_gen_compress_functions[] = {
    {"crc32", "(data: string): int", "Compute CRC-32 checksum", true, false, false, false},
    {"adler32", "(data: string): int", "Compute Adler-32 checksum", true, false, false, false},
    {"gzip", "(data: string, level?: int): string?", "Gzip compress", true, false, false, false},
    {"gunzip", "(data: string): string?", "Gzip decompress", true, false, false, false},
    {"deflate", "(data: string, level?: int): string?", "Deflate compress", true, false, false, false},
    {"inflate", "(data: string): string?", "Inflate decompress", true, false, false, false},
    {"zlibCompress", "(data: string, level?: int): string?", "Zlib compress", true, false, false, false},
    {"zlibDecompress", "(data: string): string?", "Zlib decompress", true, false, false, false},
    {"isGzip", "(data: string): bool", "Check if gzip data", true, false, false, false},
    {"isZlib", "(data: string): bool", "Check if zlib data", true, false, false, false},
};
#define GEN_COMPRESS_FUNCTION_COUNT 10

// crypto module functions
static const XaBuiltinMember g_gen_crypto_functions[] = {
    {"md5", "(data: string): string", "Compute MD5 hash", true, false, false, false},
    {"sha1", "(data: string): string", "Compute SHA-1 hash", true, false, false, false},
    {"sha256", "(data: string): string", "Compute SHA-256 hash", true, false, false, false},
    {"sha512", "(data: string): string", "Compute SHA-512 hash", true, false, false, false},
    {"hmac", "(algo: string, key: string, data: string): string?", "Compute HMAC", true, false, false, false},
    {"randomBytes", "(n: int): string", "Generate random bytes", true, false, false, false},
    {"uuid", "(): string", "Generate UUID v4", true, false, false, false},
    {"encrypt", "(key: string, plaintext: string): string", "AES-256-CBC encrypt", true, false, false, false},
    {"decrypt", "(key: string, ciphertext: string): string?", "AES-256-CBC decrypt", true, false, false, false},
    {"timingSafeEqual", "(a: string, b: string): bool", "Constant-time string comparison", true, false, false, false},
};
#define GEN_CRYPTO_FUNCTION_COUNT 10

// http.HttpResponse handle fields
static const XaBuiltinHandleField g_gen_http_httpresponse_fields[] = {
    {"status", "int", true},
    {"statusText", "string", true},
    {"headers", "Json", true},
    {"body", "string", true},
    {"error", "string", true},
    {"ok", "bool", true},
};

// http.HttpRequest handle fields
static const XaBuiltinHandleField g_gen_http_httprequest_fields[] = {
    {"method", "string", true},
    {"path", "string", true},
    {"query", "Json", true},
    {"headers", "Json", true},
    {"body", "string", true},
    {"contentLength", "int", true},
    {"params", "Json", true},
};

static const XaBuiltinHandle g_gen_http_handles[] = {
    {"HttpResponse", g_gen_http_httpresponse_fields, 6, NULL, 0},
    {"HttpRequest", g_gen_http_httprequest_fields, 7, NULL, 0},
};
#define GEN_HTTP_HANDLE_COUNT 2

// http module functions
static const XaBuiltinMember g_gen_http_functions[] = {
    {"request", "(options: Json): HttpResponse", "Generic HTTP request", true, false, false, false},
    {"route", "(method: string, path: string, handler: fn | string | Json): ()", "Register a route handler or static response", true, false, false, false},
    {"listen", "(port: int): bool", "Start HTTP server accept loop", true, false, false, false},
    {"ws", "(path: string, handler: fn(conn: WsConn): ()): ()", "Register WebSocket upgrade route on HTTP server", true, false, false, false},
    {"stopServer", "(): ()", "Stop the HTTP server", true, false, false, false},
    {"h2Request", "(options: Json): Json", "Generic HTTP/2 request", true, false, false, false},
};
#define GEN_HTTP_FUNCTION_COUNT 6

// io.FileStat handle fields
static const XaBuiltinHandleField g_gen_io_filestat_fields[] = {
    {"size", "int", true},
    {"mode", "int", true},
    {"mtime", "int", true},
    {"atime", "int", true},
    {"ctime", "int", true},
    {"uid", "int", true},
    {"gid", "int", true},
    {"isFile", "bool", true},
    {"isDir", "bool", true},
    {"isSymlink", "bool", true},
};

static const XaBuiltinHandle g_gen_io_handles[] = {
    {"FileStat", g_gen_io_filestat_fields, 10, NULL, 0},
};
#define GEN_IO_HANDLE_COUNT 1

// io module functions
static const XaBuiltinMember g_gen_io_functions[] = {
    {"appendFile", "(path: string, data: string): bool", "Append string to file", true, false, false, false},
    {"chmod", "(path: string, mode: int): bool", "Change file permissions", true, false, false, false},
    {"chdir", "(path: string): bool", "Change working directory", true, false, false, false},
    {"copyFile", "(src: string, dst: string): bool", "Copy a file", true, false, false, false},
    {"cwd", "(): string", "Get current working directory", true, false, false, false},
    {"exists", "(path: string): bool", "Check if path exists", true, false, false, false},
    {"fileSize", "(path: string): int", "Get file size in bytes", true, false, false, false},
    {"isDir", "(path: string): bool", "Check if path is a directory", true, false, false, false},
    {"isFile", "(path: string): bool", "Check if path is a file", true, false, false, false},
    {"isSymlink", "(path: string): bool", "Check if path is a symlink", true, false, false, false},
    {"mkdir", "(path: string): bool", "Create directory", true, false, false, false},
    {"mkdirp", "(path: string): bool", "Create directory recursively", true, false, false, false},
    {"readDir", "(path: string): Array<string>", "List directory entries", true, false, false, false},
    {"readDirRecursive", "(path: string): Array<string>", "List directory entries recursively", true, false, false, false},
    {"readFile", "(path: string): string?", "Read entire file as string", true, false, false, false},
    {"readFileBytes", "(path: string): Array<uint8>?", "Read entire file as byte array", true, false, false, false},
    {"readLines", "(path: string): Array<string>", "Read file as lines", true, false, false, false},
    {"readStdin", "(): string?", "Read all data from standard input", true, false, false, false},
    {"readlink", "(path: string): string?", "Read symlink target", true, false, false, false},
    {"realpath", "(path: string): string?", "Resolve to absolute path", true, false, false, false},
    {"remove", "(path: string): bool", "Remove a file", true, false, false, false},
    {"removeAll", "(path: string): bool", "Remove directory recursively", true, false, false, false},
    {"rename", "(old: string, new: string): bool", "Rename a file", true, false, false, false},
    {"stat", "(path: string): FileStat?", "Get file stat info", true, false, false, false},
    {"symlink", "(target: string, link: string): bool", "Create symbolic link", true, false, false, false},
    {"tempDir", "(): string?", "Create temporary directory", true, false, false, false},
    {"tempFile", "(): string?", "Create temporary file", true, false, false, false},
    {"touch", "(path: string): bool", "Create or update file timestamp", true, false, false, false},
    {"writeFile", "(path: string, data: string): bool", "Write string to file", true, false, false, false},
    {"writeFileBytes", "(path: string, data: Array<uint8>): bool", "Write byte array to file", true, false, false, false},
};
#define GEN_IO_FUNCTION_COUNT 30

// math module functions
static const XaBuiltinMember g_gen_math_functions[] = {
    {"abs", "(x: float): float", "Absolute value (preserves int)", true, false, false, false},
    {"floor", "(x: float): int", "Floor to integer", true, false, false, false},
    {"ceil", "(x: float): int", "Ceiling to integer", true, false, false, false},
    {"round", "(x: float): int", "Round to nearest integer", true, false, false, false},
    {"sqrt", "(x: float): float", "Square root", true, false, false, false},
    {"pow", "(base: float, exp: float): float", "Power", true, false, false, false},
    {"sin", "(x: float): float", "Sine", true, false, false, false},
    {"cos", "(x: float): float", "Cosine", true, false, false, false},
    {"tan", "(x: float): float", "Tangent", true, false, false, false},
    {"asin", "(x: float): float", "Arc sine", true, false, false, false},
    {"acos", "(x: float): float", "Arc cosine", true, false, false, false},
    {"atan", "(x: float): float", "Arc tangent", true, false, false, false},
    {"atan2", "(y: float, x: float): float", "Arc tangent of y/x", true, false, false, false},
    {"log", "(x: float): float", "Natural logarithm", true, false, false, false},
    {"log10", "(x: float): float", "Base-10 logarithm", true, false, false, false},
    {"log2", "(x: float): float", "Base-2 logarithm", true, false, false, false},
    {"exp", "(x: float): float", "Exponential e^x", true, false, false, false},
    {"min", "(...args: float): float", "Minimum (preserves int)", true, false, false, false},
    {"max", "(...args: float): float", "Maximum (preserves int)", true, false, false, false},
    {"clamp", "(x: float, min: float, max: float): float", "Clamp (preserves int)", true, false, false, false},
    {"random", "(): float", "Random float in [0, 1)", true, false, false, false},
    {"randomInt", "(min: int, max: int): int", "Random integer in [min, max]", true, false, false, false},
    {"sign", "(x: float): int", "Sign of value (-1, 0, 1)", true, false, false, false},
    {"sinh", "(x: float): float", "Hyperbolic sine", true, false, false, false},
    {"cosh", "(x: float): float", "Hyperbolic cosine", true, false, false, false},
    {"tanh", "(x: float): float", "Hyperbolic tangent", true, false, false, false},
    {"hypot", "(x: float, y: float): float", "Hypotenuse sqrt(x*x+y*y)", true, false, false, false},
    {"cbrt", "(x: float): float", "Cube root", true, false, false, false},
    {"trunc", "(x: float): int", "Truncate toward zero", true, false, false, false},
    {"fmod", "(x: float, y: float): float", "Floating-point remainder", true, false, false, false},
    {"log1p", "(x: float): float", "log(1+x) accurate for small x", true, false, false, false},
    {"expm1", "(x: float): float", "exp(x)-1 accurate for small x", true, false, false, false},
    {"lerp", "(a: float, b: float, t: float): float", "Linear interpolation", true, false, false, false},
    {"degToRad", "(deg: float): float", "Degrees to radians", true, false, false, false},
    {"radToDeg", "(rad: float): float", "Radians to degrees", true, false, false, false},
    {"isNaN", "(x: float): bool", "Check if NaN", true, false, false, false},
    {"isFinite", "(x: float): bool", "Check if finite", true, false, false, false},
    // Module constants (is_method=false)
    {"PI", ": float", "Ratio of a circle's circumference to its diameter", false, false, false, false},
    {"E", ": float", "Euler's number", false, false, false, false},
    {"TAU", ": float", "Full-circle radians, 2 * PI", false, false, false, false},
    {"SQRT2", ": float", "Square root of 2", false, false, false, false},
    {"LN2", ": float", "Natural logarithm of 2", false, false, false, false},
    {"LN10", ": float", "Natural logarithm of 10", false, false, false, false},
    {"LOG2E", ": float", "Base-2 logarithm of e", false, false, false, false},
    {"LOG10E", ": float", "Base-10 logarithm of e", false, false, false, false},
    {"EPSILON", ": float", "Smallest representable difference above 1.0", false, false, false, false},
    {"MAX_INT", ": int", "Largest signed 64-bit integer", false, false, false, false},
    {"MIN_INT", ": int", "Smallest signed 64-bit integer", false, false, false, false},
    {"MAX_FLOAT", ": float", "Largest finite IEEE-754 double", false, false, false, false},
    {"INF", ": float", "Positive infinity", false, false, false, false},
    {"NAN", ": float", "Quiet NaN value", false, false, false, false},
};
#define GEN_MATH_FUNCTION_COUNT 51

// mem module functions
static const XaBuiltinMember g_gen_mem_functions[] = {
    {"fence", "(ordering: int): ()", "Standalone memory fence; ordering mirrors Ordering enum ordinals (0 Relaxed .. 4 SeqCst)", true, false, false, false},
    {"prefetch", "(ptr: RawPtr<uint8>, rw: int): ()", "Prefetch a cache line at ptr (performance hint; rw!=0 = write intent). VM no-op, AOT __builtin_prefetch", true, false, false, false},
    {"cacheFlush", "(ptr: RawPtr<uint8>, n: int): ()", "Best-effort data-cache flush for a byte range. VM no-op; AOT emits platform cache maintenance when available", true, false, false, false},
    {"cacheInvalidate", "(ptr: RawPtr<uint8>, n: int): ()", "Best-effort data-cache invalidation for a byte range. VM no-op; AOT emits platform cache maintenance when available", true, false, false, false},
    {"nontemporalStore", "(ptr: RawMut<uint8>, v: int, size: int): ()", "Best-effort non-temporal sized store (size in {1,2,4,8}). VM stores normally; AOT emits streaming stores when available", true, false, false, false},
    {"cacheLineSize", "(): int", "CPU cache line size in bytes", true, false, false, false},
    {"sizeOf", "(): int", "Compile-time size in bytes of a statically laid out type T", true, false, false, false},
    {"alignOf", "(): int", "Compile-time alignment in bytes of a statically laid out type T", true, false, false, false},
    {"offsetOf", "(field: string): int", "Compile-time byte offset of a field in a fixed-layout struct T", true, false, false, false},
    {"alloc", "(n: int): Buffer", "Allocate n uninitialized bytes as a managed Buffer; released automatically when dropped", true, false, false, false},
    {"allocZeroed", "(n: int): Buffer", "Allocate n zero-initialized bytes as a managed Buffer", true, false, false, false},
    {"allocAligned", "(n: int, align: int): Buffer", "Allocate n managed bytes aligned to align (power-of-two >= sizeof(void*))", true, false, false, false},
    {"pageAlloc", "(bytes: int, prot?: int): RawMut<uint8>", "Allocate zero-filled anonymous pages with protection bits PROT_READ/PROT_WRITE/PROT_EXEC (mmap/VirtualAlloc). NULL on failure; pair with mem.pageFree", true, false, false, false},
    {"pageProtect", "(ptr: RawMut<uint8>, bytes: int, prot: int): bool", "Change anonymous page protection bits; returns false on OS failure", true, false, false, false},
    {"pageFree", "(ptr: RawMut<uint8>, bytes: int): bool", "Release anonymous pages from mem.pageAlloc; returns false on OS failure", true, false, false, false},
    {"fromAddress", "(addr: int): RawMut<uint8>", "Construct a raw pointer from a numeric address (MMIO/physical memory; task 147 §7.2). Constructing is safe, dereferencing requires unsafe", true, false, false, false},
    {"addressOf", "(ptr: RawPtr<unknown>): int", "Numeric address of any raw pointer (alignment checks, diagnostics; inverse of mem.fromAddress)", true, false, false, false},
    {"copy", "(dst: RawMut<uint8>, src: RawPtr<uint8>, n: int): ()", "Copy n bytes from src to dst (non-overlapping; memcpy)", true, false, false, false},
    {"move", "(dst: RawMut<uint8>, src: RawPtr<uint8>, n: int): ()", "Copy n bytes from src to dst (may overlap; memmove)", true, false, false, false},
    {"set", "(dst: RawMut<uint8>, byte: int, n: int): ()", "Fill n bytes at dst with byte (memset)", true, false, false, false},
    {"compare", "(a: RawPtr<uint8>, b: RawPtr<uint8>, n: int): int", "Compare n bytes at a and b (memcmp: <0, 0, >0)", true, false, false, false},
    {"volatileLoad", "(ptr: RawPtr<uint8>, size: int): int", "Volatile load of size bytes (MMIO; size in {1,2,4,8}, native byte order)", true, false, false, false},
    {"volatileStore", "(ptr: RawMut<uint8>, v: int, size: int): ()", "Volatile store of size bytes (MMIO; size in {1,2,4,8}, native byte order)", true, false, false, false},
    // Module constants (is_method=false)
    {"PROT_NONE", ": int", "No access protection for mem.pageAlloc/pageProtect", false, false, false, false},
    {"PROT_READ", ": int", "Readable page protection bit for mem.pageAlloc/pageProtect", false, false, false, false},
    {"PROT_WRITE", ": int", "Writable page protection bit for mem.pageAlloc/pageProtect", false, false, false, false},
    {"PROT_EXEC", ": int", "Executable page protection bit for mem.pageAlloc/pageProtect", false, false, false, false},
};
#define GEN_MEM_FUNCTION_COUNT 27

// net.UdpPacket handle fields
static const XaBuiltinHandleField g_gen_net_udppacket_fields[] = {
    {"data", "string", true},
    {"host", "string", true},
    {"port", "int", true},
};

static const XaBuiltinHandle g_gen_net_handles[] = {
    {"UdpPacket", g_gen_net_udppacket_fields, 3, NULL, 0},
};
#define GEN_NET_HANDLE_COUNT 1

// net module functions
static const XaBuiltinMember g_gen_net_functions[] = {
    {"dial", "(host: string, port: int, timeout?: int): NetConn?", "Dial a TCP connection", true, false, false, false},
    {"listen", "(port: int, backlog?: int): NetListener?", "Start listening on a port", true, false, false, false},
    {"accept", "(listener: NetListener): NetConn?", "Accept a new connection", true, false, false, false},
    {"read", "(conn: NetConn, maxlen?: int): string?", "Read data from connection", true, false, false, false},
    {"readInto", "(conn: NetConn, buffer: Bytes, maxlen?: int): int", "Read data into a reusable Bytes buffer", true, false, false, false},
    {"write", "(conn: NetConn, data: string): int", "Write data to connection", true, false, false, false},
    {"writeBytes", "(conn: NetConn, data: Bytes): int", "Write Bytes data to connection", true, false, false, false},
    {"copy", "(src: NetConn, dst: NetConn, bufferSize?: int): int", "Copy a TCP/TLS stream using a reusable native buffer", true, false, false, false},
    {"copyBidirectional", "(a: NetConn, b: NetConn): Json", "Copy two TCP/TLS streams in both directions", true, false, false, false},
    {"shutdownRead", "(conn: NetConn): bool", "Shut down the read side of a TCP connection", true, false, false, false},
    {"shutdownWrite", "(conn: NetConn): bool", "Shut down the write side of a TCP connection", true, false, false, false},
    {"shutdown", "(conn: NetConn): bool", "Shut down both sides of a TCP connection", true, false, false, false},
    {"close", "(handle: NetConn | NetListener): ()", "Close a connection or listener", true, false, false, false},
    {"fd", "(handle: NetConn | NetListener): int", "Get fd from handle", true, false, false, false},
    {"setReadDeadline", "(conn: NetConn, deadline: int): bool", "Set read deadline in monotonic ms", true, false, false, false},
    {"setWriteDeadline", "(conn: NetConn, deadline: int): bool", "Set write deadline in monotonic ms", true, false, false, false},
    {"setDeadline", "(conn: NetConn, deadline: int): bool", "Set read and write deadlines in monotonic ms", true, false, false, false},
    {"setAcceptDeadline", "(listener: NetListener, deadline: int): bool", "Set accept deadline in monotonic ms", true, false, false, false},
    {"lastError", "(handle: NetConn | NetListener): string?", "Return the last network error name", true, false, false, false},
    {"lastErrno", "(handle: NetConn | NetListener): int", "Return the last system errno", true, false, false, false},
    {"lookup", "(hostname: string): string?", "DNS lookup", true, false, false, false},
    {"hasTLS", "(): bool", "Check if TLS support is available", true, false, false, false},
    {"dialTLS", "(host: string, port: int, timeout?: int): NetConn?", "Dial a TLS connection", true, false, false, false},
    {"upgradeTLS", "(conn: NetConn, hostname: string, timeout?: int): NetConn?", "Upgrade connection to TLS", true, false, false, false},
    {"udpBind", "(port: int, addr?: string): NetConn?", "Bind a UDP socket", true, false, false, false},
    {"sendTo", "(handle: NetConn, data: string, host: string, port: int): int", "Send UDP datagram", true, false, false, false},
    {"recvFrom", "(handle: NetConn, maxlen?: int): UdpPacket?", "Receive UDP datagram (returns flat handle: data, host, port)", true, false, false, false},
};
#define GEN_NET_FUNCTION_COUNT 27

// os.ExecResult handle fields
static const XaBuiltinHandleField g_gen_os_execresult_fields[] = {
    {"stdout", "string", true},
    {"stderr", "string", true},
    {"exitCode", "int", true},
};

static const XaBuiltinHandle g_gen_os_handles[] = {
    {"ExecResult", g_gen_os_execresult_fields, 3, NULL, 0},
};
#define GEN_OS_HANDLE_COUNT 1

// os module functions
static const XaBuiltinMember g_gen_os_functions[] = {
    {"getenv", "(name: string): string?", "Get environment variable", true, false, false, false},
    {"setenv", "(name: string, value: string): bool", "Set environment variable", true, false, false, false},
    {"unsetenv", "(name: string): bool", "Unset environment variable", true, false, false, false},
    {"environ", "(): Map<string, string>", "Get all environment variables", true, false, false, false},
    {"exit", "(code?: int): ()", "Exit process", true, false, false, false},
    {"getpid", "(): int", "Get process ID", true, false, false, false},
    {"getcwd", "(): string", "Get current working directory", true, false, false, false},
    {"chdir", "(path: string): bool", "Change working directory", true, false, false, false},
    {"hostname", "(): string", "Get hostname", true, false, false, false},
    {"tmpdir", "(): string", "Get temporary directory path", true, false, false, false},
    {"username", "(): string?", "Get current user name", true, false, false, false},
    {"homedir", "(): string?", "Get user home directory", true, false, false, false},
    {"uid", "(): int", "Get user ID", true, false, false, false},
    {"gid", "(): int", "Get group ID", true, false, false, false},
    {"cpuCount", "(): int", "Get number of CPU cores", true, false, false, false},
    {"ppid", "(): int", "Get parent process ID", true, false, false, false},
    {"kill", "(pid: int, signal?: int): bool", "Send signal to process", true, false, false, false},
    {"totalMemory", "(): int", "Get total system memory in bytes", true, false, false, false},
    {"freeMemory", "(): int", "Get available system memory in bytes", true, false, false, false},
    {"uptime", "(): float", "Get system uptime in seconds", true, false, false, false},
    {"loadavg", "(): Array<float>", "Get system load averages (1, 5, 15 min)", true, false, false, false},
    {"clock", "(): float", "Get process CPU time in seconds", true, false, false, false},
    {"sleep", "(ms: int): ()", "Sleep for milliseconds", true, false, false, false},
    {"exec", "(cmd: string): ExecResult?", "Execute shell command", true, false, false, false},
    {"spawn", "(program: string, args: Array<string>): ExecResult?", "Execute a program without a shell (injection-safe argv)", true, false, false, false},
    // Module constants (is_method=false)
    {"platform", ": string", "Current operating system name", false, false, false, false},
    {"arch", ": string", "Current CPU architecture name", false, false, false, false},
    {"sep", ": string", "Platform path separator", false, false, false, false},
    {"eol", ": string", "Platform end-of-line string", false, false, false, false},
};
#define GEN_OS_FUNCTION_COUNT 29

// regex module functions
static const XaBuiltinMember g_gen_regex_functions[] = {
    {"compile", "(pattern: string, flags?: string): Regex", "Compile regex pattern", true, false, false, false},
    {"test", "(pattern: Regex, s: string): bool", "Test if regex matches", true, false, false, false},
    {"count", "(pattern: Regex, s: string): int", "Count matches", true, false, false, false},
    {"findText", "(pattern: Regex, s: string): string?", "Find first matching text", true, false, false, false},
    {"findGroup", "(pattern: Regex, s: string, index: int): string?", "Find capture group", true, false, false, false},
    {"find", "(pattern: Regex, s: string, offset?: int): RegexMatch?", "Find first match", true, false, false, false},
    {"fullFind", "(pattern: Regex, s: string): RegexMatch?", "Find full match", true, false, false, false},
    {"findAll", "(pattern: Regex, s: string, limit?: int): Array<RegexMatch>", "Find all matches", true, false, false, false},
    {"replace", "(pattern: Regex, s: string, repl: string): string", "Replace first match", true, false, false, false},
    {"replaceAll", "(pattern: Regex, s: string, repl: string): string", "Replace all matches", true, false, false, false},
    {"split", "(pattern: Regex, s: string, limit?: int): Array<string>", "Split string by regex", true, false, false, false},
    {"escape", "(s: string): string", "Escape regex special chars", true, false, false, false},
    {"isValid", "(pattern: string): bool", "Check if pattern is valid", true, false, false, false},
};
#define GEN_REGEX_FUNCTION_COUNT 13

// runtime module functions
static const XaBuiltinMember g_gen_runtime_functions[] = {
    {"collectCycles", "(): int", "Run cycle collection + whole-block reclaim, return cycle collection count", true, false, false, false},
    {"disableCycleCollection", "(): ()", "Pause the automatic cycle collector", true, false, false, false},
    {"enableCycleCollection", "(): ()", "Resume the automatic cycle collector", true, false, false, false},
    {"isCycleCollectionEnabled", "(): bool", "Check if automatic cycle collection is enabled", true, false, false, false},
    {"liveBytes", "(): int", "Get live memory usage in bytes", true, false, false, false},
    {"liveObjects", "(): int", "Get live object count", true, false, false, false},
    {"info", "(): Map", "Get memory-model runtime info as Map", true, false, false, false},
};
#define GEN_RUNTIME_FUNCTION_COUNT 7

// sys module functions
static const XaBuiltinMember g_gen_sys_functions[] = {
    {"OsMutex", "(): OsMutex", "Create an OS-domain mutex", true, false, false, false},
    {"__osMutexNew", "(): OsMutex", "Create an OS-domain mutex for sys module internals", true, false, true, false},
    {"OsRwLock", "(): OsRwLock", "Create an OS-domain read-write lock", true, false, false, false},
    {"OsCondvar", "(): OsCondvar", "Create an OS-domain condition variable", true, false, false, false},
    {"OsBarrier", "(parties: int): OsBarrier", "Create a reusable OS-domain barrier", true, false, false, false},
    {"OsOnce", "(): OsOnce", "Create an OS-domain once gate", true, false, false, false},
    {"cpuCount", "(): int", "Return the number of CPUs available to OS-thread work", true, false, false, false},
    {"threadYield", "(): ()", "Yield the current OS thread to another runnable OS thread", true, false, false, false},
    {"sleepMs", "(ms: int): ()", "Block the current OS thread for at least ms milliseconds", true, false, false, false},
    {"pinToCpu", "(cpu: int): bool", "Best-effort pin of the current OS thread to a CPU index", true, false, false, false},
    {"__threadLocalId", "(): int", "Return a stable token for the current OS thread", true, false, true, false},
    {"__threadLocalAlive", "(id: int): bool", "Return whether an internal sys.ThreadLocal OS-thread token is still live", true, false, true, false},
    {"__onSignal", "(signal: int, handler: fn(): ()): bool", "Register a VM-hosted safe-point handler for a portable process signal", true, false, true, false},
    {"__dylibOpen", "(path: string): int", "Open a dynamic library and return an opaque handle token, or 0 on failure", true, false, true, false},
    {"__dylibSymbol", "(handle: int, name: string): RawPtr<uint8>?", "Resolve a dynamic-library symbol to a raw address, or null on failure", true, false, true, false},
    {"__dylibClose", "(handle: int): bool", "Close a dynamic library handle token", true, false, true, false},
    {"__dylibLastError", "(): string", "Return the platform dynamic-loader error message for the current thread", true, false, true, false},
    {"__processSpawn", "(program: string, args: Array<string>, cwd: string?, envKeys: Array<string>?, envValues: Array<string>?, stdinRead: int?, stdoutWrite: int?, stderrWrite: int?, detached: bool): int", "Spawn a process and return an opaque process handle token, or -1 on failure", true, false, true, false},
    {"__processWait", "(id: int): int", "Wait for a process handle token and return its exit code, or -1 on failure", true, false, true, false},
    {"__processTryWait", "(id: int): int?", "Poll a process handle token; return null while running, exit code when finished, or -1 on failure", true, false, true, false},
    {"__processKill", "(id: int, signal: int): bool", "Send a portable process signal to a process handle token", true, false, true, false},
    {"__pipeOpen", "(): Array<int>?", "Create an anonymous pipe and return read/write endpoint tokens", true, false, true, false},
    {"__pipeRead", "(handle: int, maxBytes: int): Bytes?", "Read one chunk from a pipe endpoint", true, false, true, false},
    {"__pipeWrite", "(handle: int, data: Bytes): int", "Write one chunk to a pipe endpoint", true, false, true, false},
    {"__pipeClose", "(handle: int): bool", "Close a pipe endpoint", true, false, true, false},
};
#define GEN_SYS_FUNCTION_COUNT 25

// time module functions
static const XaBuiltinMember g_gen_time_functions[] = {
    {"now", "(): int", "Current time in milliseconds since epoch", true, false, false, false},
    {"clock", "(): int", "CPU clock time in milliseconds", true, false, false, false},
    {"monotonic", "(): int", "Monotonic time in milliseconds", true, false, false, false},
    {"nanos", "(): int", "Monotonic time in nanoseconds", true, false, false, false},
    {"micros", "(): int", "Monotonic time in microseconds", true, false, false, false},
    {"localOffset", "(): int", "Local UTC offset in minutes for the current wall time", true, false, false, false},
    {"localOffsetAt", "(timestamp: int): int", "Local UTC offset in minutes at a Unix timestamp", true, false, false, false},
    {"sleep", "(ms: int): ()", "Sleep for milliseconds", true, false, false, false},
};
#define GEN_TIME_FUNCTION_COUNT 8

// ws.WsConn handle fields
static const XaBuiltinHandleField g_gen_ws_wsconn_fields[] = {
    {"wsid", "int", true},
    {"url", "string", false},
    {"state", "string", false},
};

// ws.WsMessage handle fields
static const XaBuiltinHandleField g_gen_ws_wsmessage_fields[] = {
    {"data", "string | Array<uint8> | null", true},
    {"binary", "bool", true},
    {"error", "string?", true},
};

static const XaBuiltinHandle g_gen_ws_handles[] = {
    {"WsConn", g_gen_ws_wsconn_fields, 3, NULL, 0},
    {"WsMessage", g_gen_ws_wsmessage_fields, 3, NULL, 0},
};
#define GEN_WS_HANDLE_COUNT 2

// ws module functions
static const XaBuiltinMember g_gen_ws_functions[] = {
    {"connect", "(url: string, options?: Json): WsConn?", "Connect to a WebSocket server", true, false, false, false},
    {"send", "(conn: WsConn, data: string | Array<uint8>, binary?: bool?): bool", "Send data over WebSocket connection", true, false, false, false},
    {"recv", "(conn: WsConn, timeout?: int?): WsMessage?", "Receive data from WebSocket connection", true, false, false, false},
    {"close", "(conn: WsConn, code?: int?, reason?: string?): bool", "Close a WebSocket connection", true, false, false, false},
    {"ping", "(conn: WsConn): bool", "Send a ping frame", true, false, false, false},
    {"state", "(conn: WsConn): string", "Get connection state", true, false, false, false},
    {"isOpen", "(conn: WsConn): bool", "Check if connection is open", true, false, false, false},
    {"serve", "(port: int, handler: fn(conn: WsConn): ()): bool", "Start WebSocket server", true, false, false, false},
    {"stopServer", "(): ()", "Stop the WebSocket server", true, false, false, false},
};
#define GEN_WS_FUNCTION_COUNT 9

// Module registry
static const XaBuiltinModule g_gen_builtin_modules[] = {
    {"cluster", g_gen_cluster_functions, GEN_CLUSTER_FUNCTION_COUNT, NULL, 0},
    {"compress", g_gen_compress_functions, GEN_COMPRESS_FUNCTION_COUNT, NULL, 0},
    {"crypto", g_gen_crypto_functions, GEN_CRYPTO_FUNCTION_COUNT, NULL, 0},
    {"http", g_gen_http_functions, GEN_HTTP_FUNCTION_COUNT, g_gen_http_handles, GEN_HTTP_HANDLE_COUNT},
    {"io", g_gen_io_functions, GEN_IO_FUNCTION_COUNT, g_gen_io_handles, GEN_IO_HANDLE_COUNT},
    {"math", g_gen_math_functions, GEN_MATH_FUNCTION_COUNT, NULL, 0},
    {"mem", g_gen_mem_functions, GEN_MEM_FUNCTION_COUNT, NULL, 0},
    {"net", g_gen_net_functions, GEN_NET_FUNCTION_COUNT, g_gen_net_handles, GEN_NET_HANDLE_COUNT},
    {"os", g_gen_os_functions, GEN_OS_FUNCTION_COUNT, g_gen_os_handles, GEN_OS_HANDLE_COUNT},
    {"regex", g_gen_regex_functions, GEN_REGEX_FUNCTION_COUNT, NULL, 0},
    {"runtime", g_gen_runtime_functions, GEN_RUNTIME_FUNCTION_COUNT, NULL, 0},
    {"sys", g_gen_sys_functions, GEN_SYS_FUNCTION_COUNT, NULL, 0},
    {"time", g_gen_time_functions, GEN_TIME_FUNCTION_COUNT, NULL, 0},
    {"ws", g_gen_ws_functions, GEN_WS_FUNCTION_COUNT, g_gen_ws_handles, GEN_WS_HANDLE_COUNT},
};
#define GEN_BUILTIN_MODULE_COUNT 14

/* clang-format on */

#endif  // XANALYZER_BUILTINS_GENERATED_H
