/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 *
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * xanalyzer_xrd.c - .xrd type declaration file loader
 *
 * KEY CONCEPT:
 *   Parses .xrd files and registers them as dynamic XaBuiltinModule entries.
 *   Format (generated by gen_stdlib_types.py --xrd):
 *     type Connection = { const fd: int, const type: string }
 *     export fn dial(host: string, port: int): Connection?
 */

#include "xanalyzer_xrd.h"
#include "../../base/xchecks.h"
#include "../../base/xmalloc.h"
#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Dynamic module storage (linked list, grows as .xrd files are loaded)
typedef struct XrdModule {
    XaBuiltinModule module;
    XaBuiltinMember *functions;  // owned, heap-allocated
    int function_cap;
    XaBuiltinHandle *handles;  // owned
    int handle_cap;
    int *handle_method_caps;  // per-handle method capacity array
    char *name_buf;           // owned string storage
    struct XrdModule *next;
} XrdModule;

static XrdModule *g_xrd_modules = NULL;
static char g_xrd_error[256];

// Use unified xr_strdup from xmalloc.h
#define xrd_strdup xr_strdup

const char *xa_xrd_last_error(void) {
    return g_xrd_error;
}

static void xrd_set_error(const char *format, ...) {
    va_list args;
    va_start(args, format);
    vsnprintf(g_xrd_error, sizeof(g_xrd_error), format, args);
    va_end(args);
}

void xa_effect_contract_clear(XaEffectContract *contract) {
    if (!contract)
        return;
    for (uint32_t i = 0; i < contract->error_count; i++)
        xr_free((void *) contract->errors[i]);
    xr_free(contract->errors);
    memset(contract, 0, sizeof(*contract));
}

static void free_xrd_module(XrdModule *module) {
    if (!module)
        return;
    for (int i = 0; i < module->module.function_count; i++) {
        xr_free((void *) module->functions[i].name);
        xr_free((void *) module->functions[i].signature);
        xr_free((void *) module->functions[i].doc);
        xa_effect_contract_clear(&module->functions[i].effect_contract);
    }
    xr_free(module->functions);
    for (int i = 0; i < module->module.handle_count; i++) {
        xr_free((void *) module->handles[i].name);
        for (int j = 0; j < module->handles[i].field_count; j++) {
            xr_free((void *) module->handles[i].fields[j].name);
            xr_free((void *) module->handles[i].fields[j].type_str);
        }
        xr_free((void *) module->handles[i].fields);
        for (int j = 0; j < module->handles[i].method_count; j++) {
            XaBuiltinMember *method = (XaBuiltinMember *) &module->handles[i].methods[j];
            xr_free((void *) method->name);
            xr_free((void *) method->signature);
            xr_free((void *) method->doc);
            xa_effect_contract_clear(&method->effect_contract);
        }
        xr_free((void *) module->handles[i].methods);
    }
    xr_free(module->handles);
    xr_free(module->handle_method_caps);
    xr_free(module->name_buf);
    xr_free(module);
}

// Skip whitespace
static const char *skip_ws(const char *p) {
    while (*p && (*p == ' ' || *p == '\t'))
        p++;
    return p;
}

// Read identifier (alphanumeric + underscore)
static const char *read_ident(const char *p, char *buf, size_t buf_size) {
    size_t i = 0;
    while (*p && (isalnum((unsigned char) *p) || *p == '_') && i < buf_size - 1) {
        buf[i++] = *p++;
    }
    buf[i] = '\0';
    return p;
}

// Read until end of line, trim trailing whitespace
static const char *read_to_eol(const char *p, char *buf, size_t buf_size) {
    size_t i = 0;
    while (*p && *p != '\n' && *p != '\r' && i < buf_size - 1) {
        buf[i++] = *p++;
    }
    buf[i] = '\0';
    // Trim trailing whitespace
    while (i > 0 && (buf[i - 1] == ' ' || buf[i - 1] == '\t')) {
        buf[--i] = '\0';
    }
    return p;
}

static int compare_effect_error_refs(const void *lhs, const void *rhs) {
    const char *const *a = (const char *const *) lhs;
    const char *const *b = (const char *const *) rhs;
    return strcmp(*a, *b);
}

static bool effect_ref_char(char c) {
    return isalnum((unsigned char) c) || c == '_' || c == '.' || c == ':';
}

static char *duplicate_effect_ref(const char *start, size_t len) {
    char *result = (char *) xr_malloc(len + 1u);
    if (!result)
        return NULL;
    memcpy(result, start, len);
    result[len] = '\0';
    return result;
}

static bool xrd_ident_boundary(char c) {
    return !(isalnum((unsigned char) c) || c == '_');
}

static bool xrd_signature_contains_token(const char *signature, const char *token) {
    if (!signature || !token || !token[0])
        return false;
    size_t token_len = strlen(token);
    for (const char *p = signature; (p = strstr(p, token)) != NULL; p += token_len) {
        char before = (p == signature) ? '\0' : p[-1];
        char after = p[token_len];
        if ((p == signature || xrd_ident_boundary(before)) &&
            (after == '\0' || xrd_ident_boundary(after)))
            return true;
    }
    return false;
}

static bool xrd_validate_signature_types(const char *signature) {
    static const char *const removed_byte_aliases[] = {"Bytes", "ByteSpan", "ByteView"};
    if (!signature)
        return true;
    for (size_t i = 0; i < sizeof(removed_byte_aliases) / sizeof(removed_byte_aliases[0]); i++) {
        if (xrd_signature_contains_token(signature, removed_byte_aliases[i])) {
            xrd_set_error("XRD descriptor uses removed byte alias '%s'; use Array<byte> or "
                          "Slice<byte> explicitly",
                          removed_byte_aliases[i]);
            return false;
        }
    }
    return true;
}

bool xa_effect_contract_parse_suffix(char *signature, XaEffectContract *contract) {
    memset(contract, 0, sizeof(*contract));
    char *at = strchr(signature, '@');
    if (!at)
        return true;

    char metadata[256];
    size_t metadata_len = strlen(at);
    if (metadata_len >= sizeof(metadata)) {
        xrd_set_error("effect metadata is too long");
        return false;
    }
    memcpy(metadata, at, metadata_len + 1u);
    char *signature_end = at;
    while (signature_end > signature && isspace((unsigned char) signature_end[-1]))
        signature_end--;
    *signature_end = '\0';

    if (strncmp(metadata, "@nothrow", 8) == 0) {
        const char *tail = skip_ws(metadata + 8);
        if (*tail != '\0') {
            xrd_set_error("invalid or conflicting effect metadata after @nothrow");
            return false;
        }
        contract->kind = XA_EFFECT_CONTRACT_NOTHROW;
        return true;
    }
    if (strncmp(metadata, "@errors", 7) != 0) {
        xrd_set_error("unknown effect metadata '%s'", metadata);
        return false;
    }

    const char *p = skip_ws(metadata + 7);
    if (*p != '(') {
        xrd_set_error("@errors must contain a parenthesized error list");
        return false;
    }
    p++;
    uint32_t capacity = 0;
    bool expects_entry = true;
    bool closed = false;
    while (*p) {
        p = skip_ws(p);
        if (*p == ')') {
            if (expects_entry) {
                xrd_set_error("@errors requires a non-empty error list");
                xa_effect_contract_clear(contract);
                return false;
            }
            p++;
            closed = true;
            break;
        }
        const char *start = p;
        if (!(isalpha((unsigned char) *p) || *p == '_')) {
            xrd_set_error("invalid error reference in @errors");
            xa_effect_contract_clear(contract);
            return false;
        }
        while (*p && effect_ref_char(*p))
            p++;
        size_t len = (size_t) (p - start);
        p = skip_ws(p);
        if (*p != ',' && *p != ')') {
            xrd_set_error("invalid error reference in @errors");
            xa_effect_contract_clear(contract);
            return false;
        }
        if (contract->error_count == capacity) {
            uint32_t next_capacity = capacity ? capacity * 2u : 4u;
            const char **next = (const char **) xr_realloc(
                contract->errors, (size_t) next_capacity * sizeof(const char *));
            if (!next) {
                xrd_set_error("out of memory while parsing @errors");
                xa_effect_contract_clear(contract);
                return false;
            }
            contract->errors = next;
            capacity = next_capacity;
        }
        char *error_ref = duplicate_effect_ref(start, len);
        if (!error_ref) {
            xrd_set_error("out of memory while parsing @errors");
            xa_effect_contract_clear(contract);
            return false;
        }
        contract->errors[contract->error_count++] = error_ref;
        expects_entry = false;
        if (*p == ',') {
            p++;
            expects_entry = true;
        }
    }
    if (!closed || expects_entry || *skip_ws(p) != '\0') {
        xrd_set_error("invalid trailing content in @errors metadata");
        xa_effect_contract_clear(contract);
        return false;
    }

    qsort(contract->errors, contract->error_count, sizeof(const char *), compare_effect_error_refs);
    for (uint32_t i = 1; i < contract->error_count; i++) {
        if (strcmp(contract->errors[i - 1u], contract->errors[i]) == 0) {
            xrd_set_error("duplicate error '%s' in @errors", contract->errors[i]);
            xa_effect_contract_clear(contract);
            return false;
        }
    }
    contract->kind = XA_EFFECT_CONTRACT_ERRORS;
    return true;
}

// Parse handle fields from "{ const fd: int, const type: string }"
static XaBuiltinHandleField *parse_handle_fields(const char *p, int *out_count) {
    *out_count = 0;

    // Skip to opening brace
    while (*p && *p != '{')
        p++;
    if (*p != '{')
        return NULL;
    p++;

    // Count commas to estimate field count
    int cap = 8;
    XaBuiltinHandleField *fields = xr_calloc(cap, sizeof(XaBuiltinHandleField));
    if (!fields)
        return NULL;

    int count = 0;
    while (*p && *p != '}') {
        p = skip_ws(p);
        if (*p == ',' || *p == '}') {
            if (*p == ',')
                p++;
            continue;
        }

        bool is_const = false;
        if (strncmp(p, "const ", 6) == 0) {
            is_const = true;
            p += 6;
            p = skip_ws(p);
        }

        char name[64];
        p = read_ident(p, name, sizeof(name));
        p = skip_ws(p);

        if (*p == ':')
            p++;
        p = skip_ws(p);

        char type_str[64];
        p = read_ident(p, type_str, sizeof(type_str));

        if (name[0] && type_str[0]) {
            if (count >= cap) {
                cap *= 2;
                XR_REALLOC_OR_ABORT(fields, (size_t) cap * sizeof(XaBuiltinHandleField),
                                    "xrd fields grow");
            }
            fields[count].name = xrd_strdup(name);
            fields[count].type_str = xrd_strdup(type_str);
            fields[count].is_const = is_const;
            count++;
        }

        // Skip comma
        p = skip_ws(p);
        if (*p == ',')
            p++;
    }

    *out_count = count;
    return fields;
}

// Parse a single .xrd file content into an XrdModule
static XrdModule *parse_xrd_content(const char *content, const char *module_name) {
    XR_DCHECK(content != NULL, "parse_xrd_content: NULL content");
    XR_DCHECK(module_name != NULL, "parse_xrd_content: NULL module_name");
    XrdModule *xrd = xr_calloc(1, sizeof(XrdModule));
    if (!xrd)
        return NULL;

    xrd->module.name = xrd_strdup(module_name);
    xrd->name_buf = (char *) xrd->module.name;

    // Pre-allocate arrays
    xrd->function_cap = 32;
    xrd->functions = xr_calloc(xrd->function_cap, sizeof(XaBuiltinMember));
    xrd->handle_cap = 8;
    xrd->handles = xr_calloc(xrd->handle_cap, sizeof(XaBuiltinHandle));
    xrd->handle_method_caps = xr_calloc(xrd->handle_cap, sizeof(int));
    if (!xrd->functions || !xrd->handles || !xrd->handle_method_caps) {
        free_xrd_module(xrd);
        return NULL;
    }

    const char *p = content;
    while (*p) {
        // Skip blank lines and comments
        p = skip_ws(p);
        if (*p == '\n' || *p == '\r') {
            p++;
            continue;
        }
        if (*p == '/' && p[1] == '/') {
            while (*p && *p != '\n')
                p++;
            if (*p)
                p++;
            continue;
        }

        // Parse "type Name = { ... }"
        if (strncmp(p, "type ", 5) == 0) {
            p += 5;
            p = skip_ws(p);

            char handle_name[64];
            p = read_ident(p, handle_name, sizeof(handle_name));
            p = skip_ws(p);

            if (*p == '=')
                p++;
            p = skip_ws(p);

            int field_count = 0;
            XaBuiltinHandleField *fields = parse_handle_fields(p, &field_count);

            {
                int idx = xrd->module.handle_count;
                if (idx >= xrd->handle_cap) {
                    int new_cap = xrd->handle_cap * 2;
                    XR_REALLOC_OR_ABORT(xrd->handles, (size_t) new_cap * sizeof(XaBuiltinHandle),
                                        "xrd handles grow");
                    XR_REALLOC_OR_ABORT(xrd->handle_method_caps, (size_t) new_cap * sizeof(int),
                                        "xrd handle_method_caps grow");
                    // Zero-init new slots
                    for (int k = xrd->handle_cap; k < new_cap; k++) {
                        memset(&xrd->handles[k], 0, sizeof(XaBuiltinHandle));
                        xrd->handle_method_caps[k] = 0;
                    }
                    xrd->handle_cap = new_cap;
                }
                xrd->handles[idx].name = xrd_strdup(handle_name);
                xrd->handles[idx].fields = (fields && field_count > 0) ? fields : NULL;
                xrd->handles[idx].field_count = (fields && field_count > 0) ? field_count : 0;
                xrd->handles[idx].methods = NULL;
                xrd->handles[idx].method_count = 0;
                xrd->handle_method_caps[idx] = 0;
                xrd->module.handle_count++;
            }

            // Skip to next line
            while (*p && *p != '\n')
                p++;
            if (*p)
                p++;
            continue;
        }

        // Parse "fn TypeName.method(sig)" — handle instance methods
        if (strncmp(p, "fn ", 3) == 0 && p[3] != '\0') {
            const char *start = p + 3;
            start = skip_ws(start);

            char first_ident[64];
            const char *after_ident = read_ident(start, first_ident, sizeof(first_ident));

            if (*after_ident == '.') {
                // Handle method: fn TypeName.method(sig)
                after_ident++;  // skip dot
                char meth_name[64];
                after_ident = read_ident(after_ident, meth_name, sizeof(meth_name));

                char sig[256];
                read_to_eol(after_ident, sig, sizeof(sig));
                XaEffectContract effect_contract;
                if (!xa_effect_contract_parse_suffix(sig, &effect_contract)) {
                    free_xrd_module(xrd);
                    return NULL;
                }
                if (!xrd_validate_signature_types(sig)) {
                    xa_effect_contract_clear(&effect_contract);
                    free_xrd_module(xrd);
                    return NULL;
                }

                // Find handle by name
                int handle_idx = -1;
                for (int i = 0; i < xrd->module.handle_count; i++) {
                    if (strcmp(xrd->handles[i].name, first_ident) == 0) {
                        handle_idx = i;
                        break;
                    }
                }

                if (handle_idx >= 0 && meth_name[0] && sig[0]) {
                    XaBuiltinHandle *h = &xrd->handles[handle_idx];
                    int midx = h->method_count;
                    if (midx >= xrd->handle_method_caps[handle_idx]) {
                        int new_cap = xrd->handle_method_caps[handle_idx] * 2;
                        if (new_cap < 8)
                            new_cap = 8;
                        XaBuiltinMember *new_methods = xr_realloc(
                            (void *) h->methods, (size_t) new_cap * sizeof(XaBuiltinMember));
                        if (new_methods) {
                            h->methods = new_methods;
                            xrd->handle_method_caps[handle_idx] = new_cap;
                        }
                    }
                    if (midx < xrd->handle_method_caps[handle_idx]) {
                        XaBuiltinMember *methods = (XaBuiltinMember *) h->methods;
                        methods[midx].name = xrd_strdup(meth_name);
                        methods[midx].signature = xrd_strdup(sig);
                        methods[midx].doc = xrd_strdup("");
                        methods[midx].is_method = (sig[0] == '(');
                        methods[midx].is_static = false;
                        methods[midx].is_internal = false;
                        methods[midx].is_lowered_only = false;
                        methods[midx].is_yieldable = false;
                        methods[midx].effect_contract = effect_contract;
                        h->method_count++;
                    } else {
                        xa_effect_contract_clear(&effect_contract);
                    }
                } else {
                    xa_effect_contract_clear(&effect_contract);
                }

                // Skip to next line
                while (*p && *p != '\n')
                    p++;
                if (*p)
                    p++;
                continue;
            }
        }

        // Parse "export fn name(...): type"
        if (strncmp(p, "export fn ", 10) == 0) {
            p += 10;
            p = skip_ws(p);

            char func_name[64];
            p = read_ident(p, func_name, sizeof(func_name));

            // Rest of line is the signature
            char sig[256];
            p = read_to_eol(p, sig, sizeof(sig));
            XaEffectContract effect_contract;
            if (!xa_effect_contract_parse_suffix(sig, &effect_contract)) {
                free_xrd_module(xrd);
                return NULL;
            }
            if (!xrd_validate_signature_types(sig)) {
                xa_effect_contract_clear(&effect_contract);
                free_xrd_module(xrd);
                return NULL;
            }

            if (func_name[0] && sig[0]) {
                int idx = xrd->module.function_count;
                if (idx >= xrd->function_cap) {
                    xrd->function_cap *= 2;
                    XR_REALLOC_OR_ABORT(xrd->functions,
                                        (size_t) xrd->function_cap * sizeof(XaBuiltinMember),
                                        "xrd functions grow");
                }
                xrd->functions[idx].name = xrd_strdup(func_name);
                xrd->functions[idx].signature = xrd_strdup(sig);
                xrd->functions[idx].doc = xrd_strdup("");
                xrd->functions[idx].is_method = (sig[0] == '(');
                xrd->functions[idx].is_static = false;
                xrd->functions[idx].is_internal = false;
                xrd->functions[idx].is_lowered_only = false;
                xrd->functions[idx].is_yieldable = false;
                xrd->functions[idx].effect_contract = effect_contract;
                xrd->module.function_count++;
            } else {
                xa_effect_contract_clear(&effect_contract);
            }

            if (*p)
                p++;
            continue;
        }

        // Skip unknown lines
        while (*p && *p != '\n')
            p++;
        if (*p)
            p++;
    }

    xrd->module.functions = xrd->functions;
    xrd->module.handles = xrd->handles;
    return xrd;
}

// Read file into heap buffer
static char *read_file_content(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f)
        return NULL;

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0 || size > 1024 * 1024) {  // Max 1MB
        fclose(f);
        return NULL;
    }

    char *buf = xr_malloc(size + 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }

    size_t nread = fread(buf, 1, size, f);
    buf[nread] = '\0';
    fclose(f);
    return buf;
}

const XaBuiltinModule *xa_xrd_load_file(const char *xrd_path) {
    g_xrd_error[0] = '\0';
    if (!xrd_path)
        return NULL;

    char *content = read_file_content(xrd_path);
    if (!content)
        return NULL;

    // Extract module name from filename
    const char *slash = strrchr(xrd_path, '/');
    const char *base = slash ? slash + 1 : xrd_path;
    char mod_name[64];
    size_t i = 0;
    while (base[i] && base[i] != '.' && i < sizeof(mod_name) - 1) {
        mod_name[i] = base[i];
        i++;
    }
    mod_name[i] = '\0';

    // Check if already loaded
    for (XrdModule *m = g_xrd_modules; m; m = m->next) {
        if (strcmp(m->module.name, mod_name) == 0) {
            xr_free(content);
            return &m->module;
        }
    }

    XrdModule *xrd = parse_xrd_content(content, mod_name);
    xr_free(content);

    if (!xrd || (xrd->module.function_count == 0 && xrd->module.handle_count == 0)) {
        free_xrd_module(xrd);
        return NULL;
    }

    // Add to linked list
    xrd->next = g_xrd_modules;
    g_xrd_modules = xrd;

    return &xrd->module;
}

const XaBuiltinModule *xa_xrd_find_module(const char *module_name, const char *script_dir) {
    if (!module_name)
        return NULL;

    // Check if already loaded
    for (XrdModule *m = g_xrd_modules; m; m = m->next) {
        if (strcmp(m->module.name, module_name) == 0) {
            return &m->module;
        }
    }

    char path[1024];

    // 1. Search in script directory
    if (script_dir && script_dir[0]) {
        snprintf(path, sizeof(path), "%s/%s.xrd", script_dir, module_name);
        const XaBuiltinModule *mod = xa_xrd_load_file(path);
        if (mod)
            return mod;
    }

    // 2. Search $XRAY_TYPEPATH
    const char *typepath = getenv("XRAY_TYPEPATH");
    if (typepath && typepath[0]) {
        // Support colon-separated paths
        char pathbuf[4096];
        strncpy(pathbuf, typepath, sizeof(pathbuf) - 1);
        pathbuf[sizeof(pathbuf) - 1] = '\0';

        char *saveptr = NULL;
        char *dir = strtok_r(pathbuf, ":", &saveptr);
        while (dir) {
            snprintf(path, sizeof(path), "%s/%s.xrd", dir, module_name);
            const XaBuiltinModule *mod = xa_xrd_load_file(path);
            if (mod)
                return mod;
            dir = strtok_r(NULL, ":", &saveptr);
        }
    }

    return NULL;
}

const XaBuiltinHandle *xa_xrd_find_handle_by_name(const char *handle_name) {
    if (!handle_name)
        return NULL;
    for (XrdModule *m = g_xrd_modules; m; m = m->next) {
        for (int i = 0; i < m->module.handle_count; i++) {
            if (strcmp(m->handles[i].name, handle_name) == 0)
                return &m->handles[i];
        }
    }
    return NULL;
}

void xa_xrd_cleanup(void) {
    XrdModule *m = g_xrd_modules;
    while (m) {
        XrdModule *next = m->next;
        free_xrd_module(m);
        m = next;
    }
    g_xrd_modules = NULL;
}
