/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/stdlibgen/stdlibgen.py
 *
 * xaot_stdlib_generated.inc.c - AOT stdlib driver metadata
 */

/* clang-format off */

enum {
    XAOT_STDLIB_CAP_CORO = 1u << 0,
    XAOT_STDLIB_CAP_TIMER = 1u << 1,
    XAOT_STDLIB_CAP_CHANNEL = 1u << 2,
    XAOT_STDLIB_CAP_NETPOLL = 1u << 3,
    XAOT_STDLIB_CAP_TASK = 1u << 4,
    XAOT_STDLIB_CAP_WORK_QUEUE = 1u << 5,
    XAOT_STDLIB_CAP_RESULT_GROUP = 1u << 6,
    XAOT_STDLIB_CAP_OBJECTS = 1u << 7,
    XAOT_STDLIB_CAP_DEEP_COPY = 1u << 8,
    XAOT_STDLIB_CAP_EXCEPTION = 1u << 9,
    XAOT_STDLIB_CAP_REFLECTION = 1u << 10,
    XAOT_STDLIB_CAP_STACKTRACE = 1u << 11,
    XAOT_STDLIB_CAP_INSTANCEOF = 1u << 12,
    XAOT_STDLIB_CAP_SCOPE = 1u << 13,
};

static const char *xaot_stdlib_generated_object_for_symbol(const char *symbol) {
    if (!symbol)
        return NULL;
    if (strcmp(symbol, "time.now") == 0)
        return "time.now";
    if (strcmp(symbol, "time.clock") == 0)
        return "time.clock";
    if (strcmp(symbol, "time.monotonic") == 0)
        return "time.monotonic";
    if (strcmp(symbol, "time.nanos") == 0)
        return "time.nanos";
    if (strcmp(symbol, "time.micros") == 0)
        return "time.micros";
    if (strcmp(symbol, "time.sleep") == 0)
        return "time";
    if (strcmp(symbol, "math.random") == 0)
        return "math.random";
    if (strcmp(symbol, "math.randomInt") == 0)
        return "math.randomInt";
    if (strcmp(symbol, "crypto.md5") == 0)
        return "crypto.md5";
    if (strcmp(symbol, "crypto.sha1") == 0)
        return "crypto.sha1";
    if (strcmp(symbol, "crypto.sha256") == 0)
        return "crypto.sha256";
    if (strcmp(symbol, "crypto.sha512") == 0)
        return "crypto.sha512";
    if (strcmp(symbol, "crypto.hmac") == 0)
        return "crypto.hmac";
    if (strcmp(symbol, "crypto.randomBytes") == 0)
        return "crypto.randomBytes";
    if (strcmp(symbol, "crypto.uuid") == 0)
        return "crypto.uuid";
    if (strcmp(symbol, "crypto.encrypt") == 0)
        return "crypto.encrypt";
    if (strcmp(symbol, "crypto.decrypt") == 0)
        return "crypto.decrypt";
    if (strcmp(symbol, "regex.compile") == 0)
        return "regex.compile";
    if (strcmp(symbol, "regex.test") == 0)
        return "regex.test";
    if (strcmp(symbol, "regex.count") == 0)
        return "regex.count";
    if (strcmp(symbol, "regex.findText") == 0)
        return "regex.findText";
    if (strcmp(symbol, "regex.findGroup") == 0)
        return "regex.findGroup";
    if (strcmp(symbol, "regex.find") == 0)
        return "regex.find";
    if (strcmp(symbol, "regex.fullFind") == 0)
        return "regex.fullFind";
    if (strcmp(symbol, "regex.findAll") == 0)
        return "regex.findAll";
    if (strcmp(symbol, "regex.replace") == 0)
        return "regex.replace";
    if (strcmp(symbol, "regex.replaceAll") == 0)
        return "regex.replaceAll";
    if (strcmp(symbol, "regex.split") == 0)
        return "regex.split";
    if (strcmp(symbol, "regex.isValid") == 0)
        return "regex.isValid";
    return NULL;
}

static const char *xaot_stdlib_generated_define_for_symbol(const char *symbol) {
    if (!symbol)
        return NULL;
    if (strcmp(symbol, "regex.compile") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.test") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.count") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.findText") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.findGroup") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.find") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.fullFind") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.findAll") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.replace") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.replaceAll") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.split") == 0)
        return "XRT_ENABLE_REGEX";
    return NULL;
}

static uint32_t xaot_stdlib_generated_caps_for_symbol(const char *symbol) {
    if (!symbol)
        return 0;
    if (strcmp(symbol, "time.sleep") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_TIMER;
    return 0;
}

/* clang-format on */
