/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/stdlibgen/stdlibgen.py
 *
 * xaot_stdlib_generated.inc.c - AOT stdlib driver metadata
 */

/* clang-format off */

enum {
    XAOT_STDLIB_CAP_CORO = 1u << 0,
    XAOT_STDLIB_CAP_TIMER = 1u << 1,
    XAOT_STDLIB_CAP_CHANNEL = 1u << 2,
    XAOT_STDLIB_CAP_NETPOLL = 1u << 3,
    XAOT_STDLIB_CAP_TASK = 1u << 4,
    XAOT_STDLIB_CAP_WORK_QUEUE = 1u << 5,
    XAOT_STDLIB_CAP_RESULT_GROUP = 1u << 6,
    XAOT_STDLIB_CAP_OBJECTS = 1u << 7,
    XAOT_STDLIB_CAP_DEEP_COPY = 1u << 8,
    XAOT_STDLIB_CAP_EXCEPTION = 1u << 9,
    XAOT_STDLIB_CAP_STACKTRACE = 1u << 10,
    XAOT_STDLIB_CAP_INSTANCEOF = 1u << 11,
    XAOT_STDLIB_CAP_SCOPE = 1u << 12,
};

static const char *xaot_stdlib_generated_object_for_symbol(const char *symbol) {
    if (!symbol)
        return NULL;
    if (strcmp(symbol, "time.__realtimeNanos") == 0)
        return "time.__realtimeNanos";
    if (strcmp(symbol, "time.__monotonicNanos") == 0)
        return "time.__monotonicNanos";
    if (strcmp(symbol, "time.__cpuNanos") == 0)
        return "time.__cpuNanos";
    if (strcmp(symbol, "time.__utcOffsetAt") == 0)
        return "time.__utcOffsetAt";
    if (strcmp(symbol, "math.random") == 0)
        return "math.random";
    if (strcmp(symbol, "math.randomInt") == 0)
        return "math.randomInt";
    if (strcmp(symbol, "crypto.__randomBytes") == 0)
        return "crypto.__randomBytes";
    if (strcmp(symbol, "regex.__compile") == 0)
        return "regex.__compile";
    if (strcmp(symbol, "regex.__test") == 0)
        return "regex.__test";
    if (strcmp(symbol, "regex.__count") == 0)
        return "regex.__count";
    if (strcmp(symbol, "regex.__findText") == 0)
        return "regex.__findText";
    if (strcmp(symbol, "regex.__findGroup") == 0)
        return "regex.__findGroup";
    if (strcmp(symbol, "regex.find") == 0)
        return "regex.find";
    if (strcmp(symbol, "regex.fullFind") == 0)
        return "regex.fullFind";
    if (strcmp(symbol, "regex.findAll") == 0)
        return "regex.findAll";
    if (strcmp(symbol, "regex.__replace") == 0)
        return "regex.__replace";
    if (strcmp(symbol, "regex.__replaceAll") == 0)
        return "regex.__replaceAll";
    if (strcmp(symbol, "regex.__split") == 0)
        return "regex.__split";
    if (strcmp(symbol, "regex.__isValid") == 0)
        return "regex.__isValid";
    if (strcmp(symbol, "cluster.__start") == 0)
        return "cluster.__start";
    if (strcmp(symbol, "cluster.__join") == 0)
        return "cluster.__join";
    if (strcmp(symbol, "cluster.__stop") == 0)
        return "cluster.__stop";
    if (strcmp(symbol, "cluster.__send") == 0)
        return "cluster.__send";
    if (strcmp(symbol, "cluster.__listen") == 0)
        return "cluster.__listen";
    return NULL;
}

static const char *xaot_stdlib_generated_define_for_symbol(const char *symbol) {
    if (!symbol)
        return NULL;
    if (strcmp(symbol, "regex.__compile") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.__test") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.__count") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.__findText") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.__findGroup") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.find") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.fullFind") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.findAll") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.__replace") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.__replaceAll") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.__split") == 0)
        return "XRT_ENABLE_REGEX";
    return NULL;
}

static uint32_t xaot_stdlib_generated_caps_for_symbol(const char *symbol) {
    if (!symbol)
        return 0;
    if (strcmp(symbol, "time.sleep") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_TIMER;
    if (strcmp(symbol, "net.__resolveAll") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "net.__connectFd") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "net.__accept") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "net.__readInto") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "net.__writeBytes") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "net.__copyBidirectional") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "net.__close") == 0)
        return XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "net.__udpSendTo") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "net.__udpFromHost") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_NETPOLL;
    if (strcmp(symbol, "cluster.__start") == 0)
        return XAOT_STDLIB_CAP_CHANNEL;
    if (strcmp(symbol, "cluster.__join") == 0)
        return XAOT_STDLIB_CAP_CHANNEL;
    if (strcmp(symbol, "cluster.__stop") == 0)
        return XAOT_STDLIB_CAP_CHANNEL;
    if (strcmp(symbol, "cluster.__send") == 0)
        return XAOT_STDLIB_CAP_CHANNEL;
    if (strcmp(symbol, "cluster.__listen") == 0)
        return XAOT_STDLIB_CAP_CHANNEL;
    return 0;
}

static bool xaot_stdlib_generated_symbol_is_builtin_direct(const char *symbol) {
    if (!symbol)
        return false;
    if (strcmp(symbol, "math.abs") == 0)
        return true;
    if (strcmp(symbol, "math.floor") == 0)
        return true;
    if (strcmp(symbol, "math.ceil") == 0)
        return true;
    if (strcmp(symbol, "math.round") == 0)
        return true;
    if (strcmp(symbol, "math.sqrt") == 0)
        return true;
    if (strcmp(symbol, "math.pow") == 0)
        return true;
    if (strcmp(symbol, "math.sin") == 0)
        return true;
    if (strcmp(symbol, "math.cos") == 0)
        return true;
    if (strcmp(symbol, "math.tan") == 0)
        return true;
    if (strcmp(symbol, "math.asin") == 0)
        return true;
    if (strcmp(symbol, "math.acos") == 0)
        return true;
    if (strcmp(symbol, "math.atan") == 0)
        return true;
    if (strcmp(symbol, "math.atan2") == 0)
        return true;
    if (strcmp(symbol, "math.log") == 0)
        return true;
    if (strcmp(symbol, "math.log10") == 0)
        return true;
    if (strcmp(symbol, "math.log2") == 0)
        return true;
    if (strcmp(symbol, "math.exp") == 0)
        return true;
    if (strcmp(symbol, "math.min") == 0)
        return true;
    if (strcmp(symbol, "math.max") == 0)
        return true;
    if (strcmp(symbol, "math.clamp") == 0)
        return true;
    if (strcmp(symbol, "math.sign") == 0)
        return true;
    if (strcmp(symbol, "math.sinh") == 0)
        return true;
    if (strcmp(symbol, "math.cosh") == 0)
        return true;
    if (strcmp(symbol, "math.tanh") == 0)
        return true;
    if (strcmp(symbol, "math.hypot") == 0)
        return true;
    if (strcmp(symbol, "math.cbrt") == 0)
        return true;
    if (strcmp(symbol, "math.trunc") == 0)
        return true;
    if (strcmp(symbol, "math.fmod") == 0)
        return true;
    if (strcmp(symbol, "math.log1p") == 0)
        return true;
    if (strcmp(symbol, "math.expm1") == 0)
        return true;
    if (strcmp(symbol, "math.lerp") == 0)
        return true;
    if (strcmp(symbol, "math.degToRad") == 0)
        return true;
    if (strcmp(symbol, "math.radToDeg") == 0)
        return true;
    if (strcmp(symbol, "math.isNaN") == 0)
        return true;
    if (strcmp(symbol, "math.isFinite") == 0)
        return true;
    return false;
}

static bool xaot_stdlib_generated_symbol_is_constant(const char *symbol) {
    if (!symbol)
        return false;
    if (strcmp(symbol, "math.PI") == 0)
        return true;
    if (strcmp(symbol, "math.E") == 0)
        return true;
    if (strcmp(symbol, "math.TAU") == 0)
        return true;
    if (strcmp(symbol, "math.SQRT2") == 0)
        return true;
    if (strcmp(symbol, "math.LN2") == 0)
        return true;
    if (strcmp(symbol, "math.LN10") == 0)
        return true;
    if (strcmp(symbol, "math.LOG2E") == 0)
        return true;
    if (strcmp(symbol, "math.LOG10E") == 0)
        return true;
    if (strcmp(symbol, "math.EPSILON") == 0)
        return true;
    if (strcmp(symbol, "math.MAX_I64") == 0)
        return true;
    if (strcmp(symbol, "math.MIN_I64") == 0)
        return true;
    if (strcmp(symbol, "math.MAX_F64") == 0)
        return true;
    if (strcmp(symbol, "math.INF") == 0)
        return true;
    if (strcmp(symbol, "math.NAN") == 0)
        return true;
    return false;
}

static bool xaot_stdlib_generated_symbol_is_freestanding_header_only(
    const char *symbol) {
    if (!symbol)
        return false;
    if (strcmp(symbol, "math.PI") == 0)
        return true;
    if (strcmp(symbol, "math.E") == 0)
        return true;
    if (strcmp(symbol, "math.TAU") == 0)
        return true;
    if (strcmp(symbol, "math.SQRT2") == 0)
        return true;
    if (strcmp(symbol, "math.LN2") == 0)
        return true;
    if (strcmp(symbol, "math.LN10") == 0)
        return true;
    if (strcmp(symbol, "math.LOG2E") == 0)
        return true;
    if (strcmp(symbol, "math.LOG10E") == 0)
        return true;
    if (strcmp(symbol, "math.EPSILON") == 0)
        return true;
    if (strcmp(symbol, "math.MAX_I64") == 0)
        return true;
    if (strcmp(symbol, "math.MIN_I64") == 0)
        return true;
    if (strcmp(symbol, "math.MAX_F64") == 0)
        return true;
    if (strcmp(symbol, "math.INF") == 0)
        return true;
    if (strcmp(symbol, "math.NAN") == 0)
        return true;
    if (strcmp(symbol, "math.min") == 0)
        return true;
    if (strcmp(symbol, "math.max") == 0)
        return true;
    if (strcmp(symbol, "math.clamp") == 0)
        return true;
    if (strcmp(symbol, "mem.__fence") == 0)
        return true;
    if (strcmp(symbol, "mem.__prefetch") == 0)
        return true;
    if (strcmp(symbol, "mem.__cacheFlush") == 0)
        return true;
    if (strcmp(symbol, "mem.__cacheInvalidate") == 0)
        return true;
    if (strcmp(symbol, "mem.__nontemporalStore") == 0)
        return true;
    if (strcmp(symbol, "mem.__cacheLineSize") == 0)
        return true;
    if (strcmp(symbol, "mem.sizeOf") == 0)
        return true;
    if (strcmp(symbol, "mem.alignOf") == 0)
        return true;
    if (strcmp(symbol, "mem.offsetOf") == 0)
        return true;
    if (strcmp(symbol, "mem.__alloc") == 0)
        return true;
    if (strcmp(symbol, "mem.__allocZeroed") == 0)
        return true;
    if (strcmp(symbol, "mem.__allocAligned") == 0)
        return true;
    if (strcmp(symbol, "mem.ptr") == 0)
        return true;
    if (strcmp(symbol, "mem.mutPtr") == 0)
        return true;
    if (strcmp(symbol, "mem.addr") == 0)
        return true;
    if (strcmp(symbol, "mem.load") == 0)
        return true;
    if (strcmp(symbol, "mem.store") == 0)
        return true;
    if (strcmp(symbol, "mem.__copy") == 0)
        return true;
    if (strcmp(symbol, "mem.__move") == 0)
        return true;
    if (strcmp(symbol, "mem.__set") == 0)
        return true;
    if (strcmp(symbol, "mem.__compare") == 0)
        return true;
    if (strcmp(symbol, "mem.__volatileLoad") == 0)
        return true;
    if (strcmp(symbol, "mem.__volatileStore") == 0)
        return true;
    return false;
}

/* clang-format on */
