/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/stdlibgen/stdlibgen.py
 *
 * xaot_stdlib_generated.inc.c - AOT stdlib driver metadata
 */

/* clang-format off */

enum {
    XAOT_STDLIB_CAP_CORO = 1u << 0,
    XAOT_STDLIB_CAP_TIMER = 1u << 1,
    XAOT_STDLIB_CAP_CHANNEL = 1u << 2,
    XAOT_STDLIB_CAP_NETPOLL = 1u << 3,
    XAOT_STDLIB_CAP_TASK = 1u << 4,
    XAOT_STDLIB_CAP_WORK_QUEUE = 1u << 5,
    XAOT_STDLIB_CAP_RESULT_GROUP = 1u << 6,
    XAOT_STDLIB_CAP_OBJECTS = 1u << 7,
    XAOT_STDLIB_CAP_DEEP_COPY = 1u << 8,
    XAOT_STDLIB_CAP_EXCEPTION = 1u << 9,
    XAOT_STDLIB_CAP_REFLECTION = 1u << 10,
    XAOT_STDLIB_CAP_STACKTRACE = 1u << 11,
    XAOT_STDLIB_CAP_INSTANCEOF = 1u << 12,
    XAOT_STDLIB_CAP_SCOPE = 1u << 13,
};

static const char *xaot_stdlib_generated_object_for_symbol(const char *symbol) {
    if (!symbol)
        return NULL;
    if (strcmp(symbol, "time.now") == 0)
        return "time.now";
    if (strcmp(symbol, "time.clock") == 0)
        return "time.clock";
    if (strcmp(symbol, "time.monotonic") == 0)
        return "time.monotonic";
    if (strcmp(symbol, "time.nanos") == 0)
        return "time.nanos";
    if (strcmp(symbol, "time.micros") == 0)
        return "time.micros";
    if (strcmp(symbol, "time.sleep") == 0)
        return "time";
    if (strcmp(symbol, "math.random") == 0)
        return "math.random";
    if (strcmp(symbol, "math.randomInt") == 0)
        return "math.randomInt";
    if (strcmp(symbol, "compress.gzip") == 0)
        return "compress.gzip";
    if (strcmp(symbol, "compress.gunzip") == 0)
        return "compress.gunzip";
    if (strcmp(symbol, "compress.deflate") == 0)
        return "compress.deflate";
    if (strcmp(symbol, "compress.inflate") == 0)
        return "compress.inflate";
    if (strcmp(symbol, "compress.zlibCompress") == 0)
        return "compress.zlibCompress";
    if (strcmp(symbol, "compress.zlibDecompress") == 0)
        return "compress.zlibDecompress";
    if (strcmp(symbol, "compress.isGzip") == 0)
        return "compress.isGzip";
    if (strcmp(symbol, "compress.isZlib") == 0)
        return "compress.isZlib";
    if (strcmp(symbol, "crypto.md5") == 0)
        return "crypto.md5";
    if (strcmp(symbol, "crypto.sha1") == 0)
        return "crypto.sha1";
    if (strcmp(symbol, "crypto.sha256") == 0)
        return "crypto.sha256";
    if (strcmp(symbol, "crypto.sha512") == 0)
        return "crypto.sha512";
    if (strcmp(symbol, "crypto.hmac") == 0)
        return "crypto.hmac";
    if (strcmp(symbol, "crypto.randomBytes") == 0)
        return "crypto.randomBytes";
    if (strcmp(symbol, "crypto.uuid") == 0)
        return "crypto.uuid";
    if (strcmp(symbol, "crypto.encrypt") == 0)
        return "crypto.encrypt";
    if (strcmp(symbol, "crypto.decrypt") == 0)
        return "crypto.decrypt";
    if (strcmp(symbol, "regex.compile") == 0)
        return "regex.compile";
    if (strcmp(symbol, "regex.test") == 0)
        return "regex.test";
    if (strcmp(symbol, "regex.count") == 0)
        return "regex.count";
    if (strcmp(symbol, "regex.findText") == 0)
        return "regex.findText";
    if (strcmp(symbol, "regex.findGroup") == 0)
        return "regex.findGroup";
    if (strcmp(symbol, "regex.find") == 0)
        return "regex.find";
    if (strcmp(symbol, "regex.fullFind") == 0)
        return "regex.fullFind";
    if (strcmp(symbol, "regex.findAll") == 0)
        return "regex.findAll";
    if (strcmp(symbol, "regex.replace") == 0)
        return "regex.replace";
    if (strcmp(symbol, "regex.replaceAll") == 0)
        return "regex.replaceAll";
    if (strcmp(symbol, "regex.split") == 0)
        return "regex.split";
    if (strcmp(symbol, "regex.isValid") == 0)
        return "regex.isValid";
    return NULL;
}

static const char *xaot_stdlib_generated_define_for_symbol(const char *symbol) {
    if (!symbol)
        return NULL;
    if (strcmp(symbol, "regex.compile") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.test") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.count") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.findText") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.findGroup") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.find") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.fullFind") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.findAll") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.replace") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.replaceAll") == 0)
        return "XRT_ENABLE_REGEX";
    if (strcmp(symbol, "regex.split") == 0)
        return "XRT_ENABLE_REGEX";
    return NULL;
}

static uint32_t xaot_stdlib_generated_caps_for_symbol(const char *symbol) {
    if (!symbol)
        return 0;
    if (strcmp(symbol, "time.sleep") == 0)
        return XAOT_STDLIB_CAP_CORO | XAOT_STDLIB_CAP_TIMER;
    return 0;
}

static bool xaot_stdlib_generated_symbol_is_builtin_direct(const char *symbol) {
    if (!symbol)
        return false;
    if (strcmp(symbol, "math.abs") == 0)
        return true;
    if (strcmp(symbol, "math.floor") == 0)
        return true;
    if (strcmp(symbol, "math.ceil") == 0)
        return true;
    if (strcmp(symbol, "math.round") == 0)
        return true;
    if (strcmp(symbol, "math.sqrt") == 0)
        return true;
    if (strcmp(symbol, "math.pow") == 0)
        return true;
    if (strcmp(symbol, "math.sin") == 0)
        return true;
    if (strcmp(symbol, "math.cos") == 0)
        return true;
    if (strcmp(symbol, "math.tan") == 0)
        return true;
    if (strcmp(symbol, "math.asin") == 0)
        return true;
    if (strcmp(symbol, "math.acos") == 0)
        return true;
    if (strcmp(symbol, "math.atan") == 0)
        return true;
    if (strcmp(symbol, "math.atan2") == 0)
        return true;
    if (strcmp(symbol, "math.log") == 0)
        return true;
    if (strcmp(symbol, "math.log10") == 0)
        return true;
    if (strcmp(symbol, "math.log2") == 0)
        return true;
    if (strcmp(symbol, "math.exp") == 0)
        return true;
    if (strcmp(symbol, "math.min") == 0)
        return true;
    if (strcmp(symbol, "math.max") == 0)
        return true;
    if (strcmp(symbol, "math.clamp") == 0)
        return true;
    if (strcmp(symbol, "math.sign") == 0)
        return true;
    if (strcmp(symbol, "math.sinh") == 0)
        return true;
    if (strcmp(symbol, "math.cosh") == 0)
        return true;
    if (strcmp(symbol, "math.tanh") == 0)
        return true;
    if (strcmp(symbol, "math.hypot") == 0)
        return true;
    if (strcmp(symbol, "math.cbrt") == 0)
        return true;
    if (strcmp(symbol, "math.trunc") == 0)
        return true;
    if (strcmp(symbol, "math.fmod") == 0)
        return true;
    if (strcmp(symbol, "math.log1p") == 0)
        return true;
    if (strcmp(symbol, "math.expm1") == 0)
        return true;
    if (strcmp(symbol, "math.lerp") == 0)
        return true;
    if (strcmp(symbol, "math.degToRad") == 0)
        return true;
    if (strcmp(symbol, "math.radToDeg") == 0)
        return true;
    if (strcmp(symbol, "math.isNaN") == 0)
        return true;
    if (strcmp(symbol, "math.isFinite") == 0)
        return true;
    return false;
}

static bool xaot_stdlib_generated_symbol_is_constant(const char *symbol) {
    if (!symbol)
        return false;
    if (strcmp(symbol, "math.PI") == 0)
        return true;
    if (strcmp(symbol, "math.E") == 0)
        return true;
    if (strcmp(symbol, "math.TAU") == 0)
        return true;
    if (strcmp(symbol, "math.SQRT2") == 0)
        return true;
    if (strcmp(symbol, "math.LN2") == 0)
        return true;
    if (strcmp(symbol, "math.LN10") == 0)
        return true;
    if (strcmp(symbol, "math.LOG2E") == 0)
        return true;
    if (strcmp(symbol, "math.LOG10E") == 0)
        return true;
    if (strcmp(symbol, "math.EPSILON") == 0)
        return true;
    if (strcmp(symbol, "math.MAX_INT") == 0)
        return true;
    if (strcmp(symbol, "math.MIN_INT") == 0)
        return true;
    if (strcmp(symbol, "math.MAX_FLOAT") == 0)
        return true;
    if (strcmp(symbol, "math.INF") == 0)
        return true;
    if (strcmp(symbol, "math.NAN") == 0)
        return true;
    if (strcmp(symbol, "path.sep") == 0)
        return true;
    if (strcmp(symbol, "path.delimiter") == 0)
        return true;
    if (strcmp(symbol, "encoding.LE") == 0)
        return true;
    if (strcmp(symbol, "encoding.BE") == 0)
        return true;
    if (strcmp(symbol, "os.platform") == 0)
        return true;
    if (strcmp(symbol, "os.arch") == 0)
        return true;
    if (strcmp(symbol, "os.sep") == 0)
        return true;
    if (strcmp(symbol, "os.eol") == 0)
        return true;
    if (strcmp(symbol, "log.DEBUG") == 0)
        return true;
    if (strcmp(symbol, "log.INFO") == 0)
        return true;
    if (strcmp(symbol, "log.WARN") == 0)
        return true;
    if (strcmp(symbol, "log.ERROR") == 0)
        return true;
    if (strcmp(symbol, "log.FATAL") == 0)
        return true;
    return false;
}

/* clang-format on */
