/* AUTO-GENERATED by xisagen - DO NOT EDIT */
/* Source: xisa/aot/abi.def */

#ifndef XAOT_ABI_GEN_H
#define XAOT_ABI_GEN_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "../runtime/value/xtype.h"
#include "xaot_rep_gen.h"

typedef enum {
    XAOT_ABI_CLASS_SCALAR = 0,
    XAOT_ABI_CLASS_VOID = 1,
    XAOT_ABI_CLASS_POINTER = 2,
    XAOT_ABI_CLASS_COUNT
} XaotAbiClass;

typedef struct {
    const char *name;
    XrTypeKind type_kind;
    uint8_t abi_class;
    XaotRep default_rep;
    bool allows_nullable;
    bool uses_native_width;
    bool typed_boundary;
} XaotAbiInfo;

#define XAOT_ABI_ENTRIES(X) \
    X(INT, "int", XR_KIND_INT, XAOT_ABI_CLASS_SCALAR, XAOT_REP_I64, false, true, true) \
    X(FLOAT, "float", XR_KIND_FLOAT, XAOT_ABI_CLASS_SCALAR, XAOT_REP_F64, false, true, true) \
    X(BOOL, "bool", XR_KIND_BOOL, XAOT_ABI_CLASS_SCALAR, XAOT_REP_BOOL, false, false, true) \
    X(UNIT, "unit", XR_KIND_UNIT, XAOT_ABI_CLASS_VOID, XAOT_REP_VOID, false, false, false) \
    X(STRING, "string", XR_KIND_STRING, XAOT_ABI_CLASS_POINTER, XAOT_REP_PTR, false, false, true) \
    X(ARRAY, "array", XR_KIND_ARRAY, XAOT_ABI_CLASS_POINTER, XAOT_REP_PTR, false, false, true) \
    X(MAP, "map", XR_KIND_MAP, XAOT_ABI_CLASS_POINTER, XAOT_REP_PTR, false, false, true) \
    X(SET, "set", XR_KIND_SET, XAOT_ABI_CLASS_POINTER, XAOT_REP_PTR, false, false, true) \
    X(TUPLE, "tuple", XR_KIND_TUPLE, XAOT_ABI_CLASS_POINTER, XAOT_REP_PTR, false, false, true) \
    X(POINTER, "pointer", XR_KIND_POINTER, XAOT_ABI_CLASS_SCALAR, XAOT_REP_I64, false, false, true)


static inline const XaotAbiInfo *xaot_abi_for_type_kind(XrTypeKind kind) {
    static const XaotAbiInfo table[] = {
        {"int", XR_KIND_INT,
         XAOT_ABI_CLASS_SCALAR,
         XAOT_REP_I64, false,
         true, true},
        {"float", XR_KIND_FLOAT,
         XAOT_ABI_CLASS_SCALAR,
         XAOT_REP_F64, false,
         true, true},
        {"bool", XR_KIND_BOOL,
         XAOT_ABI_CLASS_SCALAR,
         XAOT_REP_BOOL, false,
         false, true},
        {"unit", XR_KIND_UNIT,
         XAOT_ABI_CLASS_VOID,
         XAOT_REP_VOID, false,
         false, false},
        {"string", XR_KIND_STRING,
         XAOT_ABI_CLASS_POINTER,
         XAOT_REP_PTR, false,
         false, true},
        {"array", XR_KIND_ARRAY,
         XAOT_ABI_CLASS_POINTER,
         XAOT_REP_PTR, false,
         false, true},
        {"map", XR_KIND_MAP,
         XAOT_ABI_CLASS_POINTER,
         XAOT_REP_PTR, false,
         false, true},
        {"set", XR_KIND_SET,
         XAOT_ABI_CLASS_POINTER,
         XAOT_REP_PTR, false,
         false, true},
        {"tuple", XR_KIND_TUPLE,
         XAOT_ABI_CLASS_POINTER,
         XAOT_REP_PTR, false,
         false, true},
        {"pointer", XR_KIND_POINTER,
         XAOT_ABI_CLASS_SCALAR,
         XAOT_REP_I64, false,
         false, true},
    };
    for (unsigned i = 0; i < sizeof(table) / sizeof(table[0]); i++) {
        if (table[i].type_kind == kind)
            return &table[i];
    }
    return NULL;
}

static inline XaotRep xaot_abi_rep_for_type(const XrType *type) {
    const XaotAbiInfo *abi;
    XaotRep rep;
    if (!type)
        return XAOT_REP_TAGGED;
    abi = xaot_abi_for_type_kind(type->kind);
    if (!abi || (type->is_nullable && !abi->allows_nullable))
        return XAOT_REP_TAGGED;
    if (abi->uses_native_width && type->native_width != 0 &&
        xaot_rep_from_native_type(type->native_width, &rep))
        return rep;
    return abi->default_rep;
}

static inline XrRep xaot_abi_storage_rep_for_type(const XrType *type) {
    const XaotRepInfo *info = xaot_rep_info(xaot_abi_rep_for_type(type));
    return info ? info->storage_rep : XR_REP_TAGGED;
}

static inline bool xaot_abi_type_can_use_typed_boundary(const XrType *type) {
    const XaotAbiInfo *abi;
    XrRep storage;
    if (!type)
        return false;
    abi = xaot_abi_for_type_kind(type->kind);
    if (!abi || !abi->typed_boundary || (type->is_nullable && !abi->allows_nullable))
        return false;
    storage = xaot_abi_storage_rep_for_type(type);
    return storage == XR_REP_I64 || storage == XR_REP_F64 || storage == XR_REP_PTR;
}

#endif  /* XAOT_ABI_GEN_H */
