/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 *
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * xi_cgen_stdlib_helpers.inc.c - AOT direct-call dispatch for runtime stdlib
 *
 * Recognizes `<module>.<method>(...)` calls whose receiver resolves to a
 * runtime stdlib module import and emits a direct call to the matching
 * isolate-free helper, bypassing the tagged runtime module table. Pure helpers
 * can live in the freestanding AOT runtime (xrt_*) while runtime-backed
 * helpers may still be local extern shims.
 *
 * This is the general, table-driven successor to the bespoke math/time AOT
 * paths: new functions are added as data rows, not new code paths. A module
 * that appears here is fully "claimed" for AOT — any unsupported method on it
 * raises a clean codegen error rather than silently dispatching on the
 * XR_NULL_VAL module placeholder.
 */

/* How a shim returns its result. */
typedef enum {
    CG_AOT_RET_VALUE,        /* tagged XrValue, converted to the call's rep */
    CG_AOT_RET_I64,          /* unboxed int64_t, converted to the call's rep */
    CG_AOT_RET_ENUM_I64,     /* enum ordinal; boxed only at a tagged boundary */
    CG_AOT_RET_STR_BORROWED, /* (const char *data, int64_t *out_len) slice into an
                              * input/static buffer; copied into an AOT string */
} CgAotRetKind;

#define CG_AOT_STDLIB_VARIADIC UINT16_MAX

typedef struct CgAotStdlibMethod {
    /* All const char* rows below are owned: static string literals from the
     * generated xstdlib_aot_methods_generated.inc.c table (program lifetime). */
    const char *module; /* owned: static literal; stdlib module identifier (e.g. "path") */
    const char *method; /* owned: static literal; method name (e.g. "isAbsolute") */
    uint16_t argc;      /* argument count excluding the receiver */
    const char *shim;   /* owned: static literal; xr_aot_<module>_<method> runtime symbol */
    /* One character per argument describing how it is passed to the shim:
     *   's' = string, lowered to specialized (const char *data, int64_t len)
     *   'p' = Path owner, lowered to specialized (const char *data, int64_t len)
     *   'v' = tagged XrValue passed as-is
     *   'i' = opaque int handle, passed as a tagged XrValue like 'v'
     *   '*' = variadic strings, lowered to (argc, data[], len[])
     * stdlibgen rejects rows whose spec length differs from the fixed argc, so
     * a fixed-arity spec always covers every argument position. */
    const char *arg_spec; /* owned: static literal (generated table) */
    /* One generated byte per fixed argument: 'w' projects a private source
     * wrapper to its provider storage and '.' passes the value through. NULL
     * is reserved for variadic rows, which may not use provider bridges. */
    const char *source_provider_arg_spec; /* owned: static literal */
    CgAotRetKind ret_kind;
    const char *extern_decl; /* owned: static literal; forward decl emitted into generated C */
    /* `enum_*` describes the enum returned by CG_AOT_RET_ENUM_I64. */
    uint32_t enum_layout_id;
    const char *enum_name;            /* owned: static literal; generated enum name */
    const char *const *variant_names; /* owned: static generated literal table */
    uint16_t variant_count;
} CgAotStdlibMethod;

typedef enum CgNativeDirectEmissionStatus {
    CG_NATIVE_DIRECT_EMISSION_UNCOVERED = 0,
    CG_NATIVE_DIRECT_EMISSION_EXACT,
    CG_NATIVE_DIRECT_EMISSION_INVALID,
} CgNativeDirectEmissionStatus;

typedef struct CgNativeDirectEmissionView {
    const XrStdlibDefEntry *entry;
    const CgAotStdlibMethod *method;
    const XrSemanticOperationRecord *operation;
    const XrTargetCallRecord *call;
    const XrTargetCallArgumentRecord *arguments;
} CgNativeDirectEmissionView;

#include "xstdlib_aot_methods_generated.inc.c"

static const CgAotStdlibMethod *cg_aot_stdlib_generated_method_at(int index) {
    if (index < 0 || index >= CG_AOT_STDLIB_GENERATED_METHOD_COUNT)
        return NULL;
    return &g_aot_stdlib_generated_methods[index];
}

static const CgAotStdlibMethod *cg_aot_stdlib_method_at(int index) {
    return cg_aot_stdlib_generated_method_at(index);
}

static const CgAotStdlibMethod *cg_find_aot_stdlib_method(const char *module, const char *method,
                                                          uint16_t argc);

static bool cg_native_direct_call_identity(XrStableId target, XrStableId native,
                                           uint32_t capabilities, XrStableId *out) {
    char target_hex[XR_STABLE_ID_BYTES * 2u + 1u];
    char native_hex[XR_STABLE_ID_BYTES * 2u + 1u];
    char key[192];
    XrFingerprint digest;
    xr_stable_id_hex(target, target_hex);
    xr_stable_id_hex(native, native_hex);
    int length =
        snprintf(key, sizeof(key), "xray-target-native-direct-v2:first=%s:second=%s:ordinal=%u",
                 target_hex, native_hex, capabilities);
    return out && length > 0 && (size_t) length < sizeof(key) &&
           xr_stable_id_from_key(key, out, &digest);
}

/* Rebind one live Xi call to the immutable SemanticPlan/TargetPlan authority
 * before exposing the generated shim row to emission.  The generated registry
 * is implementation data, not authorization: it may classify a candidate so
 * malformed native-direct sites fail closed, but it can never select a shim on
 * its own. */
static CgNativeDirectEmissionStatus
cg_native_direct_emission_view(XiCgenCtx *ctx, const XiFunc *function, const XiValue *value,
                               CgNativeDirectEmissionView *out) {
    if (out)
        memset(out, 0, sizeof(*out));
    if (!ctx || !function || !value || value->op != XI_CALL || value->nargs < 1 || !value->args)
        return CG_NATIVE_DIRECT_EMISSION_UNCOVERED;

    const XiValue *callee = cg_unwrap_identity_value(value->args[0]);
    const XiImportRef *ref = (callee && callee->op == XI_IMPORT_REF && callee->aux)
                                 ? (const XiImportRef *) callee->aux
                                 : cg_import_ref_for_value(ctx, function, callee);
    uint16_t argc = (uint16_t) (value->nargs - 1u);
    const XrStdlibDefEntry *candidate =
        ref && ref->module_path && ref->member_name
            ? xr_stdlib_metadata_exact_native_direct_call(ref->module_path, ref->member_name, argc)
            : NULL;
    if (!candidate)
        return CG_NATIVE_DIRECT_EMISSION_UNCOVERED;

    const CgValueEmissionRegistryEntry *authority = NULL;
    for (uint32_t i = 0; i < ctx->value_emission_registry_count; i++) {
        if (ctx->value_emission_registry[i].semantic_plan != function->semantic_plan)
            continue;
        if (authority)
            goto invalid;
        authority = &ctx->value_emission_registry[i];
    }
    if (!authority || !authority->semantic_plan || !authority->target_plan ||
        !xr_target_plan_is_verified(authority->target_plan) ||
        !xr_target_plan_fingerprint_is_intact(authority->target_plan))
        goto invalid;

    const XrSemanticOperationRecord *operation =
        cg_semantic_operation_for_value(ctx, function, value);
    const XrStdlibDefEntry *entry = NULL;
    XrStableId native_identity = {{0}};
    if (!operation || operation->function != function->semantic_plan_function_index ||
        !xr_semantic_native_direct_call_shape_is_exact(authority->semantic_plan, operation, &entry,
                                                       &native_identity) ||
        entry != candidate)
        goto invalid;

    uint32_t semantic_operand_count = 0;
    const XrSemanticOperandRecord *semantic_operands =
        xr_semantic_plan_operands(authority->semantic_plan, &semantic_operand_count);
    if (!semantic_operands || operation->operand_count != (uint16_t) (argc + 1u) ||
        operation->operand_begin > semantic_operand_count ||
        operation->operand_count > semantic_operand_count - operation->operand_begin)
        goto invalid;

    uint32_t live_callee = XR_SEMANTIC_INDEX_NONE;
    if (!cg_value_semantic_id(ctx, function, value->args[0], &live_callee) ||
        live_callee != semantic_operands[operation->operand_begin].value)
        goto invalid;

    uint32_t call_count = 0;
    uint32_t argument_count = 0;
    const XrTargetCallRecord *calls = xr_target_plan_calls(authority->target_plan, &call_count);
    const XrTargetCallArgumentRecord *arguments =
        xr_target_plan_call_arguments(authority->target_plan, &argument_count);
    uint32_t target_partition = UINT32_MAX;
    uint32_t partition_count = 0;
    const XrTargetModulePartitionRecord *partitions =
        xr_target_plan_module_partitions(authority->target_plan, &partition_count);
    if (!xr_target_plan_partition_for_semantic(authority->target_plan, authority->semantic_plan,
                                               &target_partition))
        goto invalid;
    uint32_t call_begin = 0;
    uint32_t call_end = call_count;
    uint32_t argument_begin = 0;
    uint32_t argument_end = argument_count;
    uint32_t function_begin = 0;
    uint32_t function_count = (uint32_t) xr_semantic_plan_function_count(authority->semantic_plan);
    if (partition_count != 0) {
        if (!partitions || target_partition >= partition_count)
            goto invalid;
        const XrTargetModulePartitionRecord *partition = &partitions[target_partition];
        if (partition->calls_begin > call_count ||
            partition->calls_count > call_count - partition->calls_begin ||
            partition->call_arguments_begin > argument_count ||
            partition->call_arguments_count > argument_count - partition->call_arguments_begin ||
            operation->function >= partition->functions_count)
            goto invalid;
        call_begin = partition->calls_begin;
        call_end = call_begin + partition->calls_count;
        argument_begin = partition->call_arguments_begin;
        argument_end = argument_begin + partition->call_arguments_count;
        function_begin = partition->functions_begin;
        function_count = partition->functions_count;
    }
    if (operation->function >= function_count || function_begin > UINT32_MAX - operation->function)
        goto invalid;
    uint32_t target_function = function_begin + operation->function;
    const XrTargetCallRecord *call = NULL;
    uint32_t operation_index = XR_SEMANTIC_INDEX_NONE;
    uint32_t operation_count =
        (uint32_t) xr_semantic_plan_operation_count(authority->semantic_plan);
    for (uint32_t i = 0; i < operation_count; i++) {
        if (xr_semantic_plan_operation(authority->semantic_plan, i) != operation)
            continue;
        if (operation_index != XR_SEMANTIC_INDEX_NONE)
            goto invalid;
        operation_index = i;
    }
    if (operation_index == XR_SEMANTIC_INDEX_NONE)
        goto invalid;
    for (uint32_t i = call_begin; calls && i < call_end; i++) {
        if (calls[i].semantic_operation != operation_index)
            continue;
        if (call)
            goto invalid;
        call = &calls[i];
    }
    const XrSemanticCallTargetRecord *target =
        call && call->semantic_call_target != XR_SEMANTIC_INDEX_NONE
            ? xr_semantic_plan_call_target(authority->semantic_plan, call->semantic_call_target)
            : NULL;
    XrStableId expected_call_identity = {{0}};
    if (!call || !target || target->kind != XR_SEM_CALL_TARGET_NATIVE_DIRECT ||
        target->operation != operation_index || call->id >= call_count ||
        &calls[call->id] != call || call->semantic_operation != operation_index ||
        !cg_native_direct_call_identity(target->id, native_identity, entry->runtime_capabilities,
                                        &expected_call_identity) ||
        !xr_stable_id_equal(call->identity, expected_call_identity) ||
        call->caller_function != target_function ||
        call->callee_function != XR_SEMANTIC_INDEX_NONE ||
        call->source_dependency != XR_SEMANTIC_INDEX_NONE ||
        call->source_export != XR_SEMANTIC_INDEX_NONE ||
        !xr_stable_id_equal(call->native_callee_identity, native_identity) ||
        call->runtime_capabilities != entry->runtime_capabilities ||
        call->calling_convention != XR_TARGET_CALL_CONVENTION_NATIVE_DIRECT ||
        call->target_kind != XR_TARGET_CALL_TARGET_NATIVE_DIRECT || call->argument_count != argc ||
        call->argument_begin < argument_begin || call->argument_begin > argument_end ||
        call->argument_count > argument_end - call->argument_begin || call->adapter_count != 0 ||
        call->flags != 0)
        goto invalid;

    uint32_t live_result = XR_SEMANTIC_INDEX_NONE;
    const XrTargetValueRepRecord *result = xr_target_plan_value_rep_for_module(
        authority->target_plan, target_partition, operation->result_value);
    const XrTargetMachineRepRecord *result_register =
        result ? xr_target_plan_machine_rep(authority->target_plan, result->register_rep) : NULL;
    const XrTargetMachineRepRecord *result_memory =
        result ? xr_target_plan_machine_rep(authority->target_plan, result->memory_rep) : NULL;
    XrSemanticNativeDirectResultKind result_kind =
        xr_semantic_native_direct_result_kind(authority->semantic_plan, operation, entry);
    if (!cg_value_semantic_id(ctx, function, value, &live_result) ||
        live_result != operation->result_value || !result ||
        result->semantic_value != operation->result_value ||
        call->result_value != operation->result_value || call->result_slot != result->slot ||
        call->result_register_rep != result->register_rep ||
        call->result_memory_rep != result->memory_rep || !result_register || !result_memory)
        goto invalid;
    if (result_kind == XR_SEM_NATIVE_DIRECT_RESULT_FRESH_NULLABLE_NATIVE) {
        uint32_t slot_count = 0;
        const XrTargetSlotRecord *slots = xr_target_plan_slots(authority->target_plan, &slot_count);
        const XrTargetSlotRecord *slot =
            slots && result->slot < slot_count ? &slots[result->slot] : NULL;
        if (call->result_mode != XR_TARGET_CALL_VALUE ||
            call->result_ownership != XR_TARGET_CALL_RETURN_OWNED ||
            result_register->kind != XR_MACHINE_REP_DYN_VALUE ||
            result_memory->kind != XR_MACHINE_REP_DYN_VALUE ||
            result_register->root_kind != XR_TARGET_ROOT_DYNAMIC ||
            result_memory->root_kind != XR_TARGET_ROOT_DYNAMIC ||
            result_register->ownership != XR_TARGET_OWNERSHIP_OWNED ||
            result_memory->ownership != XR_TARGET_OWNERSHIP_OWNED || !slot ||
            slot->semantic_value != operation->result_value ||
            slot->semantic_operation != operation_index || slot->function != target_function ||
            slot->role != XR_TARGET_SLOT_TEMPORARY || slot->register_rep != result->register_rep ||
            slot->memory_rep != result->memory_rep || slot->root_kind != XR_TARGET_ROOT_DYNAMIC ||
            slot->ownership != XR_TARGET_OWNERSHIP_OWNED ||
            cg_value_plan_storage_rep(ctx, value) != XR_REP_TAGGED)
            goto invalid;
    } else if (result_kind != XR_SEM_NATIVE_DIRECT_RESULT_TRIVIAL ||
               call->result_mode != XR_TARGET_CALL_VALUE ||
               call->result_ownership != XR_TARGET_CALL_NONE) {
        goto invalid;
    }

    for (uint16_t ordinal = 0; ordinal < argc; ordinal++) {
        uint32_t semantic_operand = operation->operand_begin + 1u + ordinal;
        const XrSemanticOperandRecord *operand = &semantic_operands[semantic_operand];
        const XrTargetCallArgumentRecord *argument = &arguments[call->argument_begin + ordinal];
        uint32_t live_argument = XR_SEMANTIC_INDEX_NONE;
        const XrTargetMachineRepRecord *callee_register =
            xr_target_plan_machine_rep(authority->target_plan, argument->callee_register_rep);
        const XrTargetMachineRepRecord *callee_memory =
            xr_target_plan_machine_rep(authority->target_plan, argument->callee_memory_rep);
        if (!cg_value_semantic_id(ctx, function, value->args[ordinal + 1u], &live_argument) ||
            live_argument != operand->value || argument->call != call->id ||
            argument->semantic_operand != semantic_operand ||
            argument->semantic_value != operand->value ||
            argument->callee_parameter != XR_SEMANTIC_INDEX_NONE ||
            argument->callee_slot != XR_SEMANTIC_INDEX_NONE || argument->ordinal != ordinal ||
            argument->mode != XR_TARGET_CALL_VALUE || argument->ownership != XR_TARGET_CALL_READ ||
            argument->transfer_mode != XR_TRANSFER_SHARE || argument->flags != 0 ||
            argument->array_element_storage != XR_TARGET_ARRAY_STORAGE_NONE || !callee_register ||
            !callee_memory || callee_register->kind != XR_MACHINE_REP_DYN_VALUE ||
            callee_memory->kind != XR_MACHINE_REP_DYN_VALUE)
            goto invalid;
    }

    const CgAotStdlibMethod *method =
        cg_find_aot_stdlib_method(entry->module, entry->name, entry->argc);
    if (!method || method->ret_kind != CG_AOT_RET_VALUE || method->argc != entry->argc ||
        strcmp(method->module, entry->module) != 0 || strcmp(method->method, entry->name) != 0 ||
        strcmp(method->shim, entry->aot) != 0 || strcmp(method->arg_spec, entry->arg_spec) != 0)
        goto invalid;

    if (out) {
        out->entry = entry;
        out->method = method;
        out->operation = operation;
        out->call = call;
        out->arguments = argc != 0 ? arguments + call->argument_begin : NULL;
    }
    return CG_NATIVE_DIRECT_EMISSION_EXACT;

invalid:
    if (ctx)
        (void) cg_value_emission_fail(ctx, "native-direct C emission authority is incomplete");
    return CG_NATIVE_DIRECT_EMISSION_INVALID;
}

static int cg_aot_stdlib_method_count(void) {
    return CG_AOT_STDLIB_GENERATED_METHOD_COUNT;
}

static int cg_aot_stdlib_method_index(const CgAotStdlibMethod *method) {
    if (!method)
        return -1;
    for (int i = 0; i < cg_aot_stdlib_method_count(); i++) {
        if (cg_aot_stdlib_method_at(i) == method)
            return i;
    }
    return -1;
}

static bool cg_mark_aot_stdlib_enum_scalar_sidecar(XiCgenCtx *ctx, const CgAotStdlibMethod *method,
                                                   uint32_t *out_index) {
    int index = cg_aot_stdlib_method_index(method);
    int count = cg_aot_stdlib_method_count();
    if (!ctx || index < 0 || method->ret_kind != CG_AOT_RET_ENUM_I64 || !method->enum_name ||
        !method->variant_names || method->variant_count == 0) {
        if (ctx)
            ctx->error = true;
        return false;
    }
    if ((uint32_t) count > ctx->stdlib_enum_scalar_sidecar_cap) {
        uint32_t old_cap = ctx->stdlib_enum_scalar_sidecar_cap;
        uint8_t *used = (uint8_t *) xr_realloc(ctx->stdlib_enum_scalar_sidecar_used,
                                               (size_t) count * sizeof(uint8_t));
        if (!used) {
            ctx->error = true;
            return false;
        }
        memset(used + old_cap, 0, (size_t) count - old_cap);
        ctx->stdlib_enum_scalar_sidecar_used = used;
        ctx->stdlib_enum_scalar_sidecar_cap = (uint32_t) count;
    }
    ctx->stdlib_enum_scalar_sidecar_used[index] = 1;
    if (out_index)
        *out_index = (uint32_t) index;
    return true;
}

static void cg_reset_aot_stdlib_enum_scalar_sidecars(XiCgenCtx *ctx) {
    if (ctx && ctx->stdlib_enum_scalar_sidecar_used && ctx->stdlib_enum_scalar_sidecar_cap > 0)
        memset(ctx->stdlib_enum_scalar_sidecar_used, 0,
               ctx->stdlib_enum_scalar_sidecar_cap * sizeof(uint8_t));
}

static void cg_emit_aot_stdlib_enum_scalar_sidecar_defs(XiCgenCtx *ctx, FILE *out) {
    if (!ctx || !out || !ctx->stdlib_enum_scalar_sidecar_used)
        return;
    const char *module_prefix =
        ctx->module && ctx->module->name && ctx->module->name[0] ? ctx->module->name : "mod";
    int count = cg_aot_stdlib_method_count();
    for (int i = 0; i < count; i++) {
        if ((uint32_t) i >= ctx->stdlib_enum_scalar_sidecar_cap ||
            !ctx->stdlib_enum_scalar_sidecar_used[i])
            continue;
        const CgAotStdlibMethod *method = cg_aot_stdlib_method_at(i);
        if (!method || method->ret_kind != CG_AOT_RET_ENUM_I64 || !method->enum_name ||
            !method->variant_names || method->variant_count == 0) {
            ctx->error = true;
            return;
        }
        fprintf(out, "static const char *const _xaot_stdlib_enum_names_%s_%d[%u] = {",
                module_prefix, i, (unsigned) method->variant_count);
        for (uint16_t variant = 0; variant < method->variant_count; variant++) {
            if (variant > 0)
                fprintf(out, ",");
            emit_c_string_literal(out, method->variant_names[variant]);
        }
        fprintf(out, "};\n");
        fprintf(out,
                "static const XrAotEnumScalarLayout _xaot_stdlib_enum_layout_%s_%d = "
                "{{XR_TENUM_SCALAR_LAYOUT, XR_OBJ_IMMORTAL, XR_RC_STICKY, 0, 0}, ",
                module_prefix, i);
        emit_c_string_literal(out, method->enum_name);
        fprintf(out, ", _xaot_stdlib_enum_names_%s_%d, %u, %u};\n", module_prefix, i,
                (unsigned) method->variant_count, (unsigned) method->enum_layout_id);
        fprintf(out,
                "static XrValue _xaot_stdlib_enum_box_%s_%d(int64_t ordinal) { "
                "if ((uint64_t) ordinal >= UINT64_C(%u)) { "
                "fputs(\"invalid direct stdlib enum ordinal\\n\", stderr); abort(); } "
                "return xrt_enum_scalar_box(&_xaot_stdlib_enum_layout_%s_%d, ordinal); }\n\n",
                module_prefix, i, (unsigned) method->variant_count, module_prefix, i);
    }
}

/* Whether `module` is a stdlib module with AOT direct-call support. The
 * import-ref emitter uses this to materialize the module object as an
 * XR_NULL_VAL placeholder (the real work happens at the call sites). */
static bool cg_module_has_aot_direct_calls(const char *module) {
    if (!module)
        return false;
    if (strcmp(module, "runtime") == 0 || strcmp(module, "test_yield") == 0)
        return true;
    for (int i = 0; i < cg_aot_stdlib_method_count(); i++) {
        const CgAotStdlibMethod *m = cg_aot_stdlib_method_at(i);
        if (m && strcmp(module, m->module) == 0)
            return true;
    }
    return false;
}

static bool cg_aot_stdlib_has_direct_member(const char *module, const char *member) {
    if (!module || !member)
        return false;
    if (strcmp(module, "runtime") == 0 &&
        (strcmp(member, "liveBytes") == 0 || strcmp(member, "liveObjects") == 0 ||
         strcmp(member, "sharedBytes") == 0 || strcmp(member, "staticBytes") == 0 ||
         strcmp(member, "info") == 0))
        return true;
    if (strcmp(module, "test_yield") == 0 &&
        (strcmp(member, "simple") == 0 || strcmp(member, "add") == 0 ||
         strcmp(member, "sync") == 0 || strcmp(member, "blocking_sleep") == 0 ||
         strcmp(member, "counter_inc") == 0 || strcmp(member, "counter_get") == 0 ||
         strcmp(member, "counter_reset") == 0))
        return true;
    for (int i = 0; i < cg_aot_stdlib_method_count(); i++) {
        const CgAotStdlibMethod *m = cg_aot_stdlib_method_at(i);
        if (m && m->module && m->method && strcmp(module, m->module) == 0 &&
            strcmp(member, m->method) == 0)
            return true;
    }
    return false;
}

static bool cg_module_has_aot_generated_constants(const char *module) {
    return cg_aot_stdlib_generated_module_has_constants(module);
}

static bool cg_emit_aot_stdlib_generated_constant_value(XiCgenCtx *ctx, FILE *out, const XiValue *v,
                                                        const CgAotStdlibConst *c) {
    if (!ctx || !out || !v || !c)
        return false;

    if (c->kind == CG_AOT_STDLIB_CONST_I64) {
        const char *conv_suffix =
            emit_conversion_prefix(out, v->type, XR_REP_I64, cg_value_plan_storage_rep(ctx, v));
        if (c->i64_value == INT64_MIN)
            fprintf(out, "INT64_MIN");
        else
            fprintf(out, "INT64_C(%" PRId64 ")", c->i64_value);
        emit_conversion_suffix(out, conv_suffix);
        return true;
    }
    if (c->kind == CG_AOT_STDLIB_CONST_F64 && c->f64_expr && c->f64_expr[0]) {
        const char *conv_suffix =
            emit_conversion_prefix(out, v->type, XR_REP_F64, cg_value_plan_storage_rep(ctx, v));
        fprintf(out, "%s", c->f64_expr);
        emit_conversion_suffix(out, conv_suffix);
        return true;
    }
    if (c->kind == CG_AOT_STDLIB_CONST_HELPER_VALUE && c->helper && c->helper[0]) {
        const char *conv_suffix =
            emit_conversion_prefix(out, v->type, XR_REP_TAGGED, cg_value_plan_storage_rep(ctx, v));
        fprintf(out, "%s()", c->helper);
        emit_conversion_suffix(out, conv_suffix);
        return true;
    }
    return false;
}

static bool cg_emit_aot_stdlib_generated_constant_import_ref(XiCgenCtx *ctx, FILE *out,
                                                             const XiValue *v,
                                                             const XiImportRef *ref) {
    if (!ctx || !out || !v || !ref || !ref->module_path || !ref->member_name)
        return false;
    const CgAotStdlibConst *c =
        cg_aot_stdlib_generated_const_for_member(ref->module_path, ref->member_name);
    return cg_emit_aot_stdlib_generated_constant_value(ctx, out, v, c);
}

/* Validate import resolution independently of value emission.  Release CGen
 * deliberately erases dead import tokens, but link resolution is a program
 * contract and must therefore fail closed even when a token has no emitted C
 * use.  Keep this predicate aligned with xicgen_import_ref's supported
 * resolution classes. */
static bool cg_import_ref_has_aot_resolution(XiCgenCtx *ctx, const XiFunc *f, const XiValue *v,
                                             const XiImportRef *ref) {
    if (!ctx || !f || !v || !ref || !ref->module_path || !ref->module_path[0])
        return false;

    if (ref->resolved_mod_index >= 0 && ref->resolved_mod_index < ctx->all_nmodules &&
        ctx->all_modules && ctx->all_modules[ref->resolved_mod_index]) {
        const XiModule *target = ctx->all_modules[ref->resolved_mod_index];
        if (!ref->member_name)
            return true;
        if (ref->resolved_shared_slot >= 0 && ref->resolved_shared_slot < target->nslots)
            return true;
    }

    for (int i = 0; i < ctx->nimports; i++) {
        const CgImportEntry *binding = &ctx->imports[i];
        if (!binding->module_path || strcmp(binding->module_path, ref->module_path) != 0)
            continue;
        if (!ref->member_name)
            return true;
        if (binding->member_name && strcmp(binding->member_name, ref->member_name) == 0)
            return true;
    }

    if (!ref->member_name &&
        (strcmp(ref->module_path, "time") == 0 || strcmp(ref->module_path, "math") == 0 ||
         strcmp(ref->module_path, "log") == 0 || strcmp(ref->module_path, "parallel") == 0 ||
         cg_module_has_aot_direct_calls(ref->module_path)))
        return true;
    if (xicgen_import_ref_is_core_math_member(ref))
        return true;
    if (ref->member_name &&
        (xa_builtin_get_object_shape(ref->module_path, ref->member_name) ||
         xa_builtin_get_enum_type(ref->module_path, ref->member_name) ||
         cg_aot_stdlib_has_direct_member(ref->module_path, ref->member_name) ||
         cg_aot_stdlib_generated_const_for_member(ref->module_path, ref->member_name)))
        return true;
    return cg_import_ref_has_verified_link_dependency(ctx, ref) &&
           cg_import_ref_value_is_dead_for_aot(ctx, f, v);
}

static bool cg_emit_aot_stdlib_generated_constant_field(XiCgenCtx *ctx, FILE *out, const XiFunc *f,
                                                        const XiValue *v) {
    if (!ctx || !out || !f || !v || v->nargs < 1 || !v->aux)
        return false;

    const char *field = (const char *) v->aux;
    for (int i = 0; i < CG_AOT_STDLIB_GENERATED_CONST_COUNT; i++) {
        const CgAotStdlibConst *c = cg_aot_stdlib_generated_const_at(i);
        if (!c || strcmp(field, c->name) != 0 ||
            !cg_value_is_module_import_ctx(ctx, f, v->args[0], c->module))
            continue;
        return cg_emit_aot_stdlib_generated_constant_value(ctx, out, v, c);
    }
    return false;
}

static bool cg_emit_runtime_control_call(XiCgenCtx *ctx, FILE *out, const XiFunc *f,
                                         const XiValue *v, const char *method, uint16_t argc) {
    /* Only this module's private leaves are answered here.  Its public surface
     * lives in runtime.xr and compiles as an ordinary cross-module call, so an
     * unrecognized name is a fall-through rather than a refusal. */
    if (!method || argc != 0)
        return false;

    const char *aot_ctx = xicgen_aot_context_expr(ctx, f);
    const char *helper = NULL;
    if (strcmp(method, "__liveBytes") == 0)
        helper = "xr_aot_runtime_live_bytes";
    else if (strcmp(method, "__liveObjects") == 0)
        helper = "xr_aot_runtime_live_objects";
    else if (strcmp(method, "__finalizerCount") == 0)
        helper = "xr_aot_runtime_finalizer_count";
    else if (strcmp(method, "__sharedLiveBytes") == 0)
        helper = "xr_aot_runtime_shared_bytes";
    else if (strcmp(method, "__staticAllocBytes") == 0)
        helper = "xr_aot_runtime_static_bytes";
    if (!helper)
        return false;
    const char *suffix =
        emit_conversion_prefix(out, v->type, XR_REP_I64, cg_value_plan_storage_rep(ctx, v));
    fprintf(out, "%s(%s)", helper, aot_ctx);
    emit_conversion_suffix(out, suffix);
    return true;
}

static bool xicgen_emit_runtime_control_method(XiCgenCtx *ctx, FILE *out, const XiFunc *f,
                                               const XiValue *v) {
    if (!v || (v->op != XI_CALL_METHOD && v->op != XI_CALL_METHOD_DIRECT) || v->nargs < 1 ||
        !cg_value_is_module_import_ctx(ctx, f, v->args[0], "runtime"))
        return false;

    return cg_emit_runtime_control_call(ctx, out, f, v, (const char *) v->aux,
                                        (uint16_t) (v->nargs - 1));
}

static bool cg_emit_test_yield_sync_call(XiCgenCtx *ctx, FILE *out, const XiFunc *f,
                                         const XiValue *v, const char *method, uint16_t argc,
                                         uint16_t arg_base) {
    (void) f;
    if (!method)
        return false;

    const char *helper = NULL;
    uint16_t expected_argc = 0;
    if (strcmp(method, "sync") == 0)
        helper = "xr_aot_test_yield_sync";
    else if (strcmp(method, "blocking_sleep") == 0) {
        helper = "xr_aot_test_yield_blocking_sleep";
        expected_argc = 1;
    } else if (strcmp(method, "counter_get") == 0)
        helper = "xr_aot_test_yield_counter_get";
    else if (strcmp(method, "counter_reset") == 0)
        helper = "xr_aot_test_yield_counter_reset";
    else if (strcmp(method, "simple") == 0 || strcmp(method, "add") == 0 ||
             strcmp(method, "counter_inc") == 0) {
        ctx->error = true;
        fprintf(stderr,
                "[xi_cgen] ERROR: yieldable AOT test_yield call '%s' escaped coroutine lowering\n",
                method);
        emit_codegen_abort_expr(out);
        return true;
    } else {
        return false;
    }

    if (argc != expected_argc) {
        ctx->error = true;
        fprintf(stderr, "[xi_cgen] ERROR: unsupported AOT test_yield call '%s' with %u args\n",
                method, (unsigned) argc);
        emit_codegen_abort_expr(out);
        return true;
    }
    const char *suffix =
        emit_conversion_prefix(out, v->type, XR_REP_I64, cg_value_plan_storage_rep(ctx, v));
    fprintf(out, "%s(", helper);
    if (expected_argc == 1)
        emit_value_as_rep_ctx(ctx, out, v->args[arg_base], XR_REP_I64);
    fprintf(out, ")");
    emit_conversion_suffix(out, suffix);
    return true;
}

static bool xicgen_emit_test_yield_method(XiCgenCtx *ctx, FILE *out, const XiFunc *f,
                                          const XiValue *v) {
    if (!v || (v->op != XI_CALL_METHOD && v->op != XI_CALL_METHOD_DIRECT) || v->nargs < 1 ||
        !cg_value_is_module_import_ctx(ctx, f, v->args[0], "test_yield"))
        return false;
    return cg_emit_test_yield_sync_call(ctx, out, f, v, (const char *) v->aux,
                                        (uint16_t) (v->nargs - 1), 1);
}

static const CgAotStdlibMethod *cg_find_aot_stdlib_method(const char *module, const char *method,
                                                          uint16_t argc) {
    if (!module || !method)
        return NULL;
    for (int i = 0; i < cg_aot_stdlib_method_count(); i++) {
        const CgAotStdlibMethod *m = cg_aot_stdlib_method_at(i);
        if (!m)
            continue;
        if ((m->argc == argc || m->argc == CG_AOT_STDLIB_VARIADIC) &&
            strcmp(module, m->module) == 0 && strcmp(method, m->method) == 0)
            return m;
    }
    return NULL;
}

/* Resolve the AOT-managed stdlib module that a method-call receiver names. */
static const char *cg_aot_stdlib_module_of_receiver(const XiCgenCtx *ctx, const XiFunc *f,
                                                    const XiValue *recv) {
    for (int i = 0; i < cg_aot_stdlib_method_count(); i++) {
        const CgAotStdlibMethod *m = cg_aot_stdlib_method_at(i);
        const char *module = m ? m->module : NULL;
        if (module && cg_value_is_module_import_ctx(ctx, f, recv, module))
            return module;
    }
    return NULL;
}

/* Emit the comma-separated shim arguments per the method's arg_spec. String
 * args ('s') are lowered to the specialized (data, length) pair via the AOT
 * string accessors; other args ('v'/'i') pass through as tagged values. SSA
 * arg references have no side effects, so emitting one twice (data + length)
 * is safe. stdlibgen guarantees the spec covers every fixed argument; a NULL
 * or exhausted spec (variadic rows, or call_argc beyond the spec length) must
 * still never be indexed past its NUL, so those positions take the default
 * tagged form. */
static void cg_emit_aot_stdlib_args(XiCgenCtx *ctx, FILE *out, const XiFunc *f, const XiValue *v,
                                    const CgAotStdlibMethod *m, uint16_t call_argc,
                                    uint16_t arg_base) {
    (void) f;
    const char *spec_cursor = m->arg_spec ? m->arg_spec : "";
    const char *provider_cursor = m->source_provider_arg_spec ? m->source_provider_arg_spec : "";
    for (uint16_t a = 0; a < call_argc; a++) {
        const XiValue *arg = v->args[arg_base + a];
        char spec = *spec_cursor;
        if (spec != '\0')
            spec_cursor++;
        char provider_spec = *provider_cursor;
        if (provider_spec != '\0')
            provider_cursor++;
        if (a > 0)
            fprintf(out, ", ");
        if (spec == 's') {
            fprintf(out, "xr_str_data(");
            emit_value_as_rep_ctx(ctx, out, arg, XR_REP_TAGGED);
            fprintf(out, "), xr_str_len(");
            emit_value_as_rep_ctx(ctx, out, arg, XR_REP_TAGGED);
            fprintf(out, ")");
        } else if (spec == 'p') {
            fprintf(out, "xrt_path_data(");
            emit_value_as_rep_ctx(ctx, out, arg, XR_REP_TAGGED);
            fprintf(out, "), xrt_path_len(");
            emit_value_as_rep_ctx(ctx, out, arg, XR_REP_TAGGED);
            fprintf(out, ")");
        } else if (provider_spec == 'w') {
            fprintf(out, "xrt_source_provider_storage(");
            emit_value_as_rep_ctx(ctx, out, arg, XR_REP_TAGGED);
            fprintf(out, ")");
        } else {
            emit_value_as_rep_ctx(ctx, out, arg, XR_REP_TAGGED);
        }
    }
}

static bool cg_aot_stdlib_method_is_variadic_strings(const CgAotStdlibMethod *m) {
    return m && m->argc == CG_AOT_STDLIB_VARIADIC && m->arg_spec && strcmp(m->arg_spec, "*") == 0;
}

static bool cg_emit_aot_stdlib_direct_call(XiCgenCtx *ctx, FILE *out, const XiFunc *f,
                                           const XiValue *v, const CgAotStdlibMethod *m,
                                           uint16_t call_argc, uint16_t arg_base) {
    if (!ctx || !out || !v || !m)
        return false;

    XrRep target_rep = xicgen_value_c_storage_rep(ctx, f, v);

    if (m->ret_kind == CG_AOT_RET_I64) {
        const char *suffix = emit_conversion_prefix_ctx(ctx, out, v->type, XR_REP_I64, target_rep);
        fprintf(out, "%s(", m->shim);
        cg_emit_aot_stdlib_args(ctx, out, f, v, m, call_argc, arg_base);
        fprintf(out, ")");
        emit_conversion_suffix(out, suffix);
        return true;
    }

    if (m->ret_kind == CG_AOT_RET_ENUM_I64) {
        if (target_rep == XR_REP_I64) {
            fprintf(out, "%s(", m->shim);
            cg_emit_aot_stdlib_args(ctx, out, f, v, m, call_argc, arg_base);
            fprintf(out, ")");
            return true;
        }
        uint32_t index = 0;
        if (!cg_mark_aot_stdlib_enum_scalar_sidecar(ctx, m, &index)) {
            emit_codegen_abort_expr(out);
            return true;
        }
        const char *module_prefix =
            ctx->module && ctx->module->name && ctx->module->name[0] ? ctx->module->name : "mod";
        const char *suffix = emit_conversion_prefix(out, v->type, XR_REP_TAGGED, target_rep);
        fprintf(out, "_xaot_stdlib_enum_box_%s_%u(%s(", module_prefix, (unsigned) index, m->shim);
        cg_emit_aot_stdlib_args(ctx, out, f, v, m, call_argc, arg_base);
        fprintf(out, "))");
        emit_conversion_suffix(out, suffix);
        return true;
    }

    /* The common value-returning ABI is already declared by the layered xrt
     * headers.  Emit it as an ordinary C expression so hosted fragments remain
     * valid ISO C11 and compile with MSVC as well as GCC/Clang. */
    if (m->ret_kind == CG_AOT_RET_VALUE && !cg_aot_stdlib_method_is_variadic_strings(m) &&
        (!m->extern_decl || !m->extern_decl[0])) {
        const char *suffix = emit_conversion_prefix(out, v->type, XR_REP_TAGGED, target_rep);
        fprintf(out, "%s(", m->shim);
        cg_emit_aot_stdlib_args(ctx, out, f, v, m, call_argc, arg_base);
        fprintf(out, ")");
        emit_conversion_suffix(out, suffix);
        return true;
    }

    /* Complex result adapters still require statement-local temporaries. They
     * are rejected by the hosted-fragment residue gate until their portable
     * statement forms are lowered explicitly. */
    fprintf(out, "({ ");
    if (m->extern_decl && m->extern_decl[0])
        fprintf(out, "%s ", m->extern_decl);

    if (m->ret_kind == CG_AOT_RET_STR_BORROWED) {
        /* The shim returns a borrowed (data, *out_len) slice; copy it into a
         * fresh AOT string. Temps are id-suffixed to nest safely. */
        unsigned id = v->id;
        fprintf(out, "int64_t _arl%u = 0; const char *_ard%u = %s(", id, id, m->shim);
        cg_emit_aot_stdlib_args(ctx, out, f, v, m, call_argc, arg_base);
        fprintf(out, ", &_arl%u); XrValue _ars%u = xrt_str_alloc((size_t) _arl%u); ", id, id, id);
        fprintf(out, "if (_arl%u) memcpy(xr_str_buf(_ars%u), _ard%u, (size_t) _arl%u); ", id, id,
                id, id);
        const char *suffix = emit_conversion_prefix(out, v->type, XR_REP_TAGGED, target_rep);
        fprintf(out, "_ars%u", id);
        emit_conversion_suffix(out, suffix);
        fprintf(out, "; })");
        return true;
    }

    if (cg_aot_stdlib_method_is_variadic_strings(m)) {
        unsigned id = v->id;
        if (call_argc > 0) {
            fprintf(out, "const char *_asd%u[%u] = {", id, (unsigned) call_argc);
            for (uint16_t a = 0; a < call_argc; a++) {
                if (a > 0)
                    fprintf(out, ", ");
                fprintf(out, "xr_str_data(");
                emit_value_as_rep_ctx(ctx, out, v->args[arg_base + a], XR_REP_TAGGED);
                fprintf(out, ")");
            }
            fprintf(out, "}; size_t _asl%u[%u] = {", id, (unsigned) call_argc);
            for (uint16_t a = 0; a < call_argc; a++) {
                if (a > 0)
                    fprintf(out, ", ");
                fprintf(out, "(size_t) xr_str_len(");
                emit_value_as_rep_ctx(ctx, out, v->args[arg_base + a], XR_REP_TAGGED);
                fprintf(out, ")");
            }
            fprintf(out, "}; ");
            fprintf(out, "XrValue _arv%u = %s((int64_t) %u, _asd%u, _asl%u); ", id, m->shim,
                    (unsigned) call_argc, id, id);
        } else {
            fprintf(out, "XrValue _arv%u = %s(0, NULL, NULL); ", id, m->shim);
        }
        const char *suffix = emit_conversion_prefix(out, v->type, XR_REP_TAGGED, target_rep);
        fprintf(out, "_arv%u", id);
        emit_conversion_suffix(out, suffix);
    } else {
        /* CG_AOT_RET_VALUE: shim returns a tagged XrValue. */
        const char *suffix = emit_conversion_prefix(out, v->type, XR_REP_TAGGED, target_rep);
        fprintf(out, "%s(", m->shim);
        cg_emit_aot_stdlib_args(ctx, out, f, v, m, call_argc, arg_base);
        fprintf(out, ")");
        emit_conversion_suffix(out, suffix);
    }
    fprintf(out, "; })");
    return true;
}

/* Emit a direct AOT call for a stdlib module method.
 * Returns true when the receiver is an AOT-managed stdlib module: supported
 * methods emit a direct shim call, unsupported ones raise a clean codegen
 * error (never a silent dispatch on the module placeholder). */
static bool xicgen_emit_stdlib_method(XiCgenCtx *ctx, FILE *out, const XiFunc *f,
                                      const XiValue *v) {
    if (!v || (v->op != XI_CALL_METHOD && v->op != XI_CALL_METHOD_DIRECT) || v->nargs < 1)
        return false;

    const char *module = cg_aot_stdlib_module_of_receiver(ctx, f, v->args[0]);
    if (!module)
        return false;

    const char *method = (const char *) v->aux;
    uint16_t call_argc = (uint16_t) (v->nargs - 1);
    const CgAotStdlibMethod *m = cg_find_aot_stdlib_method(module, method, call_argc);
    if (!m) {
        ctx->error = true;
        fprintf(stderr, "[xi_cgen] ERROR: unsupported AOT stdlib call '%s.%s'\n", module,
                method ? method : "?");
        emit_codegen_abort_expr(out);
        return true;
    }

    return cg_emit_aot_stdlib_direct_call(ctx, out, f, v, m, call_argc, 1);
}

/* Emit a direct AOT call for a selected stdlib member imported as a function
 * value, e.g. a helper exposed to stdlib/<module>/<module>.xr. */
static bool xicgen_emit_stdlib_import_call(XiCgenCtx *ctx, FILE *out, const XiFunc *f,
                                           const XiValue *v) {
    if (!v || v->op != XI_CALL || v->nargs < 1)
        return false;

    const XiValue *callee = cg_unwrap_identity_value(v->args[0]);
    const XiImportRef *ref = (callee && callee->op == XI_IMPORT_REF && callee->aux)
                                 ? (const XiImportRef *) callee->aux
                                 : cg_import_ref_for_value(ctx, f, callee);
    if (!ref || !ref->module_path || !ref->member_name)
        return false;

    uint16_t call_argc = (uint16_t) (v->nargs - 1);
    if (strcmp(ref->module_path, "runtime") == 0)
        return cg_emit_runtime_control_call(ctx, out, f, v, ref->member_name, call_argc);
    if (strcmp(ref->module_path, "test_yield") == 0)
        return cg_emit_test_yield_sync_call(ctx, out, f, v, ref->member_name, call_argc, 1);

    CgNativeDirectEmissionView native_direct = {0};
    CgNativeDirectEmissionStatus native_direct_status =
        cg_native_direct_emission_view(ctx, f, v, &native_direct);
    if (native_direct_status == CG_NATIVE_DIRECT_EMISSION_INVALID) {
        emit_codegen_abort_expr(out);
        return true;
    }
    if (native_direct_status == CG_NATIVE_DIRECT_EMISSION_EXACT)
        return cg_emit_aot_stdlib_direct_call(ctx, out, f, v, native_direct.method, call_argc, 1);

    const CgAotStdlibMethod *m =
        cg_find_aot_stdlib_method(ref->module_path, ref->member_name, call_argc);
    if (!m) {
        if (!cg_aot_stdlib_has_direct_member(ref->module_path, ref->member_name))
            return false;
        ctx->error = true;
        fprintf(stderr, "[xi_cgen] ERROR: unsupported AOT stdlib call '%s.%s' with %u args\n",
                ref->module_path, ref->member_name, (unsigned) call_argc);
        emit_codegen_abort_expr(out);
        return true;
    }

    return cg_emit_aot_stdlib_direct_call(ctx, out, f, v, m, call_argc, 1);
}
