/* ========== Multi-module API ========== */

XR_FUNC void xi_cgen_header(FILE *out) {
    XR_DCHECK(out != NULL, "xi_cgen_header: NULL output");
    fprintf(out, "/* Generated by xi_cgen - do not edit */\n");
    fprintf(out, "#define XRT_IMPL\n");
    fprintf(out, "#include \"xrt.h\"\n\n");
    fprintf(out, "#include \"xray.h\"\n");
    fprintf(out, "#include \"xray_isolate.h\"\n");
    fprintf(out, "#include \"xaot_coro.h\"\n\n");
    fprintf(out, "static XrValue xrt_builtins[%d];\n\n", XR_USER_GLOBALS_START);
}

static void emit_xrt_builtin_init(FILE *out) {
    fprintf(out,
            "    xrt_builtins[%d] = xrt_process_new(NULL, argc > 1 ? argc - 1 : 0, "
            "argc > 1 ? argv + 1 : NULL, NULL);\n",
            XR_GLOBAL_VAR_PROCESS);
    fprintf(out, "    xrt_builtins[%d] = XR_NULL_VAL;\n", XR_GLOBAL_VAR_FILE);
    fprintf(out, "    xrt_builtins[%d] = XR_NULL_VAL;\n", XR_GLOBAL_VAR_DIR);
}

XR_FUNC void xi_cgen_module(XiCgenCtx *ctx, FILE *out, XiModule *module) {
    XR_DCHECK(ctx != NULL, "xi_cgen_module: NULL ctx");
    XR_DCHECK(out != NULL, "xi_cgen_module: NULL output");
    XR_DCHECK(module != NULL, "xi_cgen_module: NULL module");
    XR_DCHECK(module->init != NULL, "xi_cgen_module: NULL init func");

    const char *prefix = module->name ? module->name : "mod";
    XiFunc *module_func = module->init;

    cg_prepare_func_tree_for_cgen(module_func);

    /* Initialize ctx from module metadata (no IR scanning) */
    cg_init_from_module(ctx, module);
    cg_register_imported_classes(ctx);

    /* Module-scoped shared variable array.
     * Multi-module builds use a prefixed name to avoid collisions. */
    char shared_buf[256];
    snprintf(shared_buf, sizeof(shared_buf), "xrt_shared_%s", prefix);
    ctx->shared_name = shared_buf;
    cg_collect_shared_native_instances(ctx);

    if (module_func->nshared > 0)
        fprintf(out, "static XrValue %s[%u];\n", ctx->shared_name, module_func->nshared);

    fprintf(out, "\n");
    emit_class_native_typedefs(ctx, out, module, prefix);
    emit_class_shared_native_storage_decls(ctx, out, prefix);
    emit_struct_native_typedefs(out, module_func, prefix);
    /* Forward declarations */
    emit_forward_decls(ctx, out, module_func, prefix);
    fprintf(out, "\n");

    /* Function bodies */
    xi_cgen_func(ctx, out, module_func, prefix);

    /* Reset shared name to default */
    ctx->shared_name = "xrt_shared";
}

XR_FUNC void xi_cgen_main(XiCgenCtx *ctx, FILE *out, XiModule **modules, int n, int entry_index) {
    XR_DCHECK(ctx != NULL, "xi_cgen_main: NULL ctx");
    XR_DCHECK(out != NULL, "xi_cgen_main: NULL output");
    XR_DCHECK(n > 0, "xi_cgen_main: no modules");
    XR_DCHECK(entry_index >= 0 && entry_index < n, "xi_cgen_main: bad entry_index");

    bool entry_is_coro = modules[entry_index] && modules[entry_index]->init &&
                         cg_func_needs_aot_coro_ctx(ctx, modules[entry_index]->init);

    fprintf(out, "int main(int argc, char **argv) {\n");
    fprintf(out, "    xrt_bump_enabled = 1;\n");
    fprintf(out, "    xrt_arc_init();\n");
    emit_xrt_builtin_init(out);
    if (entry_is_coro) {
        fprintf(out, "    XrayIsolateParams params;\n");
        fprintf(out, "    xray_isolate_params_init(&params);\n");
        fprintf(out, "    xray_isolate_setup_full(&params);\n");
        fprintf(out, "    params.init_flags = XR_INIT_RUNTIME;\n");
        fprintf(out, "    XrayIsolate *X = xray_isolate_new(&params);\n");
        fprintf(out, "    if (!X) return 1;\n");
        fprintf(out, "    xr_multicore_init(X, 0);\n");
        fprintf(out, "    xray_isolate_set_script_info(X, NULL, argc > 1 ? argc - 1 : 0, "
                     "argc > 1 ? argv + 1 : NULL);\n");
    } else {
        fprintf(out, "    (void) argc;\n");
        fprintf(out, "    (void) argv;\n");
    }
    for (int m = 0; m < n; m++) {
        if (!modules[m] || !modules[m]->init)
            continue;
        if (m == entry_index && entry_is_coro) {
            fprintf(out, "    void *_entry_frame = ");
            emit_fname_suffix(ctx, out, modules[m]->name ? modules[m]->name : "mod",
                              modules[m]->init, "_aot_frame_new");
            fprintf(out, "();\n");
            fprintf(out, "    xr_aot_run_main(X, &");
            emit_fname_suffix(ctx, out, modules[m]->name ? modules[m]->name : "mod",
                              modules[m]->init, "_aot_desc");
            fprintf(out, ", _entry_frame);\n");
        } else {
            if (cg_func_needs_aot_coro_ctx(ctx, modules[m]->init)) {
                fprintf(stderr,
                        "[xi_cgen] ERROR: suspendable AOT dependency module init '%s' must "
                        "be the entry module\n",
                        modules[m]->name ? modules[m]->name : "mod");
                ctx->error = true;
                fprintf(out, "    return 1;\n");
                continue;
            }
            fprintf(out, "    ");
            emit_fname(ctx, out, modules[m]->name ? modules[m]->name : "mod", modules[m]->init);
            fprintf(out, "(NULL);\n");
        }
    }
    if (entry_is_coro) {
        fprintf(out, "    xr_multicore_destroy(X);\n");
        fprintf(out, "    xray_isolate_delete(X);\n");
    }
    fprintf(out, "    xrt_bump_destroy();\n");
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n");
}

XR_FUNC void xi_cgen_program(XiCgenCtx *ctx, FILE *out, XiModule *module) {
    XR_DCHECK(ctx != NULL, "xi_cgen_program: NULL ctx");
    XR_DCHECK(out != NULL, "xi_cgen_program: NULL output");
    XR_DCHECK(module != NULL, "xi_cgen_program: NULL module");
    XR_DCHECK(module->init != NULL, "xi_cgen_program: NULL init func");

    XiFunc *main_func = module->init;
    const char *prefix = module->name ? module->name : "mod";

    cg_prepare_func_tree_for_cgen(main_func);

    /* Reset function name counter for each compilation unit */
    ctx->fname_counter = 0;

    XiModule *single_module[1] = {module};
    ctx->all_modules = single_module;
    ctx->all_nmodules = 1;
    ctx->nshared_native_exports = 0;
    memset(ctx->shared_native_exports, 0, sizeof(ctx->shared_native_exports));
    cg_prepare_sync_go_targets_for_modules(ctx, single_module, 1);

    /* Initialize from module metadata */
    cg_init_from_module(ctx, module);
    ctx->shared_name = "xrt_shared";
    cg_collect_shared_native_instances(ctx);

    xi_cgen_header(out);

    if (main_func->nshared > 0)
        fprintf(out, "static XrValue xrt_shared[%u];\n", main_func->nshared);

    fprintf(out, "\n");
    emit_class_native_typedefs(ctx, out, module, prefix);
    emit_class_shared_native_storage_decls(ctx, out, prefix);
    emit_struct_native_typedefs(out, main_func, prefix);

    emit_forward_decls(ctx, out, main_func, prefix);
    fprintf(out, "\n");

    xi_cgen_func(ctx, out, main_func, prefix);

    fprintf(out, "int main(int argc, char **argv) {\n");
    fprintf(out, "    xrt_bump_enabled = 1;\n");
    fprintf(out, "    xrt_arc_init();\n");
    emit_xrt_builtin_init(out);
    if (cg_func_needs_aot_coro_ctx(ctx, main_func)) {
        fprintf(out, "    XrayIsolateParams params;\n");
        fprintf(out, "    xray_isolate_params_init(&params);\n");
        fprintf(out, "    xray_isolate_setup_full(&params);\n");
        fprintf(out, "    params.init_flags = XR_INIT_RUNTIME;\n");
        fprintf(out, "    XrayIsolate *X = xray_isolate_new(&params);\n");
        fprintf(out, "    if (!X) return 1;\n");
        fprintf(out, "    xr_multicore_init(X, 0);\n");
        fprintf(out, "    xray_isolate_set_script_info(X, NULL, argc > 1 ? argc - 1 : 0, "
                     "argc > 1 ? argv + 1 : NULL);\n");
        fprintf(out, "    void *_entry_frame = ");
        emit_fname_suffix(ctx, out, prefix, main_func, "_aot_frame_new");
        fprintf(out, "();\n");
        fprintf(out, "    xr_aot_run_main(X, &");
        emit_fname_suffix(ctx, out, prefix, main_func, "_aot_desc");
        fprintf(out, ", _entry_frame);\n");
        fprintf(out, "    xr_multicore_destroy(X);\n");
        fprintf(out, "    xray_isolate_delete(X);\n");
    } else {
        fprintf(out, "    (void) argc;\n");
        fprintf(out, "    (void) argv;\n");
        fprintf(out, "    ");
        emit_fname(ctx, out, prefix, main_func);
        fprintf(out, "(NULL);\n");
    }
    fprintf(out, "    xrt_bump_destroy();\n");
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n");
}
