/* ========== Multi-module API ========== */

XR_FUNC void xi_cgen_emit_str_literal_defs(XiCgenCtx *ctx, FILE *out) {
    XR_DCHECK(ctx != NULL, "xi_cgen_emit_str_literal_defs: NULL ctx");
    XR_DCHECK(out != NULL, "xi_cgen_emit_str_literal_defs: NULL output");
    if (ctx->nstrlit == 0)
        return;
    for (int i = 0; i < ctx->nstrlit; i++) {
        const CgStrLit *lit = ctx->strlit_list[i];
        /* Hash precomputed with the runtime's own primitive (xrt_hash.h):
         * literal strings never pay a lazy hash at runtime. */
        fprintf(
            out,
            "static const xrt_str_t _xstr_%d = {INT64_C(%zu), 0x%08xu, XRT_STR_LITERAL, (char *) ",
            lit->id, lit->len, xrt_str_hash_bytes(lit->str, lit->len));
        emit_c_string_literal(out, lit->str);
        fprintf(out, "};\n");
    }
    fprintf(out, "\n");
}

typedef struct CgBuiltinInitPlan {
    bool process;
    bool file;
    bool dir;
} CgBuiltinInitPlan;

static void cg_builtin_init_scan_value(CgBuiltinInitPlan *plan, const XiValue *v) {
    if (!plan || !v || v->op != XI_GET_BUILTIN)
        return;
    if (v->aux_int == XR_GLOBAL_VAR_PROCESS)
        plan->process = true;
    else if (v->aux_int == XR_GLOBAL_VAR_FILE)
        plan->file = true;
    else if (v->aux_int == XR_GLOBAL_VAR_DIR)
        plan->dir = true;
}

static void cg_builtin_init_scan_func(CgBuiltinInitPlan *plan, const XiFunc *func) {
    if (!plan || !func)
        return;
    for (uint16_t ci = 0; ci < func->nchildren; ci++)
        cg_builtin_init_scan_func(plan, func->children[ci]);
    for (uint16_t bi = 0; bi < func->nblocks; bi++) {
        const XiBlock *blk = func->blocks[bi];
        if (!blk)
            continue;
        for (uint16_t vi = 0; vi < blk->nvalues; vi++)
            cg_builtin_init_scan_value(plan, blk->values[vi]);
    }
}

static CgBuiltinInitPlan cg_builtin_init_plan_for_modules(XiModule **modules, int n) {
    CgBuiltinInitPlan plan = {0};
    for (int i = 0; i < n; i++) {
        if (modules[i])
            cg_builtin_init_scan_func(&plan, modules[i]->init);
    }
    return plan;
}

static CgBuiltinInitPlan cg_builtin_init_plan_for_func(const XiFunc *func) {
    CgBuiltinInitPlan plan = {0};
    cg_builtin_init_scan_func(&plan, func);
    return plan;
}

XR_FUNC void xi_cgen_header(FILE *out) {
    XR_DCHECK(out != NULL, "xi_cgen_header: NULL output");
    fprintf(out, "/* Generated by xi_cgen - do not edit */\n");
    fprintf(out, "#ifndef XRT_IMPL\n#define XRT_IMPL\n#endif\n");
    fprintf(out, "#include <math.h>\n");
    fprintf(out, "#include \"xrt.h\"\n\n");
    fprintf(out, "#include \"xray.h\"\n");
    fprintf(out, "#include \"xray_isolate.h\"\n");
    fprintf(out, "#include \"xaot_coro.h\"\n\n");
    fprintf(out, "static XrValue xrt_builtins[%d];\n\n", XR_USER_GLOBALS_START);
}

static void emit_xrt_builtin_init(FILE *out, const CgBuiltinInitPlan *plan) {
    if (plan && plan->process) {
        fprintf(out,
                "    xrt_builtins[%d] = xrt_process_new(NULL, argc > 1 ? argc - 1 : 0, "
                "argc > 1 ? argv + 1 : NULL, NULL);\n",
                XR_GLOBAL_VAR_PROCESS);
    }
    if (plan && plan->file)
        fprintf(out, "    xrt_builtins[%d] = XR_NULL_VAL;\n", XR_GLOBAL_VAR_FILE);
    if (plan && plan->dir)
        fprintf(out, "    xrt_builtins[%d] = XR_NULL_VAL;\n", XR_GLOBAL_VAR_DIR);
}

XR_FUNC void xi_cgen_module(XiCgenCtx *ctx, FILE *out, XiModule *module) {
    XR_DCHECK(ctx != NULL, "xi_cgen_module: NULL ctx");
    XR_DCHECK(out != NULL, "xi_cgen_module: NULL output");
    XR_DCHECK(module != NULL, "xi_cgen_module: NULL module");
    XR_DCHECK(module->init != NULL, "xi_cgen_module: NULL init func");

    const char *prefix = module->name ? module->name : "mod";
    XiFunc *module_func = module->init;

    cg_prepare_func_tree_for_cgen(module_func);

    /* Initialize ctx from module metadata (no IR scanning) */
    cg_init_from_module(ctx, module);
    cg_register_imported_classes(ctx);

    /* Module-scoped shared variable array.
     * Multi-module builds use a prefixed name to avoid collisions. */
    char shared_buf[256];
    snprintf(shared_buf, sizeof(shared_buf), "xrt_shared_%s", prefix);
    ctx->shared_name = shared_buf;
    cg_collect_shared_native_instances(ctx);

    if (module_func->nshared > 0)
        fprintf(out, "static XrValue %s[%u];\n", ctx->shared_name, module_func->nshared);

    fprintf(out, "\n");
    emit_class_native_typedefs(ctx, out, module, prefix);
    emit_class_shared_native_storage_decls(ctx, out, prefix);
    emit_struct_native_typedefs(out, module_func, prefix);
    /* Forward declarations */
    emit_forward_decls(ctx, out, module_func, prefix);
    fprintf(out, "\n");

    /* Function bodies */
    xi_cgen_func(ctx, out, module_func, prefix);

    /* Reset shared name to default */
    ctx->shared_name = "xrt_shared";
}

XR_FUNC void xi_cgen_main(XiCgenCtx *ctx, FILE *out, XiModule **modules, int n, int entry_index) {
    XR_DCHECK(ctx != NULL, "xi_cgen_main: NULL ctx");
    XR_DCHECK(out != NULL, "xi_cgen_main: NULL output");
    XR_DCHECK(n > 0, "xi_cgen_main: no modules");
    XR_DCHECK(entry_index >= 0 && entry_index < n, "xi_cgen_main: bad entry_index");

    bool entry_is_coro = modules[entry_index] && modules[entry_index]->init &&
                         cg_func_needs_aot_coro_ctx(ctx, modules[entry_index]->init);
    CgBuiltinInitPlan builtin_plan = cg_builtin_init_plan_for_modules(modules, n);

    fprintf(out, "int main(int argc, char **argv) {\n");
    fprintf(out, "    xrt_bump_enabled = 1;\n");
    fprintf(out, "    xrt_arc_init();\n");
    emit_xrt_builtin_init(out, &builtin_plan);
    if (entry_is_coro) {
        fprintf(out, "    XrayIsolateParams params;\n");
        fprintf(out, "    xray_isolate_params_init(&params);\n");
        fprintf(out, "    xray_isolate_setup_full(&params);\n");
        fprintf(out, "    params.init_flags = XR_INIT_RUNTIME;\n");
        fprintf(out, "    XrayIsolate *X = xray_isolate_new(&params);\n");
        fprintf(out, "    if (!X) return 1;\n");
        fprintf(out, "    xr_multicore_init(X, 0);\n");
        fprintf(out, "    xray_isolate_set_script_info(X, NULL, argc > 1 ? argc - 1 : 0, "
                     "argc > 1 ? argv + 1 : NULL);\n");
    } else {
        fprintf(out, "    (void) argc;\n");
        fprintf(out, "    (void) argv;\n");
    }
    for (int m = 0; m < n; m++) {
        if (!modules[m] || !modules[m]->init)
            continue;
        if (m == entry_index && entry_is_coro) {
            fprintf(out, "    void *_entry_frame = ");
            emit_fname_suffix(ctx, out, modules[m]->name ? modules[m]->name : "mod",
                              modules[m]->init, "_aot_frame_new");
            fprintf(out, "();\n");
            fprintf(out, "    xr_aot_run_main(X, &");
            emit_fname_suffix(ctx, out, modules[m]->name ? modules[m]->name : "mod",
                              modules[m]->init, "_aot_desc");
            fprintf(out, ", _entry_frame);\n");
        } else {
            if (cg_func_needs_aot_coro_ctx(ctx, modules[m]->init)) {
                fprintf(stderr,
                        "[xi_cgen] ERROR: suspendable AOT dependency module init '%s' must "
                        "be the entry module\n",
                        modules[m]->name ? modules[m]->name : "mod");
                ctx->error = true;
                fprintf(out, "    return 1;\n");
                continue;
            }
            fprintf(out, "    ");
            emit_fname(ctx, out, modules[m]->name ? modules[m]->name : "mod", modules[m]->init);
            fprintf(out, "(NULL);\n");
        }
    }
    if (entry_is_coro) {
        fprintf(out, "    xr_multicore_destroy(X);\n");
        fprintf(out, "    xray_isolate_delete(X);\n");
    }
    fprintf(out, "    xrt_bump_destroy();\n");
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n");
}

XR_FUNC void xi_cgen_program(XiCgenCtx *ctx, FILE *out, XiModule *module) {
    XR_DCHECK(ctx != NULL, "xi_cgen_program: NULL ctx");
    XR_DCHECK(out != NULL, "xi_cgen_program: NULL output");
    XR_DCHECK(module != NULL, "xi_cgen_program: NULL module");
    XR_DCHECK(module->init != NULL, "xi_cgen_program: NULL init func");

    XiFunc *main_func = module->init;
    const char *prefix = module->name ? module->name : "mod";

    cg_prepare_func_tree_for_cgen(main_func);

    /* Reset function name counter for each compilation unit */
    ctx->fname_counter = 0;

    XiModule *single_module[1] = {module};
    ctx->all_modules = single_module;
    ctx->all_nmodules = 1;
    ctx->nshared_native_exports = 0;
    if (ctx->shared_native_exports)
        memset(ctx->shared_native_exports, 0,
               (size_t) ctx->shared_native_exports_cap * sizeof(CgSharedNativeExport));
    cg_prepare_sync_go_targets_for_modules(ctx, single_module, 1);

    /* Initialize from module metadata */
    cg_init_from_module(ctx, module);
    ctx->shared_name = "xrt_shared";
    cg_collect_shared_native_instances(ctx);

    xi_cgen_header(out);

    /* Bodies are buffered so interned string literal definitions (only
     * known after emission) can be placed ahead of every use. */
    char *bodybuf = NULL;
    size_t bodysz = 0;
    FILE *body = xr_open_memstream(&bodybuf, &bodysz);
    if (!body) {
        ctx->error = true;
        return;
    }

    if (main_func->nshared > 0)
        fprintf(body, "static XrValue xrt_shared[%u];\n", main_func->nshared);

    fprintf(body, "\n");
    emit_class_native_typedefs(ctx, body, module, prefix);
    emit_class_shared_native_storage_decls(ctx, body, prefix);
    emit_struct_native_typedefs(body, main_func, prefix);

    emit_forward_decls(ctx, body, main_func, prefix);
    fprintf(body, "\n");

    xi_cgen_func(ctx, body, main_func, prefix);

    fprintf(body, "int main(int argc, char **argv) {\n");
    fprintf(body, "    xrt_bump_enabled = 1;\n");
    fprintf(body, "    xrt_arc_init();\n");
    CgBuiltinInitPlan builtin_plan = cg_builtin_init_plan_for_func(main_func);
    emit_xrt_builtin_init(body, &builtin_plan);
    if (cg_func_needs_aot_coro_ctx(ctx, main_func)) {
        fprintf(body, "    XrayIsolateParams params;\n");
        fprintf(body, "    xray_isolate_params_init(&params);\n");
        fprintf(body, "    xray_isolate_setup_full(&params);\n");
        fprintf(body, "    params.init_flags = XR_INIT_RUNTIME;\n");
        fprintf(body, "    XrayIsolate *X = xray_isolate_new(&params);\n");
        fprintf(body, "    if (!X) return 1;\n");
        fprintf(body, "    xr_multicore_init(X, 0);\n");
        fprintf(body, "    xray_isolate_set_script_info(X, NULL, argc > 1 ? argc - 1 : 0, "
                      "argc > 1 ? argv + 1 : NULL);\n");
        fprintf(body, "    void *_entry_frame = ");
        emit_fname_suffix(ctx, body, prefix, main_func, "_aot_frame_new");
        fprintf(body, "();\n");
        fprintf(body, "    xr_aot_run_main(X, &");
        emit_fname_suffix(ctx, body, prefix, main_func, "_aot_desc");
        fprintf(body, ", _entry_frame);\n");
        fprintf(body, "    xr_multicore_destroy(X);\n");
        fprintf(body, "    xray_isolate_delete(X);\n");
    } else {
        fprintf(body, "    (void) argc;\n");
        fprintf(body, "    (void) argv;\n");
        fprintf(body, "    ");
        emit_fname(ctx, body, prefix, main_func);
        fprintf(body, "(NULL);\n");
    }
    fprintf(body, "    xrt_bump_destroy();\n");
    fprintf(body, "    return 0;\n");
    fprintf(body, "}\n");

    if (xr_close_memstream(body, &bodybuf, &bodysz) != 0) {
        ctx->error = true;
        return;
    }
    xi_cgen_emit_str_literal_defs(ctx, out);
    fwrite(bodybuf, 1, bodysz, out);
    xr_free(bodybuf);
}
