if(NOT WIN32)
    return()
endif()
foreach(mode injected production)
    set(target test_source_paths_${mode})
    add_executable(${target} "${CMAKE_CURRENT_LIST_DIR}/source_paths_owner/test_source_paths.c")
    target_link_libraries(${target} PRIVATE xray_cli_source)
    if(mode STREQUAL "production")
        target_compile_definitions(${target} PRIVATE SOURCE_PATHS_PRODUCTION)
    endif()
    target_include_directories(${target} PRIVATE "${PROJECT_SOURCE_DIR}/src" "${PROJECT_SOURCE_DIR}/include")
    target_compile_definitions(${target} PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _CRT_SECURE_NO_WARNINGS)
    set_target_properties(${target} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /WX /utf-8)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Werror -pedantic)
    endif()
    if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
        target_compile_options(${target} PRIVATE /experimental:c11atomics)
    endif()
    add_test(NAME source_paths_${mode} COMMAND ${XRAY_PYTHON} -X utf8
        "${CMAKE_CURRENT_LIST_DIR}/source_paths_owner/test_source_paths.py" $<TARGET_FILE:${target}>)
    set_tests_properties(source_paths_${mode} PROPERTIES
        TIMEOUT 120 RUN_SERIAL TRUE LABELS "unit;cli;ownership;budget")
endforeach()
