# Include after the existing test_cli_toolchain target in the full build.
if(TARGET test_cli_toolchain)
    target_link_libraries(test_cli_toolchain PRIVATE xray_compile_resources)
endif()
if(NOT WIN32)
    return()
endif()
get_filename_component(PROCESS_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include("${PROCESS_ROOT}/src/app/toolchain/xir_process.cmake")
add_executable(test_toolchain_process_owned
    "${CMAKE_CURRENT_LIST_DIR}/test_toolchain_process_owned.c"
    "${PROCESS_ROOT}/src/base/xutf8.c"
    "${PROCESS_ROOT}/src/os/win/proc_self_win.c"
    "${PROCESS_ROOT}/src/os/win/time_win.c")
add_dependencies(test_toolchain_process_owned xray_toolchain_process)
foreach(t test_toolchain_process_owned)
    target_include_directories(${t} PRIVATE "${PROCESS_ROOT}/src")
    target_compile_features(${t} PRIVATE c_std_11)
    target_compile_definitions(${t} PRIVATE NDEBUG _CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        target_compile_options(${t} PRIVATE /W4 /WX /utf-8)
        if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${t} PRIVATE /experimental:c11atomics)
        endif()
    endif()
endforeach()
add_test(NAME test_toolchain_process_owned COMMAND test_toolchain_process_owned)
set_tests_properties(test_toolchain_process_owned PROPERTIES LABELS "unit;toolchain;ownership;budget" TIMEOUT 120)
add_test(NAME test_toolchain_process_hidden_environment COMMAND test_toolchain_process_owned --hidden-env-parent)
set_tests_properties(test_toolchain_process_hidden_environment PROPERTIES LABELS "unit;toolchain;ownership;environment" TIMEOUT 30)

if(TARGET xir-runtime-sdk-bundle)
    set(XIR_PROCESS_SDK_BUNDLE "${CMAKE_BINARY_DIR}/xir-runtime-sdk")
    set(XIR_PROCESS_SDK_RECIPE "${CMAKE_BINARY_DIR}/xir-runtime-sdk")
    add_dependencies(test_toolchain_process_owned xir-runtime-sdk-bundle)
endif()
if(DEFINED XIR_PROCESS_SDK_BUNDLE)
    target_compile_definitions(test_toolchain_process_owned PRIVATE XTC_TEST_SDK=1)
    target_include_directories(test_toolchain_process_owned PRIVATE "${XIR_PROCESS_SDK_BUNDLE}" "${XIR_PROCESS_SDK_RECIPE}")
    target_sources(test_toolchain_process_owned PRIVATE "${PROCESS_ROOT}/src/base/xsha256.c")
    target_sources(test_toolchain_process_owned PRIVATE "${PROCESS_ROOT}/src/base/xjson_cursor.c")
    add_test(NAME test_toolchain_process_sdk_target COMMAND test_toolchain_process_owned --sdk "${XIR_PROCESS_SDK_BUNDLE}")
    set_tests_properties(test_toolchain_process_sdk_target PROPERTIES LABELS "unit;toolchain;sdk;ownership;budget" TIMEOUT 120 RUN_SERIAL TRUE)
endif()
