/* AUTO-GENERATED by corespecgen - DO NOT EDIT */
/* Source: xisa/core/registry.json */
#ifndef XR_CORE_SPEC_GEN_H
#define XR_CORE_SPEC_GEN_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define XR_CORE_SPEC_EPOCH 1u
/* clang-format off */
#define XR_CORE_SPEC_REGISTRY_SHA256 "fe99bb9affa94f448d8a282eb6a6d44e08ab5f6f60245175ab43d387e276e15e"
/* clang-format on */
#define XR_CORE_SPEC_OPERATION_COUNT 15u
#define XR_CORE_SPEC_FEATURE_COUNT 1u
#define XR_CORE_SPEC_VARIADIC_ARITY UINT8_MAX

typedef enum XrCoreTypeId {
    XR_CORE_TYPE_VOID = 0,
    XR_CORE_TYPE_BOOL = 1,
    XR_CORE_TYPE_I64 = 2,
    XR_CORE_TYPE_U32 = 3,
    XR_CORE_TYPE_ERROR = 4,
    XR_CORE_TYPE_TYPE_VARIABLE = 5,
} XrCoreTypeId;

typedef enum XrCoreFeatureId {
    XR_CORE_FEATURE_CORE_BASE = 1,
} XrCoreFeatureId;

typedef enum XrCoreOperationId {
    XR_CORE_OP_CORE_CONSTANT_I64 = 1,
    XR_CORE_OP_CORE_CONSTANT_BOOL = 2,
    XR_CORE_OP_CORE_ADD_I64 = 16,
    XR_CORE_OP_CORE_SUB_I64 = 17,
    XR_CORE_OP_CORE_MUL_I64 = 18,
    XR_CORE_OP_CORE_DIV_I64 = 19,
    XR_CORE_OP_CORE_COMPARE_I64 = 24,
    XR_CORE_OP_CORE_BLOCK_ARGUMENT = 32,
    XR_CORE_OP_CORE_BRANCH = 33,
    XR_CORE_OP_CORE_CONDITIONAL_BRANCH = 34,
    XR_CORE_OP_CORE_RETURN = 35,
    XR_CORE_OP_CORE_CALL_SEALED_DIRECT = 36,
    XR_CORE_OP_CORE_TRAP = 48,
    XR_CORE_OP_CORE_ERROR_PUBLISH = 49,
    XR_CORE_OP_CORE_TARGET_POINTER_WIDTH = 64,
} XrCoreOperationId;

typedef enum XrCoreCoverageStatus {
    XR_CORE_COVERAGE_COMPLETE = 1,
    XR_CORE_COVERAGE_NOT_YET_ACTIVE = 2,
    XR_CORE_COVERAGE_NOT_APPLICABLE = 3,
} XrCoreCoverageStatus;

typedef struct XrCoreOperationSpec {
    uint16_t stable_id;
    uint8_t operand_arity;
    uint8_t result_type;
    uint8_t successor_mask;
    uint32_t effect_mask;
    uint32_t capability_mask;
    const char *spelling;
    const char *operation_class;
    const char *feature;
    const char *profile_dependency;
    const char *materialization;
    XrCoreCoverageStatus spec_oracle_status;
    XrCoreCoverageStatus decoder_status;
    XrCoreCoverageStatus verifier_status;
    XrCoreCoverageStatus evaluator_status;
    XrCoreCoverageStatus vm_status;
    XrCoreCoverageStatus aot_status;
} XrCoreOperationSpec;

extern const XrCoreOperationSpec xr_core_operation_specs[XR_CORE_SPEC_OPERATION_COUNT];

const XrCoreOperationSpec *xr_core_spec_operation_by_id(uint16_t stable_id);
const XrCoreOperationSpec *xr_core_spec_operation_by_spelling(const char *spelling);
bool xr_core_spec_feature_active(uint16_t stable_id);

#endif /* XR_CORE_SPEC_GEN_H */
