#!/usr/bin/env python3
"""Derive the exact installed header closure consumed by generated AOT C."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import tempfile
from pathlib import Path


GENERATOR = "xray-aot-sdk-header-closure/1"
PRIVATE_ROOTS = (
    "src/aot/xrt.h",
    "src/aot/xrt_core_freestanding.h",
    "src/aot/xrt_c90.h",
    "src/aot/xaot_coro.h",
    "src/aot/xrt_thread_aot.h",
)
PUBLIC_ROOTS = (
    "include/runtime.h",
    "include/xray_export.h",
    "include/xray_hosted_fragment_abi.h",
    "include/xray_runtime_generation.h",
    "include/xray_target_plan_load.h",
)
INCLUDE_RE = re.compile(r'^\s*#\s*include\s*"([^"]+)"', re.MULTILINE)
ALLOWED_SUFFIXES = (".h", ".inc.c", ".def")
FORBIDDEN_PATH_RE = re.compile(
    r"(?i)(?:^|/)(?:xray_vm\.h|xproto_codec\.h|xopcode_def\.h|"
    r"[^/]*\.xrc|(?:xrc|bytecode)(?:/|$)|[^/]*bytecode[^/]*)"
)
FORBIDDEN_TEXT_RE = re.compile(
    r"(?i)(?:\.xrc\b|\bxray_vm_[A-Za-z0-9_]+\b|"
    r"\bxr_(?:bytecode_[A-Za-z0-9_]+|detect_output_format|eval_bytecode|"
    r"output_c_source|run_bytecode_file)\b|xbytecode_io\.h|xopcode_def\.h)"
)


class ClosureError(ValueError):
    pass


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def resolve_include(root: Path, owner: Path, spelling: str) -> Path:
    candidates = ((owner.parent / spelling).resolve(), (root / "include" / spelling).resolve())
    for candidate in candidates:
        if candidate.is_file():
            try:
                candidate.relative_to(root)
            except ValueError as error:
                raise ClosureError(f"quoted include escapes the source tree: {owner}: {spelling}") \
                    from error
            return candidate
    raise ClosureError(f"quoted include is not source-backed: {owner}: {spelling}")


def derive(root: Path) -> list[Path]:
    pending = [(root / relative).resolve() for relative in (*PRIVATE_ROOTS, *PUBLIC_ROOTS)]
    seen: set[Path] = set()
    while pending:
        path = pending.pop()
        if path in seen:
            continue
        if not path.is_file():
            raise ClosureError(f"SDK root is missing: {path}")
        relative = path.relative_to(root).as_posix()
        if not relative.endswith(ALLOWED_SUFFIXES):
            raise ClosureError(f"SDK closure contains an unsupported source kind: {relative}")
        if FORBIDDEN_PATH_RE.search(relative):
            raise ClosureError(f"SDK closure reaches a forbidden legacy path: {relative}")
        text = path.read_text(encoding="utf-8", errors="strict")
        match = FORBIDDEN_TEXT_RE.search(text)
        if match:
            raise ClosureError(f"SDK closure reaches forbidden legacy text: {relative}: {match.group(0)}")
        seen.add(path)
        for spelling in INCLUDE_RE.findall(text):
            pending.append(resolve_include(root, path, spelling))
    return sorted(seen, key=lambda item: item.relative_to(root).as_posix())


def install_path(relative: str) -> str:
    if relative.startswith("include/"):
        return f"include/xray/{relative.removeprefix('include/')}"
    if relative.startswith("src/"):
        return f"lib/xray/sdk/{relative}"
    raise ClosureError(f"SDK closure source has no install domain: {relative}")


def render_cmake(root: Path, files: list[Path]) -> str:
    public = []
    private = []
    for path in files:
        relative = path.relative_to(root).as_posix()
        (public if relative.startswith("include/") else private).append(relative)

    def variable(name: str, values: list[str]) -> str:
        body = "\n".join(f'    "{value}"' for value in values)
        return f"set({name}\n{body}\n)\n"

    return (
        "# Generated by derive_aot_sdk_closure.py; do not edit.\n"
        + variable("XRAY_AOT_SDK_PUBLIC_FILES", public)
        + variable("XRAY_AOT_SDK_PRIVATE_FILES", private)
    )


def render_manifest(root: Path, files: list[Path]) -> str:
    entries = []
    for path in files:
        relative = path.relative_to(root).as_posix()
        entries.append({
            "install_path": install_path(relative),
            "sha256": sha256_file(path),
            "source_path": relative,
        })
    value = {"schema": 1, "generator": GENERATOR, "entries": entries}
    return json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n"


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}-", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--cmake-output", required=True)
    parser.add_argument("--manifest-output", required=True)
    args = parser.parse_args()
    root = Path(args.root).resolve()
    files = derive(root)
    atomic_write(Path(args.cmake_output).resolve(), render_cmake(root, files))
    atomic_write(Path(args.manifest_output).resolve(), render_manifest(root, files))
    print(f"AOT SDK closure: {len(files)} exact source-backed files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
