#!/usr/bin/env python3
"""Generate xbuiltin_hash.inc — compile-time const hash table for builtin symbols.

Reads xr_builtin_symbol_names[] from xsymbol_table.c and produces an
open-addressing hash table (FNV-1a, power-of-2 size) as a C const array.

Usage:
    python3 scripts/gen_builtin_hash.py > src/runtime/symbol/xbuiltin_hash.inc
"""

import re, sys, os
from typing import List, Tuple, Optional

SRC = os.path.join(os.path.dirname(__file__),
                   "../src/runtime/symbol/xsymbol_table.c")

HASH_SIZE = 256  # must be power of 2


def fnv1a(s: str) -> int:
    h = 2166136261
    for c in s:
        h ^= ord(c)
        h = (h * 16777619) & 0xFFFFFFFF
    return h


def extract_names(path: str) -> List[str]:
    """Extract strings from xr_builtin_symbol_names[] in the source file."""
    with open(path) as f:
        src = f.read()
    # Match the entire array
    m = re.search(
        r'static\s+const\s+char\s+\*xr_builtin_symbol_names\[\]\s*=\s*\{(.*?)\};',
        src, re.DOTALL)
    if not m:
        print("ERROR: cannot find xr_builtin_symbol_names[] in", path,
              file=sys.stderr)
        sys.exit(1)
    body = m.group(1)
    # Extract all quoted strings
    return re.findall(r'"([^"]*)"', body)


def build_table(names: List[str]) -> List[Optional[Tuple[str, int]]]:
    table: List[Optional[Tuple[str, int]]] = [None] * HASH_SIZE
    for i, name in enumerate(names):
        symbol_id = i + 1  # SYMBOL_LENGTH = 1, etc.
        slot = fnv1a(name) & (HASH_SIZE - 1)
        while table[slot] is not None:
            slot = (slot + 1) & (HASH_SIZE - 1)
        table[slot] = (name, symbol_id)
    return table


def emit(table: List[Optional[Tuple[str, int]]], count: int):
    print("// AUTO-GENERATED by scripts/gen_builtin_hash.py — DO NOT EDIT")
    print(f"// {count} builtin symbols, hash table size {HASH_SIZE}")
    print(f"// Load factor: {count}/{HASH_SIZE} = {count/HASH_SIZE:.2f}")
    print()
    print(f"#define BUILTIN_HASH_SIZE {HASH_SIZE}")
    print()
    print("typedef struct {")
    print("    const char *name;")
    print("    SymbolId id;")
    print("} XrBuiltinHashEntry;")
    print()
    print(f"static const XrBuiltinHashEntry xr_builtin_hash_table[BUILTIN_HASH_SIZE] = {{")
    for i, entry in enumerate(table):
        if entry is not None:
            name, sid = entry
            # Escape special chars for C string
            c_name = name.replace('\\', '\\\\').replace('"', '\\"')
            print(f'    [{i}] = {{ "{c_name}", {sid} }},')
    print("};")


def main():
    names = extract_names(os.path.abspath(SRC))
    if not names:
        print("ERROR: no names extracted", file=sys.stderr)
        sys.exit(1)
    table = build_table(names)
    emit(table, len(names))


if __name__ == "__main__":
    main()
