#!/usr/bin/env python3
"""Generate embedded stdlib script source and bytecode tables.

Only canonical script layers named stdlib/<module>/<module>.xr are embedded.
Type declaration files (stdlib/types/*.xr) and other helper fixtures are not
runtime module script layers.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


def c_ident(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    ident = "".join(out).strip("_")
    return ident or "module"


def c_string_bytes(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), 18):
        chunk = data[i : i + 18]
        escaped = "".join(f"\\{b:03o}" for b in chunk)
        lines.append(f'    "{escaped}"')
    lines.append('    ""')
    return "\n".join(lines)


def c_byte_array(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        body = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {body},")
    return "\n".join(lines)


def canonical_module_name(root: Path, path: Path) -> str | None:
    rel = path.relative_to(root)
    if len(rel.parts) != 3 or rel.parts[0] != "stdlib":
        return None
    module_dir = rel.parts[1]
    if rel.name != f"{module_dir}.xr":
        return None
    return module_dir


def collect_entries(root: Path, sources: list[Path]) -> list[tuple[str, Path, bytes]]:
    entries: list[tuple[str, Path, bytes]] = []
    seen: set[str] = set()
    for src in sources:
        path = src.resolve()
        name = canonical_module_name(root, path)
        if name is None or name in seen:
            continue
        seen.add(name)
        entries.append((name, path, path.read_bytes()))
    entries.sort(key=lambda item: item[0])
    return entries


def emit_sources(root: Path, entries: list[tuple[str, Path, bytes]]) -> str:
    out: list[str] = []
    out.append("/* Auto-generated by scripts/generate_stdlib_embedded.py. */")
    out.append("/* Do not edit by hand. */")
    out.append("")

    for idx, (name, path, data) in enumerate(entries):
        ident = c_ident(name)
        rel = path.relative_to(root).as_posix()
        out.append(f"/* {rel} */")
        out.append(f"static const char xr_stdlib_src_{ident}_{idx}[] =")
        out.append(c_string_bytes(data))
        out.append(";")
        out.append("")

    out.append(
        "static const XrEmbeddedStdlibSource xr_embedded_stdlib_sources[] = {"
    )
    for idx, (name, _path, _data) in enumerate(entries):
        ident = c_ident(name)
        out.append(f'    {{"{name}", xr_stdlib_src_{ident}_{idx}}},')
    out.append("};")
    out.append("")
    out.append(
        "static const size_t xr_embedded_stdlib_source_count = "
        "sizeof(xr_embedded_stdlib_sources) / sizeof(xr_embedded_stdlib_sources[0]);"
    )
    out.append("")
    return "\n".join(out)


def compile_bytecodes(
    compiler: Path, root: Path, bytecode_dir: Path, entries: list[tuple[str, Path, bytes]]
) -> None:
    bytecode_dir.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["XRAY_STDLIB_PATH"] = str(root / "stdlib")
    for name, path, _data in entries:
        out_path = bytecode_dir / f"{name}.xrc"
        proc = subprocess.run(
            [
                str(compiler),
                "compile",
                str(path),
                "--output",
                str(out_path),
                "--format",
                "bytecode",
            ],
            cwd=str(root),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if proc.returncode != 0:
            if proc.stdout:
                sys.stderr.write(proc.stdout)
            if proc.stderr:
                sys.stderr.write(proc.stderr)
            raise RuntimeError(f"failed to compile stdlib module '{name}' to bytecode")


def emit_bytecodes(
    entries: list[tuple[str, Path, bytes]], bytecode_dir: Path | None, require_bytecode: bool
) -> str:
    out: list[str] = []
    out.append("/* Auto-generated by scripts/generate_stdlib_embedded.py. */")
    out.append("/* Do not edit by hand. */")
    out.append("")

    bytecode_entries: list[tuple[str, bytes]] = []
    if bytecode_dir is not None:
        for name, _path, _data in entries:
            bc_path = bytecode_dir / f"{name}.xrc"
            if bc_path.is_file():
                bytecode_entries.append((name, bc_path.read_bytes()))
            elif require_bytecode:
                raise RuntimeError(f"missing bytecode for stdlib module '{name}': {bc_path}")

    if not bytecode_entries:
        out.append(
            "static const XrEmbeddedStdlibBytecode xr_embedded_stdlib_bytecodes[1] = "
            "{{NULL, NULL, 0}};"
        )
        out.append("static const size_t xr_embedded_stdlib_bytecode_count = 0;")
        out.append("")
        return "\n".join(out)

    for idx, (name, data) in enumerate(bytecode_entries):
        ident = c_ident(name)
        out.append(f"/* {name}.xrc */")
        out.append(f"static const uint8_t xr_stdlib_bc_{ident}_{idx}[] = {{")
        out.append(c_byte_array(data))
        out.append("};")
        out.append("")

    out.append(
        "static const XrEmbeddedStdlibBytecode xr_embedded_stdlib_bytecodes[] = {"
    )
    for idx, (name, _data) in enumerate(bytecode_entries):
        ident = c_ident(name)
        out.append(
            f'    {{"{name}", xr_stdlib_bc_{ident}_{idx}, '
            f"sizeof(xr_stdlib_bc_{ident}_{idx})}},"
        )
    out.append("};")
    out.append("")
    out.append(
        f"static const size_t xr_embedded_stdlib_bytecode_count = {len(bytecode_entries)};"
    )
    out.append("")
    return "\n".join(out)


def write_text(path: Path | None, content: str) -> None:
    if path is None:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--source-output", type=Path)
    parser.add_argument("--bytecode-output", type=Path)
    parser.add_argument("--bytecode-dir", type=Path)
    parser.add_argument("--compiler", type=Path)
    parser.add_argument("--require-bytecode", action="store_true")
    parser.add_argument("sources", nargs="+", type=Path)
    args = parser.parse_args()

    root = args.root.resolve()
    entries = collect_entries(root, args.sources)
    bytecode_dir = args.bytecode_dir.resolve() if args.bytecode_dir else None

    try:
        if args.compiler:
            if bytecode_dir is None:
                raise RuntimeError("--compiler requires --bytecode-dir")
            compile_bytecodes(args.compiler.resolve(), root, bytecode_dir, entries)

        source_text = emit_sources(root, entries)
        bytecode_text = emit_bytecodes(entries, bytecode_dir, args.require_bytecode)
    except RuntimeError as exc:
        print(f"generate_stdlib_embedded.py: {exc}", file=sys.stderr)
        return 1

    if args.output:
        write_text(args.output, source_text + bytecode_text)
    write_text(args.source_output, source_text)
    write_text(args.bytecode_output, bytecode_text)
    if not args.output and not args.source_output and not args.bytecode_output:
        print("generate_stdlib_embedded.py: no output path provided", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
