#!/usr/bin/env python3
"""Generate embedded stdlib script source tables.

Only canonical script layers named stdlib/<module>/<module>.xr are embedded.
Type declaration files (stdlib/types/*.xr) and other helper fixtures are not
runtime module script layers.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def c_ident(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    ident = "".join(out).strip("_")
    return ident or "module"


def c_string_bytes(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), 18):
        chunk = data[i : i + 18]
        escaped = "".join(f"\\{b:03o}" for b in chunk)
        lines.append(f'    "{escaped}"')
    lines.append('    ""')
    return "\n".join(lines)


def canonical_module_name(root: Path, path: Path) -> str | None:
    rel = path.relative_to(root)
    if len(rel.parts) != 3 or rel.parts[0] != "stdlib":
        return None
    module_dir = rel.parts[1]
    if rel.name != f"{module_dir}.xr":
        return None
    return module_dir


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("sources", nargs="+", type=Path)
    args = parser.parse_args()

    root = args.root.resolve()
    entries: list[tuple[str, Path, bytes]] = []
    seen: set[str] = set()
    for src in args.sources:
        path = src.resolve()
        name = canonical_module_name(root, path)
        if name is None or name in seen:
            continue
        seen.add(name)
        entries.append((name, path, path.read_bytes()))
    entries.sort(key=lambda item: item[0])

    out: list[str] = []
    out.append("/* Auto-generated by scripts/generate_stdlib_embedded.py. */")
    out.append("/* Do not edit by hand. */")
    out.append("")

    for idx, (name, path, data) in enumerate(entries):
        ident = c_ident(name)
        rel = path.relative_to(root).as_posix()
        out.append(f"/* {rel} */")
        out.append(f"static const char xr_stdlib_src_{ident}_{idx}[] =")
        out.append(c_string_bytes(data))
        out.append(";")
        out.append("")

    out.append(
        "static const XrEmbeddedStdlibSource xr_embedded_stdlib_sources[] = {"
    )
    for idx, (name, _path, _data) in enumerate(entries):
        ident = c_ident(name)
        out.append(f'    {{"{name}", xr_stdlib_src_{ident}_{idx}}},')
    out.append("};")
    out.append("")
    out.append(
        "static const size_t xr_embedded_stdlib_source_count = "
        "sizeof(xr_embedded_stdlib_sources) / sizeof(xr_embedded_stdlib_sources[0]);"
    )
    out.append("")
    out.append(
        "static const XrEmbeddedStdlibBytecode xr_embedded_stdlib_bytecodes[1] = {{NULL, NULL, 0}};"
    )
    out.append("static const size_t xr_embedded_stdlib_bytecode_count = 0;")
    out.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
