#!/usr/bin/env python3
"""Generate embedded built-in standard-library source and bytecode tables.

Every script module has one canonical source at
``stdlib/<module>/<module>.xr`` and one bare module name.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import subprocess
import sys
import tempfile
from pathlib import Path


def c_ident(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    ident = "".join(out).strip("_")
    return ident or "module"


def bytecode_staging_path(bytecode_dir: Path, module_name: str) -> Path:
    """Return the canonical, build-private staging path for one module."""
    return bytecode_dir / c_ident(module_name)


def c_string_bytes(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), 18):
        chunk = data[i : i + 18]
        escaped = "".join(f"\\{b:03o}" for b in chunk)
        lines.append(f'    "{escaped}"')
    lines.append('    ""')
    return "\n".join(lines)


def c_byte_array(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        body = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {body},")
    return "\n".join(lines)


def canonical_module_name(root: Path, path: Path) -> str | None:
    rel = path.relative_to(root)
    if len(rel.parts) == 3 and rel.parts[0] == "stdlib":
        module_dir = rel.parts[1]
        return module_dir if rel.name == f"{module_dir}.xr" else None
    return None


def collect_entries(root: Path, sources: list[Path]) -> list[tuple[str, Path, bytes]]:
    entries: list[tuple[str, Path, bytes]] = []
    seen: set[str] = set()
    for src in sources:
        path = src.resolve()
        name = canonical_module_name(root, path)
        if name is None:
            raise RuntimeError(f"non-canonical stdlib module source: {path}")
        if name in seen:
            raise RuntimeError(f"duplicate stdlib module source: {name}")
        seen.add(name)
        entries.append((name, path, path.read_bytes()))
    entries.sort(key=lambda item: item[0])
    return entries


def derive_private_leaf_modules(root: Path) -> set[str]:
    generator_path = root / "tools" / "stdlibgen" / "stdlibgen.py"
    spec = importlib.util.spec_from_file_location("xray_stdlibgen_for_embedding", generator_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load stdlib metadata generator: {generator_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    entries, constants, *_ = module.parse_def_metadata(root)
    return module.derive_private_leaf_modules(root, entries, constants)


def emit_sources(root: Path, entries: list[tuple[str, Path, bytes]]) -> str:
    out: list[str] = []
    out.append("/* Auto-generated by scripts/generate_stdlib_embedded.py. */")
    out.append("/* Do not edit by hand. */")
    out.append("")

    embedded_names = {name for name, _path, _data in entries}
    private_leaf_modules = derive_private_leaf_modules(root) & embedded_names
    for name in sorted(private_leaf_modules):
        out.append(
            f"XR_FUNC bool xr_stdlib_vm_bind_{c_ident(name)}_generated("
            "struct XrVMRuntime *isolate, struct XrModule *module);"
        )
    if private_leaf_modules:
        out.append("")

    for idx, (name, path, data) in enumerate(entries):
        ident = c_ident(name)
        rel = path.relative_to(root).as_posix()
        out.append(f"/* {rel} */")
        out.append(f"static const char xr_stdlib_src_{ident}_{idx}[] =")
        out.append(c_string_bytes(data))
        out.append(";")
        out.append("")

    out.append(
        "static const XrEmbeddedStdlibSource xr_embedded_stdlib_sources[] = {"
    )
    for idx, (name, _path, _data) in enumerate(entries):
        ident = c_ident(name)
        binder = (
            f"xr_stdlib_vm_bind_{ident}_generated" if name in private_leaf_modules else "NULL"
        )
        out.append(f'    {{"{name}", xr_stdlib_src_{ident}_{idx}, {binder}}},')
    out.append("};")
    out.append("")
    out.append(
        "static const size_t xr_embedded_stdlib_source_count = "
        "sizeof(xr_embedded_stdlib_sources) / sizeof(xr_embedded_stdlib_sources[0]);"
    )
    out.append("")
    return "\n".join(out)


def compile_bytecodes(
    compiler: Path, root: Path, bytecode_dir: Path, entries: list[tuple[str, Path, bytes]]
) -> None:
    bytecode_dir.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["XRAY_STDLIB_PATH"] = str(root / "stdlib")
    for name, path, _data in entries:
        out_path = bytecode_staging_path(bytecode_dir, name)
        proc = subprocess.run(
            [
                str(compiler),
                "compile",
                str(path),
                "--output",
                str(out_path),
                "--format",
                "bytecode",
                "--stdlib-module",
                name,
            ],
            cwd=str(root),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="strict",
        )
        if proc.returncode != 0:
            if proc.stdout:
                sys.stderr.write(proc.stdout)
            if proc.stderr:
                sys.stderr.write(proc.stderr)
            raise RuntimeError(f"failed to compile stdlib module '{name}' to bytecode")


def emit_bytecodes(
    entries: list[tuple[str, Path, bytes]], bytecode_dir: Path | None, require_bytecode: bool
) -> str:
    out: list[str] = []
    out.append("/* Auto-generated by scripts/generate_stdlib_embedded.py. */")
    out.append("/* Do not edit by hand. */")
    out.append("")

    bytecode_entries: list[tuple[str, bytes]] = []
    if bytecode_dir is not None:
        for name, _path, _data in entries:
            bc_path = bytecode_staging_path(bytecode_dir, name)
            if bc_path.is_file():
                bytecode_entries.append((name, bc_path.read_bytes()))
            elif require_bytecode:
                raise RuntimeError(f"missing bytecode for stdlib module '{name}': {bc_path}")

    if not bytecode_entries:
        out.append(
            "static const XrEmbeddedStdlibBytecode xr_embedded_stdlib_bytecodes[1] = "
            "{{NULL, NULL, 0}};"
        )
        out.append("static const size_t xr_embedded_stdlib_bytecode_count = 0;")
        out.append("")
        return "\n".join(out)

    for idx, (name, data) in enumerate(bytecode_entries):
        ident = c_ident(name)
        out.append(f"/* {name} bytecode */")
        out.append(f"static const uint8_t xr_stdlib_bc_{ident}_{idx}[] = {{")
        out.append(c_byte_array(data))
        out.append("};")
        out.append("")

    out.append(
        "static const XrEmbeddedStdlibBytecode xr_embedded_stdlib_bytecodes[] = {"
    )
    for idx, (name, _data) in enumerate(bytecode_entries):
        ident = c_ident(name)
        out.append(
            f'    {{"{name}", xr_stdlib_bc_{ident}_{idx}, '
            f"sizeof(xr_stdlib_bc_{ident}_{idx})}},"
        )
    out.append("};")
    out.append("")
    out.append(
        f"static const size_t xr_embedded_stdlib_bytecode_count = {len(bytecode_entries)};"
    )
    out.append("")
    return "\n".join(out)


def write_text(path: Path | None, content: str) -> None:
    if path is None:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def self_test() -> int:
    with tempfile.TemporaryDirectory(prefix="xray-stdlib-bytecode-staging-") as directory:
        root = Path(directory).resolve()
        bytecode_dir = root / "bytecode"
        bytecode_dir.mkdir()
        module_name = "core.format"
        payload = bytes((0x00, 0x11, 0x7F, 0x80, 0xFE, 0xFF))
        path = bytecode_staging_path(bytecode_dir, module_name)
        if path != bytecode_staging_path(bytecode_dir, module_name):
            print("stdlib bytecode staging self-test: nondeterministic path", file=sys.stderr)
            return 1
        if path.parent != bytecode_dir or path.name != "core_format" or path.suffix:
            print("stdlib bytecode staging self-test: non-canonical path", file=sys.stderr)
            return 1
        path.write_bytes(payload)
        entries = [(module_name, Path("unused-source"), b"")]
        emitted = emit_bytecodes(entries, bytecode_dir, require_bytecode=True)
        if c_byte_array(payload) not in emitted or f'{{"{module_name}",' not in emitted:
            print("stdlib bytecode staging self-test: embedded bytes changed", file=sys.stderr)
            return 1
        retired_suffix = "." + "xr" + "c"
        if any(candidate.name.endswith(retired_suffix) for candidate in bytecode_dir.iterdir()):
            print("stdlib bytecode staging self-test: retired suffix revived", file=sys.stderr)
            return 1
        try:
            emit_bytecodes(
                [("missing", Path("unused-source"), b"")],
                bytecode_dir,
                require_bytecode=True,
            )
        except RuntimeError:
            pass
        else:
            print("stdlib bytecode staging self-test: missing input accepted", file=sys.stderr)
            return 1

        module_dir = root / "stdlib" / "demo"
        module_dir.mkdir(parents=True)
        canonical_source = module_dir / "demo.xr"
        noncanonical_source = module_dir / "helper.xr"
        canonical_source.write_text("export fn ready() -> bool { return true }\n", encoding="utf-8")
        noncanonical_source.write_text("fn helper() {}\n", encoding="utf-8")
        for label, sources in (
            ("duplicate", [canonical_source, canonical_source]),
            ("non-canonical", [noncanonical_source]),
        ):
            try:
                collect_entries(root, sources)
            except RuntimeError:
                pass
            else:
                print(
                    f"stdlib source descriptor self-test: {label} input accepted",
                    file=sys.stderr,
                )
                return 1
    print("stdlib bytecode staging self-test: PASS")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--root", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--source-output", type=Path)
    parser.add_argument("--bytecode-output", type=Path)
    parser.add_argument("--bytecode-dir", type=Path)
    parser.add_argument("--compiler", type=Path)
    parser.add_argument("--require-bytecode", action="store_true")
    parser.add_argument("sources", nargs="*", type=Path)
    args = parser.parse_args()

    if args.self_test:
        return self_test()
    if args.root is None:
        parser.error("--root is required")
    if not args.sources:
        parser.error("at least one stdlib source is required")

    root = args.root.resolve()
    entries = collect_entries(root, args.sources)
    bytecode_dir = args.bytecode_dir.resolve() if args.bytecode_dir else None

    try:
        if args.compiler:
            if bytecode_dir is None:
                raise RuntimeError("--compiler requires --bytecode-dir")
            compile_bytecodes(args.compiler.resolve(), root, bytecode_dir, entries)

        source_text = emit_sources(root, entries)
        bytecode_text = emit_bytecodes(entries, bytecode_dir, args.require_bytecode)
    except RuntimeError as exc:
        print(f"generate_stdlib_embedded.py: {exc}", file=sys.stderr)
        return 1

    if args.output:
        write_text(args.output, source_text + bytecode_text)
    write_text(args.source_output, source_text)
    write_text(args.bytecode_output, bytecode_text)
    if not args.output and not args.source_output and not args.bytecode_output:
        print("generate_stdlib_embedded.py: no output path provided", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
