param(
    [Parameter(Mandatory = $true)]
    [string]$SourceRoot,

    [Parameter(Mandatory = $true)]
    [string]$BuildDirectory,

    [Parameter(Mandatory = $true)]
    [string]$SeedBytecodeInclude,

    [int]$Jobs = 4
)

$ErrorActionPreference = 'Stop'
$source = (Resolve-Path -LiteralPath $SourceRoot).Path
$build = [IO.Path]::GetFullPath($BuildDirectory)
$seedBytecode = (Resolve-Path -LiteralPath $SeedBytecodeInclude).Path
if (-not $build.StartsWith($source + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
    throw "ASan build directory must stay below the source root: $build"
}

Write-Host "== [asan_focused/windows] source=$source"
Write-Host "== [asan_focused/windows] build=$build jobs=$Jobs"

cmake -S $source -B $build -A x64 `
    -DBUILD_TESTS=ON `
    -DENABLE_ASAN=ON `
    -DENABLE_UBSAN=OFF `
    -DENABLE_TLS=OFF `
    -DXRAY_BUNDLE_ZIG=OFF
if ($LASTEXITCODE -ne 0) { throw 'Windows ASan configure failed' }

$cache = Join-Path $build 'CMakeCache.txt'
$instanceLine = Get-Content -LiteralPath $cache | Where-Object { $_.StartsWith('CMAKE_GENERATOR_INSTANCE:INTERNAL=') } | Select-Object -First 1
if (-not $instanceLine) { throw 'CMake did not record a Visual Studio generator instance' }
$vsInstance = $instanceLine.Substring('CMAKE_GENERATOR_INSTANCE:INTERNAL='.Length)
$asanRuntime = Get-ChildItem -LiteralPath (Join-Path $vsInstance 'VC\Tools\MSVC') -Directory |
    Sort-Object { [version] $_.Name } -Descending |
    ForEach-Object { Get-Item -LiteralPath (Join-Path $_.FullName 'bin\Hostx64\x64\clang_rt.asan_dynamic-x86_64.dll') -ErrorAction SilentlyContinue } |
    Select-Object -First 1
if (-not $asanRuntime) { throw 'The Visual Studio x64 AddressSanitizer runtime was not found' }
$env:PATH = $asanRuntime.Directory.FullName + [IO.Path]::PathSeparator + $env:PATH
Write-Host "== [asan_focused/windows] runtime=$($asanRuntime.FullName)"

# The embedded stdlib is deterministic and was generated by the verified
# non-sanitized build which registered this CTest.  Build the ASan-instrumented
# generator so it remains compile-checked, but do not execute that large
# bootstrap workload under Windows ASan: LLVM's shadow mapping can fail before
# the focused product tests start.  Copying after the generator build keeps the
# seed newer than the custom-command dependencies.
cmake --build $build --config Debug --parallel $Jobs --target xray_stdlib_bcgen
if ($LASTEXITCODE -ne 0) { throw 'Windows ASan bootstrap generator build failed' }
$generatedDirectory = Join-Path $build 'generated\final'
New-Item -ItemType Directory -Force -Path $generatedDirectory | Out-Null
$generatedBytecode = Join-Path $generatedDirectory 'stdlib_embedded_bytecodes.inc'
Copy-Item -LiteralPath $seedBytecode -Destination $generatedBytecode -Force
[IO.File]::SetLastWriteTimeUtc($generatedBytecode, [DateTime]::UtcNow.AddSeconds(2))

$targets = @(
    'xray',
    'test_xaot_driver',
    'test_xi_stage',
    'test_xi_pipeline',
    'test_xi_lower',
    'test_cli_toolchain',
    'test_os_core'
)
cmake --build $build --config Debug --parallel $Jobs --target $targets
if ($LASTEXITCODE -ne 0) { throw 'Windows ASan build failed' }

# Keep the focused build self-contained.  PATH is still exported for tools
# launched outside the configuration output directory, but Windows resolves a
# DLL beside an executable before PATH.  Staging the exact runtime selected
# from the active Visual Studio instance therefore also protects nested CTest
# children from environment propagation differences and prevents an
# interactive "DLL not found" dialog from blocking unattended validation.
$asanOutputDirectory = Join-Path $build 'Debug'
if (-not (Test-Path -LiteralPath $asanOutputDirectory -PathType Container)) {
    throw "Windows ASan output directory was not produced: $asanOutputDirectory"
}
$stagedAsanRuntime = Join-Path $asanOutputDirectory $asanRuntime.Name
Copy-Item -LiteralPath $asanRuntime.FullName -Destination $stagedAsanRuntime -Force
if ((Get-FileHash -Algorithm SHA256 -LiteralPath $asanRuntime.FullName).Hash -ne
    (Get-FileHash -Algorithm SHA256 -LiteralPath $stagedAsanRuntime).Hash) {
    throw "Windows ASan runtime staging verification failed: $stagedAsanRuntime"
}

$env:ASAN_OPTIONS = 'abort_on_error=1:detect_leaks=0:symbolize=1'
$regex = '^(test_xaot_driver|test_xi_stage|test_xi_pipeline|test_xi_lower|test_cli_toolchain|test_os_core)$'
ctest --test-dir $build -C Debug --output-on-failure -j 1 -R $regex --timeout 300
if ($LASTEXITCODE -ne 0) { throw 'Windows ASan focused tests failed' }

$xray = Join-Path $build 'Debug\xray.exe'
$fixture = Join-Path $source 'tests\meta\fixtures\bili-analysis-server\src\main.xr'
$output = Join-Path $build 'asan-bili-fixture.c'
if (-not (Test-Path -LiteralPath $fixture -PathType Leaf)) {
    throw "required ASan fixture is missing: $fixture"
}
& $xray build $fixture --native --c-only -o $output
if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $output -PathType Leaf)) {
    throw 'Windows ASan real-workload C emission failed'
}

Write-Host '== [asan_focused/windows] PASS'
