#!/usr/bin/env python3
"""Encode complete scalar Checked fixtures with independent semantic expectations."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / "tests/unit/xir/product_consumers"


def packet(result=2, constant_type=2, immediate=42, **changes) -> bytes:
    def words(*values):
        return struct.pack("<" + "I" * len(values), *values)

    def instruction(prefix, opcode, type_id, value):
        return words(changes.get(prefix + "_opcode", opcode), type_id,
                     changes.get(prefix + "_arg0", 0), changes.get(prefix + "_arg1", 0),
                     changes.get(prefix + "_target0", 0), changes.get(prefix + "_target1", 0)) + \
            struct.pack("<Q", changes.get(prefix + "_immediate", value) & ((1 << 64) - 1)) + \
            words(changes.get(prefix + "_typearg0", 0), changes.get(prefix + "_typearg1", 0))

    body = words(0, 1, 0, 4) + b"main" + words(0, result, 1)
    body += words(changes.get("block_first", 0), changes.get("block_count", 2), 0, 0, 2)
    body += instruction("constant", 2, constant_type, immediate)
    body += instruction("return", 33, 0, 0)
    body += words(0, 0, 0, 0, 0, 0, 0)  # operands, generics, type/nominal/interface tables, defaults, provenance
    header = b"XRCHK\0\0\0" + words(25, 67, 2, 0) + struct.pack("<Q", len(body))
    return header + hashlib.sha256(header + body).digest() + body


def cases() -> list[dict]:
    values = []

    def add(name, expected, **model):
        data = packet(**model)
        values.append(dict(name=name, expected=expected, model=model, bytes=data))

    add("control_i64", "XR_XIR_OK")
    add("control_unit_result", "XR_XIR_OK", result=0)
    add("control_i32", "XR_XIR_OK", result=7, constant_type=7)
    add("control_i8_min", "XR_XIR_OK", result=5, constant_type=5, immediate=-128)
    add("control_u8_max", "XR_XIR_OK", result=8, constant_type=8, immediate=255)
    for type_id in [0, 1, 3, 4, *range(5, 17), 255, 256, 65535, 65536, 131072, 4294967295]:
        add(f"constant_type_{type_id}", "XR_XIR_BAD_TYPE", constant_type=type_id)
    for type_id in [1, 3, 4, *range(5, 17), 255, 256, 65535, 65536, 131072, 4294967295]:
        add(f"result_type_{type_id}", "XR_XIR_BAD_TYPE", result=type_id)
    for name, type_id, immediate in [("i8_high", 5, 128), ("i8_low", 5, -129),
                                     ("u8_negative", 8, -1), ("u8_high", 8, 256)]:
        add(name, "XR_XIR_BAD_TYPE", result=type_id, constant_type=type_id, immediate=immediate)
    for value in [1, 2, 4294967295]:
        add(f"return_value_{value}", "XR_XIR_BAD_VALUE", return_arg0=value)
    for prefix, fields in [("constant", ["arg0", "arg1", "target0", "target1", "typearg0", "typearg1"]),
                            ("return", ["arg1", "target0", "target1", "immediate", "typearg0", "typearg1"])]:
        for field in fields:
            add(f"{prefix}_unused_{field}", "XR_XIR_BAD_STRUCTURE", **{prefix + "_" + field: 1})
    for opcode in [0, 148]:
        add(f"invalid_opcode_{opcode}", "XR_XIR_BAD_STRUCTURE", constant_opcode=opcode)
    add("block_nonzero_first", "XR_XIR_BAD_STRUCTURE", block_first=1)
    add("block_missing_terminal", "XR_XIR_BAD_STRUCTURE", block_count=1)
    assert len(values) == 71 and sum(v["expected"] == "XR_XIR_OK" for v in values) == 5
    return values


def artifacts() -> tuple[str, dict]:
    old = (DIRECTORY / "semantic67_named/semantic67_core.inc.c").read_text(encoding="utf-8")
    body = re.search(r"named_packet_67_0\[\] = \{(.*?)\};", old, re.S)[1]
    golden = bytes(int(v, 16) for v in re.findall(r"0x([0-9a-f]{2})", body))
    if packet() != golden:
        raise ValueError("independent named scalar encoder differs from the complete original golden")
    header = ["/* Complete named scalar inputs; generated by source_product_consumer_checked_semantics.py. */",
              "typedef struct SemanticScalarCase {", "    const char *name; XrXirStatus expected;",
              "    XrXirType result, constant_type; int64_t immediate; uint8_t bytes[224];",
              "} SemanticScalarCase;", "static const SemanticScalarCase semantic_scalar_cases[] = {"]
    manifest = {"schema": 1, "identity": "Checked25/semantic67", "packet_bytes": 224,
                "controls": 5, "rejections": 66, "cases": []}
    for row in cases():
        model = row["model"]
        value = model.get("immediate", 42)
        literal = f"{'-' if value < 0 else ''}INT64_C({abs(value)})"
        header.append(f'    {{"{row["name"]}", {row["expected"]}, (XrXirType){model.get("result", 2)}u, '
                      f'(XrXirType){model.get("constant_type", 2)}u, {literal}, {{')
        data = row["bytes"]
        for offset in range(0, len(data), 16):
            header.append("        " + ",".join(f"0x{x:02x}" for x in data[offset:offset + 16]) + ",")
        header.append("    }},")
        manifest["cases"].append({k: v for k, v in row.items() if k != "bytes"} |
                                 {"sha256": hashlib.sha256(data).hexdigest(), "digest": data[32:64].hex()})
    header.append("};\n")
    return "\n".join(header), manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("write", "check"))
    args = parser.parse_args()
    header, manifest = artifacts()
    files = {DIRECTORY / "checked_semantic_scalar_cases.h": header,
             DIRECTORY / "checked_semantic_scalar_cases.json": json.dumps(manifest, indent=2) + "\n"}
    for path, text in files.items():
        if args.mode == "write":
            path.write_text(text, encoding="utf-8", newline="\n")
        elif path.read_text(encoding="utf-8") != text:
            raise ValueError(f"independent semantic packet fixture differs: {path}")
    print("Checked scalar matrix: 71 exact complete packets, 5 positive controls, 66 independent rejects")


if __name__ == "__main__":
    main()
