#!/usr/bin/env python3
"""Preserve the legacy binary64 corpus in independently encoded Checked inputs."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re

from source_product_consumer_checked_semantics import packet

ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / "tests/unit/xir/product_consumers"
LEGACY_BITS = (0, 1, 0x3ff0000000000000, 0x7fefffffffffffff,
               0x7ff0000000000000, 0x7ff0000000000001, 0x7ff8000000000001,
               0x8000000000000000, 0xfff0000000000000, 0xfff8000000000001)


def artifacts() -> tuple[str, dict]:
    legacy = (ROOT / "tests/unit/program/test_xr_program.c").read_text(encoding="utf-8")
    original = re.search(r"static const uint64_t f64_constant_bits\[\] = \{(.*?)\};", legacy, re.S)[1]
    actual = tuple(int(x, 0) for x in re.findall(r"UINT64_C\(([^)]+)\)", original))
    if actual != LEGACY_BITS:
        raise ValueError("original binary64 corpus changed")
    rows = []
    for index, bits in enumerate(LEGACY_BITS):
        rows.append((f"original_{index}", bits, 13,
                     "XR_XIR_BAD_TYPE" if index in (5, 6, 9) else "XR_XIR_OK"))
    rows.append(("canonical_nan", 0x7ff8000000000000, 13, "XR_XIR_OK"))
    rows.extend((f"wrong_type_{index}", bits, 2, "XR_XIR_BAD_TYPE")
                for index, bits in enumerate(LEGACY_BITS))
    header = ["/* Complete binary64 wire inputs; generated by source_product_consumer_checked_f64.py. */",
              "typedef struct F64WireCase {", "    const char *name; uint64_t bits; XrXirStatus expected;",
              "    uint8_t bytes[224];", "} F64WireCase;",
              "static const F64WireCase f64_wire_cases[] = {"]
    manifest = dict(schema=1, identity="Checked25/semantic67", original_bits=[f"{x:016x}" for x in LEGACY_BITS],
                    accepted=8, rejected=13, cases=[])
    for name, bits, type_id, expected in rows:
        data = packet(result=13, constant_type=type_id, immediate=bits, constant_opcode=63)
        header.append(f'    {{"{name}", UINT64_C(0x{bits:016x}), {expected}, {{')
        for offset in range(0, len(data), 16):
            header.append("        " + ",".join(f"0x{x:02x}" for x in data[offset:offset + 16]) + ",")
        header.append("    }},")
        manifest["cases"].append(dict(name=name, bits=f"{bits:016x}", constant_type=type_id,
                                      expected=expected, sha256=hashlib.sha256(data).hexdigest()))
    header.append("};\n")
    return "\n".join(header), manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("write", "check"))
    args = parser.parse_args()
    header, manifest = artifacts()
    for path, text in {DIRECTORY / "checked_f64_wire_cases.h": header,
                       DIRECTORY / "checked_f64_wire_cases.json": json.dumps(manifest, indent=2) + "\n"}.items():
        if args.mode == "write":
            path.write_text(text, encoding="utf-8", newline="\n")
        elif path.read_text(encoding="utf-8") != text:
            raise ValueError(f"independent binary64 fixture differs: {path}")
    print("Checked binary64 wire: 10 original bit patterns, 21 packets, 8 accepts, 13 rejects")


if __name__ == "__main__":
    main()
