/* AUTO-GENERATED by xisagen - DO NOT EDIT */
/* Source: xisa/xi/lowering.def */

#ifndef XI_EMIT_VM_GEN_H
#define XI_EMIT_VM_GEN_H

#define XI_EMIT_VM_LOWERING_HANDLERS(X) \
    X(CONST, emit_const) \
    X(PARAM, emit_param) \
    X(COPY, emit_copy) \
    X(MOVE, xi_emit_move) \
    X(ADD, xi_emit_arith) \
    X(SUB, xi_emit_arith) \
    X(MUL, xi_emit_arith) \
    X(DIV, xi_emit_arith) \
    X(MOD, xi_emit_arith) \
    X(NEG, xi_emit_neg) \
    X(BAND, xi_emit_arith) \
    X(BOR, xi_emit_arith) \
    X(BXOR, xi_emit_arith) \
    X(BNOT, xi_emit_bnot) \
    X(NOT, xi_emit_not) \
    X(SELECT, emit_select) \
    X(GET_SHARED, xi_emit_get_shared) \
    X(SET_SHARED, xi_emit_set_shared) \
    X(IMPORT_REF, xi_emit_import_ref) \
    X(CLOSURE_NEW, xi_emit_closure_new) \
    X(LOAD_UPVAL, xi_emit_load_upval) \
    X(STORE_UPVAL, xi_emit_store_upval) \
    X(ASSERT, xi_emit_assert) \
    X(ASSERT_EQ, xi_emit_assert_eq) \
    X(ASSERT_NE, xi_emit_assert_ne) \
    X(TYPEOF, xi_emit_typeof) \
    X(GET_BUILTIN, xi_emit_get_builtin) \
    X(PRINT, xi_emit_print) \
    X(CLASS_CREATE, xi_emit_class_create) \
    X(THROW, xi_emit_throw) \
    X(RETAIN, xi_emit_retain) \
    X(RELEASE, xi_emit_release) \
    X(SHL, xi_emit_arith) \
    X(SHR, xi_emit_arith) \
    X(EQ, xi_emit_cmp) \
    X(NE, xi_emit_cmp) \
    X(EQ_STRICT, xi_emit_cmp) \
    X(NE_STRICT, xi_emit_cmp) \
    X(LT, xi_emit_cmp) \
    X(LE, xi_emit_cmp) \
    X(GT, xi_emit_cmp) \
    X(GE, xi_emit_cmp) \
    X(NARROW_I8, xi_emit_narrow) \
    X(NARROW_U8, xi_emit_narrow) \
    X(NARROW_I16, xi_emit_narrow) \
    X(NARROW_U16, xi_emit_narrow) \
    X(NARROW_I32, xi_emit_narrow) \
    X(NARROW_U32, xi_emit_narrow) \
    X(NARROW_F32, xi_emit_narrow) \
    X(WIDEN_I8, xi_emit_widen) \
    X(WIDEN_U8, xi_emit_widen) \
    X(WIDEN_I16, xi_emit_widen) \
    X(WIDEN_U16, xi_emit_widen) \
    X(WIDEN_I32, xi_emit_widen) \
    X(WIDEN_U32, xi_emit_widen) \
    X(WIDEN_F32, xi_emit_widen) \
    X(ISNULL, xi_emit_isnull) \
    X(IS, xi_emit_is) \
    X(CONVERT, xi_emit_convert) \
    X(BOX, xi_emit_box) \
    X(UNBOX, xi_emit_unbox) \
    X(INDEX_GET, xi_emit_index_get) \
    X(INDEX_SET, xi_emit_index_set) \
    X(ARRAY_NEW, xi_emit_array_new) \
    X(MAP_NEW, xi_emit_map_new) \
    X(SET_NEW, xi_emit_set_new) \
    X(STR_CONCAT, xi_emit_str_concat) \
    X(TUPLE_NEW, xi_emit_tuple_new) \
    X(TUPLE_GET, xi_emit_tuple_get) \
    X(BYTES_LOAD_U32_LE, xi_emit_bytes_load_u32_le) \
    X(BYTES_LOAD_U64_LE, xi_emit_bytes_load_u64_le) \
    X(BYTES_COPY_WITHIN, xi_emit_bytes_copy_within) \
    X(BYTES_COPY_FROM, xi_emit_bytes_copy_from) \
    X(BYTES_REPEAT_FROM, xi_emit_bytes_repeat_from)


#endif  /* XI_EMIT_VM_GEN_H */
