/* AUTO-GENERATED by xisagen - DO NOT EDIT */
/* Source: xisa/aot/c_emission_rules.def */
#ifndef XR_C_EMISSION_RULE_IDS_GEN_H
#define XR_C_EMISSION_RULE_IDS_GEN_H

typedef enum XrCEmissionRuleId {
    XR_C_EMISSION_RULE_NONE = 0,
    XR_C_EMISSION_RULE_C_EMISSION_ARRAY_PUSH_TAGGED_V1 = 1,
} XrCEmissionRuleId;

#endif  // XR_C_EMISSION_RULE_IDS_GEN_H
