/*
 * xray - Lightweight typed scripting with native concurrency
 * https://www.xray-lang.org
 *
 * Copyright (c) 2026 Xinglei Xu <xingleixu@gmail.com>
 * Licensed under the MIT License
 *
 * xcodegen_json_decode.c - Compiler-generated Json.decode<T>() bytecode
 *
 * Generates inline bytecode for Json.decode<T>(data):
 *   1. Check data.isObject()
 *   2. For each field in T: read via GETPROP, null-check, type-check
 *   3. Build result object with NEWJSON + JSON_INIT
 *   4. On any validation failure → return null
 *
 * Supported field types: int, float, string, bool.
 * Optional fields (T?) skip the null-check; missing = null in result.
 */

#include "xcodegen_json_decode.h"
#include "xexpr.h"
#include "xexpr_desc.h"
#include "xcompiler.h"
#include "xcompiler_context.h"
#include "xemit.h"
#include "xregalloc.h"
#include "../../base/xchecks.h"
#include "../../base/xmalloc.h"
#include "../../runtime/value/xtype.h"
#include "../../runtime/value/xtype_names.h"
#include "../../runtime/value/xvalue.h"
#include "../../runtime/object/xshape.h"
#include "../../runtime/object/xshape_cache.h"
#include "../../runtime/symbol/xsymbol_table.h"
#include "../../runtime/xisolate_api.h"
#include "../parser/xast.h"
#include <string.h>

/* Map XrType kind to XrTypeId for OP_IS runtime type checks.
 * Returns -1 for unsupported/complex types. */
static int kind_to_tid(XrType *type) {
    if (!type)
        return -1;
    /* Strip nullable wrapper: email?: string → check the base string type */
    XrType *base = type;
    if (base->is_nullable && base->kind == XR_KIND_UNION && base->union_type.member_count == 2) {
        /* Optional<T> is union(T, null) — pick the non-null member */
        for (int i = 0; i < 2; i++) {
            if (base->union_type.members[i] &&
                base->union_type.members[i]->kind != XR_KIND_NULL) {
                base = base->union_type.members[i];
                break;
            }
        }
    }
    switch (base->kind) {
        case XR_KIND_INT:
            return XR_TID_INT;
        case XR_KIND_FLOAT:
            return XR_TID_FLOAT;
        case XR_KIND_STRING:
            return XR_TID_STRING;
        case XR_KIND_BOOL:
            return XR_TID_BOOL;
        default:
            return -1;
    }
}

/*
 * Compile Json.decode<T>(data) into inline validation + extraction bytecode.
 *
 * Generated bytecode outline (N = field_count):
 *
 *   ; compile data argument -> data_reg
 *   INVOKE  data_reg, SYMBOL_IS_OBJECT, 0   ; R[data_reg] = data.isObject()
 *   TEST    data_reg, 0                      ; skip next if truthy
 *   JMP     fail
 *
 *   ; for each field[i]:
 *   GETPROP val_reg, data_reg, sym[field_name]  ; val = data.field_name
 *   ISNULL  val_reg, 1                           ; skip next if NOT null
 *   JMP     fail (or skip for optional)
 *   IS      tmp_reg, val_reg, K[tid]             ; type check
 *   TEST    tmp_reg, 0
 *   JMP     fail
 *   JSON_INIT result_reg, i, val_reg
 *
 *   JMP     end
 * fail:
 *   LOADNULL result_reg
 * end:
 */
XR_FUNC int xr_compile_json_decode(XrCompilerContext *ctx, XrCompiler *compiler,
                                   AstNode *data_node, XrType *target) {
    XR_DCHECK(ctx != NULL, "xr_compile_json_decode: NULL ctx");
    XR_DCHECK(compiler != NULL, "xr_compile_json_decode: NULL compiler");
    XR_DCHECK(target != NULL, "xr_compile_json_decode: NULL target");
    XR_DCHECK(XR_TYPE_IS_OBJECT(target), "xr_compile_json_decode: target not OBJECT");
    XR_DCHECK(target->object.field_count > 0, "xr_compile_json_decode: no fields");

    int field_count = target->object.field_count;
    XrEmitter *e = compiler->emitter;
    XrSymbolTable *st = (XrSymbolTable *) xr_isolate_get_symbol_table(ctx->X);

    /* ---- 1. Compile data argument ---- */
    XrExprDesc data_expr = xr_compile_expr(ctx, compiler, data_node);
    int data_reg = xexpr_to_anyreg(ctx, compiler, &data_expr);
    int data_protect = xreg_protect_begin(compiler->regalloc, data_reg, 1, "decode_data");

    /* ---- 2. Allocate result register ---- */
    int result_reg = xreg_alloc_temp(compiler->regalloc);
    int result_protect = xreg_protect_begin(compiler->regalloc, result_reg, 1, "decode_result");

    /* ---- 3. Create target Shape for result object ---- */
    XrString **interned_names = xr_malloc(sizeof(XrString *) * field_count);
    if (!interned_names) {
        xr_compiler_error(ctx, compiler, "Json.decode: out of memory");
        xreg_protect_end(compiler->regalloc, result_protect);
        xreg_protect_end(compiler->regalloc, data_protect);
        return result_reg;
    }
    for (int i = 0; i < field_count; i++) {
        const char *name = target->object.field_names[i];
        interned_names[i] = xr_compile_time_intern(ctx->X, name, strlen(name));
    }
    XrShape *shape = xr_shape_cache_get_or_create(
        ctx->X, ctx->shape_cache, interned_names, (uint32_t) field_count);
    xr_free(interned_names);
    if (!shape) {
        xr_compiler_error(ctx, compiler, "Json.decode: failed to create shape");
        xreg_protect_end(compiler->regalloc, result_protect);
        xreg_protect_end(compiler->regalloc, data_protect);
        return result_reg;
    }

    /* ---- 4. isObject() check ---- */
    int iso_sym = xr_symbol_register_in_table(st, "isObject");
    int iso_local = emitter_add_symbol(e, iso_sym);
    /* INVOKE overwrites R[base], so use a temp copy of data_reg */
    int tmp_reg = xreg_alloc_temp(compiler->regalloc);
    xemit_move(e, tmp_reg, data_reg);
    xemit_invoke(e, tmp_reg, iso_local, 0);
    /* tmp_reg now holds bool result */
    xemit_test(e, tmp_reg, 0);  /* skip next if truthy (is object) */
    int fail_jumps[64];  /* max 64 fields */
    int fail_count = 0;
    fail_jumps[fail_count++] = emit_jump(e, OP_JMP);  /* → fail */

    /* ---- 5. Create result object ---- */
    int shape_const = xr_vm_proto_add_constant(compiler->proto, xr_int((intptr_t) shape));
    xemit_newjson(e, result_reg, shape_const, ctx->current_storage_mode);

    /* ---- 6. Per-field validation and extraction ---- */
    for (int i = 0; i < field_count && i < 64; i++) {
        const char *fname = target->object.field_names[i];
        XrType *ftype = target->object.field_types[i];
        bool is_optional = ftype && ftype->is_nullable;
        int tid = kind_to_tid(ftype);

        /* Read field: GETPROP val, data, sym[fname] */
        int global_sym = xr_symbol_register_in_table(st, fname);
        int local_sym = emitter_add_symbol(e, global_sym);
        int val_reg = xreg_alloc_temp(compiler->regalloc);
        xemit_getprop(e, val_reg, data_reg, local_sym);

        if (is_optional) {
            /* Optional: if null, init field to null and skip type check */
            xemit_isnull(e, val_reg, 0);  /* skip next if IS null */
            int skip_init = emit_jump(e, OP_JMP);  /* null → skip to init_null */

            /* Not null: type check */
            if (tid >= 0) {
                int tid_const = xr_vm_proto_add_constant(compiler->proto, xr_int(tid));
                int chk = xreg_alloc_temp(compiler->regalloc);
                xemit_is(e, chk, val_reg, tid_const);
                xemit_test(e, chk, 0);
                XR_DCHECK(fail_count < 64, "too many fail jumps");
                fail_jumps[fail_count++] = emit_jump(e, OP_JMP);  /* type mismatch → fail */
                xreg_free_temp(compiler->regalloc, chk);
            }
            /* Store value */
            xemit_json_init(e, result_reg, i, val_reg);
            int skip_null = emit_jump(e, OP_JMP);  /* skip the null-init */

            /* init_null: field is null */
            patch_jump(e, skip_init, -1);
            xemit_json_init_n(e, result_reg, i, 0);

            patch_jump(e, skip_null, -1);
        } else {
            /* Required: null → fail */
            xemit_isnull(e, val_reg, 1);  /* skip next if NOT null */
            XR_DCHECK(fail_count < 64, "too many fail jumps");
            fail_jumps[fail_count++] = emit_jump(e, OP_JMP);  /* null → fail */

            /* Type check */
            if (tid >= 0) {
                int tid_const = xr_vm_proto_add_constant(compiler->proto, xr_int(tid));
                int chk = xreg_alloc_temp(compiler->regalloc);
                xemit_is(e, chk, val_reg, tid_const);
                xemit_test(e, chk, 0);
                XR_DCHECK(fail_count < 64, "too many fail jumps");
                fail_jumps[fail_count++] = emit_jump(e, OP_JMP);  /* mismatch → fail */
                xreg_free_temp(compiler->regalloc, chk);
            }
            /* Store value */
            xemit_json_init(e, result_reg, i, val_reg);
        }
        xreg_free_temp(compiler->regalloc, val_reg);
    }

    /* ---- 7. Success: jump past fail block ---- */
    int success_jump = emit_jump(e, OP_JMP);

    /* ---- 8. Fail block: load null ---- */
    for (int i = 0; i < fail_count; i++) {
        patch_jump(e, fail_jumps[i], -1);
    }
    xemit_loadnull(e, result_reg);

    /* ---- 9. End ---- */
    patch_jump(e, success_jump, -1);

    xreg_free_temp(compiler->regalloc, tmp_reg);
    xreg_protect_end(compiler->regalloc, result_protect);
    xreg_protect_end(compiler->regalloc, data_protect);

    return result_reg;
}
