/* AUTO-GENERATED by xisagen — DO NOT EDIT */
/* Source: xisa/arch/riscv64.isa */

#include <stdint.h>

/* riscv64.add */
uint32_t rv64_add(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x0u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x0u << 25);
}

/* riscv64.sub */
uint32_t rv64_sub(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x0u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x20u << 25);
}

/* riscv64.and */
uint32_t rv64_and(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x7u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x0u << 25);
}

/* riscv64.or */
uint32_t rv64_or(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x6u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x0u << 25);
}

/* riscv64.xor */
uint32_t rv64_xor(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x4u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x0u << 25);
}

/* riscv64.sll */
uint32_t rv64_sll(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x1u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x0u << 25);
}

/* riscv64.srl */
uint32_t rv64_srl(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x5u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x0u << 25);
}

/* riscv64.sra */
uint32_t rv64_sra(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x5u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x20u << 25);
}

/* riscv64.slt */
uint32_t rv64_slt(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x33u | ((uint32_t) (rd) << 7) | (0x2u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x0u << 25);
}

/* riscv64.addw */
uint32_t rv64_addw(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x3bu | ((uint32_t) (rd) << 7) | (0x0u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x0u << 25);
}

/* riscv64.subw */
uint32_t rv64_subw(uint8_t rd, uint8_t rs1, uint8_t rs2) {
    return 0x3bu | ((uint32_t) (rd) << 7) | (0x0u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) (rs2) << 20) | (0x20u << 25);
}

/* riscv64.addi */
uint32_t rv64_addi(uint8_t rd, uint8_t rs1, int32_t imm) {
    return 0x13u | ((uint32_t) (rd) << 7) | (0x0u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) ((int32_t) (imm) & 0xfff) << 20);
}

/* riscv64.andi */
uint32_t rv64_andi(uint8_t rd, uint8_t rs1, int32_t imm) {
    return 0x13u | ((uint32_t) (rd) << 7) | (0x7u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) ((int32_t) (imm) & 0xfff) << 20);
}

/* riscv64.ori */
uint32_t rv64_ori(uint8_t rd, uint8_t rs1, int32_t imm) {
    return 0x13u | ((uint32_t) (rd) << 7) | (0x6u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) ((int32_t) (imm) & 0xfff) << 20);
}

/* riscv64.ld */
uint32_t rv64_ld(uint8_t rd, uint8_t rs1, int32_t imm) {
    return 0x3u | ((uint32_t) (rd) << 7) | (0x3u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) ((int32_t) (imm) & 0xfff) << 20);
}

/* riscv64.sd */
uint32_t rv64_sd(uint8_t rs2, uint8_t rs1, int32_t imm) {
    return (uint32_t) (0x23u | (((int32_t) (imm) & 0x1f) << 7) | (0x3u << 12) |
                       ((uint32_t) (rs1) << 15) | ((uint32_t) (rs2) << 20) |
                       (((uint32_t) ((int32_t) (imm) >> 5) & 0x7f) << 25));
}

/* riscv64.jal */
uint32_t rv64_jal(uint8_t rd, int32_t imm) {
    return (uint32_t) (0x6fu | ((uint32_t) (rd) << 7) | ((((int32_t) (imm) >> 12) & 0xff) << 12) |
                       ((((int32_t) (imm) >> 11) & 1) << 20) |
                       ((((int32_t) (imm) >> 1) & 0x3ff) << 21) |
                       ((((int32_t) (imm) >> 20) & 1u) << 31));
}

/* riscv64.jalr */
uint32_t rv64_jalr(uint8_t rd, uint8_t rs1, int32_t imm) {
    return 0x67u | ((uint32_t) (rd) << 7) | (0x0u << 12) | ((uint32_t) (rs1) << 15) |
           ((uint32_t) ((int32_t) (imm) & 0xfff) << 20);
}

/* riscv64.beq */
uint32_t rv64_beq(uint8_t rs1, uint8_t rs2, int32_t imm) {
    return (uint32_t) (0x63u | ((((int32_t) (imm) >> 11) & 1) << 7) |
                       ((((int32_t) (imm) >> 1) & 0xf) << 8) | (0x0u << 12) |
                       ((uint32_t) (rs1) << 15) | ((uint32_t) (rs2) << 20) |
                       ((((int32_t) (imm) >> 5) & 0x3f) << 25) |
                       ((((int32_t) (imm) >> 12) & 1u) << 31));
}

/* riscv64.bne */
uint32_t rv64_bne(uint8_t rs1, uint8_t rs2, int32_t imm) {
    return (uint32_t) (0x63u | ((((int32_t) (imm) >> 11) & 1) << 7) |
                       ((((int32_t) (imm) >> 1) & 0xf) << 8) | (0x1u << 12) |
                       ((uint32_t) (rs1) << 15) | ((uint32_t) (rs2) << 20) |
                       ((((int32_t) (imm) >> 5) & 0x3f) << 25) |
                       ((((int32_t) (imm) >> 12) & 1u) << 31));
}

/* riscv64.blt */
uint32_t rv64_blt(uint8_t rs1, uint8_t rs2, int32_t imm) {
    return (uint32_t) (0x63u | ((((int32_t) (imm) >> 11) & 1) << 7) |
                       ((((int32_t) (imm) >> 1) & 0xf) << 8) | (0x4u << 12) |
                       ((uint32_t) (rs1) << 15) | ((uint32_t) (rs2) << 20) |
                       ((((int32_t) (imm) >> 5) & 0x3f) << 25) |
                       ((((int32_t) (imm) >> 12) & 1u) << 31));
}

/* riscv64.bge */
uint32_t rv64_bge(uint8_t rs1, uint8_t rs2, int32_t imm) {
    return (uint32_t) (0x63u | ((((int32_t) (imm) >> 11) & 1) << 7) |
                       ((((int32_t) (imm) >> 1) & 0xf) << 8) | (0x5u << 12) |
                       ((uint32_t) (rs1) << 15) | ((uint32_t) (rs2) << 20) |
                       ((((int32_t) (imm) >> 5) & 0x3f) << 25) |
                       ((((int32_t) (imm) >> 12) & 1u) << 31));
}

/* riscv64.lui */
uint32_t rv64_lui(uint8_t rd, uint32_t imm) {
    return 0x37u | ((uint32_t) (rd) << 7) | ((uint32_t) (imm) << 12);
}

/* riscv64.auipc */
uint32_t rv64_auipc(uint8_t rd, uint32_t imm) {
    return 0x17u | ((uint32_t) (rd) << 7) | ((uint32_t) (imm) << 12);
}

/* riscv64.nop */
uint32_t rv64_nop(void) {
    return 0x00000013u;
}

/* riscv64.ebreak */
uint32_t rv64_ebreak(void) {
    return 0x00100073u;
}
