/* AUTO-GENERATED by xisagen — DO NOT EDIT */
/* x64 variable-length instruction decoder */

#pragma once

#include <stdint.h>
#include <stddef.h>

typedef enum {
    XM_X64_INSN_UNKNOWN = -1,
    XM_X64_INSN_ADD_RR = 0,
    XM_X64_INSN_SUB_RR = 1,
    XM_X64_INSN_AND_RR = 2,
    XM_X64_INSN_OR_RR = 3,
    XM_X64_INSN_XOR_RR = 4,
    XM_X64_INSN_CMP_RR = 5,
    XM_X64_INSN_TEST_RR = 6,
    XM_X64_INSN_IMUL_RR = 7,
    XM_X64_INSN_ADD_RI8 = 8,
    XM_X64_INSN_ADD_RI32 = 9,
    XM_X64_INSN_SUB_RI8 = 10,
    XM_X64_INSN_SUB_RI32 = 11,
    XM_X64_INSN_AND_RI8 = 12,
    XM_X64_INSN_AND_RI32 = 13,
    XM_X64_INSN_OR_RI8 = 14,
    XM_X64_INSN_OR_RI32 = 15,
    XM_X64_INSN_CMP_RI8 = 16,
    XM_X64_INSN_CMP_RI32 = 17,
    XM_X64_INSN_TEST_RI32 = 18,
    XM_X64_INSN_MOV_RR = 19,
    XM_X64_INSN_MOV_RI64 = 20,
    XM_X64_INSN_SHL_RCL = 21,
    XM_X64_INSN_SHR_RCL = 22,
    XM_X64_INSN_SAR_RCL = 23,
    XM_X64_INSN_LOAD_BD32 = 24,
    XM_X64_INSN_STORE_BD32 = 25,
    XM_X64_INSN_CALL_REL32 = 26,
    XM_X64_INSN_CALL_R = 27,
    XM_X64_INSN_RET = 28,
    XM_X64_INSN_JMP_REL32 = 29,
    XM_X64_INSN_JCC_REL32 = 30,
    XM_X64_INSN_PUSH_R = 31,
    XM_X64_INSN_POP_R = 32,
    XM_X64_INSN_NOP = 33,
    XM_X64_INSN_INT3 = 34,
    XM_X64_INSN_NEG_R = 35,
    XM_X64_INSN_NOT_R = 36,
    XM_X64_INSN_LEA_BD32 = 37,
    XM_X64_INSN_CQO = 38,
    XM_X64_INSN_IDIV_R = 39,
    XM_X64_INSN_SHL_RI = 40,
    XM_X64_INSN_SHR_RI = 41,
    XM_X64_INSN_MOV_RI32 = 42,
    XM_X64_INSN_MOV_RM = 43,
    XM_X64_INSN_MOV_MR = 44,
    XM_X64_INSN_LEA = 45,
    XM_X64_INSN_MOVSXD_RM = 46,
    XM_X64_INSN_MOV_RM32 = 47,
    XM_X64_INSN_MOV_MR32 = 48,
    XM_X64_INSN_MOVZX_RM8 = 49,
    XM_X64_INSN_MOVSX_RM8 = 50,
    XM_X64_INSN_MOVZX_RM16 = 51,
    XM_X64_INSN_MOVSX_RM16 = 52,
    XM_X64_INSN_MOV_MR8 = 53,
    XM_X64_INSN_MOV_MR16 = 54,
    XM_X64_INSN_CMOV_RR = 55,
    XM_X64_INSN_SETCC = 56,
    XM_X64_INSN_JMP_REL8 = 57,
    XM_X64_INSN_ADDSD = 58,
    XM_X64_INSN_SUBSD = 59,
    XM_X64_INSN_MULSD = 60,
    XM_X64_INSN_DIVSD = 61,
    XM_X64_INSN_MOVSD_RR = 62,
    XM_X64_INSN_MOVSD_RM = 63,
    XM_X64_INSN_MOVSD_MR = 64,
    XM_X64_INSN_CVTSI2SD = 65,
    XM_X64_INSN_CVTTSD2SI = 66,
    XM_X64_INSN_UCOMISD = 67,
    XM_X64_INSN_MOVQ_XMM_GP = 68,
    XM_X64_INSN_MOVQ_GP_XMM = 69,
    XM_X64_INSN_XORPD = 70,
    XM_X64_INSN_MOVSS_RM = 71,
    XM_X64_INSN_MOVSS_MR = 72,
    XM_X64_INSN_CVTSS2SD = 73,
    XM_X64_INSN_CVTSD2SS = 74,
    XM_X64_INSN__COUNT = 75
} XmX64InsnId;

/* Returns the mcinsn name string (e.g. "x64.add.rr") for the given
 * id, or "(unknown)" if id is out of range. */
const char *xm_x64_insn_name(int id);

/* Decode one variable-length x64 instruction starting at `code`.
 * Returns the instruction length in bytes (0 if unrecognized).
 * If out_id is non-NULL, writes the XmX64InsnId. */
int xm_x64_disasm(const uint8_t *code, size_t avail, int *out_id);
